### PR TITLE
Update cargo capacity

### PR DESCRIPTION
**Pull request by VuradoZ**
Summary
Category "Balance"
Increase in the volume of the trunk and cargo rack.

Purpose of change

The current cargo rack has too little load capacity, which makes the vehicle too large and uncomfortable.

Describe the solution

To increase cargo rack capacity to 500L and trunk to 250L.

Describe the alternatives you considered

Nothing.

Testing

Successfully.

Additional context

I would like to increase cargo rack to 750L if possible.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I'd like to hear some rationale here. I'm not completely against the idea, but "too little/too much" needs to be more specific.
What is your target number and why? Why should trunks and cargo holders be buffed so much over other vehicle storage parts?

**Comment by VuradoZ** [comment]
1. As a player who abuses saving through ALT F4 after death, the world weighs at least 300MB. I have about 10,000L of stuff, a car with so many cargo compartments looks like a barge on 20 wheels and two gas turbine engines are difficult to navigate through cities. I have to sacrifice half of my things and cut the car. There is a 1500L cargo hold, but I have no idea where to look for it. In front of him is a refrigerator with 300L of cargo, and only then there is a cargo compartment for 250L. Should I carry my things in the fridge? This is nonsense.
2. I want to raise the trunk from 162L to 250L to facilitate the early game and the search for a new home. Raise the cargo hold from 250L to 500L so that in the late game you can drive a NORMAL looking car with NORMAL dimensions.
3. The rest of the cargo compartments look normal and I see no reason to remodel them.
- P.S. Sorry for the google translator.

**Comment by VStraken** [comment]
I also noticed that no vehicle I've encountered in my games has any hauling spaces. I decided to spawn vehicles I figured would have them, but I didn't find any. I think there's simply no vehicle that has them, and I don't think they spawn as unattached parts. I think you should feel free to spawn them in at your discretion.

Coolthulhu, are there plans to add/modify existing vehicles to use hauling spaces?

**Comment by VuradoZ** [comment]
> I don't see a good case for the trunk, but the cargo holder could get a buff. Though not for free.
> How about: cargo holder weight increased to 200kg, but gets cargo capacity doubled, as in your PR. And the recipe would need to be adjusted to use 3 heavy frames.
> This way it would allow heavy but compact vehicles.

Hmm, it looks logical. I will make a new PR with this change, since this one cannot be changed for technical reasons.

**Comment by Mom-Bun** [comment]
> I also noticed that no vehicle I've encountered in my games has any hauling spaces. I decided to spawn vehicles I figured would have them, but I didn't find any. I think there's simply no vehicle that has them, and I don't think they spawn as unattached parts. I think you should feel free to spawn them in at your discretion.
> 
> Coolthulhu, are there plans to add/modify existing vehicles to use hauling spaces?

Bit late, but you can't find hauling spaces anywhere because we the aftershock maintainers (over on the DDA branch) decided to obsolete it, it made no sense and didn't fit in for the "sci-fi" mod, and by the time BN was forked, they were already obsoleted

If you wish to use something similar to hauling spaces, there is nothing stopping you, but if you want to have big cargo holds like hauling spaces without it involving debugging or whatever, use blaze industries, it contains cargo shelving. 

@Coolthulhu The main reason why AFS has those fridges instead of mainline is because it was deemed that the recipe was too unrealistic to convert a fridge to work on vehicle power, they work completely fine, if a bit too easy to make; my main suggestion is if you want to add them to mainline is keep in mind the balance, and that they basically make things like minifreezers and minifridges useless.

**Comment by DrPariah** [comment]
Also a bit late, but if anyone misses the old Hauling Space I broke it out into a separate mod. Should be available in Kennan's BN Mod Pack. That way, you get your Hauling Space if you want it, and don't if you don't. I didn't go so far as to restore vehicles that used it, mind.

**Pull request closed without merging**
