### PR TITLE
C.R.I.T. Renewal

### PR DESCRIPTION
**Pull request by Zlorthishen**
#### Summary
Summary: [Mods]: C.R.I.T. Renewal

#### Purpose of change
Maintains C.R.I.T. Expansion stays up to date and implements several dda ports

[CRIT → C.R.I.T #56406](https://github.com/CleverRaven/Cataclysm-DDA/pull/56406) by [ZhilkinSerg](https://github.com/ZhilkinSerg)

[CRIT Mod update  #44324](https://github.com/CleverRaven/Cataclysm-DDA/pull/44324) by [ZhilkinSerg](https://github.com/ZhilkinSerg)

#### Describe the solution
Implements several dda pull requests and keeps the mod up to date with current Bright Nights version

#### Describe alternatives you've considered
Letting this mod rot is not acceptable, and dda made it obsolete. 

#### Testing
tested items and monsters spawns with debug

### CODE REVIEW

**Comment by olanti-p** [comment]
1. Looks like you've somehow committed windows-style line endings (cr+lf) instead of linux style used by this repository (lf).
2. Please add original authors as co-authors to commit description using pattern `Co-authored-by: NAME <NAME@EXAMPLE.COM>`

**Comment by Zlorthishen** [comment]
updated the item groups so that C.R.I.T. items will actually spawn

**Comment by Coolthulhu** [comment]
Do you have access to "JSON Validation" check on this page? I hope it's enabled for everyone.
Either way, the relevant bit is:
```
Needs linting : data/mods/CRT_EXPANSION/monsters/crt_monstergroups.json
Please read doc/JSON_STYLE.md
```

**Comment by Zlorthishen** [comment]
> Do you have access to "JSON Validation" check on this page? I hope it's enabled for everyone. Either way, the relevant bit is:
> 
> ```
> Needs linting : data/mods/CRT_EXPANSION/monsters/crt_monstergroups.json
> Please read doc/JSON_STYLE.md
> ```

Is there any way to tell what is still failing??

**Comment by Coolthulhu** [comment]
I don't have good knowledge of CRIT.
I'll trust you on this one.

**Comment by Zlorthishen** [comment]
> I don't have good knowledge of CRIT. I'll trust you on this one.

thanks. 
i have plans for a future addition of lab rooms, maybe a mission or something.

**Pull request merged**
