### PR TITLE
(Port) Decouple encumbrance, max_encumbrance and coverage in armor on a per bodypart_id basis

### PR DESCRIPTION
**Pull request by meladath**
#### Summary

SUMMARY: Features "Port - Decouple encumbrance, max_encumbrance and coverage in armor on a per bodypart_id basis"

#### Purpose of change

Currently an items coverage and encumber values apply to every limb that item covers. This PR will allow us to cover and encumber different limbs at different rates with the same item.

#### Describe the solution

Port:
- https://github.com/CleverRaven/Cataclysm-DDA/pull/40866
- https://github.com/CleverRaven/Cataclysm-DDA/pull/41522
- https://github.com/CleverRaven/Cataclysm-DDA/pull/42513

#### Testing

Not much right now. I have loaded the game, opened the menus and checked the output. It appears to be correct on the few items I have tested. I have only played for a few hours on various random characters so far.

#### Additional context

Almost there I believe. Attention needs to be paid to max_encumber as this code was ported from DDA where I believe due to the pocket system, the calculations worked differently to BN, I am not sure if BN is functioning correctly after this change as I havent played enough.

### CODE REVIEW

**Comment by scarf005** [comment]
image

sorry for the extremely long delay (5 months!), but i finally got a bit of time to review and ready this PR for merge. I've merged upstream `upload` branch with this PR so it could be merged right away.

image

however, I'm unable to push merges to the PR. could you allow maintainers to edit the PR?

**Review by scarf005 — CHANGES_REQUESTED** [review]
image

sorry for the extremely long delay (5 months!), but i finally got a bit of time to review and ready this PR for merge. I've merged upstream `upload` branch with this PR so it could be merged right away.

image

however, I'm unable to push merges to the PR. could you allow maintainers to edit the PR?

**Comment by meladath** [comment]
Hey, I believe it should already be enabled

image

Not sure why you cant push to it.

**Comment by scarf005** [comment]
it may be due to branch protection.

**Review by scarf005 — COMMENTED** [review]
image

`tests/iteminfo_test.cpp` also fails, would it be possible to match display order, or should the test output be changed?

**Comment by scarf005** [comment]
https://github.com/meladath/Cataclysm-BN/pull/1

**Comment by meladath** [comment]
Swapping the output should be OK. I believe I made sure all tests passed
before I submitted the pr, however I did need to modify them for the new
behaviour. I can't so this right now but feel free to do this yourself.

**Comment by meladath** [comment]
Should note, modification of the actual item_info to sort as per the test
should also be relatively trivial.

**Comment by scarf005** [comment]
@meladath could you disable branch protection on your fork's `upload` branch?

**Comment by meladath** [comment]
I believe its done now, also merged your PR.

**Review by scarf005 — APPROVED** [review]
locally ran tests, astyle, json formatting, they all look good. also the game does not crash and burn.

image

**Comment by olanti-p** [comment]
Test failed on MacOS for this PR
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cata_test is a Catch v2.13.8 host application.
Run with -? for options

Randomness seeded to: 1696695419

-------------------------------------------------------------------------------
item rigidity
  rigid items do not indicate they are rigid, since almost all items are
-------------------------------------------------------------------------------
../tests/iteminfo_test.cpp:155
...............................................................................

../tests/iteminfo_test.cpp:43: FAILED:
  CHECK( info == reference )
with expansion:
Error:   "--
  <color_c_white>Encumbrance</color>:
  L. Arm:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>
  R. Arm:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>
  L. Hand:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>
  R. Hand:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>
  "
  ==
  "--
  <color_c_white>Encumbrance</color>:
  L. Hand:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>
  R. Hand:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>
  L. Arm:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>
  R. Arm:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>
  "
with messages:
  escape_newlines( info ) := "--\n
  <color_c_white>Encumbrance</color>:\n
  L. Arm:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>\n
  R. Arm:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>\n
  L. Hand:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>\n
  R. Hand:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>\n
  "
  escape_newlines( reference ) := "--\n
  <color_c_white>Encumbrance</color>:\n
  L. Hand:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>\n
  R. Hand:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>\n
  L. Arm:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>\n
  R. Arm:  <color_c_yellow>30</color>  Coverage:  <color_c_yellow>10</color>\n
  "

-------------------------------------------------------------------------------
armor coverage and protection values
  shows coverage, encumbrance, and protection for armor with coverage
-------------------------------------------------------------------------------
../tests/iteminfo_test.cpp:261
...............................................................................

../tests/iteminfo_test.cpp:43: FAILED:
  CHECK( info == reference )
with expansion:
Error:   "--
  <color_c_white>Encumbrance</color>:
  Torso:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>
  Arms:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>
  Legs:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>
  "
  ==
  "--
  <color_c_white>Encumbrance</color>:
  Torso:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>
  Legs:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>
  Arms:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>
  "
with messages:
  escape_newlines( info ) := "--\n
  <color_c_white>Encumbrance</color>:\n
  Torso:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>\n
  Arms:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>\n
  Legs:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>\n
  "
  escape_newlines( reference ) := "--\n
  <color_c_white>Encumbrance</color>:\n
  Torso:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>\n
  Legs:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>\n
  Arms:  <color_c_yellow>12</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>95</color>\n
  "

../tests/iteminfo_test.cpp:43: FAILED:
  CHECK( info == reference )
with expansion:
Error:   "--
  <color_c_white>Encumbrance</color>: <color_c_red>(poor fit)</color>
  Torso:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>
  Head:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>
  L. Arm:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>
  R. Arm:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>
  L. Leg:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>
  R. Leg:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>
  "
  ==
  "--
  <color_c_white>Encumbrance</color>: <color_c_red>(poor fit)</color>
  Torso:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>
  L. Leg:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>
  R. Leg:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>
  Head:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>
  L. Arm:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>
  R. Arm:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>
  "
with messages:
  escape_newlines( info ) := "--\n
  <color_c_white>Encumbrance</color>: <color_c_red>(poor fit)</color>\n
  Torso:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>\n
  Head:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>\n
  L. Arm:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>\n
  R. Arm:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>\n
  L. Leg:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>\n
  R. Leg:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>\n
  "
  escape_newlines( reference ) := "--\n
  <color_c_white>Encumbrance</color>: <color_c_red>(poor fit)</color>\n
  Torso:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>\n
  L. Leg:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>\n
  R. Leg:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>\n
  Head:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>\n
  L. Arm:  <color_c_yellow>5</color>  When Full:  <color_c_yellow>5</color>
  Coverage:  <color_c_yellow>50</color>\n
  R. Arm:  <color_c_yellow>10</color>  When Full:  <color_c_yellow>25</color>
  Coverage:  <color_c_yellow>100</color>\n
  "
```

**Pull request merged**
