### PR TITLE
fix: Grenade rework

### LINKED ISSUE #5294: Gas and incendiary grenades do not work
### Describe the bug

After activating and throwing gas/incendiary grenades nothing happens as seen in the attached video below.

### Steps To Reproduce

1. Activate item.
2. Throw item.
3. Nothing happens.

### Screenshots

[CBN Grenades FAIL.webm](https://github.com/user-attachments/assets/3ff215e2-03d1-4311-a0da-274662c706c0)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: cbd6d2c [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KheirFerrum**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

- fix #5294 which was due to #5188 reworking how items were handled when they needed more charge than the item could provide. The rather odd logic is detailed there.
  - Basically, when I did #5188, I "fixed" a very fucked up piece of code that our grenades rely on, namely that an item that runs out of charges will attempt to invoke itself first then revert, even if the invoke actually changes the item to something else, testing revealed that this was "necessary" for incendiary/gas grenades, as they have a revert and cannot explode unless invoked (in a fake way that makes the game think the player invoked it, the mystery of why active molotovs/grenades explode when invoked is now resolved...).
- Further found a fun issue with how our `active_item_cache` is handled, it's had an issue apparently for at least 5/6 years that made it process an extra item on it's "list" every turn, desyncing the active list and meaning that if a single active explosive was on a tile it would be processed twice per turn.

## Describe the solution

- Grenade logic reworked such that exploding is handled in active turn processing by tick instead of requiring a fake player invoke from the `process_tool` code. ~~This has hit a snag that I am commiserating with @joveeater on, as the `explosion_iuse::use` function is incapable of destroying the item it is called on due to how `process_internal` code functions.~~ Reworked so that for now it doesn't require this, but it's a hack, detailed in the code.
- Separate from this also fixes an issue that causes active item processing to process items more than they should due to bad handling in `get_for_processing()` where `num_to_process` is checking for `>= 0` instead of `> 0` Apparently this was used for food item processing, but that has been updated to not be broken by me.

## Describe alternatives you've considered

- Reinserting the weird code used to handle item charges.
  - Would appreciate not doing so, as it presents some very weird edge cases.

## Testing

- [x] Makeshift gas canisters, incendiary grenades and grenades function as they should, exploding and forming appropriate fields, while not lingering beyond their turn.
- [x] Atomic lamps and other active items that do not use charge do not spontaneously turn themselves off for some reason.
- [x] Electric lamps still use more or less the same number of charges over time on the floor and in inventory.
- [x] Grenades in inventory and on floor explode at the same time rather than the one on the floor having it's timer move at double speed.
- [x] Check that food still rots when placed on the ground.

### CODE REVIEW

**Comment by KheirFerrum** [comment]
I screwed something up somehow.

**Comment by KheirFerrum** [comment]
Oh, never mind, I was building on a test build for reworking our active item cache. Look forward to that next PR.

**Comment by chaosvolt** [comment]
Oh hecc, lemme see...

**Comment by RoyalFox2140** [comment]
I live. I can test this then

**Comment by RoyalFox2140** [comment]
image
image

**Review by RoyalFox2140 — APPROVED** [review]
Compiled, tested, it does what it says it does. Screenshots in previous comment.

**Comment by chaosvolt** [comment]
I got interrupted by offline errands before I could fully playtest, but can at least confirm compile-test worked fine, so. :>

**Pull request merged**
