### PR TITLE
feat(balance): gasoline engines can burn alcohol, V8 and V12 engines in general require higher-quality fuel

### PR DESCRIPTION
**Pull request by chaosvolt**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

I mentioned in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5749 that allowing gasoline engines to run biodiesel but not regular diesel was a bit of an oddball decision, with alcohol arguably being the better choice for them (as @yay855 initially did in their PR before being nudged to switch it to biodiesel).

## Describe the solution

1. Changed the `gasoline_engine` abstract to allow ethanol, denatured alcohol, and methanol instead of biodiesel. As noted in discussion of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3716 the worry was that easy access to putting booze in your gasoline engine would make diesel engines obsolete. The main counterpoints are that ethanol still takes time and resources to set up (made arguably a bit less roadblocked but no less of a logistical hassle by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4977), while diesel engines have the even easier to produce option of lamp oil to run off of. It was additionally pointed out that ethanol has a fuel value of 15.6 compared to biodiesel's 29.6, so if anything if the concern is making diesel engines stay relative why would you give it a fuel option that has twice the effectiveness of the more obvious choice?
2. Additionally added those three fuel options to the `gas_turbine_engine` abstract, maintaining the glorious tank and heli engine superiority over puny gasoline and diesel engines.
3. Per Coolthulhu's suggestion, V8 and V12 engines were given stricter fuel requirements for balancing purposes, losing access to alcohol (gasoline engines) and lamp oil/motor oil (diesel engines). Per his suggestion, turbine engines retain the ability to eat whatever they like since they're low-efficiency.
4. Updated description entries accordingly.

## Describe alternatives you've considered

1. Adding E85 fuel for more realism points and/or a way to stretch out the player's supply of gasoline without going full dorf mode like using pure alcohol would entail.
2. Rigging it so we can power engines with just vodka and other drinkable alcohols for the lulz.

## Testing

1. Checked affected files for syntax and lint errors.
2. Load-tested in compiled test build.
3. Spawned a regular car, confirmed it lets me switch it to run off denatured alcohol.
4. Spawned a big-ass V8 truck, confirmed it only accepts gasoline and avgas, and the engine description is different.

image
image
image
image

### CODE REVIEW

**Comment by yay855** [comment]
Yes, I tried to do the same thing and it didn't get approved. Chaos's reasons are sound, at least.

**Comment by chaosvolt** [comment]
Adding my musings from the discord here:
image

**Comment by blot-runner** [comment]
> Adding my musings from the discord here: image

You seem to focus exclusively on ethanol and denatured alcohol in your comparison. But methanol is super easy to produce in the game. No still, no fermenting, no rare tools or components al all, no books to search for, all you need is wood, water, clay retort, brazier and fire, and you're mass-producing fuel. The only real gateway here is Cooking 4, as opposed to 2 for the lamp oil, but that can be trained quite fast (I think it took me a day of game time). It does take twice the time to produce the same amount, comparing to the lamp oil, but the latter requires you to at least search for a pot or other proper cooking implement, not to mention hunting, fighting zombies or scavenging for the necessary fats.

**Comment by chaosvolt** [comment]
> No still

It does require distilling quality 1 which a clay retort provides, same as denatured alcohol. You're right though, wood does make the comparison more complicated and makes it possible to skip out on the fermentation. I do still feel that this is more reasonable than lamp oil to be honest?

Plus we really should not have added biodiesel to gasoline engines as an alternative to that, it makes it seem really weirdly inconsistent to allow one form of diesel but not factory-made ones.

**Comment by RoyalFox2140** [comment]
I am fine taking off biodiesel from gasoline engines unless a realism argument exists for biodiesel being used in a gasoline engine.

**Comment by chaosvolt** [comment]
That would work too I suppose. Any other devs we should ask for an opinion on the current PR proposal, or should I just make it a removal of gasoline engines running biodiesel?

**Comment by Coolthulhu** [comment]
Feels a bit weird IMO. Not as weird as biodiesel in gas engines, but still weird.

Blending would be more realistic, but wouldn't solve the gameplay issue of gas being non-renewable.
Is it really a huge deal if gas engines are non-renewable? It seems that the lamp oil diesel is the biggest outlier here, so rebalancing everything around that means more work than nerfing lamp oil.

I'd say that the best way to balance it would be to have lower level engines accept more fuel types, but have V12 only work with (av)gas for gasoline, and (bio)diesel for diesel. As far as I recall, gas turbines are inefficient, so it seems fine for them to be able to burn weird stuff.

**Comment by chaosvolt** [comment]
> I'd say that the best way to balance it would be to have lower level engines accept more fuel types, but have V12 only work with (av)gas for gasoline, and (bio)diesel for diesel. As far as I recall, gas turbines are inefficient, so it seems fine for them to be able to burn weird stuff.

That works then.

**Comment by blot-runner** [comment]
@RoyalFox2140 
> I am fine taking off biodiesel from gasoline engines unless a realism argument exists for biodiesel being used in a gasoline engine.

From what I was able to learn, it's the opposite - even stock diesel engines cannot run on pure biodiesel, you'll need AT LEAST 80% of petrol diesel in the mix (pure biodiesel is still possible if the engine is modified to accept it). Taking into account the fact that one of the main problems is much higher viscosity than that of petrol diesel, I think gasoline engine will die quite fast when fueled with biodiesel (presumably, the injectors would be the first thing to go, but I'm no mechanic.

@Coolthulhu 
> I'd say that the best way to balance it would be to have lower level engines accept more fuel types, but have V12 only work with (av)gas for gasoline, and (bio)diesel for diesel.

I know that you're talking about gasoline/diesel engines and what I'm saying might be beyond this PR's scope, but - wouldn't it be nice to have steam engines to accept liquid fuels too? All of them? I mean, as far as I know, they aren't really efficient, but their RL staple is "anything that burns is fuel" and it might provide an interesting alternative for lowtec runs.


>As far as I recall, gas turbines are inefficient, so it seems fine for them to be able to burn weird stuff.

IRL they can get more efficient than diesels (>60% vs. ~55% if the Wik is to be trusted). IDK, I always thought the main balancing factor there was "like hell you're going to find one". Or is it just my luck?))

**Comment by chaosvolt** [comment]
To be fair, Coolthulhu likely meant they're inefficient more than they're wasteful unless you have a downright wacky deathmobile. They have decent efficiency in game terms if I recall, just their power is so high that their fuel use is just high overall as a result.

**Comment by blot-runner** [comment]
> To be fair, Coolthulhu likely meant they're inefficient more than they're wasteful unless you have a downright wacky deathmobile. They have decent efficiency in game terms if I recall, just their power is so high that their fuel use is just high overall as a result.

Wait, you mean, there are people who **don't** build wacky deathmobiles?
Jokes aside, though, I've just checked combustion.json - gasoline engines, diesels and gas turbines are coded at 30%, 40% and 25% efficiency, respectively. For comparison, steam engines are 50% efficiency. 0_0
So, the gas turbines are the least efficient, while steam engines are the most. Shouldn't it be the other way round?

**Comment by Coolthulhu** [comment]
>  So, gas turbines are the least efficient, while steam engines are the most. Shouldn't it be the other way round?

Gas turbines are not that efficient alone. They do get mega efficient when combined with steam turbines and run at constant power, but that's not how they're used in the game.
Our steam engines could possibly get an efficiency nerf, partly for realism and partly for balancing. They're not the giant turbines used at constant power for electricity generation, so the 50% efficiency has no rationale.

But regarding this PR: is there a good reason to use gasoline engines over diesel? If not, gas engines could get a buff to something, like max power output at given size category.

**Comment by chaosvolt** [comment]
> But regarding this PR: is there a good reason to use gasoline engines over diesel? If not, gas engines could get a buff to something, like max power output at given size category.

Mostly seems to come down to personal preference in practice. Fuel spawns do vary a bit, generally gasoline tends to spawn commonly in small amounts while diesel and jp8 vehicles are rarer, but skewed towards larger stockpiles due to some of those spawns being big vehicles that can roll for fuel in multiple and/or bigger tanks. Both can potentially be plentiful if you hit the right location, like airports or helipads (also potentially including avgas for gasoline engines).

For diesel you can also get by in emergencies with lamp oil but while it's easy to produce it doesn't scale well, in my most recent laptop playthrough I got a Tankmod tank going using lamp oil and it took a decent chunk of a town's worth of zombies (and a lot of trying to make the tallow before it spoiled) to get 30 liters, which wouldn't have lasted me long but was enough to get started on a trip out of town. It was all a moot point however, because I'd completely forgot (somehow, despite being the one that picked that engine for the tank when I remade the old mod's vehicles to resemble IRL ones better) that I was running an Abrams and thus had a turbine engine the whole time, so I could've just been stealing gas from all the nearby cars the whole time...

Another time in a much older playthrough I'd got a humvee running off motor oil stolen from car engines, specifically ones from a bandit camp I'd happened to spawn not far from, which was less of a waste of time since that time it actually got the vehicle far enough to find some proper diesel and I wasn't forgetting about any easier sources of fuel that time.

**Comment by blot-runner** [comment]
> Gas turbines are not that efficient alone. They do get mega efficient when combined with steam turbines and run at constant power, but that's not how they're used in the game.

Hmm, the Google Almighty states the M1 Abrams specific fuel consumption as 0.289-0.3 kg/kWt-hours depending on the rpm. With JP-8 energy density of 44 MJ/kg it translates to 27-28% efficiency, close enough to 25%. You're right, apologies for derailing the discussion. 

> But regarding this PR: is there a good reason to use gasoline engines over diesel? If not, gas engines could get a buff to something, like max power output at given size category.

Speaking as a layman: I always thought gas/diesel boils down essentially to peak power/efficiency, so it sounds plausible. The only problem  is diesels provide more torque, which, to my knowledge, is not simulated in the game, so if the gas engines get a power buff, it'll provide a somewhat counterintuitive outcome of a heavy deathmobile performing better off-road with a gas engine than with a diesel. Not sure how impactful it is, though, with the Impenetrable Trees of Doom still a thing, the vehicles are mostly confined to the roads anyway.
BTW, I think IRL diesels are also noisier, harder to repair (no idea HOW harder) and have issues starting in winter (though I imagine that one is already in place with "E_COLD_START" flag).

**Comment by RoyalFox2140** [comment]
Diesel engines are a bit more powerful, slightly heavier, have better fuel options, and cold start flag. Cold Start does almost nothing but in winter it's harder to start the car.

I think if we talk about fuel based cars diesel is superior, but I think if we talk about vehicles overall I always go with solar because of how much power you can produce as you scale up, a good electric motor is just harder to find.

**Comment by karxi** [comment]
> > Gas turbines are not that efficient alone. They do get mega efficient when combined with steam turbines and run at constant power, but that's not how they're used in the game.
> 
> Hmm, the Google Almighty states the M1 Abrams specific fuel consumption as 0.289-0.3 kg/kWt-hours depending on the rpm. With JP-8 energy density of 44 MJ/kg it translates to 27-28% efficiency, close enough to 25%. You're right, apologies for derailing the discussion.
> 
> > But regarding this PR: is there a good reason to use gasoline engines over diesel? If not, gas engines could get a buff to something, like max power output at given size category.
> 
> Speaking as a layman: I always thought "gas vs. diesel" boils down essentially to "peak power vs. efficiency", so it sounds plausible. The only problem is diesels provide more torque, which, to my knowledge, is not simulated in the game, so if the gas engines get a power buff, it'll provide a somewhat counterintuitive outcome of a heavy deathmobile performing better off-road with a gas engine than with a diesel. Not sure how impactful it is, though, with the Impenetrable Trees of Doom still a thing, the vehicles are mostly confined to the roads anyway. BTW, I think IRL diesels are also noisier, harder to repair (no idea HOW harder) and have issues starting in winter (though I imagine that one is already in place with "E_COLD_START" flag).

Just of curiosity, how did you calculate that? I'm not familiar with the math regarding specific fuel consumption to efficiency.

On-topic, I'm a little uncertain of what the intended fuel pipeline looks like—recent changes to biodiesel crafting, alongside this change, have me a bit confused.
I take it there's no clean way to implement engine damage from using motor oil or lamp oil in an engine that expects higher-grade fuel?

**Review by RoyalFox2140 — APPROVED** [review]
I still think it's a good idea given gasoline engines are fairly worse, and additionally have no fuel alternatives that are renewable.

**Comment by blot-runner** [comment]
> Just of curiosity, how did you calculate that? I'm not familiar with the math regarding specific fuel consumption to efficiency.

No idea if this is a correct approach, but I went with the energy conversion efficiency, which is the ratio of the useful energy output to the energy input. Brake-specific fuel consumption is defined as the rate of fuel consumption divided by the rotational power produced, which translates into the fuel mass required to dish out one unit of useful energy (assuming all the rotational energy produced is useful, which is, I believe, not exactly correct IRL, but whatever). Thus, multiplying it by the respective fuel energy density (which can be viewed as the energy input per the fuel mass unit used) we get the ratio of the energy input to the useful energy output, and the inverse of that gives us the energy conversion efficiency.

Coming to the actual calculations, this document (https://www.tfd.chalmers.se/~thgr/gasturbiner/Material_for_generating_slides/Lecture2/AlliedSignal%20AGT%201500%20-%20Archived%203-1997.htm), which looks like some kind of a declassified military report, but, frankly, I've no data to confirm it, states SFC for the AGT 1500 gas turbine engine (M1 Abrams engine) is 0.30 kg/kWh at full power and 0.289 kg/kWh at 1200 shp (it's not stated explicitly, but it must be brake-specific fuel consumption, since the thrust-specific one is for jet engines), 1kWh = 3.6MJ, so it's 0.083333 x 10^(-6) to 0.080278 x 10^(-6) kg/J. SFC depends on the fuel used, so I assumed JP8, since, by my information, multi-fueled or not, this is what the M1s use in the US Army, so any specifications would probably be based on it. So, JP8 energy density is 44 x 10^6 J/kg, so AGT 1500 gas turbine energy conversion efficiency is 1 / (44 * 0.083333) = 27.27% at full power and 1 / (44 * 0.080278) = 28.31% at 1200 shp.

> I take it there's no clean way to implement engine damage from using motor oil or lamp oil in an engine that expects higher-grade fuel?
Something I'd LOVE to see, too) And from what I was able to understand, the tools are already present, it probably should work like the gun fouling. But, to my knowledge, it's not implemented.

**Pull request merged**
