### PR TITLE
feat: Basic framework for multiple attacks per weapon

### PR DESCRIPTION
**Pull request by Coolthulhu**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

- [X] This is a C++ PR that modifies JSON loading or behavior.
  - [X] I have documented the changes in the appropriate location in the `doc/` folder.
  - [X] If documentation for this feature does not exist, please write it or at least note its lack in PR description.
  - If applicable, add checks on game load that would validate the loaded data.
    - Uses other types, which are validated (`damage_instance`)
  - If it modifies format of save files, please add migration from the old format.
    - Artifacts don't seem to save fields the same way as other items, but finalization fixes them

## Purpose of change

Allow weapons to have multiple different attacks, like spear stab vs spear haft bash. Currently, all weapons have weird "omni-attack" attack, which tries to cover all possible attacks that can be executed with said weapon.

## Describe the solution

* Items get a new field, `"attacks"`
  * In most cases, auto-calculated from old fields
  * Allows specifying damage and to-hit bonus
* If only one attack is present, nothing changes compared to `main` branch
* If weapon with >1 attack is used against a monster, the attack with best `sum(dmg - armor)` is used

## Describe alternatives you've considered

* Leaving omni-attacks
* Simplifying attacks to 1 damage type per weapon

## Testing

* Tests pass
* Normal attacks against monsters and NPCs aren't broken

Also possible longer test (not necessary, since tests test that):
* Start game in a world with TEST DATA mod added to mods.json
* Spawn "two attack lucerne hammer", "unstabbable monster" and "unbashable monster"
* Wield lucerne
* Attack unstabbable monster - all attacks should be bashing (message like "you whack", "you batter")
* Attack unbashable monster - all attacks should be piercing ("you pierce", "you stab")

## Additional context

Sum of `dmg - armor` is obviously a placeholder. Later, I'd like it to include things like monster's current hp. Also, handle human armor.

### CODE REVIEW

**Comment by RoyalFox2140** [comment]
I'd like to stress test but since we've obsoleted MSYS2 I don't know how to compile now (and it took hours just to get MSYS2 functional the last time) Can you supply a test release like we did with Item Identity? I still want to learn to compile again but it would be faster this way for now.

I'd like to try out: 
1: Piercing and bash attacks on a rifle and maybe a pistol.
2: Piercing bash cut on a sword
3: See what is possible with magic, so maybe a cold or heat attack on a sword.

**Comment by chaosvolt** [comment]
Finally got it all loaded and before I could really get to martial arts testing uh.
image

It only showing one damage value seems like a problem.

**Comment by Coolthulhu** [comment]
> It only showing one damage value seems like a problem.

It's just a framework for now, not fully functional yet. The full rework will take a while and I'd like UI changes to come later, if possible.

**Comment by chaosvolt** [comment]
In that case, fair. I'll let Royal test stuff if they get the chance to, and possibly tomorrow I'll try to mess with seeing how it interacts with martial arts stuff.

**Comment by Coolthulhu** [comment]
> It only showing one damage value seems like a problem.

It's mostly just a framework for now. I will require a whole lot of updates before it can work properly.

>  1: Piercing and bash attacks on a rifle and maybe a pistol.

Alright, I'll need to test those. Probably also disable multiple attacks on bayonets for now, it's the only thing that affects things with old syntax.

**Comment by RoyalFox2140** [comment]
I should apologize, it appears I can still compile with my existing MSYS2 setup despite Scarf's changes to our compiling process. I'll see if I can compile at some point later today or tomorrow and do some weird stuff with the framework.

**Comment by chaosvolt** [comment]
No worries, I got distracted recently and didn't get the chance to test stuff either. @.@

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
