### PR TITLE
Merges shelled and unshelled nuts to remove activity deemed pointless, per request

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Balance "Remove pointless busywork of shelling nuts, per suggestion"

#### Purpose of change

Some recent discussion elsewhere in the Cataclysm community drew attention to the unrealistically long ten-minute recipe time for shelling nuts. This also reminded me of how the time needed to process nuts was one of many things that turned me off faction camps last time I tried it, as the bulk of edible forage results are in the form of nuts, and at 10 minutes per handful it's generally just tedious using nuts for any particular purpose.

Following feedback from Coolthulhu in discussion below, the distinction between shelled and unshelled nuts was deemed not worth bothering with, leading to the suggestion of obsoleting the need to actively crack nuts.

#### Describe the solution

~~Went with the reduction in time chosen by @ERRORCODE509 in their minor mod, crack_the_nut. They went with a time of 20 seconds, which in my experience seems reasonable for someone not interested in aesthetically pleasing intact halves. Alternative times that could be used instead (if desired) will be mentioned in alternatives.~~

~~Main difference is this reduces the time taken to uncraft the nuts since unshelling is currently handled via deconstruction, the mod mentioned above tackles this via re-introducing the old obsoleted recipes with corrected craft time instead.~~

There was a pull request (https://github.com/CleverRaven/Cataclysm-DDA/pull/35741) that aimed to solve this a while back, that got closed mainly because it tried to re-introduce the old recipes instead of changing the uncrafts. ~~So this solution still forces you to rely on uncrafting the nuts but still benefits from the reduction in time per uncraft.~~

1. Per feedback, all uses of shelled nuts have been merged into the base variety, so that all formerly-still-in-shell nuts are now ready to eat. As a bonus, this makes them consistent with acorns anyway, which spawn ready-to-eat despite mention of shells.
2. Descriptions for nuts changed to be ambigious as to whether they're shelled or not.
3. Obsoleted the uncrafts the initial commit set out to edit.
4. Added migration to update existing nuts.
5. Checked and updated both vanilla JSON and mods folder, only change needed in mods was one usage of shelled hickory nuts in Tolerate This.

#### Describe alternatives you've considered

1. The PR mentioned above favored time ranges of 5 or 10 seconds, which was deemed by feedback in PR discussion to be a bit too fast for a handful.
2. One minute would probably be the extreme high end for time taken to shell a few nuts with a hammer. Maybe 2-3 minutes if you're both using pliers instead *and* very delicately trying to salvage nice-looking pecan halves, based on personal experience.
3. Re-implementing the recipes anyway because recipe clutter is a silly reason to make.
4. Just letting the roasted nut recipes allow you to use unshelled nuts as components, either as-is or with an alternative recipe that takes about as long but requires throwing in a hammer quality.
5. Nutcracking proficiency. ~~Presumably grants a bonus while you're using the brawling martial art or Krav Maga.~~

#### Testing

1. JSON change checked for correct syntax and linting.
2. Started a character in build 2036 with enough skill to know how to bonk nut bois with a rock.
3. Saved, ported JSON changes over, and load-tested.
4. No errors reported on load.

#### Additional context

Mod credited for initial proposed change: https://github.com/ERRORCODE509/crack_the_nut

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Wait, unshelling nuts is survival 1? That's nuts.

Are nut shells really important enough to be a thing? If the processing is just 20 seconds and takes a rock, it can be skipped.

**Comment by chaosvolt** [comment]
> Wait, unshelling nuts is survival 1? That's nuts.

image

I'm fine with reworking it to skip this step, but it will add a bit more work to make existing nuts count as comestibles, obsolete de-shelled nuts, and replace any spawns of them with the base variant. Or other way around, however that'd work.

Whatever method you'd prefer?

**Comment by Coolthulhu** [comment]
> I'm fine with reworking it to skip this step, but it will add a bit more work to make existing nuts count as comestibles, obsolete de-shelled nuts, and replace any spawns of them with the base variant.

Yeah, it would be the best to have just one kind.
Unless there is a reason to have shells, it would probably be easier to migrate shelled to unshelled. The id should be of the nuts without shell/unshell implication, but unshelled if there are only shelled/unshelled ids and no neutral.
As for obsoleting: it would help if you removed them at first and checked load errors and only later added migration and obsoletion. That should be faster than hunting for the entries while they are still valid.

**Comment by chaosvolt** [comment]
> As for obsoleting: it would help if you removed them at first and checked load errors and only later added migration and obsoletion.

I can do that for the sake of quickly getting a list of places that still use the no-longer-desired ID, but I can also accomplish that via a search-in-folder in Notepad++, one search for json and then one for mods folder. Then of course adding a migration entry for the sake of all saves.

**Comment by Coolthulhu** [comment]
Nice.

I just noticed that before the change (ie. in current game), you need a rock to break the tough shell of a peanut. Reminds me of the Soylent bottle opening machine.

**Comment by chaosvolt** [comment]
>I just noticed that before the change (ie. in current game), you need a rock to break the tough shell of a peanut. Reminds me of the Soylent bottle opening machine.

Yeah, other discussion on the BN discord pointed out that quite a lot of nuts would reasonably be openable by hand, even if one were still interested in accurately simulating the act of opening them.

**Pull request merged**
