### PR TITLE
feat(balance): Wild Veggy, Mushroom Buff

### PR DESCRIPTION
**Pull request by yay855**
Increased the calorie count of mushrooms from 24 to 50 and wild veggies from 34 to 50; increased specific calorie-overriding recipes' calorie count to compensate. Also increased the number of mushrooms and wild veggies you can forage at once.

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

Wild veggies and mushrooms were fairly useless beforehand thanks to their exceptionally low calorie count; they weren't worth farming, and they were barely worth foraging.

## Describe the solution

Mushrooms and wild veggies have had their calorie count nearly doubled and their forage amount increased slightly, making them a better choice for foraging and farming players.

## Describe alternatives you've considered

Rebalance every single fruit and veggie out there to make them all worthwhile to eat, even if some are still worth more calories.

### CODE REVIEW

**Comment by yay855** [comment]
Mother_lover,_ the calorie test is based on mushroom soup.

**Comment by chaosvolt** [comment]
Comestibles test are most likely failing because recipes are calling for amounts of the `mushroom_soup_ingredients` crafting requirement now providing twice the calories they were earlier.

**Comment by yay855** [comment]
> Comestibles test are most likely failing because recipes are calling for amounts of the `mushroom_soup_ingredients` crafting requirement now providing twice the calories they were earlier.

Yeah, I figured. The question is, what can I do about it?

**Comment by chaosvolt** [comment]
> Yeah, I figured. The question is, what can I do about it?

```JSON
  {
    "id": "mushroom_soup_ingredients",
    "type": "requirement",
    "components": [
      [ [ "broth", 1 ] ],
      [ [ "mushroom", 1 ], [ "mushroom_cooked", 1 ], [ "dry_mushroom", 1 ], [ "morel_cooked", 1 ] ],
      [ [ "flour", 1 ] ]
    ]
  },
```
These already call for only one each of the ingredient, so my initial assumed solution of cut how many mushrooms are called for by this recipe in half won't work. I'd say start by trying this:
1. Increase the required broth and flour in that crafting quality from 1 to 2, leaving the mushrooms untouched.
2. Cut the amounts of this quality in all recipes that use it in half.

Hopefully then tests will pass, if not then will have to see what else is being fucky.

**Comment by RoyalFox2140** [comment]
Calorie changes are fine to me, feel free to merge when tests pass.

**Comment by chaosvolt** [comment]
Tests are already failed and still need fixing. If they don't tackle it by the time I get home I'll do it.

**Comment by chaosvolt** [comment]
So I just realized that the broth and flour is not alternatives but part of a component set actually, will fix the item calories in a sec.

**Review by chaosvolt — APPROVED** [review]

**Pull request merged**
