### PR TITLE
fix: nailboard trap is using nails again

### LINKED ISSUE #5074: Nailboard trap can be made with 20 glue and zero nails
### Describe the bug

image
You shouldn't be able to substitute glue for nails in a nailboard trap. When building directly from raw components, it should specifically require 18 nails and separately 2 glue or nails.

### Steps To Reproduce

Build a nailboard trap out of 20 glue, 3 planks, and zero nails.

### Screenshots

_No response_

### Versions and configuration

Current experimental, windows 10.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lamandus**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
Fixes #5074

## Describe the solution
make it use nails only for the nails part

## Testing
grafik

### CODE REVIEW

**Comment by Lamandus** [comment]
grafik

**Comment by chaosvolt** [comment]
That doesn't make sense because:
1. Making a nailboard trap from scratch requires 20 nails.
2. Making a nailboard requires 6 nails.
3. Making a nailboard trap from nailboards requires 3 nailboards, meaning 18 nails have been spent...

So can you guess that that extra two nails in the recipe are for?

**Comment by Lamandus** [comment]
> That doesn't make sense because:
> 
>     1. Making a nailboard trap from scratch requires 20 nails.
> 
>     2. Making a nailboard requires 6 nails.
> 
>     3. Making a nailboard trap from nailboards requires 3 nailboards, meaning 18 nails have been spent...
> 
> 
> So can you guess that that extra two nails in the recipe are for?

for connecting, THEN we can use it differently, 18 nails and 2 nail_glues

**Comment by chaosvolt** [comment]
Then update the first recipe to use 18 nails and 2 nail_glue to at least make it consistent?

**Comment by Lamandus** [comment]
grafik

**Review by chaosvolt — APPROVED** [review]
94f0653d30bd368e5dfe492f0f60e01e

**Pull request merged**
