### PR TITLE
Misc bugfixes from DDA 3

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
SUMMARY: None

#### Purpose of change
Removing bugs from the game

#### Describe the solution
CleverRaven#41447
CleverRaven#41743
CleverRaven#42751
CleverRaven#42951
CleverRaven#42933 (squashed with CleverRaven#43003)
CleverRaven#42645
CleverRaven#44102
CleverRaven#44146
CleverRaven#42149
CleverRaven#41631

#### Describe alternatives you've considered
Seeking dichlorvos

#### Testing
Underwent surgery by the nurse bot - dropped bionic is the correct one.
Drove through a tear in reality in a car - no errors, no teleportations, car is fine.
Tried hacking while Illiterate or when lacking charges for electrohack/bionic - failed, with no time spent; hacking with bionic/electrohack does not crash the game, can still fail or succeed and draws correct amount of charges/power.
Tried starting faulty engine via engine configuration menu - failed, as intended.
Made towing cable snap - message is fixed.
Threw around a bunch of molotovs - they blow up immediately and don't produce errors.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I just realized that molotovs are kinda bad. Could use a fun buff.

**Comment by DrPariah** [comment]
Does a fun buff involve clouds of confetti? 
--
Sent from myMail for Android Thursday, 05 November 2020, 01:26PM -06:00 from Coolthulhu  notifications@github.com :

**Comment by Coolthulhu** [comment]
Applying burn status to things in range and not just the ground.

**Comment by DrPariah** [comment]
Ooh, that's good. I like it! Though I'm still thinking about confetti Molotovs. 
--
Sent from myMail for Android Thursday, 05 November 2020, 01:36PM -06:00 from Coolthulhu  notifications@github.com :

**Pull request merged**
