### PR TITLE
Plant Mutant Rework [WIP]

### PR DESCRIPTION
**Pull request by acssimpson**
#### Summary

SUMMARY: Features "A whole bunch of changes to the plant muties, including a new mechanic - root spreading"

#### Purpose of change

Make plant mutants less boring, and give them a mechanic to help them deal with their absurd slowness.

#### Describe the solution

A root field that will lash out at attackers, and slow enemies inside of it. Gives the plant mutant a better means of holding their ground.

A whole bunch of clean up and QoL changes to the mutation tree [WIP]

#### Describe alternatives you've considered

A whole bunch of different propogation ideas, letting them spawn turret like plants from corpses, etc. A lot to work with here.

#### Testing
PlantRetal
PlantGrowthFinal2_actual
PlantGrowthCorners

### CODE REVIEW

**Comment by acssimpson** [comment]
putting this up as a WIP.
I know I need to clean up a lot of the code, but I figured I can get it up so if you see anything **alarming** you can let me know now.

I also know my plant growth code isn't very optimized. There are a few changes I plan on making.

**Comment by Night-Pryanik** [comment]
Root field shouldn't grow on the pavement and similar types of solid terrain.

**Comment by chaosvolt** [comment]
A simple check for the `DIGGABLE` flag would work if limiting propagation is desired. Alternatively, flavoring this as vines or kudzu would make it more reasonable to have growth not limited by terrain.

**Comment by acssimpson** [comment]
> Root field shouldn't grow on the pavement and similar types of solid terrain.

Once its over the pavement, the root growth is limited by distance from you. This was intended to enforce a fiction where the roots are able to exist on the pavement because you are sending them crawling over the top of the turf.

Balance wise, its important that you can use this ability to some extent over the non diggable, else you would be defenseless indoors.

**Comment by Coolthulhu** [comment]
```
/home/runner/work/Cataclysm-BN/Cataclysm-BN/src/map_field.cpp:75:1: error: Variable 'effect_bleed' declared but not used. [cata-unused-statics,-warnings-as-errors]
/home/runner/work/Cataclysm-BN/Cataclysm-BN/src/map.cpp:5631:12: error: the 'empty' method should be used to check for emptiness instead of 'size' [readability-container-size-empty,-warnings-as-errors]
/home/runner/work/Cataclysm-BN/Cataclysm-BN/src/map.cpp:5655:87: error: use nullptr [modernize-use-nullptr,-warnings-as-errors]
```

**Pull request closed without merging**
