### PR TITLE
fix: clang-tidy-wrapper's c++ fixes

### PR DESCRIPTION
**Pull request by RobbieNeko**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

Better code practices are nice, and this will hopefully prevent yelling at us by clang in the future.

## Describe the solution

Uses the included script by Scarf that acts as a wrapper for clang-tidy

## Describe alternatives you've considered

- Explode
- Implode
- Wait for someone else to do it

The script itself seemed to have some bugs (I had to change which flag it was using to tell it to fix the bugs for one, but it also complained about some missing files). However, any improvement is good

## Testing

I ***hope*** clang-tidy isn't going to break anything, or else we've got some very bad news for the project as a whole.

## Additional context

Thanks for RoyalFox asking me to run the script in the first place

Feel free to update the semantic title category as needed

Updated run command for the script:
```bash
$ parallel ./build-scripts/clang-tidy-wrapper.sh {} -fix-errors ::: src/*.{c,h}
```

### CODE REVIEW

**Comment by RobbieNeko** [comment]
Uh oh, looks like it made some bad fixes

**Comment by RoyalFox2140** [comment]
I don't know what went wrong but this script makes our problems worse, specifically: 
parallel ./build-scripts/clang-tidy-wrapper.sh {} -fix ::: src/*.{c,h}

Just for context from Discord where we were discussing it. It was supposed to fix the clang errors while Scarf was gone

**Review by scarf005 — CHANGES_REQUESTED** [review]
the changes seems to break namespace statements

**Comment by RoyalFox2140** [comment]
Stale, I'll reopen if we want to get this to work

**Pull request closed without merging**
