### PR TITLE
feat(content): house_fence07

### PR DESCRIPTION
**Pull request by LilShiningMan**
## Summary
SUMMARY: CONTENT "house_fence07"

## Purpose of change
more houses

## Testing
linted and spawned in game

## Additional context

house_fence07_1

house_fence07_2

house_fence07_3
house_fence07_r

### CODE REVIEW

**Comment by chaosvolt** [comment]
So many houses wow. XD

**Comment by LilShiningMan** [comment]
I'm working through my backlog, so 10ish more to go after this. 

Good question -- I'm going to be re-purposing some of these layouts for other specialized versions (under construction, derelict houses,etc). I've contributed some survivor layouts in the past, and I'd like to do so in the future, but I'm debating the best way to go about that. I realize putting a bunch of "normal" houses dilutes the pool of other specialized houses, so that's something I'd like to tackle as well. 

It's been a while, but from what I remember in CDDA they have a way of randomly switching things to other layouts like "looted" variants. Something like that for these houses would be great.

**Comment by chaosvolt** [comment]
Will be neat to see, then. In theory this can be done a bit with nested mapgen chunks, or even variant spawns of the same buildings. Nested chunk spawns will generally be more lightweight than having to specify entirely new om_terrain files however, just being a lil more complex to set up.

~~Speaking of the "simpler but clunkier" route, at some point I oughta add arcanist variants to some of those new houses to Arcana mod...~~

**Comment by LilShiningMan** [comment]
Yeah, one of my ideas was to have some nested chunks. I don't use those in any of my previous submissions but I have some other buildings yet to submit that use them quite a bit. They're really powerful in terms of what you can do. I'd have added some of them to these other submissions but honestly, I made all of these houses years ago and I'm pretty done with them and just want to get them out there so I can start on new stuff.

The tricky thing with the variants is it's only good for the one z level houses. As far as I know there's no way to have BN choose the same palette for all z levels of that instance of house.

And yeah, if you added some variants of these I'd be pumped to see them!

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
