### PR TITLE
feat: Large building new apartment start scenario

### PR DESCRIPTION
**Pull request by LucioFurnari**
### Required

- [ ] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [ ] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
I decided to add a new start to the apartment, since it seemed strange to only be able to appear on the roof, and not inside a house.

## Describe the solution
Add a new start to the stage by choosing one of the apartment floors.

## Testing
I tried several times, and it always appears in a house in the apartment, in general a zombie never spawns inside the house.

### CODE REVIEW

**Comment by LucioFurnari** [comment]
Yes, I'm sorry, I don't know why that change was added.

**Comment by RoyalFox2140** [comment]
> Yes, I'm sorry, I don't know why that change was added.

Your first commit carried over the explosive change, likely from another branch.

**Comment by LucioFurnari** [comment]
How i can remove that change, I don't know how it appeared

**Comment by RoyalFox2140** [comment]
> How i can remove that change, I don't know how it appeared

I just put the original number back for you, I don't really mess with Github CLI and proper reverts that much.

**Review by RoyalFox2140 — APPROVED** [review]

**Comment by LucioFurnari** [comment]
Thanks, and sorry for the commit, I didn't know what happened.

**Comment by scarf005** [comment]
nitpick: this doesn't seem to be a balance change. otherwise looks good

**Pull request merged**
