### PR TITLE
Mark factions' currencies as stackable

### PR DESCRIPTION
**Pull request by olanti-p**
#### Purpose of change
Refugee center merc asks for 750 Free Merchant certified notes, so it's expected that player may possess thousands of them.
Yet, the notes are handled as individual items, which imposes huge penalties on handling times. Picking up aforementioned 750 notes takes almost 13 in-game minutes, or 12 IRL seconds.

This PR marks items used as factions' currencies as stackable, and implements load-time merging of count-by-charges items that used to be non-c-b-c (e.g. glass shards after #748).

#### Testing
* Merc can be hired, consumes exactly 750 Merch
* Merchant gives proper amount of Merch as awards
* Trading migrated Merch works
* Broker gives proper amount of Merch for meat jerky
* Merches (Merchs?) merge into stacks on load, no matter where they were (on map, in vehicle, on character)

#### Additional context
* You can level traps 1 almost instantly if you find a big enough pile of glass shards.
* Some NPCs, particularly Tacoma ones, have existing issues with how they handle payment for services.
    I've fixed some of those issues, but that'll have to come in another PR.
* Dropping 750 notes takes 80 IRL seconds (!?) on official Win release; VS release build is much faster - approx. 8 seconds.
    Not sure where such disparity comes from.
    <details>
    <summary>VS profiler output</summary>

    image  

    </details>

### CODE REVIEW

**Comment by olanti-p** [comment]
@Zireael07 Marking rags and glass shards as `"stackable": true` will definitely solve the issue for those items, but I believe that solution falls under `PRs making some culprits "charges"` category.

The load time merging is for migrating existing submaps where items were saved as individual instances of non-stackable item, it won't do anything for the issue on its own. The game works fine even without it, but such unmigrated piles look extremely ugly in UI:

**Comment by Coolthulhu** [comment]
> Dropping 750 notes takes 80 IRL seconds (!?) on official Win release; VS release build is much faster - approx. 8 seconds.

I bet it's optimizing some repetitive bit out.
That `get_item_position` sure looks bad in the profile, from what I can tell, it does a full scan on the inventory for every item.

**Comment by Coolthulhu** [comment]
That re-merging thing is helpful, but in cases of temporary migration stuff, it's OK to let it stay mildly bugged sometimes, like until first restack.

**Comment by olanti-p** [comment]
I mostly added it with future migrations of this kind in mind.
Seeing those broken stack for a few types of items is ok, but if they'd be commonplace, that would get annoying real fast.

**Pull request merged**
