### PR TITLE
feat(mods/teleportation_tech): Teleporter mod

### LINKED ISSUE #3164: Expose player teleport function to lua
### Is your feature request related to a problem? Please describe.

I have no idea what I'm doing with C++, so I would like to request someone exposes
"void place_player_overmap"
to LUA.

I've put together a teleporter mod, most of the functionality is implemented the actual teleportation step is missing, and the best would be the above function I could throw a tripoint in and move the player to the chosen overmap.

Many thanks for any help!

I'll be posting (and linking) the in-progress mod PR shortly. #3165 there we go

### Describe the solution you'd like

void place_player_overmap exposed to LUA

### Additional context

If someone exposes item spawning and explosion effects I have a few other ideas for mods I would implement!

### PR DESCRIPTION
**Pull request by borsek**
## Purpose of change

- fixes #3164

With LUA modding added to CBN, I tried my hand at making a sensible teleporter mod. With this mod, a static base should be much more viable.

If possible with LUA, I intend to extend it to vehicles (stations and anchors as vehicle parts). I'd probably need some more hooks for that, but there could also be workarounds.

## Describe the solution

The mod description is in main.lua. In short - the player places teleport stations and anchors (by using the respective items, which use LUA to place furniture). Everything else is done by using the 'teleporter remote' item.

Stations fill by 1 energy per hour, and can also be pumped with grid energy to get 'charge'. 1 charge allows teleporting for 1 overmap tile. The station charging is done locally (player and grid with power must be on the teleport station omt) with a teleport controller, allowing the player to convert 1000kj into 1 charge for a picked station.

Using a teleport controller, the player can teleport from anywhere (charge permitting) to a teleport anchor (placed furniture), using a station, provided the station has enough power, 

The hourly charge and kj-to-charge variables are easily modified by the user in main.lua.

## Describe alternatives you've considered

Play more Avorion instead of coding.

## Testing

No major bugs. Some features I want still need to be implemented.

## Screenshots

image

image

image

image

image

image

### CODE REVIEW

**Comment by borsek** [comment]
Oh, I'm totally open to any suggestions, code improvements, etc.

very noob coder, so any help is appreciated!

**Comment by Ali-Anomma** [comment]
> Oh, I'm totally open to any suggestions, code improvements, etc.
> 
> very noob coder, so any help is appreciated!

what about ability of naming the waystations?

**Comment by borsek** [comment]
I haven't checked this for compatibility since my last update, but I needed #3164 done to finish up. Obviously the naming suggestion is not in as of yet, but I can get around to it at some point, if not otherwise, then as an update - I get it though, name teleport destinations as "lab" "home" etc.

**Comment by borsek** [comment]
Need the item spawning on ground/in player inventory functions added, otherwise should work if scarf merges his lua update, at least the teleportation will, that is.

**Review by scarf005 — APPROVED** [review]
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/8b30fa31-ec8d-46f5-9d17-02e3dedb4619

sorry for the long delay. while our Lua infrastructure has much to desire, the mod work alright, and this would be the stepping stone for better Lua support.

thank you for the hard work.

**Comment by scarf005** [comment]
future planned issue:
- add Lua formatter
- format all Lua files
- document Lua style guide

**Pull request merged**
