### PR TITLE
Ammo rebalance project, part 7

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Balance "Ammo rebalance part 7, shotshells and sci-fi ammo"

#### Purpose of change

This should be the last major part off the ammo rebalance project, barring any refinements to the formulas in use, or should we also apply this to some other things like explosive ammo.

#### Describe the solution

- [X] First and foremost, after some discussion and feedback from others, I was talked into reworking how armor penetration is set for FMJ and AP rounds, with the below ammo having this new scaling implemented. Before, FMJ was considered to have 125% Effective Damage relative to HP, and AP had 140%. Now the values are 115 and 130, making expected performance against ballistic armor more forgiving.
- [X] Updated documentation accordingly.
- [X] 5mm has been tweaked to be in line with the other military ammo, with its baseline version fitting the stats of an AP round. The high-velocity version meanwhile sets the idea of sci-fi AP++ ammo having boosted damage and arpen over standard AP
- [X] Damage of baseline 8x40mm adjusted slightly to differentiate it better from other ammo. Standard caseless acts like FMJ, HVP balanced as AP++ like with 5mm penetrators, JHP acts as hollowpoint, etc.
- [X] Balance updates applied to 20mm shells, per Coolthulhu's request, phased out the idea of low-velocity FMJ, so now big slow bullets like slugs get their full expected arpen value anyway. Slugs in this case balanced as FMJ, flechette as AP.
- [X] Flintlock ammo updated, with standard cartridges gaining FMJ levels of arpen, and paper shot being balanced as JHP.
- [X] Shotshells rebalanced with slugs gaining FMJ stats, flechette shells balanced as AP.
- [X] LeMat shot cartridges given the expected tweak to slugs relative to the shot version.
- [X] Blunderbuss ammo updated, slugs balanced as FMJ, while flechette rounds are balanced like AP to allow it to have lower damage but more arpen. Additionally, all blunderbuss rounds have been given an ammo_multiplier of 1.5.
- [X] Balanced 40x46mm buckshot, slugs, and flechettes accordingly, with slugs and flechettes getting low-velocity FMJ and FMJ stats relative to M576 buckshot respectively.
- [X] Added migration of makeshift M956 40mm shells to just become regular buckshot shells. The recipe for it is now obsoleted, in favor of allowing the player to craft M576 buckshot shells.
- [X] Updated migration stuff in Generic Guns accordingly.
- [X] Altered names of 40mm shells to make it clear what type they are at a glance, as well as descriptions for the handload making it clear what casing they use.
- [X] Likewise updated descriptions of 40x46mm casings to clarify which loads they were specific to, and which ones are actually useful.
- [X] Also updated 40x53mm, obsoleted improvised flechette rounds in favor of allowing the player to make standard M1001 shells, and added the requisite updates to names for clarity.
- [X] Migrated 8x40mm FMJ into regular 8x40mm caseless, as standard caseless is now specifically balanced as FMJ and an "also just FMJ" round would be redundant. Removed it from the standard ammo itemgroup, and replaced with HVP and JHP in a couple military itemgroups where it showed up (this also means that HVP is no longer absent from group `military`, and JHP is no longer absent from group `mil_hw`).

#### Describe alternatives you've considered

1. Replacing 8x40mm FMJ with something like non-HVP AP or +P rounds.
2. Phasing out all the different 40x46mm casings in favor of generic 40x46mm casings.

#### Testing

Checked affected files for syntax and lint errors.

#### Additional context

A related issue this affects would be https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1455, since it reduces base damage of slugs, along with introducing a drawback specific to blunderbuss ammo overall. Pinging @RodriguesCIA for their thoughts on if this would be enough to resolve the original issue, together with previous PRs that made pipe guns a bit less hassle to make.

### CODE REVIEW

**Comment by chaosvolt** [comment]
So, regarding the endless varieties of 40mm casing and how it leads to several identical versions of 40mm buckshot and slug, should we:
1. Make these cases generic since we don't care about, for example, 2.75-inch vs 3-inch shells for 12 gauge?
2. Make them vary in damage and resource cost a bit based off whatever info I can find about casing lengths?
3. Simply phase out the handloaded version of M576 and keep the other handloads as variants that're all statistically identical to the standard buckshot load aside from different casing?

I might start with 3 for the moment then shift to 1 or 2 if requests by Coolthulhu, not sure at present. Either way buckshot handloads should be shifted towards being in line with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1481 presumably.

**Comment by Coolthulhu** [comment]
Conflicts with #1851, will test the earlier one first.

**Comment by chaosvolt** [comment]
Whoops, forgot that resolving merge conflicts would be needed. There we go.

**Comment by chaosvolt** [comment]
So, per https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/2042#discussioncomment-4110681 I'm pondering some considerations that would not only affect this PR but warrant going back and adjusting over stuff too, in particular:

> We adjust it so that the Effective Damage (damage+arpen) for FMJ and AP is lower? For reference, per Coolthulhu's advice, balancing off HP as the assumed default of 100% damage, FMJ has 125% Effective Damage (80 damage, 45 arpen), while AP has 140 (70/70). Targetting 115% and 130% (80/35 and 70/60) might help nudge things down to make it less painful when scaling things up.

This seems the most likely to get results that nudge arpen of high-damage rifle ammo back down to something sane, along with making AP ammo look less janky. I'd need to update the values in this PR, update the documentation, then set aside a PR to go back and update other values, if a decision is made on this.

**Comment by Coolthulhu** [comment]
> slugs balanced as low-velocity with reduced arpen

Why?
2good as regular?
Slugs are supposed to be the armor piercing ammo for shotguns.

**Comment by chaosvolt** [comment]
> 2good as regular?

Because the arpen would be on par with rifle rounds, when one of the things with slugs is while they can penetrate armor better than buckshot, they won't mess up kevlar anywhere near as badly as even a .223 rifle round will. Plus it builds on the consistency set elsewhere for big, slow bullets that aren't hollowpoints being balanced as FMJ with reduced arpen.

That said, I'm still more concerned about the question I raised in the issue. I'm really wondering if I should switch to a 115/130 standard for FMJ and AP instead of 125/150, because it makes the issue of getting killed through ceramic vests in a couple shots much less of a concern. Example: 7.62x51mm would deal 26 damage through ceramic MBR vests instead of 33, while 5.56x45mm would deal 6 damage through it instead of 11.

**Comment by Coolthulhu** [comment]
> Because the arpen would be on par with rifle rounds, when one of the things with slugs is while they can penetrate armor better than buckshot, they won't mess up kevlar anywhere near as badly as even a .223 rifle round will.

Seems like realism over gameplay here.
If you think we should have different rules for some ammo types, it would need to be written down somewhere and analyzed regarding gameplay implications. Shotguns certainly don't need to get worse when compared to rifles.

**Comment by chaosvolt** [comment]
Alright. I'll have to mess with it when I get home, along with most likely messing with arpen logic as noted above.

**Comment by chaosvolt** [comment]
Per my musings earlier and Coolthulhu's feedback, I've scrapped the idea of low-velocity FMJ having half the expected arpen of regular FMJ. In addition, implemented the nerf I mentioned for how arpen is calculated for FMJ and AP ammo.

I'll need to also PR a part 8 and/or 9 that applies this rework to all the other ammo I touched, but when I do it'll make 5.56mm and 7.62mm a lot less of a pain in the ass to balance.

**Pull request merged**
