### PR TITLE
feat(balance): place soldering iron fix

### PR DESCRIPTION
**Pull request by yay855**
The 'place soldering iron' construction no longer requires a soldering iron as the tool and the ingredient.

## Purpose of change

The 'place soldering iron' construction was buggy, requiring three soldering irons in total (one with a battery, two without) to attach a single one to the power grid, and it still only consumed one of them.

## Describe the solution

Now, instead of requiring a second soldering iron, the recipe presumes that the soldering iron you use as an ingredient is used to prepare the hookup.

## Testing

I have tested it ingame, it works nicely.

### CODE REVIEW

**Comment by yay855** [comment]
> The recipe is mine, so I gonna bite. Does the new recipe need any electricity? Because how do you attach the soldering iron, when it doesn't use any electricity?
> 
> Rather than adding a hacky way to circumvent the problem, someone should take a look into the code to repair it there.

I understand not wanting a hacky way to circumvent the problem, but this has been an ongoing problem for at least two years now.

**Comment by yay855** [comment]
> > > The recipe is mine, so I gonna bite. Does the new recipe need any electricity? Because how do you attach the soldering iron, when it doesn't use any electricity?
> > > Rather than adding a hacky way to circumvent the problem, someone should take a look into the code to repair it there.
> > 
> > 
> > I understand not wanting a hacky way to circumvent the problem, but this has been an ongoing problem for at least two years now.
> 
> There is one other way of doing it. Make it a 2 step construction. One for preparing the calbework (so anything you need the soldering iron for) and the 2nd step of plugging it in. Like those multi step door or window recipes.

That's actually a good idea, I'll start working on that.

**Comment by VissValdyr** [comment]
That can be some kind of "construct grid socket" kind of thing. Maybe it can be used for all installations of grid related stuff (yes even fridge and oven, even if this means it is locked behind a "electrics skill", not like now, where a lvl 0 character can install it)

**Comment by VissValdyr** [comment]
Ooh, if we do the socket thing, we can maybe even plug stuff out (simple deconstruct) and plug others in.

And even provide 1 or 2 socket slots to shelters, lmoe and other pre installed grid things.

**Comment by yay855** [comment]
Right, that's a good idea; I'll get started on adding in the socket furniture, what kind of sprite should it use, do you think?

**Comment by yay855** [comment]
I 100% appreciate suggestions as to what I did wrong, it's throwing errors but I don't know how to fix them.

**Comment by yay855** [comment]
Alright, Kheir is going to investigate the source of this bug and see if they can't fix the bug that started all this. This PR is on standby for now, and likely to be deleted.

**Pull request closed without merging**
