### PR TITLE
Humvee headlight reduction, and GL ammo change to 40x53mm

### PR DESCRIPTION
**Pull request by metalheimer**
#### Summary

Humvee had 3 headlights and they were placed asymmetrically. One of them resided on a windshield tile. No more. Also changing GL ammo to 40x53mm because that's what it uses (and not 40x46mm).

#### Purpose of change

The placement of the 3rd headlight never made sense. This is a very old and serious issue. So very serious.

#### Describe alternatives you've considered

I thought about relocating the 3rd light but eh.

#### Testing

(EDIT1) I deny any allegations of testing any chang... AHEM, what I mean now is that I spawned each Humvee variant and they correctly spawned with 2 reinf headlights, in right places even. The GL works too.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
> Absolutely no testing was done. Idk if I've ever modified a vehicle before. But looking at the JSON, it seems pretty straightforward.

To test you can use debug menu. And spawn->vehicle from there.
You can look for instruction here: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/.github/CONTRIBUTING.md#in-game-testing-test-environment-and-the-debug-menu

Testing from PR creator side always should be done if it is possible- this way we are making even experimental builds stable. Even if change looks simple- there is always something can go wrong.

Please test your PR. It is required.

**Comment by Firestorm01X2** [comment]
@metalheimer by the way- we have discord server. Feel free to join.
Permanent link to server: https://discord.gg/XW7XhXuZ89

**Comment by metalheimer** [comment]
Well, this got tricky. Humvee appears in 3 mods, and has 3 variants. Good thing I tested everything thoroughly and not try to push through untested changes. I mean, who would do such a thing? Stop looking at me.

**Comment by metalheimer** [comment]
> Please test your PR. It is required. Just spawn modified car via debug and check if everything right. If you have questions, regarding working with debug menu- feel free to ask.

Yes... testing always is probably wise, or at least the professional thing to do. I know my way around the debug menu.

**Comment by metalheimer** [comment]
So ummm since I 'm new, is there a reason why some checks fail? It's not a linting issue, is it? I'm pretty sure I got my stuff sorted out. Got all the humvees, all the variants, in all mods... (Beavis voice).

**Comment by Zireael07** [comment]
Looks like the vehicle efficiency test fails, probably because your humvees mass is now slightly different w/o the third headlight

**Comment by metalheimer** [comment]
I see. I guess the check efficiency test system itself could use a tweak. It shouldn't fail due to minor vehicle weight changes. Give it a 5% leeway for mass change maybe? Or solid number like 100lbs or 20kgs?

**Comment by Firestorm01X2** [comment]
@metalheimer 
This will change the test to pass:
изображение

**Comment by Firestorm01X2** [comment]
Good. But one more line left:

Change it  (line 451)    

`test_vehicle( "humvee", 5503245, 767900, 306900, 25620, 9171 );`

To


`test_vehicle( "humvee", **5502045**, 767900, 306900, 25620, 9171 );`

**Comment by metalheimer** [comment]
Blah. I screwed up. That map_extras update (typo fix) wasn't supposed to end up here but be its own PR, and idk how to delete it.

**Comment by Firestorm01X2** [comment]
> Blah. I screwed up. That map_extras update (typo fix) wasn't supposed to end up here but be its own PR, and idk how to delete it.

You can revert commit using git revert.

It may be easier to just put old value back and do commit and push. It is an option as well.

**Comment by Zireael07** [comment]
You *should* be able to fix this somehow but I'm not 100% sure. Rewinding the branch to one commit earlier and force pushing? Hopefully someone more certain will come along and help.

**Comment by Firestorm01X2** [comment]
> Blah. I screwed up. That map_extras update (typo fix) wasn't supposed to end up here but be its own PR, and idk how to delete it.

Also that is what is why should create separate branch for each PR.
But in this case as I said  - it is easy fixable.
Just edit value back and commit it and push. But just that value.

**Comment by Firestorm01X2** [comment]
@metalheimer Great! It worked. Now I can finally review PR and merge it. Just do not push anything.

And for the future PRs - alsways create separate branch for each PR! This will help to not mess things.
Do not create PRs from upload branch.

**Comment by Firestorm01X2** [comment]
I have to note that this  change affeccted obsolatemod "Salvaged Robots". I've tested the change - everything fine, except mod itself loading with errors, unrelated to this PR. Mod was obsoleted for the reason, I guess.

**Pull request merged**
