### PR TITLE
Port Relative/Proportional Support in Generic Factory. Port Mod Source.

### PR DESCRIPTION
**Pull request by KheirFerrum**
#### Summary

SUMMARY: Infrastructure/Interface "Port Relative/Proportional Support in Generic Factory. Port Mod Source."

#### Purpose of change

Mod Source PR will be immensely helpful to help track down bugs and issues with both mods and vanilla items, by clearly indicating what source the item is from and what mods have affected it.

Also, as @thelonestander has asked me to walk through the process of this PR, will be doing it in more increments and logging my thought processes in between and after commits.

#### Describe the solution

Ports over [#43144](https://github.com/CleverRaven/Cataclysm-DDA/pull/43144) which is necessary for the function of the mod source PRs. Edits it as BN has quite a few changes to the ecosystem to consider.

Will then port over [#49723](https://github.com/CleverRaven/Cataclysm-DDA/pull/49723) and [#51277](https://github.com/CleverRaven/Cataclysm-DDA/pull/51277). Furthermore, will update the mod source PRs such that items in containers will also be tagged appropriately.

Made Debug Mode a requirement for mod source to be listed, as
- If you need to use it you're probably debugging something.
- Some concerns have been raised that seeing this in vanilla may be distracting and immersion breaking.

#### Describe alternatives you've considered

- Work around the need for `cata_void.h` and other systems that I'm not sure of the use for.
Beyond my expertise, and at a glance it seems to provide more options without drastically impacting performance, so I've decided to use it anyway.

#### Additional context

### CODE REVIEW

**Comment by KheirFerrum** [comment]
A merge conflict was noted by github, specifically an entire block of code from line 860 onward in `generic_factory.h`. After consideration, the section was removed entirely, as it was learned that much of the code affected had actually been shifted to `generic_readers.h` instead, so the changes to the reader were instead moved to that section.

**Comment by KheirFerrum** [comment]
A merge conflict was noted by github, specifically an entire block of code from line 860 onward in `generic_factory.h`. You can see the changes that are within this line of code [here](https://github.com/CleverRaven/Cataclysm-DDA/commit/add6f7d0aa1dd0baa8ccd49dd6b638a4650ef8f5#) after line 910/1077 of `generic_factory.h`. After consideration, the section was removed entirely, as it was learned that much of the code affected had actually been shifted to `generic_readers.h` instead, so the changes to the reader were instead moved to that section.

Furthermore, DebugLevel was changed to DL in Bn itself, thus `generic_factory.h` references to it had to be adjusted.

**Comment by KheirFerrum** [comment]
@olanti-p noted that the `support_proportional` templates themselves needed to be moved into `generic_readers.h` in order for the system to function.

**Comment by KheirFerrum** [comment]
3 Merge conflicts total in above commit. 1 in `item_factory.cpp`, involving a block of code from [here](https://github.com/CleverRaven/Cataclysm-DDA/commit/8ce3dc53a7453df6b2589e2b52103ba11a5aedd2#diff-1e01c1cff2c08cfea4f0cdbec28db8b93440c2088e4587b29f00bc06289f9a27) from line 3082 to line 3099. It was determined that lines 3087 and onward were code for nested containers, and thus were removed.

2 involved `output.h` involving code from [here](https://github.com/CleverRaven/Cataclysm-DDA/commit/8ce3dc53a7453df6b2589e2b52103ba11a5aedd2#diff-3bb338c28a4e486e44afbcd436e3387aa9acf8b2c4bf286fce849cc5c5d869fd) from line 675 to 676 and line 696 to 697. This was determined to be because BN had more `enumeration_conjunctions` than DDA at the time, so they were both folded into the list.

**Comment by KheirFerrum** [comment]
Mod tracking for monsters was slightly more difficult than anticipated, as DDA was using ostringstream for monster `print_info` function. A few tweaks were necessary and code from lines 651 to 657 [here](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1875/commits/d8f260efca8c7284868db851b5eaf530d6b80e27#diff-93bf2d875a96b58e6dec4bf3aeea7756b1747513da879599505c8e8640daabb9) can be compared against lines 654 to 661 [here](https://github.com/CleverRaven/Cataclysm-DDA/commit/cf533db586c67e15f5934b5504d9e7491966f301#diff-93bf2d875a96b58e6dec4bf3aeea7756b1747513da879599505c8e8640daabb9).

**Comment by KheirFerrum** [comment]
Mod tracking for monsters was slightly more difficult than anticipated, as DDA was using `std::ostringstream` for `monster::print_info` function. A few tweaks were necessary and code from lines 651 to 657 [here](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1875/commits/d8f260efca8c7284868db851b5eaf530d6b80e27#diff-93bf2d875a96b58e6dec4bf3aeea7756b1747513da879599505c8e8640daabb9) can be compared against lines 654 to 661 [here](https://github.com/CleverRaven/Cataclysm-DDA/commit/cf533db586c67e15f5934b5504d9e7491966f301#diff-93bf2d875a96b58e6dec4bf3aeea7756b1747513da879599505c8e8640daabb9).

**Comment by KheirFerrum** [comment]
Debug Mode was made a requirement for it to print Mod Source messages, and Mod Source was added to items within containers so that liquids won't be untraceable.

**Comment by Coolthulhu** [comment]
Great!

One thing worth changing: instead of using `debug_mode`, it should use an option. `debug_mode` is clunky to use because it tries to do too many things at once.

**Pull request merged**
