### PR TITLE
Add Electric Forge and Electrolysis Kit furniture versions

### PR DESCRIPTION
**Pull request by Dueu**
#### Summary

[Content] "I made electric forge and electrolysis kit tools installable in a electrical grid"

#### List of content added

- Electric Forge
- Electrolysis kit

#### Minor changes

- I fixed a typo error that made the "Place arc welder" seems out of place in the construction menu

How it was before

Fixed version

- Installing grid tools no longer requires a jumper cable, instead it requires 5 charges of copper cable.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Now that I think about it, jumper cable is a bit expensive for those. Same for the welder.

How about changing it to power converter, plus maybe 5-10 copper cables?
Power converter represents the AC-DC conversion, since building grid is supposed to be the regular "wall socket" grid.

**Comment by Coolthulhu** [comment]
The JSON validation check failed. I see you have tabs in your files. You'll have to convert them to spaces.
Tabs and spaces display the same in many editors, but good editors have an option to only use spaces and to convert tabs to spaces.

**Comment by Dueu** [comment]
> The JSON validation check failed. I see you have tabs in your files. You'll have to convert them to spaces.
> Tabs and spaces display the same in many editors, but good editors have an option to only use spaces and to convert tabs to spaces.

Fixed

**Comment by Coolthulhu** [comment]
"Power converter" is a component in itself. It has ID `"power_supply"`.
Without it, you're supplying AC to a welder(/forge/electrolysis kit) that expects DC.

I'm not going to fuss over realism much, but that power converter also represents some gameplay cost. It's not as rare as a jumper cable, but still a bit harder to get than copper cable.

**Comment by Dueu** [comment]
> "Power converter" is a component in itself. It has ID `"power_supply"`.
> Without it, you're supplying AC to a welder(/forge/electrolysis kit) that expects DC.
> 
> I'm not going to fuss over realism much, but that power converter also represents some gameplay cost. It's not as rare as a jumper cable, but still a bit harder to get than copper cable.

I forgot that change when you recomended it. Thanks

**Pull request merged**
