### PR TITLE
feat: New/Updated door sprites

### PR DESCRIPTION
**Pull request by thedyze**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional
 - [x] I have documented the changes in the appropriate location in the `doc/` folder.

## Purpose of change
To improve door graphics. The current ones were quite lacking in contrast and polish.

## Describe the solution
Added new door sprites or updated existing ones.

doors_final

## Describe alternatives you've considered
Redoing all the door. Ran out of steam, so there still is some future work to do.

## Testing
Spawning doors with the terrain editor.

### CODE REVIEW

**Review by RoyalFox2140 — APPROVED** [review]

**Review by chaosvolt — APPROVED** [review]

**Comment by NobleJake** [comment]
The new doors and the sharpened floor tile colors are nice individually, but as you can see in the photo, they look awkwardly out of place as a whole, like they belong in an RPG Maker game, not an Undead people tile.

**Comment by NobleJake** [comment]
@thedyze The new doors and the sharpened floor tile colors are nice individually, but as you can see in the photo, they look awkwardly out of place as a whole, like they belong in an RPG Maker game, not an Undead people tile.

**Comment by RoyalFox2140** [comment]
> @thedyze The new doors and the sharpened floor tile colors are nice individually, but as you can see in the photo, they look awkwardly out of place as a whole, like they belong in an RPG Maker game, not an Undead people tiles. I think it would be a good idea to break out these tiles as mod for those who want the old tile styles.

Then delete them from your files.

**Comment by thedyze** [comment]
> @thedyze The new doors and the sharpened floor tile colors are nice individually, but as you can see in the photo, they look awkwardly out of place as a whole, like they belong in an RPG Maker game, not an Undead people tiles. I think it would be a good idea to break out these tiles as mod for those who want the old tile styles.

I'm gonna respond here for "official" reasons. There is an ongoing discussion on Discord regarding this.
When leaving feedback (which I very much appreciate) it would be a lot more constructive if the following points are taken into account.

- Post the comment while the PR is open (or ping me on Discord) so I have a chance to easily make adjustments.
- Be precise in your feedback, and suggest changes to the sprites that in your opinion would improve it. Sweeping statements are really not that helpful.
- Take part in the development channel on Discord as I generally post sprites there while they are still wip.

**Pull request merged**
