### PR TITLE
feat(content): allow mounting flags on vehicles too

### PR DESCRIPTION
**Pull request by chaosvolt**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

A small followup to the flavor addition of flagpoles, for people who prefer their bases mobile.

## Describe the solution

1. Defined a vehiclepart for a flag mounted on the roof, in the same vein as sails are now.
2. Added sprite to UDP external tileset, after having confirmed in testing earlier that a multi-tile sprite works correctly in this case (in short: don't have it extend into tiles to the right and don't allow it to rotate, or it will layer wrong).
3. And predictably, cooked up vehiclepart entries and sprites for pride flag mod. This time I remember to copypaste the description stuff Robbie added.

## Describe alternatives you've considered

Making the flagpole sprites single-tile just to avoid encouraging people from using this feature too much and learning the hard way that vehicle sprite rendering always places tiles on the right over anything in the way, meaning anything that extends to the right will get covered up like this:
image

## Testing

1. Checked affected files for syntax and lint errors.
2. Installed flags on a vehicle and checked again to confirm they look correct and don't have parts showing under other roof tiles, no matter vehicle orientation.
3. Loaded up pride flag mod and slapped all the relevant flags on a vehicle.

Wagons in multiple orientations, with solars to make sure fellow `on_roof` tiles don't add any new problems:
image

Party bus, showing all the pride mod flags:
image

### CODE REVIEW

**Review by RoyalFox2140 — DISMISSED** [review]

**Comment by chaosvolt** [comment]
I forgor the external tileset documentation again aaaa

**Comment by RoyalFox2140** [comment]
> I forgor the external tileset documentation again aaaa

I question why we document every sprite we add in a document tbh

**Comment by chaosvolt** [comment]
Eh, mostly to help me keep track of what all stuff will someday need sprite compatibility in other tilesets. If I ever get around to Ultica external_tileset for example it'll basically be my todo list.

**Review by RoyalFox2140 — APPROVED** [review]
Okay, now that you've documented it.

**Pull request merged**
