### PR TITLE
fix(i18n): metric bullets part 1: rename `.223` -> `5.56x45mm`

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: I18N "metric bullets part 1: rename `.223` -> `5.56x45mm`"

#### Purpose of change

part 1 of #2690.

1. the inconsistency in displayed bullet diameter was causing issues. 
    - you need to search twice, once for `.223` and once again for `5.56`.
    - some bullets use `5.56 NATO`, 
    - `5.56x45mm ammo belt` is crafted from `.223 ammo belt linkage`, unintuitive.
2. `.223` and `5.56x45mm` are [technically of same calibre](https://en.wikipedia.org/wiki/5.56×45mm_NATO),
3. therefore, it'd be safe to display `5.56x45mm` first then display it's a `.223`.

#### Describe the solution

1. changed default display name of `.223` to `5.56x45mm`.
2. regex-replaced occurances of `.223` to `5.56x45mm`.
3. changed name of `.223 Remington` to `5.56x45mm '.223 Remington'`.

#### Describe alternatives you've considered

- rename ammo id `223` to `5.56x45mm` as well, but that'd cause issues with previous saves. also id migration is undocumented.
- use shorter name, e.g `5.56mm` where appliable, as iirc cata only has one variant of 5.56mm wheras 7.62mm has multiple (7.62x39mm(soviet), 7.62x51mm(NATO), 7.62x63mm(30-06 springfield)

#### Testing
loaded without problems.

image
all 5.56 / .223 calibre bullets can be searched at once.

Cataclysm: Bright Nights - cbn-experimental-2023-04-24-0723_02
ammunition type is displayed as "5.56x45mm".

### CODE REVIEW

**Comment by chaosvolt** [comment]
Thing is also that both of these are bullet sizes, so the consistency is already broken (and kinda has to be broken if we want the item to be at all easy to tell apart from the other 5.56mm ammo, because it being the US-unit variant is literally the distinguishing factor).

**Comment by scarf005** [comment]
But the point is that it being distinguishable from 5.56mm is the problem. lores aside, they're the same 5.56x45mm bullet with different damage property. player should be easily able to figure out that these bullets are interchangeable for their bullet without prior knowledge with ammos.

> if we want the item to be at all easy to tell apart from the other 5.56mm ammo

but the point of the PR is to not tp make it easy to tell apart from other 5.56mm ammo, because it *is* 5.56mm ammo.

**Comment by chaosvolt** [comment]
I suppose this does work too. Plus since this is a case where the ammo (minor differences in specifications aside) is well-known by two names, US or metric, depending on context, then I suppose it doesn't matter. Technically for most purposes the order of the names doesn't matter either I suppose, since searching for 5.56 will return all such results, but it will throw off results when you have a pile of ammo sorted alphabetically.

**Comment by Krwak** [comment]
Completely agree with the OP, it adds to the confusion when crafting and also more items, and searching. Very small benefit in keeping them for the gun enthusiasts when compared to the negatives - bloat it adds.

**Pull request merged**
