### PR TITLE
Port demangle RTTI, backtrace on android

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: Infrastructure "Port backtrace on android"

#### Purpose of change

prepare for DDA `android/` total migration.

#### Describe the solution

port following PR:

- https://github.com/CleverRaven/Cataclysm-DDA/pull/48371
- https://github.com/CleverRaven/Cataclysm-DDA/pull/52633

### CODE REVIEW

**Comment by olanti-p** [comment]
Is this PR independent or does it depend on one of the others? It doesn't build in CI.

**Comment by scarf005** [comment]
i think it removed a symlink to source code, will rebase the part that did it

**Comment by scarf005** [comment]
...uhh... this is extracted out from #2502 and i think it's depending the PR

**Comment by scarf005** [comment]
closing in favor of #2502

**Pull request closed without merging**
