### PR TITLE
feat(balance): Phase out some redundant bionics, add bionic infolink

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

This does a bit of work towards phasing out a couple of completely redundant and pointless bionics, improving underwhelming ones, and/or packaging some functions that could reasonably be combined. Goal is reducing a few cases where a bionic is in some way not worth the hassle of installing.

## Describe the solution

C++ changes:
1. In character.cpp, bumped the brightness of cranial flashlight from 60 up to 300, to match that of a regular flashlight. It's a bionic installation that's overall more effort to set up than just wearing a headlamp, so making it comparable seems reasonable.
2. Also, on being talked into keeping it, bumped brightness of LED tats from 5 to 40, on the basis of making it about 1/8th that of cranial flashlight since it drains 1/8th the power. 
3. In general, changed all uses of `bio_watch` and `bio_infolink` in avatar.cpp, bionics.cpp, character.cpp, panels.cpp, player_hardcoded_effect.cpp, and sounds.cpp to refer to a new bionic as mentioned below that replaces both internal chronometer and weather reader...
4. And in addition, added references to infolink in the relevant functions in faction.cpp and npcmove.cpp so that they count as a two-way radio for the purpose of communications.

JSON changes:
1. Obsoleted directional EMP CBM, as the EMP arm gun does everything it does at the same power cost, but with 10 times the range. Only real benefit is lower slot usage but that can be adjusted if ever desired.
2. Bumped power draw of cranial flashlight from 3 joules to 8, making it 80% the wattage of a basic flashlight.
3. Obsoleted internal chronometer and weather reader bionics, with descriptions indicating the bionics are now useless (for old saves), in favor of...
4. Bionic Infolink, in the vein of things like JC Denton constantly being harassed by every NPC in the game. Described as a communications package, as such it provides both the watch and weather reader functions but additionally doubles as a two-way radio. Picked slot usage and install difficulty of weather reader.
5. Removed obsoleted bionics from itemgroups and professions, replacing with their counterparts where needed.
6. As a bonus for the extra Deus Ex experience, added bionic infolink to bionic agent profession. 
7. Likewise removed where relevant from mods folders.
8. Removed watch and phone from professions that get an infolink. :3

## Describe alternatives you've considered

I was originally gonna obsolete the LED tattoo and water extractor CBMs, but got talked into rebalancing the LED tats a bit to be more actually worth using, and talked into keeping extractor for now because it'll make it less hassle to convert it to be less fucking weird like it currently is.

## Testing

1. Checked affected JSON for syntax and lint errors.
2. Compiled and load-tested.
3. Tested that light radius of cranial flashlight when underground matches that of a normal flashlight.
4. Installed a bionic infolink, confirmed I get time and temp info, activation gives me weather report.
5. Recruited starter NPC and gave them a two-way radio, confirmed on teleporting away it let me talk with them.

## Additional context

I've already got another idea for a bionic to add (an electroreception CBM that will combine the utility of the Electoreceptor mutation, a bionic scanner, and a voltmeter) but figuring out how to code that one seems complex enough I'd rather save it for later.

### CODE REVIEW

**Comment by EkarusRyndren** [comment]
The rest is good but can we please keep the tattoo? I like having it for RP reasons.

**Comment by chaosvolt** [comment]
Pain. Between that and possible plans to rework the water extractor into something that purifies water en mass, I might I guess undo the obsoletion of water extractor and LED tattoo I guess weh XD

**Comment by RoyalFox2140** [comment]
> Pain. Between that and possible plans to rework the water extractor into something that purifies water en mass, I might I guess undo the obsoletion of water extractor and LED tattoo I guess weh XD

No reason to hold up the PR because I have longterm plans to do something with the water extractor. If its just in obsolete.json it can be resurrected as fast as it was killed. LED tattoo is its own story and I already commented that we work with ascii and 32x32 so you can't meaningfully represent such sprites on the character, a tattoo system in general is menu text if it doesn't glow enough to be useful.

**Comment by chaosvolt** [comment]
Auuuugh make your minds weh. I'm gonna just make the LED tattoo bright enough to ensure it actually lets you craft and unobsolete it, plus not like it really hurts to have it in weh XD

**Review by scarf005 — APPROVED** [review]
Merging multiple small CBMs into one sounds like a good QoL improvement.

**Review by scarf005 — APPROVED** [review]

**Comment by ZChris13** [comment]
Man, I come back and you've obsoleted one of the best bionics. Directional EMP was good because it was a melee attack and couldn't miss if you ended up in melee with a robot.

**Pull request merged**
