### PR TITLE
feat(content): fuel briquette

### PR DESCRIPTION
**Pull request by yay855**
Added in fuel briquette, a puck of dried plant matter that's used as firewood.

## Purpose of change

Straw and dried plants have very few uses beyond cordage and some innawoods constructions. I decided to give them another.

## Describe the solution

Added in fuel briquette, a lump of dried plant matter that burns.

### CODE REVIEW

**Review by scarf005 — COMMENTED** [review]
maybe would it be possible to make withered plant and straw pile 'rot' into dried fuel?

**Comment by yay855** [comment]
If you think that's a better idea, I'm all for it.

**Comment by chaosvolt** [comment]
I don't think we have support for items rotting into other items, plus withered plants and straw don't rot currently anyway.

Side note, it could also be set to count as charcoal if it was converted to ammo (and its bulkiness tweaked to be more in line with charcoal)

**Comment by yay855** [comment]
It could, but it's not exactly processed like charcoal, it's literally just dried plants woven into a brick.

**Comment by yay855** [comment]
I'm also not sure what the point of making charcoal an ammo type would serve.

**Comment by RoyalFox2140** [comment]
I should note I don't know what this is useful for given we can burn straw and plants directly and they dont rot at all, but I'm all for processing it to condense item count for less lag and item count in a tile.

**Comment by chaosvolt** [comment]
Charcoal is already an ammotype, I meant changing it to ammo of that type so forges, smokers, and the like have a potential non-kiln source of fuel innawods. :>

**Comment by RoyalFox2140** [comment]
> Charcoal is already an ammotype, I meant changing it to ammo of that type so forges, smokers, and the like have a potential non-kiln source of fuel innawods. :>

Yes then we can use it for steam engines.

**Comment by yay855** [comment]
> I should note I don't know what this is useful for given we can burn straw and plants directly and they dont rot at all, but I'm all for processing it to condense item count for less lag and item count in a tile.

That, and for making it work better with zoning, so you can autosort excess plants into your fuel pile directly.

**Review by scarf005 — DISMISSED** [review]
image

https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/7564900282/job/20599773521?pr=4121#step:14:1964

test failure unrelated to PR. ~~why doesn't this get added on problem matcher?~~

**Comment by RoyalFox2140** [comment]
> > I should note I don't know what this is useful for given we can burn straw and plants directly and they dont rot at all, but I'm all for processing it to condense item count for less lag and item count in a tile.
> 
> That, and for making it work better with zoning, so you can autosort excess plants into your fuel pile directly.

Probably also use a custom filter zone to dump piles of straw into your kilns.

**Comment by yay855** [comment]
> > Charcoal is already an ammotype, I meant changing it to ammo of that type so forges, smokers, and the like have a potential non-kiln source of fuel innawods. :>
> 
> Yes then we can use it for steam engines.

Ohh, perhaps. Though IRL steam engines could run off of just about any wood, but that would make steam engines ingame able to use fuel briquettes. Fair point.

**Comment by yay855** [comment]
> > > I should note I don't know what this is useful for given we can burn straw and plants directly and they dont rot at all, but I'm all for processing it to condense item count for less lag and item count in a tile.
> > 
> > 
> > That, and for making it work better with zoning, so you can autosort excess plants into your fuel pile directly.
> 
> Probably also use a custom filter zone to dump piles of straw into your kilns.

I suppose. Though the condensing is still useful.

**Comment by scarf005** [comment]
> I should note I don't know what this is useful for given we can burn straw and plants directly and they dont rot at all, but I'm all for processing it to condense item count for less lag and item count in a tile.

for condensing item count, i think making it stackable would be better (or is it already?)

**Comment by NappingOcean** [comment]
Is the Bash 18 for this item intended? That seems like a high value for any weapon.
If the item is not hard enough and breaks easily when wielded as a weapon, consider adding a `FRAGILE_MELEE` flag.

**Comment by chaosvolt** [comment]
Yeah it might be better off toning down overall bulk and other stats, I'll have to look at it in the morning I guess.

**Review by chaosvolt — APPROVED** [review]
Looks good as is, it being usable as charcoal would be neat too but can always mess with another time.

**Pull request merged**
