### PR TITLE
Kill tracker and ongoing game support for new achievements

### PR DESCRIPTION
**Pull request by KheirFerrum**
#### Summary

SUMMARY: Infrastructure "Add a kill_tracker check for achievements. Allow newly added achievements to ongoing games."

#### Purpose of change

Was part of my older PR #2719 but that got merged a lot quicker than I expected. Basically looking to reorganize skill code for achievements, and define kill requirements for achievements.

#### Describe the solution

This reorganizes the code such that if you define skill requirements of lower than it will now properly fail when you exceed that level (I know skill rust can allow a player to drop their skill level, but it likely goes against the spirit of that requirement.

Furthermore, it adds the ability to define kill requirements, either for specific monster types or monster species, to facilitate this a name field was added to species json objects.

Lastly, this removes the `initial_achievements_` field, allowing achievements added after game start to be added to the game. I'm not sure what the impact of this is yet so best that a bunch of people help me test if new trackers work when added to ongoing games.

#### Describe alternatives you've considered

- Continue using event trackers to track kills instead of the kill tracker.
  - The kill tracker allows retroactive attainment of kill requirements, so this seems a bit meh, I'd only consider this if removing `initial_achievements_` is proven to cause catastrophic game failure that I can't fix.

#### Testing

- [x] Start game with Undertaker achievement removed. Kill 50 zombies. Save game. Add back Undertaker Achievement, check that after loading, achievement is gained on next zombie kill.
- [x] Start game with Undertaker achievement already present. Kill zombies and check that tracker properly increments.
- [x] Check that Pacifist achievement is failed upon any kill. Check that if set to an hour instead of 7 days it will be attained on next wake up after an hour.
- [x] Add achievement with skill requirement comparator less than. Save. Check that achievement fails when skill exceeds target value.

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]
> Start game with Undertaker achievement removed. Kill 50 zombies. Save game. Add back Undertaker Achievement, check that after loading, achievement is gained on next zombie kill.

> Start game with Undertaker achievement removed. Kill 50 zombies. Save game. Add back Undertaker Achievement

image

> check that after loading, achievement is gained on next zombie kill.

>  Start game with Undertaker achievement already present. Kill zombies and check that tracker properly increments.

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/877901e0-794c-44a3-a0b8-c566ef453ed6

>  Add achievement with skill requirement comparator less than, and monster kill requirement with comparator less than. Save. Check that achievement fails when skill or monster kill exceeds target value.

added `achievement_dont_kill_50_zombie`:
```json
  {
    "id": "achievement_dont_kill_50_zombie",
    "type": "achievement",
    "name": "[Combat] No more than 50 kill",
    "kill_requirements": [ { "faction": "ZOMBIE", "is": "<=", "count": 50 } ],
    "requirements": [ { "event_statistic": "num_avatar_zombie_kills", "is": "anything" } ]
  },
```
image

achievement fails immediately upon loading.

**Review by scarf005 — CHANGES_REQUESTED** [review]
it's a bit concerning that 'kill any monster' is achieved by setting monster category to `mon_null`. could you add this behavior to documentation?

**Comment by scarf005** [comment]
oh I'm so sorry for taking this so long, forgot this existed and just found out while sorting PRs. Are any noticeable changes since https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2720#pullrequestreview-1431991202 ? If so, I'll do the same manual test and approve it

**Comment by KheirFerrum** [comment]
> oh I'm so sorry for taking this so long, forgot this existed and just found out while sorting PRs. Are any noticeable changes since [#2720 (review)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2720#pullrequestreview-1431991202) ? If so, I'll do the same manual test and approve it

Not to my understanding. Most of this was just making sure I didn't need to hack around things.

**Review by scarf005 — APPROVED** [review]
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/172b9e42-c0fb-41a3-bf43-b7b0a60ec3c0

Looks good to me. Sorry for the long delay.

**Pull request merged**
