### PR TITLE
feat(balance): `FIT` items with 10 or less encumbrance act as if `COMPACT`

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

This continues the same idea as in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3792 with the aim of fixing issues like clashes between underwear items, knee-high boots clashing with pants, jackets never being able to properly get a sense of what layer they go on, etc.

After some discussion, I scrapped my "just slap `COMPACT` on items that deserve it" in favor of an actual system put in place. Put simply, any item that counts as fitting and has a current encumbrance of 10 or less (so that most basic clothing will apply once refitted) will act as if affected by the `COMPACT` flag, automatically catching basically all items we'd expect this to apply to while also locking it behind having the item fit you properly.

## Describe the solution

C++ changes:
1. In armor_layers.cpp, changed `get_item_penalties` so that an item that has the `FIT` flag plus an average encumbrance of 10 or less does not count against how many items you have on that layer for the sake of triggering the layering penalty, just as the `COMPACT` flag does.
2. In character.cpp, changed `layer_item` so that the check for `COMPACT` items also looks for the above combo of an item that fits you and has the required encumbrance.
1. In iteminfo_armor.cpp, changed `item::armor_info` so that an item with either the `COMPACT` flag or the above properties will display a message indicating what that does directly under the layer in the item UI, instead of being in the section with generic item flags. This is to make it clear at a glance that an item is valid for this effect.

JSON changes:
1. Removed description from the `COMPACT` JSON flag now that it's placed in a more useful place by the code.
2. MISC: Changed leather apron from `BELTED` to `OUTER` now that it should clash less with conventional jackets. Stood out to me as an item that lacks `VARSIZE` (adjustable tie for the back I assume) and was on `BELTED` layer presumably because someone figured better it clash with backpack (despite being draped over the front) than with a jacket for...reasons?
3. Misc: Gave `POWERARMOR_COMPATIBLE` to medical gloves, zentai. Minor shit I missed in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3797

## Describe alternatives you've considered

Handling this the hard way by deciding what items deserve having `COMPACT` handed out manually, like I was initially going to.

## Testing

1. Checked affected JSON files for syntax and lint errors.
2. Load-tested and started spawning in as professions I knew to traditionally have gear troubles.
3. Checked affected C++ files for astyle.

Examples of professions affected by this:
1. Historical/ahistorical reenactor (male/female variant respectively, knee-high boots no longer conflict with breeches)
2. Military rifleman and most related professions (army jacket no longer conflicts with MBR vest)
4. Maid (female variant, stockings no longer conflict with panties)
5. Home mechanic (female variant, tank top no longer conflicts with bra)

### CODE REVIEW

**Comment by scarf005** [comment]
i think removing `COMPACT` flag completely in favor alternative#2 would be better long-term.

**Comment by chaosvolt** [comment]
I think `COMPACT` flag's support should stay for when we explicitly want to set a non-`VARSIZE` item to not clash with layering (like most of the items in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3792) but otherwise yeah, presumably some combination of `FIT` (if we want to exclude poor-fit `VARSIZE` items) potentially combined with any of:
1. Encumbrance below a given threshold.
2. Material thickness below a given threshold.
3. Item counts as "soft" for the sake of mutation compatibility.

Thoughts I guess?

**Comment by chaosvolt** [comment]
Pushed what I have so far but I'm getting an error: `'c' cannot be implicitly captured because no default capture mode has been specified`

**Comment by scarf005** [comment]
> In armor_layers.cpp, changed get_item_penalties so that an item that has the FIT flag plus an average encumbrance of 10 or less does not count against how many items you have on that layer for the sake of triggering the layering penalty, just as the COMPACT flag does.

would it mean that wearing 1 or 100 tshirts would give same encumbrance?

**Comment by chaosvolt** [comment]
Limit is 2 of any item, so the ability to abuse this is limited to 2 times however many zero-encumbrance items still exist. Could apply a base encumbrance of 1 to any leftovers then I guess?

**Comment by scarf005** [comment]
https://github.com/chaosvolt/Cataclysm-BN/blob/1f440c29f9e4ac8fb301cca999305c10bc656579/src/armor_layers.cpp#L368-L371

I think this info should also be described. I'll add a quick commit to fix it.

**Review by scarf005 — APPROVED** [review]
image

LGTM

**Comment by YeOldeMiller** [comment]
There also needs to be this line in the armor layers screen:
image

It is currently present for actual `COMPACT` items but not ones that are supposed to behave like `COMPACT`.

**Comment by chaosvolt** [comment]
> It is currently present for actual `COMPACT` items but not ones that are supposed to behave like `COMPACT`.

That was a problem I ran into, yeah. Basic gist of it is the check for fitted encumbrance needed to be able to check character, but the function responsible for adding those lines doesn't have character available to use for stuff.

**Pull request merged**
