### PR TITLE
fix: Remove surround groups in large buildings scenario

### PR DESCRIPTION
**Pull request by LucioFurnari**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
I decided to remove the default zombie spawn in the scenario, because it makes no sense, for example in the shopping center, zombies are trapped between walls that should not pass, in the apartment zombies spawn in the air, or a large number of zombies in the roof.

## Describe the solution
Remove surround groups in the scenario.

## Testing
I tried it and no more zombies spawn unnecessarily.

## Additional context
14110693 100000024_image
15388833 100000024_image

### CODE REVIEW

**Comment by RoyalFox2140** [comment]
I'm not fully sure about this as zombies spawning inside walls feels like a bug we have to address sooner than later, I'll ask some people their thoughts.

**Comment by LucioFurnari** [comment]
Apparently, at least in that case of the mall some spawn inside the wall, I also consider it unbalanced in some cases, for example appearing on the roof of the apartment surrounded by zombies and your chance of surviving depends where you appear when you start, or for example in the case of appearing in a house, the zombies spawn in the air.

**Review by RoyalFox2140 — APPROVED** [review]
I'm going to let it through given we should expand our scenario options a lot more anyway.

**Comment by chaosvolt** [comment]
This seems less than ideal to be honest but...

**Review by KheirFerrum — COMMENTED** [review]
I'm against this. The surrounded start _should start_ surrounded. Spawning in walls and open air with no floor is a bug that must be fixed, the solution is _not_ the removal of surround groups from these starts.

I'm as yet divided on roof spawns, as they make sense from a gameplay point of view but a bit less on the "realistic" sense since how the fuck did the zombies get up there?

**Comment by blot-runner** [comment]
> how the fuck did the zombies get up there?

Same as the character did? The stairs?

**Pull request closed without merging**
