### PR TITLE
feat(content, mods/aftershock): Return vehicle freezers/fridges to aftershock

### PR DESCRIPTION
**Pull request by KheirFerrum**
## Purpose of change

- Freezers mainlined in #2172. #4455 was done shortly thereafter to remove aftershock fridge/freezer appliances, but accidentally removed full size vehicle fridges/freezers as well.

## Describe the solution

- Adds back the full size vehicle fridges/freezers to Aftershock. Adds the ability to install the glass variants as well (though benefit is minimal, except that light on those tiles will now radiate out.) though the epower cost is 20 points higher (to reflect the energy inefficiency of glass fridges/freezers both in real life and in vanilla.
- Removed an unused construction group while I was at it.

## Testing

- Start a world with Aftershock, make a vehicle and install the fridge/freezer into them. 
  - [x] Check that each installation uses the appropriate materials (glass fridges use glass fridges not normal fridges)
- [x] Check that items placed into them once turned on has the appropriate timer displayed.

## Additional context

It's really odd to me that this was only noticed recently.

One odd quirk of the system is that the "turn on freezer/fridge" vehicle command doesn't allow you to selectively turn them on, they will turn on all corresponding vehicle parts. (Luckily it checks for flags and not IDs so the glass freezer/fridge both will be appropriately... turned on)

### CODE REVIEW

**Comment by VissValdyr** [comment]
To be perfectly honest, full size freezers can be in a vehicle too. Especially RVs can benefit from them. https://images.app.goo.gl/JohSQgGzArRuWykK9

**Comment by scarf005** [comment]
if so, should full-size fridges be mainlined too?

**Comment by VissValdyr** [comment]
> if so, should full-size fridges be mainlined too?

I would say yes. We can fit a forge into a car, so why not a regular sized fridge. Make the full sized fridge even spawn into RVs (regular and deluxe). Mini fridges will still be part of limousines, so they still spawn.

I would support the full size fridge into mainline.

**Comment by RoyalFox2140** [comment]
In that PR I knew I was removing full-sized vehicle freezers but figured if it was necessary to have them they needed to be mainlined content. I simply wanted to remove redundancy from aftershock in as quick as possible. Adding them back to Aftershock would put it back in obscurity.

**Comment by Relgar** [comment]
> > if so, should full-size fridges be mainlined too?
> 
> I would say yes. We can fit a forge into a car, so why not a regular sized fridge. Make the full sized fridge even spawn into RVs (regular and deluxe). Mini fridges will still be part of limousines, so they still spawn.
> 
> I would support the full size fridge into mainline.

This would be great - I just took a look at chest freezers and apparently those can store a whopping SEVEN HUNDRED LITERS compared to the upright freezers of 300L (current standard), so this could also be a future addition as well.

**Comment by KheirFerrum** [comment]
> > if so, should full-size fridges be mainlined too?
> 
> I would say yes. We can fit a forge into a car, so why not a regular sized fridge. Make the full sized fridge even spawn into RVs (regular and deluxe). Mini fridges will still be part of limousines, so they still spawn.
> 
> I would support the full size fridge into mainline.

My issue with mainlining it is that there's no discernible drawback between minifridges/freezers vs their full size variants. If for instance we made minifreezers/fridges more compatible with other vehicle parts, or full size versions less compatible, I'd be more persuaded. That said. I'd rather that be a different PR discussion entirely.

**Review by chaosvolt — APPROVED** [review]
¯\\_(ツ)_/¯.

**Pull request merged**
