### PR TITLE
feat(balance): Convert drugdeal itemgroup to collection

### PR DESCRIPTION
**Pull request by RoyalFox2140**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.
## Purpose of change

When map extras were jsonized, the drugdeal map extra had all of its firearm spawns in a distribution that contained large amounts of clothing and other items like cigs, lighters, the drugs, etc. This meant it was nearly impossible for the game to roll for weapons.

## Describe the solution

Update into a collection and heavily change what can spawn, being a collection means each item has a chance to roll instead.

## Describe alternatives you've considered

Better distribution?

## Testing

image
image
image

## Additional context

@chaosvolt You must update Cataclysm++ as it sets drugdeals to a collection and that stops my game from loading. Basegame loads just fine, in fact most mods load fine.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Interesting, a lot of single-item spawns in the collection could still potentially be rolled up into itemgroup calls I suspect.

**Comment by RoyalFox2140** [comment]
> Interesting, a lot of single-item spawns in the collection could still potentially be rolled up into itemgroup calls I suspect.

Wasn't sure generally how we wanted to handle it, I think it could use more work grouping some spawns but I didn't know where to go with it generally.

**Comment by chaosvolt** [comment]
Fair enough. I could mess with it if you'd like. Currently preparing draft updates for mods (and also waking up bleh).

**Comment by chaosvolt** [comment]
Went ahead and condensed the itemgroups a lot more, lemme know if it looks okay.

**Comment by RoyalFox2140** [comment]
Chaos's tweaks look good to me. Think this will be good overall

**Review by chaosvolt — APPROVED** [review]

**Pull request merged**
