### PR TITLE
Port DDA's font loading via file paths

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
SUMMARY: Interface "Ported DDA's fix for broken non-ascii characters"

#### Purpose of change
Fix interface for non-English users

#### Describe the solution
Cherry-picked from DDA:
CleverRaven#42227
CleverRaven#42520 (with CleverRaven@21d0591b16762637c34023f7f0de9040bb5a41f5)
CleverRaven#45319

Also noticed that the new code makes the game print a backtrace on startup, and fixed that
(backtrace emission delayed the startup by ≈5s on my laptop. Game was compiled via `make CLANG=1 TILES=1`).

#### Testing
The game compiles and works, non-ascii characters are displayed correctly.

#### Additional context
image

### CODE REVIEW

**Comment by olanti-p** [comment]
The test seems to be stuck in this loop
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/8a80d3c6525cd723bdef12e31d37fc5531bb094c/src/overmap.cpp#L4260-L4269

**Comment by Coolthulhu** [comment]
> Game was compiled via make CLANG=1 TILES=1).

Do you compile release builds once in a while?
I'm experiencing a slowdown during load and testing on my release builds on GCC.

**Comment by olanti-p** [comment]
> Do you compile release builds once in a while?

Almost never - it takes too long already, even with multiple threads...
Unless it's Windows + Visual Studio, since debug builds there are so slow it's not even funny.

> I'm experiencing a slowdown during load and testing on my release builds on GCC.

You mean this PR, or in general?

Just tested on Linux + SSD with `make CLANG=1 TILES=1 SOUND=1 RUNTESTS=0`:
It's 1-1.5 seconds between `./cataclysm-tiles` and the game's window showing up.
The @'s soundpack extends it to 2-2.5s.
Loading the definitions takes 15s.
Loading a save takes 2-3 seconds.

All of that is both with and without this PR.

**Comment by Coolthulhu** [comment]
> You mean this PR, or in general?

In general.
I hoped it might be something related to GCC, but 15 second definition load doesn't look good.

**Comment by ZhilkinSerg** [comment]
`calculate_mapgen_weights` is major offender in DDA right now, probably in BN too.

image

Also do you have #43268 merged? Blueprints autocalc was a major pita for some time.

**Comment by Coolthulhu** [comment]
> calculate_mapgen_weights is major offender in DDA right now, probably in BN too.

Yep. I always see the loading hang on that one. The name is pretty misleading.
> Also do you have CleverRaven#43268 merged?

Nope. Faction camp stuff is currently untouched.

**Pull request merged**
