### PR TITLE
Harvested CBMs no longer spawn faulty and filthy

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Balance "Harvested CBMs no longer spawn filthy and faulty"

#### Purpose of change

Part of the ideas outlined in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/872, this tackles the easiest stuff as a first step. Per feedback, going with Coolthulhu's suggestion regarding handling bionic faults.

#### Describe the solution

1. Set all bionic harvests to not spawn filthy bionics, under reasoning that it's just a pointless bit of realism that doesn't add anything to installation.
2. Also set it so they don't spawn faulty. Initially I figured reducing the time taken would be a good middle ground between keeping it as-is and removing it, reasoning that it helps nudge the player to advance those skills before trying to install, but per request I went with axing the idea instead. Besides, players who find fresh CBMs wouldn't be getting that nudge anyway, and there are better ways to hint at what skills are needed that could go in companion PRs, as mentioned in alternatives below.

#### Describe alternatives you've considered

1. Making the install prompts say up-front what skills affect installation, for both the autodoc UI and the self-install prompt, would be a good companion to this. The only thing bionic mending really added to the game was to nudge the player in the right direction, hinting at which skills will later be useful while installing, but that hint would be missed by players who find brand-new CBMs, and the hint doesn't reveal that mechanics or computers are useful depending on install method. Again, would be good for a separate PR.
2. Of the skills needed to mend and install bionics, first aid is the biggest pain in the ass to get to a decent level from nothing. Doing point 1 removes one of the things than makes its annoyance visible, but as it's still needed for the install roll and other things. Tweaking the recipe chain for early-game first aid might be useful for that purpose. It's definitely better than it was back in the old days when makeshift bandages needed tailoring to craft, though.

#### Testing

Checked affected files for syntax and lint errors.

#### Additional context

A separate PR for making it suck less to deal with cleaning gun fouling might be warranted too, in addition to the above-mentioned ideas about good fodder for companion PRs.

Note to self: Don't let me forget I oughta set aside an update to the BN version of Cata++ for consistency with vanilla.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
> Then you use the tool requirement in installation to add scalpel and you go back to the fast paced scalpel installation of 0.C.

Installation of bionics never required any tool, scalpel included. You just activated the CBM, and bam, you got your eye replaced with a telescopic one.

**Comment by chaosvolt** [comment]
> Why keep the mending?

I already gave my reasoning in the OP. I'd be fine with removing mending outright if Coolthulhu prefers it that way, but I do feel it's actually somewhat useful

As I said, since all the skills needed to mend are skills used by the bionic install roll, this means that the mending action helps nudge players towards building up the skills needed for a successful installation. If they have the skills needed to mend it, then they have a head start on a successful installation.

> If cleaning is already too much the whole thing should go too.

It isn't that cleaning is too much of a barrier to restoring harvested CBMs. It's just that Firestorm and Coolthulhu consider it pointless. An unnecessary obstacle that adds nothing to the actual process but wasting a handful of keypresses and a bit of some unimportant resources.

It's similar to the reason why filthy clothing has been largely redundant as a barrier: it doesn't really nudge the player to do anything (they're already going to be on the lookout for water, and soap isn't a rare resource), and it there are already more effective barriers to entry that're both harder to overcome and actually encourage the player to do something that'll be interesting or at least useful later on.

> that way you can also drop autoclaves and the pouch if it's not already done.

We mostly just need to balance the wacky spawn issues autoclaves and pouches have, as well as make it less of a pain in the ass to get them running. The main advantage of keeping autoclaves is, again, it encourages players to actively go explore science locations. Main problem right now is the spawns for it are spread thin as low weights in common itemgroups, which the net effect that finding one is a bit of a crapshoot. Long-tern you WILL find them eventually, but it's basically just by stumbling upon them in a random room out of countless other rooms that all just so happen to call the `science` itemgroup.

Autoclave rooms do seem to exist but, so far it seems, are vanishingly rare. This could also be improved by making microlabs actually spawn useful stuff common to other labs, instead of just thousands upon thousands of bottles of chemicals and tools that have no use whatsoever.

Coolthulhu has brought up possible plans regarding making sterilization an optional step however, leaning towards some sort of blob-related. mutagenic consequence for doing so if I recall (because "you die of infection" would be realistic but bland), but we'll have to see regarding overall plans.

Being able to hook the autoclave up to the electrical grid will also bee a MASSIVE help as far as making autoclaves less annoying to use goes. See here for an issue related to that: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/937 If we can get examine_action to optionally require power, we'd be able to plug in autoclaves right after that.

**Comment by Coolthulhu** [comment]
> Reduced time taken to mend a faulty bionic from 45 minutes to 10 minutes.

Adjusting time doesn't make it significantly less tedious. You should obsolete the fault and remove the requirement to remove it from the bionic.
Or keep it and move the skill check to installation if the fault is present, if you think that the extra skill requirement has a role.

> player who lacks the skills needed for a successful mend is probably going to botch the roll

There's no roll, just a check. Have -> can mend, don't have -> can't mend.

**Comment by chaosvolt** [comment]
> Or keep it and move the skill check to installation if the fault is present, if you think that the extra skill requirement has a role.

I suppose it's not that essential to have the skill check from mending. As mentioned in alternatives, it might be more useful overall for the install menus (both autodoc and the self-install prompt) to openly list what skills will improve the chance. Then just trust that the player will seek out those skills on their own, or take a gamble and risk hilarity ensuing.

I'll see if I can work on removing the faulty spawns while I have a chance to grab some wifi while I'm out and about, then.

> There's no roll, just a check. Have -> can mend, don't have -> can't mend.

I meant that being able to pass the mend check means they have a head start on passing the install roll later, rather.

**Comment by Coolthulhu** [comment]
There are other files with mentions of the fault, mostly in mods.
The fault should be moved to obsoletion.
There are lines in the source that add the fault to bionics. Those should be removed as well.

**Comment by chaosvolt** [comment]
Oh right, I can update mods and obsolete the fault then.

Not sure about removing the code for it just yet though, that would make the PR more complicated as I'd need to hunt it all down.

Plus that would immediately break third-party mods.

**Pull request merged**
