### PR TITLE
feat(balance): bionic harvest follow-ups part 1

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

Follow-up mentioned in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3719.

Get those bionic scanners ready. More to follow later on, either in this PR or as a follow-up probably.

## Describe the solution

1. Defined harvest entry `zombie_maybe_mil_bionics`, which is based off `zombie` but adds a bionic group for potentially yielding military bionic spawns. Military bionics spawn chooses between military power storage, bio-operator CBMs, or sometimes...
2. Defined itemgroup `bionics_heavy_mil`, intended mainly for use by armored zombies but sometimes obtained from regular military grunts.
3. Defined harvest entry `zombie_maybe_heavy_mil_bionics` as something mainly for armored zombies to use.
4. Defined itemgroup `harvest_maybe_military_heavy` which has 25% (elevated over the 10% regular military zeds default to) chance of picking salvage components, a military power storage bionic, or something from `bionics_heavy_mil`.
5. Changed harvest entry for zombie soldiers (affects acid soldiers by proxy), black-ops zombies, pilots, and lab-sec zombies (as they can upgrade into kevlar zeds) to use `zombie_maybe_mil_bionics`.
6. Changed harvest entry for armored zombies and burners to use `zombie_maybe_heavy_mil_bionics`. Reason for the latter is burners being potentially specialist hazmat soldiers and/or trained to carry heavy equipment that's not normal for battlefield use.
7. Added a call to `harvest_maybe_military` to `zombie_kevlar` harvest group.
8. Per feedback, changed `cyborg_harvest` back to yielding bionics 50% of the time.
9. Updated ghouldon in Aftershock to use `zombie_maybe_heavy_mil_bionics` harvest entry.
10. Updated No Hope's override of soldier zeds to use new harvest entries.

## Describe alternatives you've considered

Screaming.

## Testing

Checked affected files for syntax and lint errors.

## Additional context

Planned additions later on:
1. Medical and hazmat zombies will likely have a potential chance of spawning with related civilian bionics (mainly medical and science CBMs). Possibly 5% as opposed to the 10% military zeds use.
2. Miners could potentially gain a chance (5% or 10%) of calling the same drops technicians do, or possibly a list that includes any CBMs present in mine spawns not already available from technicians (if any).
3. Lab mutants also warrant a low chance of calling for harvests seen in cyborgs, likely either 10% or 25%.
4. Survivor zeds may logically gain a chance of generating with survival-themed civilian CBMs. Probably elevated above the general populace's chance of bionics but still low (5%?).
5. Other generic zeds are planned to gain a global chance of spawning standard civilian bionics, likely as low as 1% chance given you'll be carving through a fuckton of them. This will likely apply to all standard non-profession zeds that don't have a good reason to lack exposure to future medical tech (rural-specific zeds, Church of Starry Wisdom cult zeds, etc).
6. Figuring out how to give generic human corpses similar odds of generating with a bionic will be...interesting.

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]

**Comment by YeOldeMiller** [comment]
One issue I haven't seen addressed is that harvesting corpses with large numbers of bionics is one of the few (easily repeatable) ways of leveling First Aid past level 8. If there's going to be fewer corpses with 3-4 bionics overall, some way to compensate that for the purposes of skill leveling may be needed.

**Comment by chaosvolt** [comment]
That'd be good yeah, I do want to sanity-check EXP rates to ensure that any action that uses a skill will grant EXP at a rate that reasonably competes with craft-grinding as a way to make craft-grinding less nessecary.

As more potential sources of bionic zeds get added this should also help spread out the spawns and bump the number off bionics one obtains in the long run back up.

**Comment by YeOldeMiller** [comment]
What I'm worried specifically is that there's apparently a threshold, you need a body with no less than X bionics to even gain any first aid XP for dissecting it past certain skill level. Maybe that threshold should be relaxed so that you gain at least SOME progress by harvesting more common augmented enemies with 1-2 CBM, even if it's slower.

**Comment by chaosvolt** [comment]
> you need a body with no less than X bionics to even gain any first aid XP for dissecting it past certain skill level.

If that's true that's very janky and needs to be fixed, yeah. The only cyborgs in vanilla to even have that many potential CBM spawns are the upgraded bio-operators if I recall, so this would be a big problem even beforehand given that should mean literally only one enemy in the game would be a valid source of EXP even before this change.

**Pull request merged**
