### PR TITLE
Extend ammo effects and Fix Grenade launcher rounds don't explode

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Extending ammo effects

#### Summary
SUMMARY: Bugfixes "Extending ammo effects"

#### Purpose of change
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/82

#### Describe the solution
Adding support for "extend" and "delete" for ammo effects.
Used https://github.com/CleverRaven/Cataclysm-DDA/pull/37804 as example

#### Describe alternatives you've considered
Waiting for https://github.com/CleverRaven/Cataclysm-DDA/issues/36851 to resolve. But it may take months/years.

#### Testing
1) Spawn Milkor MGL / Mark 19
2) Shot with greande launcher
3) Grenade must explode.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Since I've got from Jenkins.
```
Failed to visit member flags in JsonObject

    },

    "extend": { "effects": [ "RECYCLED", "BLACKPOWDER", "MUZZLE_SMOKE" ] },

    "delete": { "effects": [ "NEVER_MISFIRES" ], "flags":

                                                         ^

                                                          [ "IRREPLACEABLE_CONSUMABLE" ] }
```

I had to impelement extends/remove for flags also?

**Comment by Firestorm01X2** [comment]
Should this grenades also use EXPLOSIVE flag? Or it is frag only by design?

**Comment by Coolthulhu** [comment]
> Should this grenades also use EXPLOSIVE flag? Or it is frag only by design? HEDP I mean?

With 80 stab damage on hit, it's in overkill territory already.
DDA design decisions need not be considered here.

The name "HE" suggests it should be explosive, so it's better to give it weak hit damage and explosive+frag, making it similar to hand grenade.

**Comment by Firestorm01X2** [comment]
> The name "HE" suggests it should be explosive, so it's better to give it weak hit damage and explosive+frag, making it similar to hand grenade.

But also this:
https://en.wikipedia.org/wiki/High-explosive_anti-tank_warhead#High-explosive_dual-purpose
>Another variant of HEAT warheads has the warhead surrounded with a conventional fragmentation casing, to allow the warhead to be more effectively used for blast and fragmentation attacks on unarmored targets, **whilst remaining effective in the anti-armor role**. These are sometimes referred to as high-explosive dual-purpose (HEDP) warheads. In some cases, this is merely a side effect of the armor-piercing design. In other cases, this dual role ability is a specific part of the design. 

Looks like it must be be explsive but at the same time armor piercing.

**Comment by Firestorm01X2** [comment]
Ok. I've figured that out. There was outdated explosive flags (as it was reported in issue). So it if FRAG and explisive. Armore piercing is by design since it is HEDP.

**Comment by Firestorm01X2** [comment]
Ready.

**Comment by Coolthulhu** [comment]
> Looks like it must be be explsive but at the same time armor piercing.

It can't have all 3: blast, frag, massive stab damage. If it can 1-shot a player with "level appropriate" (at best survivor grade) armor, it needs balancing.
Some ideas:
* Wide blast with good damage, no frag, moderate stab damage
* Narrow shrapnel blast, but with good (for shrapnel) armor piercing, cosmetic blast or no blast (currently shrapnel is invisible - this needs a fix), low stab damage but with low armor multiplier or high armor piercing

Blast damage can't be customized right now, it's only power and range. Shrapnel damage can have specific armor piercing and multiplier, but this isn't displayed (will need fixing someday).
Multiple effects (blast, frag, stab) go through the armor individually.

**Comment by Cactoideae** [comment]
Thing is, if grenades can't oneshot the player, they can't oneshot most enemies either. Almost all zombies have more hp than the player, and a lot of them have more armor too.

When I fire a grenade into a crowd of zombies, I want to get multiple kills, not scratch a few weaker ones for a third of their hp.

I think grenades should be deadly, and then we just need to make sure enemies don't get access to them (no grenade firing bots, NPCs can't spawn with grenade launchers, etc).

**Comment by Coolthulhu** [comment]
> When I fire a grenade into a crowd of zombies, I want to get multiple kills, not scratch a few weaker ones for a third of their hp.

At the moment blast and frag damage is roughly doubled (post armor) for monsters, to account for lack of body parts.
A grenade that hits the player for 80 should kill most of the zombies.

**Comment by Firestorm01X2** [comment]
I've decided to leve frag only for now. Balancing can be done in separate PR.

**Comment by Firestorm01X2** [comment]
Ready.. Also tested on dragon breath shotgun ammo. It gives fire now.

**Comment by Firestorm01X2** [comment]
Notes to self:
https://github.com/CleverRaven/Cataclysm-DDA/pull/44750
https://github.com/CleverRaven/Cataclysm-DDA/issues/42795

**Pull request merged**
