### PR TITLE
docs: PR title generator & update contributing guideline

### PR DESCRIPTION
**Pull request by scarf005**
## Purpose of change

make opening PR (and following requirements) easier for beginners.

## Describe the solution

- auto-update `semantic.yml` (and allowed mod list)
- made checklist more prominent
- added pr title generator in docs page

## Describe alternatives you've considered

using UI framework like preact over raw dom manipulation, but the component was simple enough.

## Additional context

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/643b6aa5-dddf-42bf-9712-d87a6033a8b3

## Checklist

- [x] I wrote the PR title in conventional commit format, see above
- [x] I ran the code formatter
- [x] I linked any relevant issues using github keyword syntax

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]

**Comment by chaosvolt** [comment]
>     * made checklist more prominent

Shit, I didn't see this and also didn't realize it meant bringing back the checklist spam that was removed in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3677 specifically because it's a nuisance for 90% of PRs, or I wouldn't have approved this.

**Comment by scarf005** [comment]
it does say to remove unrelated sections, tho

**Comment by chaosvolt** [comment]
Yes but that's a pointless annoyance to clutter every single PR with when 90% of it just gets removed.

**Comment by chaosvolt** [comment]
Eh, for now we can leave it be, see if it helps anyone and just comment it out if others complain I guess.

**Pull request merged**
