### PR TITLE
feat(balance,mods): rebalance mod that disables most recharging from UPS

### PR DESCRIPTION
**Pull request by Secret-Cisco**
#### Summary

SUMMARY: Mods "Adds a rebalance mod that disables most recharging of small electronics from a UPS"

#### Purpose of change

Smartphones, MP3 players, and such draining my UPS is bothersome and unnecessary to me.

#### Describe the solution

Makes common electronics recharge only in a recharger and not from your UPS by replacing `"USE_UPS"` with  `"RECHARGE"`

#### Describe alternatives you've considered

Make small electronics charging toggleable in some manner, but alas I cannot code.

#### Testing

Loaded it up in game, everything seemed to check out. Stuff recharged in a charger but left my UPS alone.

#### Additional context

I'm open to changing the name. 
image

### CODE REVIEW

**Comment by chaosvolt** [comment]
Every one of these items should already be rechargeable, and if not they really should be in vanilla since this is generally used as a standin for being able to plug it in.

A feature that lets you specifically set a UPS item to toggle charging would be a much better solution here but that'd be code stuff (or dirty hacks involving transform use action to gain or lose the UPS flag), so hmm. :/

**Comment by Secret-Cisco** [comment]
> Every one of these items should already be rechargeable, and if not they really should be in vanilla since this is generally used as a standin for being able to plug it in.
> 
> A feature that lets you specifically set a UPS item to toggle charging would be a much better solution here but that'd be code stuff (or dirty hacks involving transform use action to gain or lose the UPS flag), so hmm. :/

They all are indeed rechargeable in a station already, I haven't poked around that much so I don't know if they get that from `"USE_UPS"` or if they'd have it either way because of their battery charge or what. All I know for sure is that the rechargeable flag adds that line "This tool has a rechargeable power cell..." to the info panel and I was concerned that without it or the UPS flag it'd stop charging. It seems to work perfectly like this so I didn't poke around further at the time.

Adding togglable UPS use would be nice. I also like the idea of separate, in inventory, non-UPS charging system. I did experiment a bit with the idea of a hand-crank charger type tool that charged batteries from the UPS but it didn't work.

I did get a fun hack working well enough on the aftershock UPS (with the integrated charge), when it's "on" `UPS_off` it works normally but when it's activated it starts working in reverse losing `is_ups` and gaining `use_ups` so that I can charge it up on the go from my bionic UPS and use it as a large buffer.

**Comment by Coolthulhu** [comment]
Workaround mods suggest that something is wrong in the core.
I'll consider the mod, but wait with it a bit, since removing a mod can be a disturbance (saves, players asking where it is etc.) and we might be able to figure out a way to make rechargeables suck less in core.

**Comment by Secret-Cisco** [comment]
> Workaround mods suggest that something is wrong in the core. I'll consider the mod, but wait with it a bit, since removing a mod can be a disturbance (saves, players asking where it is etc.) and we might be able to figure out a way to make rechargeables suck less in core.

That's fine, I mostly made this for my own use and thought I might as well throw it up here too. Tbh I think consumer electronics work pretty well without in-inventory recharging. MP3 players will run almost an entire day in a full charge and are dirt common, and I'm not sure how you'd ever really drain a normal laptop other than using it as a flashlight.

**Comment by AngelicosPhosphoros** [comment]
I think they already should be rechargable. They have been remaining to be UPS since times when there was only 2 kind of power supply: batteries or UPS.

**Comment by Secret-Cisco** [comment]
As I said, **the items do recharge as expected in the base, vanilla game** but I just tested it and they do not charge at all if they don't have either the `"USE_UPS"` OR `"RECHARGE"` flags.

So `"USE_UPS"` allows battery chargers and UPS's to charge

and `"RECHARGE"` allows just chargers and not UPS

**Comment by Secret-Cisco** [comment]
It might be nice if recharging and using the UPS were more fully separated, without one implying the other. By which I mean that `"RECHARGE"` allows charging at stations and "USE_UPS" allows using the UPS's power instead of its own, that way you could have tools with internal batteries that could be recharged and use their own power and also use UPS power (if they run out of their own?) but without constantly topping up their battery from the UPS.

Though unless you added some new behavior of some kind it would then be impossible to recharge any type of battery on the go (via the bionic UPS for example)

**Comment by scarf005** [comment]
@Secret-Cisco, sorry for leaving the PR open for so long. I mostly agree with [BFN that it'd be preferable to keep this mod as 3rd-party (not mainline) and fix the issue with code](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1605#issuecomment-1150122584). Would it be ok to close this PR as stale? Please feel free to share your opinion.

**Comment by scarf005** [comment]
thanks for the context. in an ideal solution, would it mean small electronics like phones or mp3 still use UPS but would only charge from recharger (thus not drain from UPS anywhere)?

**Comment by chaosvolt** [comment]
Finally implemented the most logical alternative in this PR: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4775

**Pull request closed without merging**
