### PR TITLE
feat(content): look like for retrodays part2, 40mm ammo

### PR DESCRIPTION
**Pull request by VissValdyr**
## Purpose of change
part 1: #4611

This time I looked over the ammo. 40x ammo was missing a look alike, so they got one for retrodays

### CODE REVIEW

**Review by scarf005 — COMMENTED** [review]
feels bit weird, given `looks_like` for grenade is for much larger rockets. could there be alternate sprites?

**Review by chaosvolt — APPROVED** [review]

**Comment by VissValdyr** [comment]
> feels bit weird, given `looks_like` for grenade is for much larger rockets. it may cause issues with other tilesets. could there be alternate sprites?

I will check. It is fine enough for retrodays. Dead people have the right ones. I see to it.

**Comment by VissValdyr** [comment]
@scarf005 sadly I can't find a better sprite for it. So we have to take that one for now. I mean best thing would be to have a real sprite for it. But that will do.

**Comment by chaosvolt** [comment]
Hmm. Would shotshells be a better lookalike I wonder?

**Comment by VissValdyr** [comment]
I checked with all other tile sets we have via hitchhiker guide. That sprite is the best one fitting.

Screenshot_20240509-120435_Opera
Screenshot_20240509-120440_Opera
Screenshot_20240509-120449_Opera
Screenshot_20240509-120500_Opera
Screenshot_20240509-120717_Opera

**Comment by VissValdyr** [comment]
> Hmm. Would shotshells be a better lookalike I wonder?

Could you be more precise? Which one? Shotshell itself is not an item name. Do you mean shotgun shells?

**Comment by VissValdyr** [comment]
20ga is also missing a sprite. Regular shotgun shots don't fit so well @chaosvolt 
Screenshot_20240509-122350_Opera
Screenshot_20240509-122408_Opera

**Review by chaosvolt — APPROVED** [review]
Welp, that works good enough then.

**Pull request merged**
