### PR TITLE
feat: stack comestibles regardless of rot

### PR DESCRIPTION
**Pull request by scarf005**
## Purpose of change

- improve QOL by allowing 10h and 11h old pancakes to stack
- improve performance a tiny bit by not having 123 kinds of slightly different food around

## Describe the solution

- Added option group to configure comestible merging.
	- the new stacking strategy is enabled by default.
	- you can rollback to previous strategy via setting it `legacy`
	- ~~by default, only comestibles that's up to 75% fresh can be merged (tweakable)~~
	- by default, comestibles that has up to 25% similar freshness can be merged (tweakable)
- On item merging, the rot is set to weighted average of their rotness and charges
	- mixing small fresh food with huge amount of near rotten food won't make it much fresher and vice versa

## Describe alternatives you've considered

- [x] allow mixing two items not by freshness compared to shelf life, but similarities between the two?

## Testing

image

### Solid comestible

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/2e755378-e5b7-46ed-81f9-cb0f95a6a0e6

### Liquid comestible

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/ada331c4-7bb1-47a7-bd07-44c49fe8cac1

have to change the option before testing.

also updated `stacking_over_time` test to test both legacy and new behavior.

## Additional context

related: #3057

### CODE REVIEW

**Comment by Lamandus** [comment]
How is the freshness threshold working?

**Comment by scarf005** [comment]
1. freshly spawned item is 100% fresh.
2. rotten item is 0% fresh.
3. when freshness threshold is set to 0%, item of any freshness can be merged.
4. when freshness threshold is set to 75%, only very fresh items can be merged.
5. when freshness threshold is set to 100%, only items of identical freshness can be merged.

**Comment by Lamandus** [comment]
can you put the option menu in line with the others? Because that is the only one that is using that system except for logging. Should we use drop downs for all other of that kind or go back to the old system.

grafik
see here for example autosave and sound

**Comment by Lamandus** [comment]
looks good, do you intend to change the system? Or is it the final version?

**Comment by scarf005** [comment]
oh, i'm intending to change it to merge based on similarities to freshness

**Review by chaosvolt — APPROVED** [review]
Here's hoping nothing big was missed in testing...

**Comment by Lamandus** [comment]
> Here's hoping nothing big was missed in testing...

Actually if wasn't tested with the new system....

**Pull request merged**
