### PR TITLE
Add New House - 2storymodern03

### PR DESCRIPTION
**Pull request by LilShiningMan**
#### Summary

SUMMARY: CONTENT "Add New House -  2StoryModern03"

#### Purpose of change

Adding to house spawn variety.

#### Describe the solution

Created new house, 2StoryModern03

#### Testing
Linted files and tested spawn in-game. It spawns correctly.

#### Additional context

base

r

### CODE REVIEW

**Comment by Coolthulhu** [comment]
A small problem:
The weird spots in the screenshot lack roof. They have furniture, but no terrain.

Screenshot from 2022-09-15 22-41-04

**Comment by LilShiningMan** [comment]
So, in looking at the palette  (roof_palette.json, used by lots of other buildings) I found the following entries

image

there are a couple different symbols used in the roof, but for example the "&" symbol for the roof turbine vent is listed, and the terrain underneath is "t_null".

**Comment by Coolthulhu** [comment]
> You mention there's furniture but no terrain, but looks like that's the way it's supposed to be

`"t_null"` is usually used with `"fill_ter"`. Maybe DDA changed it from `t_null` to flat roof to avoid this dependency on `fill_ter`.

**Comment by LilShiningMan** [comment]
OK, I've changed the fill_terr to the flat roof option, so that should fix the problem.

**Pull request merged**
