### PR TITLE
feat(balance): Rapid strike rebalance

### PR DESCRIPTION
**Pull request by yay855**
Rapid strike and similar techniques have been rebalanced to no longer reduce damage dealt, and their movecost reduction is changed from 50% to 75%. Eskrima also had three techniques that served that same purpose, which was mild bloat given that techniques are chosen semi-randomly.

## Purpose of change

Rapid strike and similar techniques punished already-weak weapons (knives, mostly), reducing their already-low damage in favor of greater attack speed- but this game's armor calculations make damage far more important than speed, making such a technique horrible.

## Describe the solution

Rapid strike and similar techniques have had their damage reduction removed and their movecost reduction lessened, with most techniques of that type now simply being a 75% move speed boost for that attack.

### CODE REVIEW

**Review by scarf005 — CHANGES_REQUESTED** [review]
tests are failing due to removed techniques. could you check whether they're fully migrated?

```
(~[slow] ~[.],starting_items)=> (continued from above) ERROR: Technique with id tec_eskrima_fan in style Eskrima doesn't exist.
(~[slow] ~[.],starting_items)=> 01:12:47.838 ERROR DEBUGMSG : src/martialarts.cpp:392 [void check_martialarts()] Technique with id tec_eskrima_snap in style Eskrima doesn't exist.
```

**Comment by yay855** [comment]
> tests are failing due to removed techniques. could you check whether they're fully migrated?
> 
> ```
> (~[slow] ~[.],starting_items)=> (continued from above) ERROR: Technique with id tec_eskrima_fan in style Eskrima doesn't exist.
> (~[slow] ~[.],starting_items)=> 01:12:47.838 ERROR DEBUGMSG : src/martialarts.cpp:392 [void check_martialarts()] Technique with id tec_eskrima_snap in style Eskrima doesn't exist.
> ```

I do not remember how to do that...

**Comment by chaosvolt** [comment]
Hmm. Any ideas for what could potentially be added back to Eskrima to make up for the nerf? Bloat or not, this phases out two tecs that form a decent chunk of its early-game roster.

Alternatively, if the later-game techniques all feel too same-y when the style also gets rapid strikes, trimming or reworking the higher-end techniques may be a desirable alternative.

**Review by chaosvolt — CHANGES_REQUESTED** [review]
So, general problems I see with this:
1. As noted, removing the low-level tecs from Eskrima kinda undermines the style. In particular, its main thing is supposed to be it's the style for quick attacks with fast weapons, now basically every other weapon style with a rapid attack can now do it better because it's suddenly one of the only styles to get its rapid attack options so much later.
2. The change to make puno strike a basic no-frills rapid attack and not a tec specifically for the baton side of the style makes things more generic and is at best a band-aid for having removed the actual founding rapid tecs from the style. And not a very good one since it's a crit tec, so really all this does is make the style more generic. Removing the damage multiplier from it is probably okay but I'd rather you keep the weapon damage threshold and the negation of cut/stab damage, that last bit is distinct from the general focus of making rapid tecs not nerf overall damage. It's closer to a rapid version of Swordsmanship's mordhau in a sense.
3. I'm not sure if removing the damage nerf on sojutsu's trip attack is good or not. At bare minimum I'd say it's out of scope for this PR since the focus is on rebalancing rapid attacks, which it's not. Plus the shove technique doesn't get its damage penalty removed so not buffing it might be better for consistency, though balance-wise I could understand the argument that since it doesn't actually clear space like shove does then it could deserve doing more damage to offset being a lower-tier counterpart to shove. But given shove doesn't come with any stun and just nudges the target away, it doesn't really give you enough extra time to capitalize on the space it creates so it's not actually a better move than trip.

**Comment by KheirFerrum** [comment]
> I'm not sure if removing the damage nerf on sojutsu's trip attack is good or not. At bare minimum I'd say it's out of scope for this PR since the focus is on rebalancing rapid attacks, which it's not. Plus the shove technique doesn't get its damage penalty removed so not buffing it might be better for consistency, though balance-wise I could understand the argument that since it doesn't actually clear space like shove does then it could deserve doing more damage to offset being a lower-tier counterpart to shove. But given shove doesn't come with any stun and just nudges the target away, it doesn't really give you enough extra time to capitalize on the space it creates so it's not actually a better move than trip.

The main thing for me is that trip and shove both allow the player to buy more time, they're trading damage in this case for utility. Making all moves purely about damage is probably something we want to avoid, as is making such moves utterly superior to all other techniques that grant just damage (as stunlocking is _very_ strong)

**Comment by yay855** [comment]
There we go, removed the controversial elements to the PR. Eskrima's techniques are returned, sojutsu's trip has its damage penalty restored, and puno strike now is a bash-only attack again.

**Review by chaosvolt — APPROVED** [review]
If desired we can still mess with making the advanced tecs of Eskrima to more interesting things in a future PR, possibly also mess with the balance of sojutsu push vs trip if desired too.

For now, these simpler changes look aight and don't come with a side nerf to the designated "hahaha fast strikes go brrr" style so should just be a matter of ensuring no obscure tests don't fail. :3

**Comment by yay855** [comment]
> tests are failing due to removed techniques. could you check whether they're fully migrated?
> 
> ```
> (~[slow] ~[.],starting_items)=> (continued from above) ERROR: Technique with id tec_eskrima_fan in style Eskrima doesn't exist.
> (~[slow] ~[.],starting_items)=> 01:12:47.838 ERROR DEBUGMSG : src/martialarts.cpp:392 [void check_martialarts()] Technique with id tec_eskrima_snap in style Eskrima doesn't exist.
> ```

I fixed the issue!

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
