### PR TITLE
fix: starting item sorting differently on mac

### LINKED ISSUE #3813: False positive test failures due to Power Armor Soldier staritng equipment
### Describe the bug

new_character_test.cpp occasionally fails in PR testing with:
```
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> ../tests/new_character_test.cpp:103
(~[slow] ~[.],starting_items)=> ...............................................................................
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/new_character_test.cpp:191: FAILED:
(~[slow] ~[.],starting_items)=>   REQUIRE( failures.empty() )
(~[slow] ~[.],starting_items)=> with expansion:
(~[slow] ~[.],starting_items)=>   false
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   power_armor_soldier ANTIFRUIT PROF_MILITARY  power_armor_helmet_light:
(~[slow] ~[.],starting_items)=>   Couldn't wear it.`
```

Problem here is, when you actually select that profession in-game, they spawn with all their outfit and have no trouble taking off and putting back on their starting items.

This also prevented me from giving them a canteen in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3778 since it complained about the canteen. I'd marked it as not auto-equiping so the test shouldn't have been complaining at all, the character was starting with their canteen in inventory as expected.

### Steps To Reproduce

Make PRs. It just seems to happen sometimes at random.

### Screenshots

_No response_

### Versions and configuration

Version info for branch that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3811 is in, which currently has this test failure:
```
- OS: Windows
    - OS Version: 10.0.19041.450 (2004)
- Game Version: 34d1bf82cc87 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn]
]
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scarf005**
## Purpose of change

- fix #3813

## Describe the solution
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3814#issuecomment-1842917642

### CODE REVIEW

**Comment by chaosvolt** [comment]
>test still fails

I cri

**Comment by scarf005** [comment]
```
2023-12-03T05:25:48.4376580Z (~[slow] ~[.],starting_items)=> worn: straw_hat { is power armor?: false, has helmet?null}
2023-12-03T05:25:48.4377780Z (~[slow] ~[.],starting_items)=> worn: mbag { is power armor?: false, has helmet?null}
2023-12-03T05:25:48.4379020Z (~[slow] ~[.],starting_items)=> worn: leather_belt { is power armor?: false, has helmet?null}
2023-12-03T05:25:48.4380400Z (~[slow] ~[.],starting_items)=> power_armor_helmet_light: { flag_POWERARMOR_EXO: false, wearing PA: 0 }
2023-12-03T05:25:48.4381970Z (~[slow] ~[.],starting_items)=> power_armor_helmet_light: { flag_POWERARMOR_EXO: false, wearing PA: 0 }
2023-12-03T05:25:48.4383290Z (~[slow] ~[.],starting_items)=> You can only wear power armor components with power armor!
2023-12-03T05:25:48.4384590Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4386140Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4387470Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4388790Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4390110Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4391420Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4392800Z (~[slow] ~[.],starting_items)=> power_armor_helmet_light: { flag_POWERARMOR_EXO: false, wearing PA: 0 }
2023-12-03T05:25:48.4394220Z (~[slow] ~[.],starting_items)=> power_armor_helmet_light: { flag_POWERARMOR_EXO: false, wearing PA: 0 }
2023-12-03T05:25:48.4395540Z (~[slow] ~[.],starting_items)=> You can only wear power armor components with power armor!
2023-12-03T05:25:48.4396840Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4398160Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4399480Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4400910Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4402240Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4403550Z (~[slow] ~[.],starting_items)=> worn: power_armor_light { is power armor?: true, has helmet?null}
2023-12-03T05:25:48.4405050Z (~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
2023-12-03T05:25:48.4406040Z (~[slow] ~[.],starting_items)=> [0mstarting_items
2023-12-03T05:25:48.4407120Z (~[slow] ~[.],starting_items)=> [0m-------------------------------------------------------------------------------
2023-12-03T05:25:48.4408310Z (~[slow] ~[.],starting_items)=> [0;37m../tests/new_character_test.cpp:103
2023-12-03T05:25:48.4409380Z (~[slow] ~[.],starting_items)=> ...............................................................................
2023-12-03T05:25:48.4410220Z (~[slow] ~[.],starting_items)=> 
2023-12-03T05:25:48.4419870Z (~[slow] ~[.],starting_items)=> [0m[0;37m../tests/new_character_test.cpp:199: [0m[1;31mFAILED:
2023-12-03T05:25:48.4421160Z (~[slow] ~[.],starting_items)=> [0m[0;36m  REQUIRE( failures.empty() )
2023-12-03T05:25:48.4422060Z (~[slow] ~[.],starting_items)=> [0mwith expansion:
2023-12-03T05:25:48.4422790Z (~[slow] ~[.],starting_items)=> [1;33m  false
2023-12-03T05:25:48.4423500Z (~[slow] ~[.],starting_items)=> [0mwith message:
2023-12-03T05:25:48.4424620Z (~[slow] ~[.],starting_items)=>   power_armor_soldier ANTIFRUIT PROF_MILITARY  power_armor_helmet_light: You
2023-12-03T05:25:48.4425980Z (~[slow] ~[.],starting_items)=>   can only wear power armor components with power armor!
```

judging by the error output, it looks like for some reason `flag_POWERARMOR_EXO` flag isn't set for light PA helmet. also i think tests try to make the character wear helmet _first_ then the armor, hence the failure.

**Comment by chaosvolt** [comment]
Tests are weird, checked the item and its flags are same as basic and heavy helms, and confirmed via testing that swapping the helm and armor in the profession's items menu is a bad idea...

**Comment by scarf005** [comment]
## On my machine (Ubuntu 23.10, clang 16.0)

```
Filters: starting_items
Prof: power_armor_soldier, traits: ANTIFRUIT , items: {UPS_off, two_way_radio, m240, power_armor_light, power_armor_helmet_light, power_armor_chest_rig, power_armor_sheath, power_armor_frame, }
Prof: power_armor_soldier, traits: ANTIFRUIT , items: {UPS_off, two_way_radio, m240, power_armor_light, power_armor_helmet_light, power_armor_chest_rig, power_armor_sheath, power_armor_frame, }
```

## On CI (Mac, clang)

https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/7075387380/job/19257447631?pr=3814#step:16:1965

```
Prof: power_armor_soldier, traits: ANTIFRUIT , items: {UPS_off, two_way_radio, power_armor_helmet_light, power_armor_light, m240, power_armor_sheath, power_armor_chest_rig, power_armor_frame, }
Prof: power_armor_soldier, traits: ANTIFRUIT , items: {UPS_off, two_way_radio, power_armor_helmet_light, power_armor_light, m240, power_armor_sheath, power_armor_chest_rig, power_armor_frame, }

You can only wear power armor components with power armor!
```

this is certainly strange.

**Comment by chaosvolt** [comment]
Weird, could test that by editing profession I guess. That would presumably also ensure that clothing is being spawned in a specific order, too.

**Comment by scarf005** [comment]
image
1. using `entries` over `items` will [make the tests pass](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/7114891291/job/19369843649?pr=3814), but [as said by @Vollch](https://discord.com/channels/830879262763909202/830916451517857894/1181952435753865308), it's a hack that may cause problem anytime.

```diff
diff --git a/data/json/professions.json b/data/json/professions.json
index 3bc7fee94697..b19dc35e6f5e 100644
--- a/data/json/professions.json
+++ b/data/json/professions.json
@@ -1127,8 +1127,11 @@
     ],
     "items": {
       "both": {
-        "items": [ "power_armor_light", "power_armor_helmet_light", "power_armor_frame" ],
+        "items": [  ],
         "entries": [
+          { "item": "power_armor_light" },
+          { "item": "power_armor_helmet_light" },
+          { "item": "power_armor_frame" },
           { "item": "heavy_plus_battery_cell", "charges": 2500, "container-item": "UPS_off" },
           { "item": "two_way_radio", "contents-item": [ "battery_ups" ] },
           { "item": "power_armor_chest_rig", "contents-group": "army_mags_power_armor" },
```

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/f3d7db35815b0128e557cd9fa7ed2388936a02c5/src/profession.cpp#L467-L471

2. me and volch are suspecting `std::sort` is causing misordering. maybe [`std::stable_sort`](https://en.cppreference.com/w/cpp/algorithm/stable_sort) might work.

**Comment by scarf005** [comment]
image

_why_

**Comment by scarf005** [comment]
also cc @Vollch

**Review by chaosvolt — APPROVED** [review]
Only check failures I saw on this are unrelated so I'm gonna hope this fixes everything, yeah. Fucking wacky-ass `std::sort` I swear. Approving but may want to wait to merge until after Jove takes a look at it, just to be sure.

EDIT: Er Jove, not Volch, brain smol.

**Review by joveeater — APPROVED** [review]
This looks perfect. Great catch!

**Comment by chaosvolt** [comment]
Now to update from upstream for that power armor PR and see if any errors come up. :D

**Pull request merged**
