### PR TITLE
feat(port,UI): Allow Bionics to be hidden

### PR DESCRIPTION
**Pull request by Zlorthishen**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.
- [x] This PR ports commits from DDA or other cataclysm forks.
  - [x] I have attributed original authors in the commit messages adding [`Co-Authored-By`](https://docs.github.com/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) in the commit message.
  - [x] I have linked the URL of original PR(s) in the description.
  - [x] I have linked the URL of original PR(s) in the description.

## Purpose of change
allows bionics to be hidden

## Describe the solution
ports dda PR
 - https://github.com/CleverRaven/Cataclysm-DDA/pull/65243

## Additional context

Screenshot 2024-12-30 184700

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]
LGTM, only playtesting needed

**Review by RoyalFox2140 — APPROVED** [review]
image
image
image


Today I learned passive CBM's have their own menu

**Comment by scarf005** [comment]
~~i'm so excitied with this change i want to release a new one today~~

**Review by RobbieNeko — APPROVED** [review]
Builds on my machine and I can hide my alloy plating
image
image

**Pull request merged**
