### PR TITLE
fix: weapon, ammo and magazine storages don't need marksmanship or melee anymore

### PR DESCRIPTION
**Pull request by VissValdyr**
## Purpose of change
1. The usage for melee or marksmanship for some of the pouches/holsters was a bit arbitrary.
2. You can craft a holster of a pistol if you manage to throw enough stones.
3. You can craft a stealth if you brawl your way through a bar.
~~4. You could train marksmanship by crafting.~~

## Additional context
We should consider the same for bullets, since it is still quite arbitrary. Using a slingshot doesn't make you a gun expert, etc.

Also still old phone:
Screenshot_20240424-230907_FX
Pain, but better pain

### CODE REVIEW

**Comment by KheirFerrum** [comment]
I think using marksmanship and melee for more specialized versions could work, for instance you'd be able to make holsters without marksmanship but to make fast-draw holsters you'd either need a book or have enough marksmanship skill to know what design is most ergonomic for fast-draw.

**Comment by VissValdyr** [comment]
> I think using marksmanship and melee as secondary requirements for more specialized versions could work, for instance you'd be able to make holsters without marksmanship but to make fast-draw holsters you'd either need a book or have enough marksmanship skill to know what design is most ergonomic for fast-draw.

The problem with the "secondary skill" skill exists tho. It will be trained as well. Having the fast draw holster locked behind a book can work, but as far as I know has it a very limited range of volume for it (100-500 ml) while the regular has up to 1 liter. Also the time saved is not super high. I would leave as is, to be honest.
My characters Taurus spectrum is not big enough for the regular holster but fits in the fast draw.

**Comment by chaosvolt** [comment]
>     4. You could train marksmanship by crafting.

> The problem with the "secondary skill" skill exists tho. It will be trained as well.

Incorrect: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3921/files#diff-9459f71c123a6ab8652dd59412904defe2b9bef6b326d1da4b7e7671949ddd64R793

I assume you did not test this, or else was misled by the fact that a recipe can still train combat skills if it's set to the PRIMARY skill. If you are getting weapon or marksmanship EXP from these recipes then that's 100% a bug and not intended behavior.

**Comment by VissValdyr** [comment]
> > ```
> > 4. You could train marksmanship by crafting.
> > ```
> 
> > The problem with the "secondary skill" skill exists tho. It will be trained as well.
> 
> Incorrect: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3921/files#diff-9459f71c123a6ab8652dd59412904defe2b9bef6b326d1da4b7e7671949ddd64R793
> 
> I assume you did not test this, or else was misled by the fact that a recipe can still train combat skills if it's set to the PRIMARY skill. If you are getting weapon or marksmanship EXP from these recipes then that's 100% a bug and not intended behavior.

I was sure that I was able to train it? But maybe I checked wrong, apologies to that. But still, I would leave combat skills out of those containers. My points still stand.

**Comment by VissValdyr** [comment]
@scarf005 and @chaosvolt since you both are here active with the half gas mask PR, any reason to not implement it? If so, say so, and get it in please, so I can use it myself.

**Comment by chaosvolt** [comment]
Hmm. I guess it's fine either way, it's just the only real angle for this that really applies is ease of recipe access and/or recipe consistency. For the latter, how many other storage items are left after this that need combat skills to make?

**Comment by VissValdyr** [comment]
> Hmm. I guess it's fine either way, it's just the only real angle for this that really applies is ease of recipe access and/or recipe consistency. For the latter, how many other storage items are left after this that need combat skills to make?

None. Some use survival. But none use gun or melee skills

**Review by chaosvolt — APPROVED** [review]
¯\\_(ツ)_/¯

**Comment by VissValdyr** [comment]
> ¯\_(ツ)_/¯

At least you kept your arm this time

**Comment by VissValdyr** [comment]
You still have to merge it @chaosvolt .

**Comment by VissValdyr** [comment]
@scarf005 would you please merge it?...

**Pull request merged**
