### PR TITLE
Glues added to soldering iron recipe

### PR DESCRIPTION
**Pull request by Krwak**
#### Purpose of change

It is not possible to craft soldering iron without having duct tape. In order to get duct tape you either have to find it or learn the recipe from a book. You can't do any proper electronics work without having soldering iron and the problem of duct tape is a stopgap in this issue.

#### Describe the solution

I added the possibility of using bone glue or super glue in the recipe of soldering iron. I see no reason why only duct tape should be able to put the parts together.

#### Testing

Changed the recipe, loaded the game.

### CODE REVIEW

**Comment by Zireael07** [comment]
Suspicion: heat involved in soldering would melt the glue again?

**Comment by Krwak** [comment]
> Suspicion: heat involved in soldering would melt the glue again?

Could be an issue for bone glue but i'm unsure about that too as glues after being done have different properties as the ingredients used for creating the glue. And besides, these parts aren't holding together with glue alone. Besides besides, i'd omit that for gaming reasons.

**Comment by Krwak** [comment]
An alternative would be to have duct tape as auto learn recipe and scrape this PR.

**Comment by Lamandus** [comment]
> An alternative would be to have duct tape as auto learn recipe and scrape this PR.

we can do this, later autolearning duct tape

**Comment by Drugitechnik** [comment]
i think duct tape would been required to make soldering. To isolate cable ends. Also many glues are either destroyed by heat or getting soft.

**Pull request merged**
