### PR TITLE
fix: NPCs actually give items when asked

### LINKED ISSUE #1252: NPC can't provide anything to help in form of items even with successful check
# Describe the bug

When player asks NPC about any available job and there is one, it's always concludes in options about asking for advice and sharing equipment. TALK_SHARE_EQUIPMENT seems to me working as indented and provides necessary checks, but will always conclude in "NPC has nothing to give!" message (you can even thank them for it, nice)
In my experience, every NPC affected: the one that spawns in "fixed scenarios", any random encountered, and any traders from base game and/or from mods. See context below for additional details.

In short: right now NPC can't provide anything to help when you're accepting mission, but owe you literally everything when you complete it (most of the time). This is not very logical nor balanced.

# Steps To Reproduce

1. Start the game, create new world
2. Choose default "Play now!" fixed scenario
3. There will be NPC nearby, ask them for work
4. Convince them to share the stuff because you're helping them (it will most likely be 100% or close to it)
(you can repeat this check if failed - there is no practical punishment for asking multiple times in a row)
5. Thank them for nothing
6. Try nearby console to reveal refugee center
7. Debug teleport or walkthere
8. Repeat same stuff with trader who obviously HAS stuff to share
9. Thank them for nothing as well

# Expected behavior

NPC should be able to provide something practical to help player with accepted mission.

# Screenshot

изображение

# Versions and configuration

- OS: Windows 11
    - OS Version: 10.0 2009
- Game Version: 43e3981 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda]
]

# Additional context

Now things are getting interesting: they are, in fact, can share something - but only after successful completing mission. You can ask them to teach you something as a reward, or share equipment - and now this will work, because there is added debt for that NPC in form of mission value.

Said values for base game missions are out of hand, this is somewhat separate issue: they are too generous and this dialogue option is not a trial, but a fixed 100% success option that will provide player an option to simply take everything that NPC have as a reward because item values are far less than mission value is. Situation is a little better for refugee center since their value is less generous, but require a check as well since in some cases it provides opportunity to grab everything that NPC could provide in trade window, their Doctor as example. As continuation of steps above:

1. Debug "mark as complete" accepted mission from start-spawned NPC or complete it normally
2. Talk and ask for items as rewards.
3. Behold, they owe you a fortune that you're free to utilize right ahead or ask them later via "care to trade?" option

изображение

This is separate thing and "simple fix" via `missiondef.json` edit, but main issue here lies in the code that I'm not very good with; I think this should be something with `void talk_function::give_equipment( npc &p )` in `npctalk_funcs.cpp`.

### LINKED ISSUE #2662: "X has nothing to give!" commonly occurs when asking for items after accepting a mission, even when an NPC has items in inventory
### Describe the bug

When asking an NPC for a handout, most notably when accepting a mission for them and successfully getting them to give you stuff, they'll say they have nothing to give. This seems to occur most often with standard static NPCs like the evac merchant, and less often with starter/dynamic NPCs.

### Steps To Reproduce

1. Start off at the refugee center.
2. Accept their first mission and ask for stuff.
3. Assuming you have like 20 speech, get them to agree and see the mentioned message.
4. Repeat this with your starting NPC in an evac shelter, they seem more likely to successfully give you stuff.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: d0f7a99 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    <color_light_green>Cataclysm++</color> [Cata++],
    Elevated bridges [elevated_bridges],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    <color_cyan>Arcana</color>/<color_light_green>Cata++</color> Patchmod [Arcana_Cata++_Patch],
    Mining Mod [Mining_Mod],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Stats Through Kills [stats_through_kills]
]

### Additional context

So, I'd done a bit of poking around and some tests to try and find the cause. I came up stumped but it might help. First, the relevant functions seem to be, in order, `npc::wants_to_sell` -> `npc_trading::init_selling` -> `talk_function::give_equipment`. A cursory glance at `npc::wants_to_sell` indicates that's not the cause because the evac merchant should ALWAYS be returning true on that, as they're assigned to the shopkeeper status.

So one thing I tried was inserting a use of `add_msg` to `npc_trading::init_selling` to confirm that it was actually successfully finding items when it does this. It does even when it still fails to find anything to give:
image

All signs point to the cause PROBABLY being something in `alk_function::give_equipment` (https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/src/npctalk_funcs.cpp#L528), possibly this bit right here:
```C++
    std::vector<item_pricing> giving = npc_trading::init_selling( p );
    int chosen = -1;
    while( chosen == -1 && !giving.empty() ) {
        int index = rng( 0, giving.size() - 1 );
        if( giving[index].price < p.op_of_u.owed ) {
            chosen = index;
        } else {
            giving.erase( giving.begin() + index );
        }
    }
```

Now, I had a "wait a second" thought and for a briefly instant thought I had an easy JSON fix for this, but sadly that turned out to be a red herring. It SEEMS like something about NPC debt is failing to process right here. So you ever noticed that "because I'm helping you out" is probably the persuasion option literally everyone picks because the other dialogue options have utterly abysmal success rates even at 10 speech skill? Funny thing about that: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/npcs/TALK_COMMON_OTHER.json#L309

It's the only one of the bunch that doesn't call `add_debt` on a success. So I tried getting the evac merchant to gimme shit using one of the other options, again noting that the success rate is always annoyingly much lower than the option everyone picks. No dice, the message still triggers. So something weird is PROBABLY going on with the NPC trying to decide how much debt they need to resolve when giving you stuff, but it doesn't seem that it's MERELY a lack of starting debt on the NPC.

Or maybe it is a lack of starting debt and calling `add_debt` at the exact same time as `give_equipment` doesn't let the debt itself actually hit, I dunno.

### PR DESCRIPTION
**Pull request by scarf005**
## Summary

SUMMARY: Bugfixes "NPCs actaully give items when asked"

## Purpose of change

- fix #1252
- fix #2662 

## Describe the solution

- removed checks for debt entirely, as the player already passed the check.
- `TALK_SHARE_EQUIPMENT` was wrongly checking `infected`, fixed it to use `asked_for_item` instead.
- as that blocks repeated asking for items, added another dialogue option (with higher difficulty)
- made denying less rude, because that causes even friendly npc to swear at you

## Describe alternatives you've considered

migrate entire dialogue system to Lua

## Testing

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/6d752f00-7f2a-4bf7-996b-9e7564a4e737

### CODE REVIEW

**Comment by olanti-p** [comment]
There's some weird behavior with persuasion chances.
1. Spawn random NPC
2. Ask to do something for them
3. Accept mission
4. Ask for equipment
5. Choose "Well, I'm helping you out..." with 100% chance
6. Get equipment
7. Ask for more equipment
8. Persuasion check shows 100%
9. NPC agrees and gives something
10. Goto step 7
11. Eventually NPC gives away all their inventory and has nothing to give anymore.

**Comment by scarf005** [comment]
not sure why but persuation seems to be bugged atm.

**Comment by chaosvolt** [comment]
Looked into this now that I finally got it compiling. The rough problem is:
1. Accepting the mission bumps that NPC's value rating up high enough that "but I'm helping you out" will always pass. This is expected behavior I assume, makes it a quid pro quo situation.
2. The "I need more stuff to complete the mission" check will also always succeed at this level of value. This is less desirable.
3. Most importantly, repeatedly bullying the NPC for stuff does not modify the trust rating since both of these are the only success responses that don't penalize you, so the difficulty will never climb back up.


My thinking is probably some combination of:
1. Modifying the difficulty of the new "please sir can I have some more" check to be below 100% with the current trust level.
2. Making value or trust take a penalty when you succeed at talking them into stuff.

**Comment by chaosvolt** [comment]
Oh right, bonus: higher difficulty is easier, not harder. It going up from 12 difficulty to 30 is actually probably a way bigger cause here I just realized. XD

Good news, I played around with the JSON and got a setting that'd no longer let you freely steal everything from that NPC. Bad news, immediately afterward the NPC confronted me about stealing their shit because for some reason it's not cleaning up ownership of the dropped item.

I tested in build ` 2024-06-11` via artificially inflating an NPC's owed value, confirmed that this is indeed present in that build and not related to this PR. But I might do some testing right quick and maybe if I can find an easy fix for it this PR can double as a fix for that too...

**Review by chaosvolt — APPROVED** [review]
There we go, the second attempt to get stuff from an NPC is now much harder than the freebie first attempt, and it no longer has the NPC freak out over stolen goods because it correctly sets ownership before the item is passed around.

Approving but will leave it for either you to merge, Olanti to take another look at if he wants, etc.

image

**Pull request merged**
