### PR TITLE
Port over some DDA relic effects to BN

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Features "Port over a few more relic effects from DDA"

#### Purpose of change

Some basic enchantment values to port over. Took a bit of looking it over as the code as-is was affected by several prerequisite PRs. Evidently if I were to port over https://github.com/CleverRaven/Cataclysm-DDA/pull/41242 that would improve build speed but it looks significantly more involved. On top of that, I'd have had to implement MAX_HP different no matter what since the source PR's handling of it is rooted in the unhardcoded bodypart stuff.

Not actually all of them just yet, the second source PR contains a high volume of changes broken up into single commits. I decided I'd only port over the values specifically being used by Arcana mod at present. I'll port over the rest in a follow-up PR, if I can. The individual commits themselves are all easily ported over, basic one-line changes for the most part (aside from changing enchant_vals::mod back to enchantment::mod).

#### Describe the solution

1. Changes to character.cpp adding code that looks for REGEN_HP enchantments. MAX_HP is going in the "when I understand the code better" pile due to some issues with current code not pinging recalc_hp on grabbing an enchantment.
2. Change to character.cpp implementing the REGEN_STAMINA value.
3. Change to character.cpp implementing the FATIGUE value.
4. Added a REGEN_HP modifier to the cube of shame.

#### Describe alternatives you've considered

Mutations from enchantments would be great for this (HP modifiers, healing rate, stamina regen modifer, fatigue modifier, etc) but 90% of mutation properties still don't seem to work when called by an enchantment, even in the DDA version. Pretty much only hardcoded effects, mutation flags, and a handful of obscure things like `ignored_by`.

#### Testing

1. Compiled and load-tested.
2. Set HP to 1.
3. Spawned in a cube of shame, confirmed it now works after resolving previous inconsistencies (see below).
4. Temporarily dumped the BN version of Arcana in for testing.
5. Observed that Life Sign Suppression's current multiplier of -1.0 appeared to slow, but not halt, healing while the CBM was active.
6. Observed that debug mode reported an increase in stamina regen with the Temporal Stimulation CBM active.
7. Observed a fatigue gain of 3 every 5 minutes instead of 1 every 5 minutes, while Temporal Stimulation is on.

#### Additional context

PRs being ported over:
1. Part of https://github.com/CleverRaven/Cataclysm-DDA/pull/42030
2. Part of https://github.com/CleverRaven/Cataclysm-DDA/pull/42090

Properties that will be a priority for my to port over next PR:
1. MAX_HP turned out to be harder to get working than I'd hoped.
2. METABOLISM and THIRST, since I ported over FATIGUE. Since BN doesn't have the metabolic rate stuff, from what I can tell I'll need to put the implementation in Consumption.cpp instead for METABOLISM to work. We'll see.
3. MAX_STAMINA, since I ported over REGEN_STAMINA.

Side note, I was trying to find SOCIAL_PERSUADE since it's also one Arcana uses, but checked on https://github.com/CleverRaven/Cataclysm-DDA/issues/33837 and realized it actually hasn't been implemented yet. Not important to me, Arcana's use of it is basically just a flavor effect, I'll just have to remember to remove it from my mod JSON so I don't get confused in the future.

So, important note on REGEN_HP, I have observed some major issues with how it handles as of the source PR' s version of it:
1. Health regen modifier only did anything if you had a fast-healing trait, otherwise it had no visible effect on healing, with or without medical items applied.
2. Trying to disable healing with a -1.0 multiplier did not appear to properly disable healing outright.
3. An absurdly large negative multiplier, like -99 for example, did absolutely nothing without any healing traits, but would kils you dead as hell if if you do.
4. `add` had the same wacky behavior as `multiply`, i.e. only taking effect if you have a fast-healing trait, in both DDA and BN.

This was found to be present up to DDA build 11218, and mimicking the source PR's way HP regen was done produced the exact same inconsistencies. I've since been able to get it working as expected (though minimum healing appears to be enforced such that trying to outright disable healing with an enchantment won't work).

As for more current DDA handling, testing with 11246 found that the enchantment now just outright doesn't work at all in DDA, Fast Healer or no. Would recommend someone report an issue over there to inform them that the feature is broken.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The tests are failing. For a good reason.

**Comment by chaosvolt** [comment]
Uhoh. Any idea what's causing it? I as able to compile in VS and load-test it without issues.

**Comment by chaosvolt** [comment]
https://travis-ci.org/github/cataclysmbnteam/Cataclysm-BN/jobs/747771352 seems to imply overmap stuff?

**Comment by anothersimulacrum** [comment]
All (or many) of the healing tests are failing https://travis-ci.org/github/cataclysmbnteam/Cataclysm-BN/jobs/747771352#L1167-L1559

Consider learning how to compile the tests, it makes this much easier.

**Comment by chaosvolt** [comment]
I see that now, yes. Let me go over the change made to add the HP regen value, I'm fairly certain what I did was basically the same way it was structued in the source PR, just using BN's older method for pinging enchantment values, the one that predated the `enchant_vals` namespace.

**Comment by Firestorm01X2** [comment]
Visual studio already compiling tests. To run it look for separate exe in output directory. Likely it is already there.

**Comment by chaosvolt** [comment]
Ah, okay. I did see what might be a possible cause maybe?

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/248/files#diff-4fb59232b9e70232ceadaef037d3091e34e4a773b8d2c7fba8f488c15bdd6955R4736 vs https://github.com/CleverRaven/Cataclysm-DDA/pull/42030/files#diff-4fb59232b9e70232ceadaef037d3091e34e4a773b8d2c7fba8f488c15bdd6955R7077, `enchant_val::mod` does not have a boolean in its parameters while `calculate_by_enchantment` does, and is set to true in this case, which I'd retained due to all previous examples in character.cpp defaulted to true if I recall.

**Comment by chaosvolt** [comment]
I'll look for the test to run it in VS before I attempt to tinker with it though. Sorry I didn't get back to this until just now, stuff had come up.

**Comment by chaosvolt** [comment]
Some discussion on the modder discord later and found out the issue was because rounding is set to true. Just did the tests and just about now committing the change.
image

If I'd gone with my initial wild-ass guess I formed when I first tried to look into the problem that wouldn't fixed it ("Huh, DDA's take on this method doesn't even have that boolean, should I test switching it off or should I look at the function first..."), obvious downside being I wouldn't have known WHY it fixed it.

Problem on my end eventually became that I looked at what the boolean does in the function, forgot that it's altering a float that could potentially return 0.4 or lower, and continued with assuming that wasn't the problem. That was less "I don't know the code" and more "I didn't think it through all the way" in this case.

**Comment by Coolthulhu** [comment]
Alright, it doesn't break tests now. But I can't really test if it actually does the job...

**Comment by chaosvolt** [comment]
Oh, doh. I forgot to add these to the cube of shame. Guess I'll do that?

**Comment by Coolthulhu** [comment]
You should start porting and PRing a mod that actually uses all of that. The cube doesn't have any tests or mods tied to it. Without a mod that makes use of things, they may randomly be disabled or break.

It can be debug stuff for now, but it's n-th time in a row.

**Comment by chaosvolt** [comment]
True. Arcana would be the only mod that comes to mind as a good testbed for all this, as far as my mods go. And that one is still getting a lot of updates so making it in-repo might bog things down a bit.

I know that Magiclysm also makes use of a lot of this, but that's currently hung up by all the work needed to get https://github.com/cataclysmbnteam/Cataclysm-BN/pull/123 in working order.

**Comment by chaosvolt** [comment]
I've done some testing on this, and turns out I'm going to need to figure out some other way to implement the HP max enchantment. It's only updating if something else pings recalc_hp (like gaining the toughness mutation), and I can't figure out how the DDA version gets it to correctly grok that the enchantment has changed max HP.

Meanwhile, fixing up HP regen and it...sorta works. Well, it works exactly the same as it does in DDA, that is to say it's broken as all hell in both versions:
1. Health regen modifier only does anything if you have a fast-healing trait, otherwise it has no visible effect on healing, with or without medical items applies.
2. Trying to disable healing with a -1.0 multiplier does absolutely nothing, healing traits or no healing traits.
3. An absurdly large negative multiplier, like -99 for example, does absolutely nothing without any healing traits, but kills you dead as hell if if you do.

I'm gonna see if maybe `add` at least sorta works for DDA or BN, then strip out the max HP modifier and put it on my "stuff to do when I understand the code better" pile, because unless HP regen I don't actually use it in any mods.

**Comment by chaosvolt** [comment]
There we go. Health regen now seems to actually work without fast healing traits, and also made sure that fatigue and stamina regen enchantments actually work too.

**Comment by Coolthulhu** [comment]
I'm not sure if it works correctly. I tested a character with over 3.6 hp per limb and he healed from 1 hp to full in one "tick".

Also, other regeneration values don't have anything to back them up.

Honestly I'd rather hold this up until you can port bits of a mod that actually make some use of it. Even if it's cheap, it's not free performance-wise and it doesn't have test cases to guarantee it doesn't break.

**Comment by chaosvolt** [comment]
Hmm. I'm not sure then what would be the best option for a mod that uses it, nor any easy uses for that feature. Only arcana really uses it, and only for a very limited feature that honestly could be axed if necessary, nevermind that porting over arcana would be a massive endeavor. And given that it's currently just not even working at all in the DDA version...I guess I can go ahead and skip that one too, in favor of just the few other relic features I have actual use for.

I know that Magiclysm makes some use of various relic features, so if we can successfully modernize that it'll be easier to have working implementation for other features, but I know HP regen isn't used yet.

**Comment by chaosvolt** [comment]
Closing for now per discussion on the discord, there isn't any useful implementation of these features in Magiclysm to port over yet to provide an example, the only mod I use it for would be a lot of hassle to port into BN, and there are other existing ways to do what little I use this for using other relic/enchant properties like effects.

**Pull request closed without merging**
