### PR TITLE
Next changes to Generic Guns. (Renaming, Balancing, Removal and inclusion of guns, changes to migration, etc.)

### PR DESCRIPTION
**Pull request by Lamandus**
This is a biggy it changes around quite a bit in Generic Guns. Some changes may be disliked by one or the other, but all in all I am happy with the results:

- Give ammo a representative name. Gun names are based on the used ammo type.
- Removal of the player made pistol and magnum lever gun.
- Magnum guns can only use magnum rounds
- Addition of a bolt action sniper rifle and .22 revolver
- Addition of speedloader for magnum and .22
- Changes to the miggration lists to make it more fitting
- Standartization of damage output of all guns and balancing via dispersion. (Added damage to specific guns can be considered later on)
- removal of build in mods of every droped gun, since there was no variaty
- pump action shotguns now hold 7 shots

### CODE REVIEW

**Comment by scarf005** [comment]
i suggest to keep the names of the guns as-is unless there's overwhelming reason.

## Disadvantages to renaming gun names

### it's not possible to relate to gun names to what they do.
for example, the name `Skorpion` does not imply it's a pistol. the name `machine pistol` does.

### it makes ammo confusing
1. iirc `AT4` and `Carl Gustav M3` uses different ammo w/o generic guns. in generic guns, they share same `ammo_rocket` ammo. it could confusing.
2. it's easy to figure out `sporting shotgun`, `tactical shotgun` and `double-barrel shotgun` are both shotgun and share same ammo.  `Remington 870` and `Saiga 12` does not.

using more specific gun names could be frustrating and hinder user experience.

**Comment by scarf005** [comment]
(continuation from [discord](https://discord.com/channels/830879262763909202/830916451517857894/1075030499766046722))
some idea for 'truly generic' gun names:
```yaml
# data/mods/Generic_Guns/firearms/grenade.json
grenade pistol: [
    handheld grenade launcher,
    modular grenade launcher,
    one handed grenade launcher,
    detachable grenade launcher,
]

# data/mods/Generic_Guns/firearms/pistol.json
defensive pistol: pistol
survivalist carbine: pistol-caliber carbine
survivor subgun: survivor submachine gun

# data/mods/Generic_Guns/firearms/pistol_magnum.json
hand cannon: automatic magnum pistol
magnum levergun: magnum leveraction rifle
hunting magnum: hunting magnum pistol

# data/mods/Generic_Guns/firearms/pistol_tiny.json

plinker carbine: small caliber carbine
target pistol: small caliber pistol
zip gun: improvised small caliber pistol

# data/mods/Generic_Guns/firearms/rifle.json

sporter carbine: semi-automatic rifle
```

**Comment by scarf005** [comment]
love your new naming changes so far. my two cents on ammo name, tho:

### rifles
i think it'd be a good idea to be consistent with `5.56mm` diameter.

`.300` -> `7.62mm`
`.50` -> `12.7mm`

## pistols
maybe keep using the ammo name 'magnum' instead of `.44` could be a better choice since iirc the word magnum is more known.

**Comment by Lamandus** [comment]
> 

I can change it to mm, no problem. I would like to keep the .44 tho, keeping it constant.

**Comment by scarf005** [comment]
yeah, i agree that `.44` being consistent would be better.

**Comment by Lamandus** [comment]
> yeah, i agree that `.44` being consistent would be better.
> 
> more on gun rounds in inch / milimetre: .223 is [5.56mm NATO](https://en.wikipedia.org/wiki/5.56%C3%9745mm_NATO) .300 is [7.62mm NATO](https://en.wikipedia.org/wiki/7.62%C3%9751mm_NATO) .50 is [12.7mm NATO](https://en.wikipedia.org/wiki/12.7%C3%9799mm_NATO)

should I leave the grenade round ambiguous or make it 40mm

**Comment by scarf005** [comment]
i guess we could keep using the name `grenade`, since there's only one diameter (40mm), therefore being unambigous. the same could be said for shotgun ammo.

**Comment by Lamandus** [comment]
I tested the changes. Now all should run smoothly. The only thing we should reconsider is, if we call the sub machine gun: SMG or by its full name.
grafik

**Pull request merged**
