### PR TITLE
Allow turreted laser weapons to fire manually

### LINKED ISSUE #931: Unable to fire laser weapons from the same tile where turret mount is placed in a vehicle
# Describe the bug

Placed turret mount on the same tile as are vehicle controls and seat, with laser rifle but unable to shoot it by pressing 'f'(fire wielded item).
It works when going through the menu though but this is very tedious.
Error message appears, which is below.
When changing setting 'circular distance' in options then the error disappears but still unable to move reticle from the position.
When using regular weapons it is possible to shoot with 'f' from the same spot as turret mount is, whether vehicle controls are present or not.

# Steps To Reproduce

1. New, world with new vehicle a laser A7 rifle and turret mount
2. Place turret mount somewhere in the vehicle and mount A7 laser rifle
3. Stand on the same spot as the turret mount is and press 'f' while hands of the character are empty.

# Expected behavior

I expect laser weapons to behave the same as non laser weapons - that is i can place turret mount above the driver's seat in a vehicle and be able to shoot from that position by pressing 'f' (fire wielded item).
I expect being able to use turret mount that is not placed in the same spot as vehicle controls using the same method - just like it works with non-laser weapons.

# Screenshots

image
image
image
image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 31c2adc [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda]
]

# Additional context

[Lake Success.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7230486/Lake.Success.zip)

### PR DESCRIPTION
**Pull request by OrenAudeles**
#### Summary
SUMMARY: Bugfixes "Allow turreted laser weapons to be fired manually"

#### Purpose of change
Fixes #931

#### Describe the solution
Adds check to see if the weapon being fired has UPS drain if the weapon's ammunition is "null"

#### Testing
Before fixing tested to make sure the issue was as stated in the linked issue and that it is not already fixed.
Placed a loooooooooooot of calls to `DebugLog( DL::Info, DC::Main )` to figure out relevant differences between manual fire and group firing from vehicle control.
Added the check to see if it would be using UPS power / Vehicle Battery and reset the range.
After adding in the UPS test and solution, successfully fired the laser turret manually.

### CODE REVIEW

**Comment by OrenAudeles** [comment]
This might be cleaner if I changed the code to
```cpp
if( relevant->get_gun_ups_drain() == 0 && ( ammo_current == "null" || ammo_current.empty() ) ) {
    ammo = nullptr;
    range = 0;
} else {
    ammo = item::find_type( ammo_current );
    range = turret->range();
}
```

**Comment by Coolthulhu** [comment]
Has a minor conflict with the `itype_id` PR that I merged recently.

**Comment by OrenAudeles** [comment]
> Has a minor conflict with the `itype_id` PR that I merged recently.

ah, the `itype_id -> string_id<itype>` PR. I was wondering why `itype_id` wasn't already using `string_id<T>` and now it does :D I'll fix shortly

**Comment by Coolthulhu** [comment]
Still shows "ammo: none", but it can fire.

**Pull request merged**
