### PR TITLE
Quickfix for sweetbread missing from offal_raw

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Bugfixes "fix sweetbread not being usable in offal recipes, make comestible_test.cpp more forgiving"

#### Purpose of change

Quick fix for a thing I just now noticed got missed during https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1371, sweetbread was axed from the new crafting requirement by accident.

#### Describe the solution

Re-added sweetbread to the `offal_raw` crafting requirement, also added a suggested tweak to one of the tests along the way. Basically less use of standard deviation in favor of a fixed (more forgiving) distance away from default calories.

#### Describe alternatives you've considered

Procrastinating until Coolthulhu does it.

#### Testing

Checked affected file for syntax and lint errors.

#### Additional context

How the fuck did I not notice that when I looked over that PR, I thought I eyeballed it for the sake of grabbing offal item IDs for the follow-up PR (https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1519)...

### CODE REVIEW

**Comment by chaosvolt** [comment]
Okay, so now we have what should be a basic one-line fix instead being more complicated because the test is being weird. First it was complaining because 2 sweetbread seemed to be too much, but this latest test failure makes zero sense:
```
/home/runner/work/Cataclysm-BN/Cataclysm-BN/tests/comestible_test.cpp:144: FAILED:
  CHECK( lower_bound <= mystats.calories.avg() )
with expansion:
  196.77972f <= 193.1666666667



RecipeID: offal_canned, Lower Bound: 196.779724, Average: 193.166667, Upper Bound: 607.220276

/home/runner/work/Cataclysm-BN/Cataclysm-BN/tests/comestible_test.cpp:144: FAILED:
  CHECK( lower_bound <= mystats.calories.avg() )
with expansion:
  393.55945f <= 386.3333333333



RecipeID: offal_pickled_jarred, Lower Bound: 393.559448, Average: 386.333333, Upper Bound: 1214.440552
```

**Comment by Coolthulhu** [comment]
> It already has two high-calorie offal items and several low-calorie ones, an in-between ingredient shouldn't screw things up that readily.

It calculates standard deviation, meaning every point close to the mean makes it want less variance.

**Comment by chaosvolt** [comment]
> It calculates standard deviation, meaning every point close to the mean makes it want less variance.

Ah, weird. Any idea on how to enable it to pass the test while still letting sweetbread work in the recipe again?

**Comment by Coolthulhu** [comment]
> Ah, weird. Any idea on how to enable it to pass the test while still letting sweetbread work in the recipe again?

We probably should rework the test to have some minimum spread. `stddev` is not a good idea for thresholds.

**Comment by chaosvolt** [comment]
Ah, hmm. Not sure how to go about that, nor if that'd be out of scope for this fix.

**Comment by chaosvolt** [comment]
Reverting the change to the comestible test, this seems to need to be a separate PR as it's going to be bigger than the intended one-line change to allow sweetbread.

**Pull request merged**
