### PR TITLE
feat(content): more ramp options

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

Another random item on the todo list, I was gonna add this to the mod but now it's mainlined so :3

## Describe the solution

C++ changes:
1. In construction.cpp, defined versions of `check_ramp_low` and `check_ramp_high` that also call `check_empty`, so wooden ramps need clear space to construct on (unlike with the other two that construct on specific non-empty terrain).

JSON changes:
1. Added construction and construction group entries for rammed earth and wooden ramps. Each step is set to equal the resources needed to craft one rammed earth wall and wooden wall respectively. These currently, per feedback, produce generic ramps instead of specific terrain, since the ramp_up functions would all need to be special-cased in for each ramp type.
2. Edited name and description of road ramps to fit being used as generic ramps.

## Describe alternatives you've considered

Figuring out how to JSONize the ramp functions properly.

## Testing

1. Checked affected JSON files for syntax and lint errors.
2. Compiled and load-tested.
3. Constructed ramps with debug hammerspace on.
4. Confirmed that wooden ramps can't be built in shallow pits or fence posts like the other two are meant to.
5. Checked affected C++ file for astyle.

## Additional context

zq340nye28l61

### CODE REVIEW

**Comment by scarf005** [comment]
i think until we get to make ramp generic on material it'd be better to not hardcode variants of it. (example: many many grills)

**Comment by chaosvolt** [comment]
So make the output generic instead of coding new ramp functions and adding new ramp terrain?

**Comment by scarf005** [comment]
yeah, i think it would be easier to maintain in the long term.

**Review by scarf005 — APPROVED** [review]
image
image

the rules for building is quite confusing but at least i was able to build both two new types of ramps.

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
