### PR TITLE
feat: Remove z-level restriction for zones.

### PR DESCRIPTION
**Pull request by vitalyo7**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

Update the code to ignore z-level differences when working with zones. This should make it easier to setup loot zones across the z-levels for easier loot managements, i.e. basements, roofs, apartments and LMOE. It was a bit annoying to carry the loot up/down stairs.

## Describe the solution

Solution is to remove all checks for z-level, both in the GUI and code that interacts with zones.

## Describe alternatives you've considered

None. I think zones are currently the best way to manage loot, and just need to tweak them to work properly.

## Testing

This is half-tested. I compiled the code, did some zone setup in my LMOE bunker and asked my main char to sort out the loot. Seem(s) like it worked. However more testing will likely be required. Volunteers appreciated.

## Additional context

I am not sure why there was an original z-level restriction in place, was it because game could not handle multi-z? So removing the restriction could possible break something else. I will be monitoring this closely as I use npcs + zones frequently. Having multi-z zones should also make it easier to use NPC to do more manual labor.

I plan on adding more zone-related changes in the future like npc: specific zones for sleeping, labor, relaxing so this is one step in that direction.

### CODE REVIEW

**Review by chaosvolt — CHANGES_REQUESTED** [review]
Compiled and load-tested, two flaws found so far, one minor then one bigger:
1. Minor, but the zone menu doesn't really show you when a zone occupies more than one z-level.
2. More major, if the input zone occupies more than one z-level, trying to sort loot cancels out if you try to go up or down stairs:
image

I tested placing a zone in the basement that was confined to a single z-level and it correctly moves stuff to a receiving zone on ground level, so not sure why it starts acting up if the zone is a multi-level one.

**Comment by vitalyo7** [comment]
I will fix the issues reported. I think zones themselves should be restricted to 1 z-level, but you should be able to work with the zones located on different levels, i.e. have loot drop off at the ground level, and loot zones in basements, roofs etc, for those players who like to setup their hoard in locations other than z=0.

**Comment by chaosvolt** [comment]
Good luck, hope it goes well.

**Comment by vitalyo7** [comment]
Added a restriction to same z-level for now, should be a good workaround for the issues reported.

**Comment by vitalyo7** [comment]
Closing the pull request because i messed up the branches/commits and the file revisions are not showing correctly, will re-add when fixed on my end.

**Pull request closed without merging**
