### PR TITLE
ci: ignore `no_hope` and `aftershock` on all mods test

### LINKED ISSUE #3896: add `no_hope` to all mods test blocklist
i think it'd be safe to ignore `no_hope` for all mods test

_Originally posted by @scarf005 in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3870#issuecomment-1849129896_
            
## Rationale

- not actively maintained anymore
- causes frequent test failure

### PR DESCRIPTION
**Pull request by scarf005**
## Purpose of change

- resolves #3896
- fixes test failure introduced by #3876

### CODE REVIEW

**Comment by Vollch** [comment]
Ehm, i don't think it's good idea to allow mods to be broken. With ranting tests we're at least fixing game breaking bugs when they shows up, even if mods are not actively maintained. But if we'll just ignore them we'll eventually end having totally broken and unusable garbage in repo.
Imo in-repo mods should be either be in working state... or obsoleted, and ditched form repo.

**Comment by Vollch** [comment]
I specifically checked that before posting, and no_hope it's *not* obsoleted in current master, you can create world with it.

**Comment by RoyalFox2140** [comment]
We haven't heard anything back from the author of No Hope in the Discord, I think it's time to obsolete No Hope and allow it to be taken up as third party. Aftershock will only have bugs if I do something stupid while I'm mainlining things, it's not far reaching like No Hope and it's hundreds (I don't think this is an exaggeration) of overwritten locations itemgroups and monsters.

Note that obsoletion is just a single line in the modinfo so it will still be playable if someone goes the extra mile, I wouldn't fully delete it until someone is maintaining our version as we've put a fair bit of work into maintaining it once it actually does break tests.

**Comment by scarf005** [comment]
alternatively, #3927 could work.

**Comment by scarf005** [comment]
closing in favor of #3927.

**Pull request closed without merging**
