### PR TITLE
feat(content): Adds Mechanical and Electrical engineering professions

### PR DESCRIPTION
**Pull request by teater1**
Adds two professions, one for Electrical Engineering and one for Mechanical Engineering. They are mostly based on the Medical Resident profession and their own Mechanic/Electrician counterparts and are more focused on skill than gear.

This is my first Github PR ever, so perhaps expect a gigantic messup.

### CODE REVIEW

**Comment by Zlorthishen** [comment]
The numbers seem a little low. Is a skill level of 4 considered a college degree?

**Comment by teater1** [comment]
> The numbers seem a little low. Is a skill level of 4 considered a college degree?

Fair observation, but this seems to be the trend with a lot of roles like Medical Intern who starts with a teeny weeny 4 First Aid.

**Review by chaosvolt — APPROVED** [review]
One of these days profession skills could use a big sanity-checking since skill points on their own aren't that valuable, but in any case this looks aight. I do wonder whether their outfits could be made to differ any, or if any in-game items would be reasonable as profession tools to start with (though them having higher skills but not starting with practical tools of their trade is I guess the main contrast they have vs the regular working mechanic and electrician professions).

**Comment by teater1** [comment]
> One of these days profession skills could use a big sanity-checking since skill points on their own aren't that valuable, but in any case this looks aight. I do wonder whether their outfits could be made to differ any, or if any in-game items would be reasonable as profession tools to start with (though them having higher skills but not starting with practical tools of their trade is I guess the main contrast they have vs the regular working mechanic and electrician professions).

Fair! I did give it a bit of thought, and as far as I know most electrical and mechanical engineers are just your good old technical white-collar workers dealing mostly with programs and Excel sheets (soulless). The only difference I can think of would be Civil Engineers who get to wear reflective vests and white hard hats. Another reason for no unique equipment is the fact that these are meant to be more brain-heavy counterparts for their Electrician and Mechanic counterparts, like you pointed out.

**Pull request merged**
