### PR TITLE
Mutation rebalancing

### PR DESCRIPTION
**Pull request by Coolthulhu**
Plenty of mutations are terrible, especially armor mutations.
This should help a bit.

Quick: cost 3->4
Thick skin: +2 all phys armor
Thin skin: -2 all phys armor
Bad knees: cost -1->-2
Sleepy: cost -1->-2
Deaf: cost -4->-6
Forgetful: OBSOLETED
Lightweight: 0 points, no longer starting trait
Addictive personality: cost -2->-1
Chemical imbalance: cost -2->-1, no longer randomly mutated
Animal discord: no longer starting trait
Schizo: cost -3->-1, renamed "Psychosis"
Weak stomach: no longer starting trait

All armor-providing mutations got 50%-100% boost to armor
All claws got damage bonus around 3*hand*points
Lowered strength scaling of hooves and raptor talon
Horns got big boost to damage, added strength scaling

Exposed the NV range of mutations to json as "night_vision_range"

Removed unused bash_bonus, cut_bonus, size_bonus from Creature
Fixed stab bonus not working on claws

### CODE REVIEW

**Comment by TrainTurningPoint** [comment]
-6 for deaf seems like too much, hearing isn't really that important.
What's the reason for 'Animal discord' change?

**Comment by Coolthulhu** [comment]
> -6 for deaf seems like too much, hearing isn't really that important.

Deafness can't be compensated for in many cases. You lose the ability to check for existence of things on the other side of the wall, turret warnings, night raid warnings.
I'm not sure if 6 points is a good value, but I certainly wouldn't pick it at 4.

> What's the reason for 'Animal discord' change?

It was a free point.
The way animal aggression works, you'd need a partly-provoked animal to notice you for this trait to matter. Or to move within 5 tiles of a potentially-aggressive animal.
Also, animals other than insects generally suck after very early game, so even when it does things, it doesn't do much.

**Comment by TrainTurningPoint** [comment]
>turret warnings

A chance of random death (or debilitating wounds) because you can't see nor hear a dangerous enemy isn't worth even 6 points.
It would be better to return turret light. 

>things on the other side of the wall

Creatures are not making sounds constantly, at least not sounds loud enough to hear without bionics or mutations.
So hearing is not a reliable way of detection. If you don't hear an enemy on the other side of the wall, it doesn't mean there is no enemy. The objectively optimal way is to behave as if there is one.
It's good to have an additional bit of info here and there, but it's not a game-changer.

>night raid warnings

'Light step' + 'Night vision' + 3 points in perception would allow you to see zombies before they notice you much more reliable than hearing, thus negating this penalty completely while giving tons of other benefits.

>The way animal aggression works, you'd need a partly-provoked animal to notice you for this trait to matter. 
In my experience, it did matter. 
The little buff in aggression prevented you from screaming the animals away, made it harder to lure a pack of wolves into killing some zombies for you, things like that. I'll concede that it's very situational, and might not even come up before animals stop being a threat.

I'd rather see it reworked than removed, because "more triggering to enemies" is one of the starting traits which actually could have interesting effect on gameplay. Maybe extend it to all enemies (yes, I know that zombies are always at max anger right now) and/or raise the aggression range.
But I get your point now.

**Comment by Coolthulhu** [comment]
> A chance of random death (or debilitating wounds) because you can't see nor hear a dangerous enemy isn't worth even 6 points.

It's not about instakills, it's about planning your kiting, avoiding opening doors that lead to zombies, detecting underground labs.
Nothing vital, but still useful.

> negating this penalty completely while giving tons of other benefits

As a starting trait, deaf has to be balanced slightly differently.
It can't be compared to positive traits of equal values, but rather to combinations of negative traits.
For example, high thirst, lactose intolerant, wool allergy combo, which is less detrimental than deaf.

> I'd rather see it reworked than removed, because "more triggering to enemies" is one of the starting traits which actually could have interesting effect on gameplay.

It's not entirely removed, just no longer a starting trait.
It's not an inherently wrong idea, it just doesn't really work with aggression+morale+triggers. It would work with Qud style factions or if animal companions were an important mechanic.

**Comment by TrainTurningPoint** [comment]
>For example, high thirst, lactose intolerant, wool allergy combo

I'd rather get rid of these instead of using them for comparison.
Or lump all of these intolerances and allergies into a single 1-point composite trait. Akin to martial art ones, only with the ability to choose one or more (for roleplaying purposes) specific problems.
While potentially important, right now these are free points.

Compare it with 'Illiterate', a single 6 point trait. Prevents the comfiest way of raising skills and a good way to replenish focus, blocks off half of the crafting recipes, forces you to waste a lot of resources breaking into lab vaults. Overall tremendously cuts the available strategic options.
Compare with 'Frail' for 6 points. While not as bad as it sounds (getting hurt for 50% of HP in a single fight usually means a pain spiral which would cause you to die anyway), it makes player much more vulnerable to certain enemies. A particularly lucky shocker could outright kill you in just two zaps from full HP. Same for turrets and other high damage ranged opponents.
Compare with 'Languorous' + 'Slow-footed', which would practically remove your ability to walk away. A very drastic change to the gameplay for 5 points only. Throw in 'Bad knees' for 7 and you'll have to fight pretty much every enemy you encounter right then and there.
Deafness doesn't even come close to these limitations.

>It's not entirely removed, just no longer a starting trait.

Effectively removed, since animals would be irrelevant by the time you get it.
I'm fine with it, it doesn't really work as is. Was just curious about your reasoning.

**Comment by Coolthulhu** [comment]
> Compare it with 'Illiterate', a single 6 point trait. Prevents the comfiest way of raising skills and a good way to replenish focus, blocks off half of the crafting recipes

Until you befriend even a single NPC to read for you.
Then it only blocks off computers.
In a no-NPC world I'd give it -12, but there is no way of splitting up point costs like that.

> Compare with 'Frail' for 6 points.

I forgot to note, but it's 10 in this PR. Flimsy is now 6 points.
Flimsy is painful, but so is missing all the loud warning signs of a hulk charging through multiple walls.

> Compare with 'Languorous' + 'Slow-footed'

That's a synergy, they aren't as painful separately.
Those traits are hard to evaluate because they have positive counterparts of similar magnitude. The negative ones hurt more, but playstyle adjustments make them not matter as much. If the positive ones had higher point costs, they would be bad.
Another problem with those is that a vehicle makes them not matter, but vehicles aren't all that balanced anyway.

Once there are fewer free point traits, I'll probably boost value (magnitude) of the anti-movement ones above their positive counterparts.

> I'd rather get rid of these instead of using them for comparison.

Worth considering.
I'll be removing or merging the free points traits as they become noticeably free-pointy. I didn't do a proper allergy purge yet.
For example, a "vegan" trait forbidding wearing leather (among other things, obviously) would be a good allergy trait, since many of the really good armors include leather, fur or wool.

For now, I still see Deaf as a 5-6 point trait. That's how many points would I want for taking it over the existing alternatives.
Once I go through the free pointers, I'll probably bring it back down.

**Comment by TrainTurningPoint** [comment]
>Until you befriend even a single NPC to read for you.

Having to keep an NPC alive for reading significantly limits your playstyle.
Good that you brought up NPCs though, I completely forgot that deafness prevents conversations.
That's a serious downside which does justify the high payoff in points.

>I forgot to note, but it's 10 in this PR. Flimsy is now 6 points.

And Frail is -14? Can you even take it without freeform?
It's one of the reasons I don't like 4+ point traits, they take too much of the allotted 12 point limit and decrease your options.

I'm also not sure Fragile/Frail/Flimsy in particular deserve this much for the reason stated above.
You HP is not really important most of the time. The way health mechanic works, if an enemy can remove 25-75% of your HP, it can usually do 100% just as well and you shouldn't be fighting him at all. Played plenty of 4 str Fragile characters into and it barely mattered, even with risky playstyle.
I'd like to rework them to be completely different, but it's probably a topic for a separate PR.

>That's a synergy, they aren't as painful separately.

Yes, but we've been talking about thematic combos.

>For now, I still see Deaf as a 5-6 point trait.

Yes, I agree now that you mentioned NPCs.

**Comment by Coolthulhu** [comment]
> And Frail is -14? Can you even take it without freeform?

I'll need to check. I may need to make it -12.
> The way health mechanic works, if an enemy can remove 25-75% of your HP, it can usually do 100% just as well and you shouldn't be fighting him at all.

Being able to kill most of the things without taking any damage is a serious problem, but low HP is still more painful than most of equally priced traits. I hope this improves as the game becomes faster paced and complete damage avoidance becomes much harder to pull off.
Though I disagree about the 25% - 100% equivalence, BN pain and stamina spirals are much more stable than in DDA. Also, you can apply adrenaline.
> Yes, but we've been talking about thematic combos.

In the context of bundling free point traits together, not combining already painful traits.

**Pull request merged**
