### PR TITLE
feat(balance): Solar power bump

### PR DESCRIPTION
**Pull request by yay855**
Made regular solar panels generate 80 power instead of 50 and advanced solar panels generate 160 instead of 100.

## Purpose of change

Solar panels are rather weak ingame currently, and struggle to properly recharge vehicles and power grids.

## Describe the solution

The power generation of all solar panels will be increased by roughly 60%.

## Describe alternatives you've considered

Reimplementing quantum solar panels.

### CODE REVIEW

**Comment by yay855** [comment]
I have no idea why this doesn't work, can someone please help?

**Comment by RoyalFox2140** [comment]
I have no idea what power units this game is in since 80 is an arbitrary number, but some real world data:

So the average commercial solar panel is 1.75m x 1.03m and is a 500 watt panel. Given advancements of course that will go up and we set BN in the future. We can calculate the power per meter squared from this if we want. Though it's also worth mentioning nothing is in it's proper wattage including refrigerators. The whole grid system is arbitrary.

https://www.solarreviews.com/blog/500-watt-solar-panels
https://www.cleanenergyreviews.info/blog/most-powerful-solar-panels

**Comment by yay855** [comment]
That's a good idea, but I'm too burnt out today to figure that out. Maybe tomorrow.

**Comment by Zireael07** [comment]
I remember a similar discussion either here or on CDDA repo with links to insolation maps and panel power outputs...

**Comment by chaosvolt** [comment]
I hate the vehicle power tests I swear XD

**Review by chaosvolt — APPROVED** [review]

**Pull request merged**
