### PR TITLE
[WIP] CBM rebalance to make installation more accessible.

### PR DESCRIPTION
**Pull request by Firestorm01X2**
CBM rebalance to make installation more accessible.

#### Summary
SUMMARY: Balance "CBM rebalance to make installation more accessible."

#### Purpose of change
https://github.com/cataclysmbnteam/Cataclysm-BN/projects/3
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/57

First step- making CBM more accessible.
For now used Aftershock approach with certain tweaks.

#### Describe the solution
Tasks:
* [ ] Making Autodoc installation safer by increasing autodoc bonus.

#### Describe alternatives you've considered
None for now.

#### Testing
TODO

#### Additional context
None.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Slot system isn't ready for enabling yet. The slots aren't balanced.
If the anesthesia system is disabled in core, it needs to be properly ripped out, not just suppressed.

Harvestable CBMs and slots will require their own PRs, since they are big.

Also:
To get checkmarks, you write `* [ ] Text`.
You should get a spellchecker in English.

**Comment by Firestorm01X2** [comment]
Ok. I need to think about approach a bit. I am starting to think that starting throwing away things like anastetic kits probably is not great idea now.
Maybe we can work with current requerments after certain tweaking.

Overall idea is to make CBM more acessable. It can work even with anastetic kits.

**Comment by Coolthulhu** [comment]
Try to make PRs as specific as possible at first.
For example, "safe autodoc" mod, added to default mods, would be specific and achieve easier CBMs pretty quickly.

**Comment by Coolthulhu** [comment]
You could easily make it a ~10 line thing by creating a "Guaranteed Autodoc Installation" mod, overriding autodoc in it, then adding it to `data/mods/default.json`.
Though it would be better to open a new PR, because this one has a history of commits.

**Comment by Firestorm01X2** [comment]
> 
> 
> You could easily make it a ~10 line thing by creating a "Guaranteed Autodoc Installation" mod, overriding autodoc in it, then adding it to `data/mods/default.json`.
> Though it would be better to open a new PR, because this one has a history of commits.
Yeah.  should start from scratch. 
I am thinking about not just making gurantedd install but just buffing install chances via autodoc to the pointmm where chance going to quite hight but not 100% guranteed.

**Pull request closed without merging**
