### PR TITLE
Move all uncraft recipes (except unpacking) into uncraft folder

### PR DESCRIPTION
**Pull request by Lamandus**
This is a double whammy. It moves all uncraft recipes into the uncraft folder (where it belongs) and also sane checks a lot of recipes (for example 5 hours for an AI array for a bot, giving not much stuff for the time wasted).

### CODE REVIEW

**Comment by Lamandus** [comment]
this will conflict with the #2345 , so either this should merge first, or the other, repectively

**Comment by Lamandus** [comment]
conflicts resolved

**Comment by Coolthulhu** [comment]
Having both changes happen in one commit makes it harder to review...

I'll need to figure out how to compare just the changed times.

**Comment by Lamandus** [comment]
I will split the PR then, no problem

**Pull request merged**
