### PR TITLE
BN ascii art name for main menu

### PR DESCRIPTION
**Pull request by Firestorm01X2**
screenshot 2020-09-11 001

BN ascii art name for  main menu
First line (Graffiti) is: http://www.patorjk.com/software/taag/#p=display&f=Graffiti&t=Cataclysm
Second line (Big) is: http://patorjk.com/software/taag/#p=display&v=1&f=Big&t=Bright%20Nights
#### Summary

BN ascii art name for  main menu
#### Purpose of change

We need at least proper title.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Ready also. Probably there is still special ascii titles for rework (like New Year one).

**Comment by Firestorm01X2** [comment]
I need to think a about logo for a bit

**Comment by Firestorm01X2** [comment]
No. it is ready.

**Comment by Firestorm01X2** [comment]
screenshot 2020-09-11 001

**Comment by Firestorm01X2** [comment]
Ready

**Comment by anothersimulacrum** [comment]
Documentation for anyone in the future who is curious: The Bright Nights does not use the same (Graffiti) font, because the `N` in particularly does not look very good.

http://www.patorjk.com/software/taag/#p=display&f=Graffiti&t=Cataclysm%0ABright%20Nights

**Comment by Firestorm01X2** [comment]
> The Bright Nights does not use the same (Graffiti) font, because the `N` in particularly does not look very good.

screenshot 2020-09-11 001g

**Pull request merged**
