### PR TITLE
feat(balance): updates to firestarting tools

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

Some adjustments to firestarting tools and related items. In particular making ember carriers a bit less bothersome to work with, while making the tinder mechanic used on a couple more tools in exchange for allowing more items to be used for that.

## Describe the solution

1. Added the `REQUIRES_TINDER` flag to fire drills and camp fire drills. These are even more work to light a fire with than a flint and steel, which was the only item to have this flag.
2. Added `SLEEP_IGNORE` to light ember carriers. As oddball of an item as they are, I've found them to be really useful for extreme innawoods runs where keeping a slow-burning fire on hand is a lot less trouble than fiddling with flint and steel and helps skip some potential issues when in the dark, but the main drawback with it is it expects you to keep it burning for long periods of them. Not pestering you about sleeping with it on will help make it more usable for that purpose.
3. Added the `TINDER` flag to several more items that might reasonable be useful fodder for starting a fire: rolling paper, feathers, down feathers, coal/charcoal, withered plants, pine boughs, straw piles, cigarette butts and related, cotton balls, and fuel briquette.

## Describe alternatives you've considered

1. Adding `TINDER` flag to splintered wood to make things slightly easier, or any other items that others feel may be appropriate.
2. Alternatively, phasing out the `REQUIRES_TINDER` flag for now. In particular, I kinda would like for the fireplace examine action to automatically target an item with the `TINDER` flag as its first choice of fuel if the selected firestarter has the relevant flag, so that tinder gets used automatically from firewood sources. Not sure how to implement that though.

## Additional context

1. Checked affected files for syntax and lint errors.
2. Checked in compiled test build that pine boughs and other non-ammo items are accepted as tinder.

### CODE REVIEW

**Comment by VissValdyr** [comment]
Do the fuel briquettes also have tinder tag added? https://cbn-guide.mythoscraft.org/item/fuel_briquette

**Comment by VissValdyr** [comment]
> Alternatively, phasing out the REQUIRES_TINDER flag for now. In particular, I kinda would like for the fireplace examine action to automatically target an item with the TINDER flag as its first choice of fuel if the selected firestarter has the relevant flag, so that tinder gets used automatically from firewood sources. Not sure how to implement that though.

Maybe as a second option in the examine menu, start fire with tinder (will take tinder item first) or start regular fire, it will take something else. Like a log for example

**Comment by VissValdyr** [comment]
Sorry for the spam, did you check the functionality with the charcoal kin?

**Comment by chaosvolt** [comment]
Oh right I forgot the fuel items existed, I need to follow up on those someday if I recall.

**Comment by chaosvolt** [comment]
> Maybe as a second option in the examine menu, start fire with tinder (will take tinder item first) or start regular fire, it will take something else. Like a log for example

I mean, there's no reason not to just make it grab tinder automatically if the tool being used needs it, it's just I haven't really looked that deep into the code to figure out how to do that.

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
