### PR TITLE
build: Add deno typescript support to repository

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: Infrastructure "Add deno typescript support to repository"

#### Purpose of change

[deno](deno.land/) is a cross-platform runtime for running typescript in local environment. some of its benefits:

> **TypeScript out of the box**
> First-class support for TypeScript – no need to spend hours configuring things that break as soon as you update a dependency.

> **Great all-in-one tooling**
> Built in linter, code formatter, ability to build a self-contained executable, test runner, IDE integration, and more.

also, packages are imported from URL, making deno script very portable.
```ts
import { brightGreen } from "https://deno.land/std@0.182.0/fmt/colors.ts"

const world = "World"
console.log(`Hello, ${brightGreen(world)}!`)
```

some examples of deno's benefits in #2544: 
- [fully type safe argument parsing](https://github.com/scarf005/Cataclysm-BN/blob/6d76bf2ec829e7623b08ab2054c355ce6f6daa1e/tools/json_tools/gunmod/run_migration.ts)
- [type definitions](https://github.com/scarf005/Cataclysm-BN/blob/6d76bf2ec829e7623b08ab2054c355ce6f6daa1e/tools/json_tools/gunmod/types.ts)
- [built in testing support](https://github.com/scarf005/Cataclysm-BN/blob/6d76bf2ec829e7623b08ab2054c355ce6f6daa1e/tools/json_tools/gunmod/crossbow_test.ts)
- comments allowd in config file (`deno.jsonc`)

#### Describe the solution

cherry-picked config from #2544

### CODE REVIEW

**Comment by scarf005** [comment]
its primary use is to replace outdated python 2 `tools/json_tools`. deno was chosen not just because it's cool, but it's type safety makes maintaining tools written in them easier. for immediate usages, #2544 could be an example.

**Comment by olanti-p** [comment]
Ok, I can get the desire behind replacing python with typescript.

I don't necessarily agree with it: having the majority of the tooling in python is much better than having most of it in python and some parts in typescript. From [googling around](https://www.statista.com/statistics/793628/worldwide-developer-survey-most-used-languages/) it seems that typescript is a bit behind python in popularity, but pure JS is way ahead, so we can expect contributors to know typescript to some extent same as we would with python. But having to know 1 language if you want to work with any tooling script is better than having to know 2.

Given the benefits and how outdated some python scripts are, I wouldn't be opposed if most or all our relevant scripts were to be switched to typescript (even if I would have to learn the language). Don't know what the other devs and contributors think though, or whether it impacts them.

>for immediate usages, https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2544 could be an example.

It should've been added in that PR then, along with documentation that explains what it is and how to use it. Config file for tooling that does not exist serves no purpose.

**Comment by Zireael07** [comment]
@olanti-p: Python is VERY popular (heck, we use it at my day job for a large Django website) BUT the lack of typing IS indeed often getting in the way.

JS is more popular than TS by a looong shot (it's pretty much THE language to use if you do ANY webdev at all). But it has the same problem as Python, with no types. Hence the bigger and more complex projects readily move to typescript.

**Comment by scarf005** [comment]
@Zireael07 yeah fully safe type python can be written usong type hints but our scripts aren't written using any of these type hints.

**Comment by scarf005** [comment]
> How much effort is it to set up TS support on Windows in a way that will work with the build system (if needed)?

> "How required" would it be to set it up to build a full build (tiles, sounds, translations, tests) in MSVC?

### To run the scripts

Only one executable, deno (or deno.exe) [(installation)](https://deno.com/manual/getting_started/installation) is needed to setup the system. No additionawl step is required to set up formatter, tester, linter, benchmark tool, etc as deno has all of them bundled. Also, no node_modules are required as deno manages package using URL.

### Make it with the build system

```yaml
- uses: denoland/setup-deno@v1
```

https://github.com/denoland/setup-deno works with linux, windows and mac.

> Would you be willing to write a doc on it?

Of course. it could take multiple PRs, however.

> Would it be easy enough that say, a tileset maker could follow it, despite having no knowledge of TS or any real programming for that matter?

With some help (and some 3 hours of screensharing) @Kenan2000 could understand the scripts. I've also provided lots of guides and templates so beginners could edit the values and use.

> What's the expected role of TS in the project? Just used for some parsing or general usage?

General usages. Can be used for any jobs that is not done by the game engine.

> Is it supposed to replace Python or be used alongside?
I'd prefer replace, so that we don't have multiple scripting languages, but then someone would need to rewrite the scripts.

> Is it supposed to replace Python or be used alongside?

The plan is to completely replace them. I've only rewritten `cddatags.py` for now. Might as well as ask for help to @DeltaEpsilon7787 as they are experienced in TS.

**Pull request merged**
