### PR TITLE
feat: Armor values specified directly in armor JSON

### PR DESCRIPTION
**Pull request by Coolthulhu**
## Purpose of change

Allow fine-tuning armor values, without having to rely on materials and material thickness.

## Describe the solution

Armor item type now has an extra field: "resistance".
It looks like this:
```JSON
"resistance": { "cut": 0, "bullet": 1000 }
```

If this field is specified, armor values from materials and thickness are ignored.

Note: if armor override is specified, armor values are not reduced when the armor is damaged.

## Describe alternatives you've considered

* Trying to salvage material thickness system by adding material percentage (10% plastic, 90% steel etc.) to allow more fiddling

## Testing

* Tests pass
* Spawn debug item "bulletproof armor"
* Spawn turrets
* Get shot and take no damage
* Spawn zombie predator
* Confirm that all attacks deal damage, including the impale attack, which is piercing type and scratch, which is cutting

## Checklist

* [x] Default to material values if override isn't specified for a given type
* [ ] Docs
* [x] (Optional) Reduce armor value with damage based on material thickness pre-damage and post-damage

### CODE REVIEW

**Comment by scarf005** [comment]
maybe it'd be better if overrides could be defined using #2776

**Comment by Coolthulhu** [comment]
> maybe it'd be better if overrides could be defined using #2776

Will do, it may be a source of conflict otherwise.

**Comment by scarf005** [comment]
alright. in my opinion, while manually overriding armor values could be useful in some cases, i'd like the material system to get more love, e.g computing various armor stats from material composition
we do have material thickness, but it's manually defined and doesn't get computed from coverage/armor proportion data/weight/volume.

**Comment by Coolthulhu** [comment]
> i'd like the material system to get more love, e.g computing various armor stats from material composition

That could be cool if we could manage it, but so far, the material system has been more of a hindrance than a benefit.
We don't have transmutation of materials or material variants of the same item, but we still have all the downsides that come from a material system. If we ever get material variants, we could revisit calculation from materials.

**Review by scarf005 — APPROVED** [review]

**Comment by chaosvolt** [comment]
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\optional(69,17): warning C4244: 'initializing': conversion from '_Ty' to 'float', possible loss of data
1>        with
1>        [
1>            _Ty=double
1>        ] (compiling source file ..\src\damage.cpp)
1>C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\src\damage.cpp(528): message : see reference to function template instantiation 'std::_Optional_destruct_base<_Ty,true>::_Optional_destruct_base<double>(std::in_place_t,double &&)' being compiled
1>        with
1>        [
1>            _Ty=float
1>        ]
1>C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\src\damage.cpp(528): message : see reference to function template instantiation 'std::_Optional_destruct_base<_Ty,true>::_Optional_destruct_base<double>(std::in_place_t,double &&)' being compiled
1>        with
1>        [
1>            _Ty=float
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\optional(185): message : see reference to function template instantiation 'std::_Optional_construct_base<_Ty>::_Optional_construct_base<double>(std::in_place_t,double &&)' being compiled
1>        with
1>        [
1>            _Ty=float
1>        ] (compiling source file ..\src\damage.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\optional(185): message : see reference to function template instantiation 'std::_Optional_construct_base<_Ty>::_Optional_construct_base<double>(std::in_place_t,double &&)' being compiled
1>        with
1>        [
1>            _Ty=float
1>        ] (compiling source file ..\src\damage.cpp)
1>C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\src\damage.cpp(437): message : see reference to function template instantiation 'std::optional<float>::optional<double,0>(_Ty2 &&)' being compiled
1>        with
1>        [
1>            _Ty2=double
1>        ]
1>C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\src\damage.cpp(435): message : see reference to function template instantiation 'std::optional<float>::optional<double,0>(_Ty2 &&)' being compiled
1>        with
1>        [
1>            _Ty2=double
1>        ]
```
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(660,27): warning C4244: 'return': conversion from 'float' to '_Rx', possible loss of data
1>        with
1>        [
1>            _Rx=int
1>        ] (compiling source file ..\src\item_factory.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(821): message : see reference to function template instantiation '_Rx std::_Invoker_ret<_Rx,false>::_Call<_Callable&,const material_type&>(_Fx,const material_type &) noexcept(false)' being compiled
1>        with
1>        [
1>            _Rx=int,
1>            _Callable=Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>,
1>            _Fx=Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c> &
1>        ] (compiling source file ..\src\item_factory.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(822): message : see reference to function template instantiation '_Rx std::_Invoker_ret<_Rx,false>::_Call<_Callable&,const material_type&>(_Fx,const material_type &) noexcept(false)' being compiled
1>        with
1>        [
1>            _Rx=int,
1>            _Callable=Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>,
1>            _Fx=Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c> &
1>        ] (compiling source file ..\src\item_factory.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(821): message : while compiling class template member function '_Rx std::_Func_impl_no_alloc<Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>,_Rx,const material_type &>::_Do_call(const material_type &)'
1>        with
1>        [
1>            _Rx=int
1>        ] (compiling source file ..\src\item_factory.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(717): message : see reference to class template instantiation 'std::_Func_impl_no_alloc<Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>,_Ret,const material_type &>' being compiled
1>        with
1>        [
1>            _Ret=int
1>        ] (compiling source file ..\src\item_factory.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(911): message : see reference to variable template 'const bool _Is_large<std::_Func_impl_no_alloc<<lambda_4b9ec9ab2f0215014811fd4b67454d7c>,int,material_type const &> >' being compiled (compiling source file ..\src\item_factory.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(1042): message : see reference to function template instantiation 'void std::_Func_class<_Ret,const material_type &>::_Reset<Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>>(_Fx &&)' being compiled
1>        with
1>        [
1>            _Ret=int,
1>            _Fx=Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>
1>        ] (compiling source file ..\src\item_factory.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\functional(1042): message : see reference to function template instantiation 'void std::_Func_class<_Ret,const material_type &>::_Reset<Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>>(_Fx &&)' being compiled
1>        with
1>        [
1>            _Ret=int,
1>            _Fx=Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>
1>        ] (compiling source file ..\src\item_factory.cpp)
1>C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\src\item_factory.cpp(605): message : see reference to function template instantiation 'std::function<int (const material_type &)>::function<Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>,0>(_Fx)' being compiled
1>        with
1>        [
1>            _Fx=Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>
1>        ]
1>C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\src\item_factory.cpp(603): message : see reference to function template instantiation 'std::function<int (const material_type &)>::function<Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>,0>(_Fx)' being compiled
1>        with
1>        [
1>            _Fx=Item_factory::finalize_pre::<lambda_4b9ec9ab2f0215014811fd4b67454d7c>
1>        ]
```
Still compiles but pretty error spammy, both seem to be caused by this PR?

**Pull request merged**
