### PR TITLE
wheels can be uncrafted to scrap metal and rubber chunks

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Features "wheels can be uncrafted to scrap metal and rubber chunks"

#### Purpose of change
Wheels couldn't be uncrafted. This will add the recipe for doing so. Metal saw needed.

### CODE REVIEW

**Comment by Zireael07** [comment]
I guess this applies to DDA too?

**Comment by Lamandus** [comment]
There was a big PR about making tires and wheels separate and with a lot of busywork. So no

**Comment by Coolthulhu** [comment]
The resulting mass is a bit low. You should bump it a bit, compare it with mass and volume of the wheel.

**Comment by Lamandus** [comment]
Ok, maybe some more metal... I will tweak it a bit

**Pull request merged**
