### PR TITLE
Security camera doesn't overlap vehicle doors anymore

### PR DESCRIPTION
**Pull request by Krwak**
#### Purpose of change

Fixing the issue #1922 where security cameras will overlap vehicle doors and make it impossible to see if doors are opened or closed.

#### Describe the solution

I have removed "location": "on_roof" from the vehicle_parts.json and thus security cameras will no longer show on cars.
This isn't ideal solution but i don't know of anything else to make it work.

#### Describe alternatives you've considered

Anything that will show security cameras on car but not when on the same tile with doors.
Please let me know if you have a better solution to this problem.

#### Testing

I made the change and loaded the game. Cameras aren't visible anymore on cars and thus don't overlap doors.
Tested if cameras are working with closed curtains and they are.

#### Additional context

image

### CODE REVIEW

**Comment by RelMayers** [comment]
Does it change how cameras behave in any way?

**Comment by Krwak** [comment]
A better solution from Coolthulhu was to:
>- specify z order in parts as a separate field that defaults to the one that we have right now. The second field would use same syntax and all. So you could have "real layer" be roof, but the "draw layer" be set to something else.
>- there should be a .h file where vehicle_part is defined and a .cpp file that contains something like vehicle_part::load or deserialize or something like that
>- vehicle_part would need to have the new draw layer field declared (same type as location), the loading function would need to try to load the field in the same way it loads location, then the z-order calculating function would need to use the new draw layer instead of location.

**Comment by Krwak** [comment]
> Does it change how cameras behave in any way?

No, it doesn't change it but there are more elegant solutions to this problem which would require to change hardcode and atm waiting if that will be implemented or not before closing this.

**Review by scarf005 — APPROVED** [review]
this PR has been waiting for over half an year, and there weren't better solution than this really.

**Comment by KheirFerrum** [comment]
I don't think this is a particularly ideal solution though. If the cameras are destroyed I'd like to be able to see it. You can sort of work around the camera and door overlap by not building cameras on doors, you can't do anything to work around cameras being invisible, which makes it so that you'll only know if a camera has been destroyed if you look at the frame one by one in the vehicle build menu, or if you turn on the camera system to see that one section of your camera field has gone dark.

**Comment by scarf005** [comment]
i'm not sure why, but this PR seems to break vehicle tests in #2690.

**Pull request merged**
