### PR TITLE
feat(balance): Survivor Suits Rebalance Mk2

### PR DESCRIPTION
**Pull request by yay855**
## Purpose of change

Survivor suits required kevlar or a kevlar vest (and you can use the former to craft the latter) to craft, but had far more encumbrance and far less armor, as well as having far less storage than the nomad gear. Having _some_ higher encumbrance is good because it has storage and protects from the weather, but the rest are problems.

## Describe the solution

The survivor suits are now rebalanced, with the light survivor suit having the same armor stats as the kevlar vest, the other survivor suits having increased armor to compensate, and the storage capacity buffed to 15 liters to be similar to the Nomad Gear.

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]
uwu

**Comment by chaosvolt** [comment]
Having screenshots of the armor values would be neat too tho, if possible.

**Comment by yay855** [comment]
Sure, I'll grab some. First, for reference, the kevlar vest, which I haven't altered:
image

Next, the light survivor suit:
image

The light superalloy suit:
image

The medium suit:
image

The winter suit:
image

The heavy suit:
image

And the heavy superalloy suit:
image

**Comment by yay855** [comment]
Wait, shit, the nomad gear is much more encumbering. I'll bump up the encumbrance of the suits.

**Review by chaosvolt — APPROVED** [review]

**Pull request merged**
