### PR TITLE
feat(balance): allow more ingredients in different meat based recipes, add of new meat groups

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
Meat and wood soups were good, but they lacked some consistency, for example, already cooked meat products can be used, but not all. For example raw offal was possible, but cooked variants weren't. Also I added some groups to make better list and add missing meals.

## Describe the solution
1. Add a cooked offal group
2. Add a raw and cooked meat+sausage group
3. Add those groups to different soups
4. Add cooked offal to many recipes that only took raw offal (sausage)
5. added large craft versions for sausages (for large stomach)
6. moved bologna and jerky out of raw meat, added them to their groups respectively
7. tinker the amount of ingredients used for different soups
8. 

## Testing
No errors.

## Additional context
smoked meat is now found in a lot more recipes, same with canned meat and fried offal.

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]
Seems aight, wait for tests just in case tho

**Comment by Firestorm01X2** [comment]
Unrelated broken ranged test
изображение

https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/8535955466/job/23383476166?pr=4422

**Comment by Lamandus** [comment]
> `meat_cooked` seems to not exist, causing errors in tests. https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/8536528897/job/23385237383?pr=4422#step:14:2014

ah, one mod was using that. I corrected it.

**Review by Firestorm01X2 — APPROVED** [review]
Ready

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
