### PR TITLE
standard house palette update - bedside table

### PR DESCRIPTION
**Pull request by LilShiningMan**
#### Summary
SUMMARY: Content "added standard house palette furniture entry - nightstand"

#### Purpose of change

adding an entry for a bedside table or nightstand to standard house palette for all of my upcoming house additions.

#### Describe the solution

added entry to house palette. Changed corresponding entry in 2StoryModern03 to reflect the nighstand change on basement level and 2nd floor.

#### Describe alternatives you've considered
not adding the entry

#### Testing
added, linted, spawned 2storymodern03 ingame, it works.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
`Json error: data/mods/dda/../../json/mapgen/house/2storymodern03.json:131:38: format: rows: row 15 column 7: '¤' has no terrain, furniture, or other definition`

Looks like only one of the houses changed to use the new symbol have a floor for it set as well.

**Comment by LilShiningMan** [comment]
Strangely enough, this is really similar to the issue I'm having in [adding these houses to CDDA ](https://github.com/CleverRaven/Cataclysm-DDA/pull/61174) as well. In that case, the symbol in question is already an established entry in the standard house palette, and it spawns perfectly in game when I add the symbol to house layout (and call the standard palette), but Github isn't happy about it, saying it's undefined.  

Same issue here, as I've defined the symbol in BN's standard palette, which is called by the updated house entries on both the basement and 2nd floor levels that are throwing the error.

From what I can tell, either:
1) I shouldn't add the palette update in the same PR that I am changing the house layout   *OR*
2) the above won't make a difference and it'll still throw the error like in my CDDA PR

This might be an issue with calling multiple palettes in the same house layout and Github not appreciating that, or it could be that GitHub doesn't like these weirder symbols ("image" in BN or "image" in CDDA), even though the games recognize them just fine.
 
Definitely open to suggestions on this one.

**Comment by olanti-p** [comment]
Same as with #1904, it's caused by No_Hope overwriting the `standard_domestic_palette` palette in `data/mods/No_Hope/palettes.json`. Duplicating your changes there should fix it.

**Comment by LilShiningMan** [comment]
Thanks, I'll try and fix this when I'm home.

**Pull request merged**
