### PR TITLE
feat(balance): Sandwich standardization and tweaks

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
Sandwiches were all over the place. Strange values, no standard charges and very sloppy "coding". Spawns were also very strange.

## Describe the solution
1. Use "copy-from" for all sandwiches, deluxe being the standard
2. remove cucumber and BLT sandwiches
3. spawn deluxe and deluxe no cheese in different places
4. spawn a lot more deluxe sandwiches
5. only one charge is produced per craft
6. all have the same volume and weight because a 250 ml ingredient pile got 1500 ml out of nowhere

### CODE REVIEW

**Review by chaosvolt — COMMENTED** [review]
Basic idea seems good but obsoleting BLT is probably gonna look weird.

**Comment by Lamandus** [comment]
> Basic idea seems good but obsoleting BLT is probably gonna look weird.

I take the blame from BLT lovers. The Deluxe version also can use bacon has more enjoy-ability, and is a lot more versatile

**Comment by chaosvolt** [comment]
If the tests pass I guess... ¯\_(ツ)_/¯

**Comment by Lamandus** [comment]
> If the tests pass I guess... ¯_(ツ)_/¯

you lost an arm

**Review by chaosvolt — APPROVED** [review]

**Pull request merged**
