### PR TITLE
feat(port,content): Add Convention Center

### PR DESCRIPTION
**Pull request by Zlorthishen**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
ports dda 
- https://github.com/CleverRaven/Cataclysm-DDA/pull/65097

## Describe the solution
adds the map location `Convention Center` along with a couple of items, also adds the convention center to the Large Building scenario

## Testing
👍 

## Additional context
temp2
temp3
temp1

### CODE REVIEW

**Comment by RoyalFox2140** [comment]
Time to screm

**Comment by RoyalFox2140** [comment]
Can we get some screenshots for everyone's reference?

**Review by RoyalFox2140 — APPROVED** [review]
We do not use ALIGN_WORKBENCH AFAIK

**Comment by RoyalFox2140** [comment]
WAIT that was the wrong button!

**Review by RoyalFox2140 — CHANGES_REQUESTED** [review]
We don't make use of ALIGN_WORKBENCH

**Review by chaosvolt — COMMENTED** [review]
Don't spot anything obviously screwy this time, though it could arguably use monster spawns, and item spawns seem a lil barebones.

**Comment by 0Monet** [comment]
can we change in the palette "!": "t_grate" into "!": "t_grate_indoor"?

**Review by RoyalFox2140 — APPROVED** [review]

**Comment by RoyalFox2140** [comment]
> Don't spot anything obviously screwy this time, though it could arguably use monster spawns, and item spawns seem a lil barebones.

I said in the Discord it was already hard to review with how big and it was going to get followups

**Comment by RoyalFox2140** [comment]
> can we change in the palette "!": "t_grate" into "!": "t_grate_indoor"?

Seems reasonable. I'll try to get Zlor on Discord.

**Review by RoyalFox2140 — DISMISSED** [review]

**Comment by RoyalFox2140** [comment]
@Zlorthishen @0Monet We haven't ported t_grate_indoors so now tests are failing. It's an invalid terrain. I don't mind if someone wants to port it later but that change needs a revert.

**Comment by 0Monet** [comment]
https://cbn-guide.mythoscraft.org/terrain/t_grate_indoor
tests fail because the id was not written correctly, also "t_grate_indoor" doesn't even exist on cdda

**Comment by Zlorthishen** [comment]
> https://cbn-guide.mythoscraft.org/terrain/t_grate_indoor tests fail because the id was not written correctly, also "t_grate_indoor" doesn't even exist on cdda

the only grate is on the roof, therefore it is outdoors

**Review by RoyalFox2140 — APPROVED** [review]

**Pull request merged**
