### PR TITLE
[CR] Normalize electric tools' ridiculous power comsumption

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary
SUMMARY: Balance "Normalize electric tools' ridiculous power comsumption"

#### Purpose of change
there were already numerous issues about electric construction tools power consumtion in DDA:
- https://github.com/CleverRaven/Cataclysm-DDA/pull/31757
- https://github.com/CleverRaven/Cataclysm-DDA/issues/35203
- https://github.com/CleverRaven/Cataclysm-DDA/issues/32503
- https://github.com/CleverRaven/Cataclysm-DDA/issues/46742

and complains in korean roguelike community:
- https://gall.dcinside.com/board/view/?id=rlike&no=408923&page=1

in terms of realism, battery powered electric jackhammer might make no sense at all and only having two charge to go out may be reasonable. however in terms of gameplay it's a terrible tool and really needs some buff.

#### Describe the solution
reduce electric jackhammer and chainsaw's power usage by a factor of tens.
since i don't know much about electric tools, numbers could always change. any opinions are appreciated.

#### Describe alternatives you've considered
Make electric constructon tools to be able to connect into vehicle with jump cables or power grid.
That's going to be a large project, however.

#### Testing
Json only.

#### Additional context
None

### CODE REVIEW

**Comment by chaosvolt** [comment]
Regarding chainsaw charges per use in particular, see: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1487

In short, the idea of "turn chainsaw on, use it while it's on and hope it doesn't run dry in the middle" is considered a poor hack, and it's much more sane to simply shift the axe quality (and thus all the uses its use action provides) to the inactive state. This takes advantage of a...quirk, shall we say, in which item transformation basically does not even remotely handle `charges_per_use` the way you'd expect it to, which means that an item can have a use action that drains X amount of charges while allowing it to transform without consuming any charges.

**Comment by scarf005** [comment]
yeah, this PR is more of a hack than a proper solution. i still think something should be done quickly to the numbers before better solution is merged..

**Comment by chaosvolt** [comment]
To be fair, pretty much every solution currently available is a hack of some form or another. I don't think these two PRs will run too afoul of each other other then a possible merge conflict due to one picking a charges_per_turn of 250 for electric chainsaws and this one going for 125, however. That said, changing the value as seen in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1544/files#diff-61088bc015dff8071426938caf72c858940c2136a0fd9a8e8c587dfd1c428db7R162 doesn't really do anything currently, since transforming the item to its active state doesn't actually drain charges.

In fact if I went and changed it so electric chainsaws consumed 25% their expected battery capacity instead of 50% that'd put the two PRs back in sync with each other and should (I think) prevent a merge conflict regardless of which gets merged first.

**Comment by scarf005** [comment]
alright, i think it'd be better to change numbers to match up with your PR, since this PR was focused around fixing electric jackhammers.

**Comment by chaosvolt** [comment]
No worries, whichever way works.

**Comment by Coolthulhu** [comment]
I'm not concerned about realism, but if electric tools were much more efficient, it could reward micro.
From my manual test, it looks like 250 units of gasoline can become:
* ~1100 batteries when converted by a car - ~4.4 conversion ratio
* ~1800 batteries when converted by a generator - ~7.2 conversion ratio

I checked a gallon jug (3.75L) of gas in generator to make sure it's not randomness and got ~27400, so ~7.3 conversion ratio.

I don't remember when did it improve, but in the past, gas to batteries was almost free energy. Back then, those inefficient electric jackhammers were just equivalent to the gas ones in energy use.

Looks like your numbers fit the current conversion ratios much better than the old ones, so it's an improvement.

**Pull request merged**
