### PR TITLE
fix: don't spawn military guns or ammo on shooting range

### PR DESCRIPTION
**Pull request by Lamandus**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
grafik

Guns and ammo may spawn somewhere on the shooting range, but we have a weapon safe and a ammo dispenser doing the job.

## Describe the solution
Remove random played gun spawns, tidy up.

### CODE REVIEW

**Comment by scarf005** [comment]
but maybe it could be someone dropped the guns and ammo when evacuating?

**Comment by Zireael07** [comment]
I think that represents range goers who took out things out of the dispenser/safe and then dropped it/were killed/changed during the event

**Comment by Lamandus** [comment]
> but maybe it could be someone dropped the guns and ammo when evacuating? overall, i'm a bit leery on removing potential loots from shooting range.

I think when such a evacuation happens, they would try to take every gun with them, not leave them behind. We have the gun safe and the ammo vendor there now, so very high value things. 

also
`{ "chance": 75, "item": "guns_milspec", "x": 5, "y": 4 },` <- it had the chance of 75% of spawning military rifles/ammo/magazines, which doesn't fit.

**Comment by Lamandus** [comment]
I am still hesitant to put those things back in, I will put in the common guns back, but not the military rifle.

**Review by scarf005 — APPROVED** [review]

**Comment by RoyalFox2140** [comment]
Just to add my two cents here:

In a case of game balance removing this would be amazing because we already hand out way too many free firearms via military supply drops, corpse piles of scientists/soldiers/drug deals, and military vehicles with turrets you can uninstall

From a realism standpoint those loose firearms should be on a corpse or a zombie because I don't see the range goers leaving that behind during an apocalyptic event, so even if we keep them I'd prefer spawning a corpse with the gun on it. I know that's pedantic but I find it more immersive. I'd still prefer axing the spawn altogether as Viss wants to do.

**Pull request merged**
