### PR TITLE
refactor: split `options.cpp` to individual files

### PR DESCRIPTION
**Pull request by scarf005**
## Summary

SUMMARY: Infrastructure "Split options.cpp to individual files"

## Purpose of change

it takes too long to adjust options because the file is very long

## Describe the solution

split options.cpp into multiple sub-src files to make rebuild faster

## Describe alternatives you've considered

completely JSONize options

## Testing

_it built on my machine_

## Additional context

tree structured project when?

### CODE REVIEW

**Comment by olanti-p** [comment]
There's little sense to split it up like this while we have flat project structure. This will make 10 new files in the main source folder, which is already a pain to navigate. Also, more `.cpp` files -> more translation units -> more work for compiler.

> it takes too long to adjust options because the file is very long

I always search needed options there with Ctrl+F, it's much faster than any manual search through the file.

**Comment by scarf005** [comment]
oh, i meant compilation time wise.

**Comment by olanti-p** [comment]
How long does it take to compile after single change?

**Comment by scarf005** [comment]
around 4 times faster.

## method used

1. built with same command twice to ensure it is incremental
2. flipped default boolean value of `ANIMATIONS` and `ANIMATION_RAIN`, once to avoid CCache caching output

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/879c61970bf514b86ab51d4a6e3dafd1076fe92c/src/options.cpp#L1795-L1803

## Output

### before splitting
```sh
 ~/r/c/Cataclysm   *$-  build  time ninja -j 10 cataclysm-tiles
[2/2] Linking CXX executable /home/...repo/cata/Cataclysm/cataclysm-tiles

________________________________________________________
Executed in   12.26 secs    fish           external
   usr time   11.38 secs  410.00 micros   11.38 secs
   sys time    0.39 secs   99.00 micros    0.39 secs
```

### after splitting
```sh
 ~/r/c/Cataclysm   split-options $  build  time ninja -j 10 cataclysm
-tiles
[2/2] Linking CXX executable /home/...repo/cata/Cataclysm/cataclysm-tiles

________________________________________________________
Executed in    3.06 secs    fish           external
   usr time    2.36 secs    0.00 micros    2.36 secs
   sys time    0.24 secs  533.00 micros    0.24 secs
```

**Comment by olanti-p** [comment]
I think you're exaggerating the issue.

It's -9 seconds from incremental build of that single file, which is rarely edited more than once a month, at the cost of +N seconds to overall compile time each time the clean build is done and +N milliseconds each time you try to navigate around the files starting with "o".

**Comment by scarf005** [comment]
well, this will be better handled after tree file structure gets introduced.

**Pull request closed without merging**
