### PR TITLE
feat(balance): make dog whistle easier to craft

### PR DESCRIPTION
**Pull request by VissValdyr**
## Purpose of change
The wooden dog whistle is a typical grind recipe. It takes no effort to make it and requires fab 4 to make.

## Describe the solution
1. Reduce fabrication to 2 to fit to other recipes in its category 
2. Instead of fine cutting, drilling is needed

### CODE REVIEW

**Comment by VissValdyr** [comment]
> So does it fixing it being a typical grind recipe actually do anything to fix grinding past fabrication level 4?

Somewhat. You can just go for metallurgy. Forge is lvl 4, anvil lvl 3 and you can then start to craft your base tools to level up, or if you are fancy, get some bolts.

**Comment by chaosvolt** [comment]
Hmm. I guess consistency-wise, regular flutes are also level 2, but bone flutes use cutting while wooden flutes use drilling. That's an inconsistency I didn't spot last time. Nevermind that I would assume a dog whistle would be a higher fabrication level anyway for both realism (not super vital) and gameplay (more relevant) purposes. For the former making a specific pitch would logically take more finesse, while for the latter the dog whistle actually does something combat-related while the flute is just a flavor item for morale.

Worth noting as well that even level 1 drilling is a pain in the ass in vanilla, since makeshift drills use metal parts and flint drills are still in MST Extra.

**Comment by chaosvolt** [comment]
It's all very minor since it's not like this item is that useful anyway and there are still good ways to get past fabrication 4, and even if there aren't, we want to try and make it so you can level more skills without deliberate craft-grinding anyway.

I just mostly don't want to disrupt cases where craft-grinding is the only reasonable way to progress a level until after we've made it no longer needed via adding better ways to get past that level, and I hadn't scrutinized this fabrication level to see how easy it is to get past currently.

**Comment by VissValdyr** [comment]
Yeah, I totally forgot to mention the consistency. I was looking at the other flutes and because I was grind crafting, I noticed the difference in-between the recipes. I can however make it a fabrication 2, learn at 4 if you wish, Chaosvolt

**Comment by chaosvolt** [comment]
Maybe? I mean, I guess it works either way, just seems...eh.

**Comment by VissValdyr** [comment]
> Maybe? I mean, I guess it works either way, just seems...eh.

Since it is in no recipe book, let it at fab 2... If you manage to make musical instruments at that level, so you should make a high pitch whistle

**Review by chaosvolt — APPROVED** [review]
Still seems kinda inconsistent but eh. ¯\\_(ツ)_/¯

**Pull request merged**
