### PR TITLE
feat(balance): less fruit, berries and nuts in forests

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
Right now it is very very easy to life off acorns and other nut/fruits from one stroll in the forest.

The reason for this is, that the original t_tree now have said acorns, which make around 70% of all trees in the forest. Living of a forest is very easy.

This still doesn't remove the playstyle at all, but it takes a bit more effort, so much so, that raiding a town (for non innawoods players), get more of a option. Pine trees are more common, so pine nuts are still farmable.

## Describe the solution
This fixes it by reducing the amount of oak trees significantly, lowering the amount of fruit/nut bearing trees, raising the amount of dead trees without being overbearing. And raise the amount of non berry bushes as well.

## Additional context
this is an "old" forest
grafik

this is the same distance walked with the new forest
grafik

### CODE REVIEW

**Comment by Zireael07** [comment]
Like the idea as such but a) tulips don't grow in forests and b) tulips don't grow on trees

**Comment by Lamandus** [comment]
> Like the idea as such but a) tulips don't grow in forests and b) tulips don't grow on trees

I went another approach

**Comment by Zireael07** [comment]
Looks like your another approach just consists of boosting cottonwood trees' numbers

Also: I went to google to help you find other stuff that could grow in forests and it seems you were on a track with the original idea, something called 'tulip tree' is indeed native to the area and grows pretty flowers: https://www.westonnurseries.com/the-large-trees-of-new-england/ but needs a translator comment as a very minimum as more people will get confused like I just did

Back to 'other stuff' idea, wiki has this to say: 

> Typical woody [understory] and shrub layer species include moosewood, low-bush blueberry and other heath species, especially the genera [Gaylussacia and [Vaccinium].

Woody plants of the ground cover layer include American wintergreen and partridge berry. Common wildflowers include star flower, bluebead Lilly, foam flower, bunchberry, twinflower, dewdrops, wild sarsaparilla, and Canada mayflower. [Trilliums], and yellow lady slippers (genus Cypripedium) are also common showy wildflowers. The herbaceous layer also includes many mosses, lichens, and ferns. Bracken fern is often particularly abundant in these communities.

**Comment by Lamandus** [comment]
> Looks like your another approach just consists of boosting cottonwood trees' numbers
> 
> Also: I went to google to help you find other stuff that could grow in forests and it seems you were on a track with the original idea, something called 'tulip tree' is indeed native to the area and grows pretty flowers: https://www.westonnurseries.com/the-large-trees-of-new-england/ but needs a translator comment as a very minimum as more people will get confused like I just did
> 
> Back to 'other stuff' idea, wiki has this to say:
> 
> > Typical woody [understory] and shrub layer species include moosewood, low-bush blueberry and other heath species, especially the genera [Gaylussacia and [Vaccinium].
> 
> > Woody plants of the ground cover layer include American wintergreen and partridge berry. Common wildflowers include star flower, bluebead Lilly, foam flower, bunchberry, twinflower, dewdrops, wild sarsaparilla, and Canada mayflower. [Trilliums], and yellow lady slippers (genus Cypripedium) are also common showy wildflowers. The herbaceous layer also includes many mosses, lichens, and ferns. Bracken fern is often particularly abundant in these communities.

yes, for now it is. Due to making it easier to implement for now, and later we can think about introducing other trees.

**Review by scarf005 — COMMENTED** [review]
this is a giant changes to balance, i'd like to wait a few days to gather more opinion.

**Comment by NerdPunkFu** [comment]
I like it. The amount of fruit trees in forests is way too high. Maybe also add an mechanic where as time passes fewer healthy trees will spawn in newly explored forests? Also, I'd personally like to see the grove specials be made rarer.

**Review by chaosvolt — APPROVED** [review]

**Comment by chaosvolt** [comment]
Personally I'm fine with this idea, didn't make usable trees completely impossible. That said, two minor things I'd add:
1. We have more dead tree variants besides dead oak trees. We can probably make increased use of dead pine trees and dead hickory instead of relying on cottonwood as our main filler.
2. We may or may not want to follow up on groves and shrubberies depending on how valuable they become as a food resource after this.

**Comment by Lamandus** [comment]
> Personally I'm fine with this idea, didn't make usable trees completely impossible. That said, two minor things I'd add:
> 
>     1. We have more dead tree variants besides dead oak trees. We can probably make increased use of dead pine trees and dead hickory instead of relying on cottonwood as our main filler.
> 
>     2. We may or may not want to follow up on groves and shrubberies depending on how valuable they become as a food resource after this.

it already has a significant higher amount of dead trees than before, so the ratio should be okey?

**Comment by AlecWhite** [comment]
Before nerfing, I would first measure the amount of total foraged calories per season and compare it with previous number of calories and with the calories found in a grocery store and random houses, before nerfing foraging, because it is almost mandatory with people that doesn't use default season length and have a static base, and thus can't readily switch to farming to cover their calories needs.

Also this PR will make it so that (besides grocery stores and house food loot) shrubberies patchs and groves become a very needed source of calories for early game, as CV points out.

All this reminds me that I wanted to make a discussion about how we as Bright Nights want to tackle the food challenge, without DDA legacy balancing.
Do we want "realistic" balancing? Do we want a more gameyfied balancing?

Anyway I think this issue, and the last ones I point out will be in need of lots of testing to find the right balance.

**Comment by Lamandus** [comment]
grafik
@chaosvolt

**Comment by chaosvolt** [comment]
> it already has a significant higher amount of dead trees than before, so the ratio should be okey?

I mainly mean use dead trees, dead pine trees, and dead hickory trees more instead of using more cottonwood trees, it'll look less odd. You bumped the weights of cottonwood trees up to 256 and it shows in that screenshot.

**Comment by Lamandus** [comment]
> cottonwood

I can, yeah, but we don't have a "default tree" anymore. Since someone in DDA thought, it would be neat to put all acorns in there. So that's why I went with the tree without drops, cottonwood. I had another tree made before (tulip tree) it can use oak tree sprite, but that's not the right way to do it.


Do you know any other tree without drops, that I can use as well? too many dead trees are .... too dead.

**Comment by Lamandus** [comment]
ah the elm tree

**Comment by Lamandus** [comment]
grafik
Elm!

**Comment by Lamandus** [comment]
> Before nerfing, I would first measure the amount of total foraged calories per season and compare it with previous number of calories and with the calories found in a grocery store and random houses, before nerfing foraging, because it is almost mandatory with people that doesn't use default season length and have a static base, and thus can't readily switch to farming to cover their calories needs.
> 
> Also this PR will make it so that (besides grocery stores and house food loot) shrubberies patchs and groves become a very needed source of calories for early game, as CV points out.
> 
> All this reminds me that I wanted to make a discussion about how we as Bright Nights want to tackle the food challenge, without DDA legacy balancing. Do we want "realistic" balancing? Do we want a more gameyfied balancing?
> 
> Anyway I think this issue, and the last ones I point out will be in need of lots of testing to find the right balance.

The amount of food per forest tile gets significantly lowered. You will be able to survive off of forests even with 91 day seasons, with a small - medium sized forest. Groceries offer now a bigger risk <-> benefit ratio for food. But as I said, I played with this settings on a 91 day year and I was able to live off a forest. But: hunting and farming would help, fishing also.

**Comment by Ali-Anomma** [comment]
> I like it. The amount of fruit trees in forests is way too high. Maybe also add an mechanic where as time passes fewer healthy trees will spawn in newly explored forests? Also, I'd personally like to see the grove specials be made rarer.

or we can slowly turn them in their harvested variants over time: healthy but has no fruit

**Comment by scarf005** [comment]
https://gall.dcinside.com/board/view/?id=rlike&no=457095

image

There are also opposing views in korean forum (33% out of 15 votes are against the change).

**Comment by chaosvolt** [comment]
That's also a 2:1 majority in favor though, hmm.

**Comment by Lamandus** [comment]
> That's also a 2:1 majority in favor though, hmm.

I checked it out, myself, now there are 22 votes with the same 2:1 distribution. 66% are for the change.

**Review by scarf005 — APPROVED** [review]
it's `experimental` after all. let's see how it works out and revert if it's not successful.

**Pull request merged**
