### PR TITLE
feat(comestible): more omelette variants

### PR DESCRIPTION
**Pull request by AlecWhite**
#### Summary

SUMMARY: [Content] "Add Omelettes"
#### Purpose of change

Added some basic omelettes and its recipes to help the QoL of homesteaders that grow and depend on their own crops and chickens, by adding omelettes of various kinds. Thus reducing the need to cook two different foodstuff and eat them separately saving keypresses and in-game time.

#### Describe the solution

So that homesteaders don't have to cook scrambled eggs and a vegetable/mushroom and eat them separately, I added omelettes recipes that combines the two foodstuff into one.
The vegetables picked are some of the most common ones to grow and forage, more can be added later if wished.

#### Describe alternatives you've considered

None.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
PR has failed tests.
You need to increase `calories` output your your recepies. It seems new recipes give not enough calories based on components.
изображение

**Comment by Firestorm01X2** [comment]
From https://github.com/cataclysmbnteam/Cataclysm-BN/blob/033901af4b52ad0bfcfd6abfe06bca4e403d44b1/tests/comestible_test.cpp#L110C9-L110C9

`  // Are these tests failing? Here's how to fix that:
    // If the average is over the upper bound, you need to increase the calories for the item
    // that is causing the test to fail (or decrease the total calories of the ingredients)
    // If the average is under the lower bound, you need to decrease the calories for the item
    // that is causing the test to fail (or increase the total calories of the ingredients)
    // If it doesn't make sense for your component and resultant calories to match, you probably
    // want to add the NUTRIENT_OVERRIDE flag to the resultant item.`

Tests still failing. Try more calories

**Comment by Firestorm01X2** [comment]
Tip indicates that you actually need to decrease calories. My bad.
Still- you've used override flag. If it make sense to keep current level of calories- I'll merge it.

**Review by Firestorm01X2 — APPROVED** [review]
Ready

**Comment by Unrepentant-Atheist** [comment]
Where [Omelette du Fromage ](https://www.youtube.com/watch?v=2kArCRjT29w)?

**Comment by scarf005** [comment]
this could only mean one thing... _opening a PR!_ @Unrepentant-Atheist

**Pull request merged**
