### PR TITLE
[DinoMod] DinoLab

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary

SUMMARY: Mods "Adds DinoLab"

#### Purpose of change

Special location for DinoMod content

#### Describe the solution

Starting from 4x4_microlab_surface as a template, customizing with DinoMod content. Simple substitution done, created new monster spawn list, put this in the DinoLab mission instead of the generic microlab.

#### Describe alternatives you've considered

Wait for someone else with more map skills to do this

#### Testing

Game loads, no errors, looks right.
Screen Shot 2021-07-02 at 6 55 44 PM

#### Additional context

"Where I'm From, The Birds Sing A Pretty Song.... And There's Always Music In The Air..." -The Man from Another Place, Twin Peaks

### CODE REVIEW

**Comment by LyleSY** [comment]
At this point it appears to work perfectly and is almost entirely generic. Future modders and people who want to make specialized versions of the generic 4x4 surface microlab, this is a pretty good template to work off of

**Comment by Coolthulhu** [comment]
Sounds good.
If you think it's ready for review, I think you can mark it as such. It looks like a draft at the moment.

**Comment by LyleSY** [comment]
Yes, I still need to customize it with more DinoMod content, just wanted to timestamp it for others

**Comment by LyleSY** [comment]
Finally figured out how wrecked the mapgen was. Mapgen can be broken in more ways than I understood, just a magical journey of discovery

**Pull request merged**
