### PR TITLE
Prevent crash when `lastworld.json` is corrupted or empty.

### PR DESCRIPTION
**Pull request by KheirFerrum**
#### Summary

SUMMARY: Bugfixes "Prevent crash when `lastworld.json` is corrupted or empty."

#### Purpose of change

Had an issue today where someone's computer didn't end the game appropriately, corrupting `lastworld.json`, this caused a crash that would consistently prevent the game from starting with no warning except crash log messages.

#### Describe the solution

Use try and catch to catch exceptions and report them when they occur loading `lastworld.json`

#### Testing

Need others to test for me, my computer is down. This should be tested via creating `lastworld.json` in the config folder. Either leave it empty or in various states of incomplete/wrong format.

### CODE REVIEW

**Review by scarf005 — CHANGES_REQUESTED** [review]
## moderately corrupt JSON

```json
{
  "world_name": Very-Empty",
  "foo": [1,,2,3]
  "character_name": "Maribel Hearn"
}  
```
image

## array in `lastworld.json`:

```json
[]
```

image

## empty `lastworld.json`:

```json
```

image

## corrupt `options.json` for comparison:

```json
[adfs
  { "info": "If enabled, when your character dies, the player is given a prompt that gives the option to cancel savefile deletion and other death effects, returning to the main menu without saving instead.", "default": "Default: False", "name": "PROMPT_ON_CHARACTER_DEATH", "value": "true" },
(continues below)
```

image

---
the changes doesn't seem to work, could you have a look?

**Comment by KheirFerrum** [comment]
Dammit, will make draft, can't really do much with a notepad, so will have to wait until I get my computer back. Weird that `test_object()` isn't working at all.

**Comment by olanti-p** [comment]
`test_object` only checks if an object is about to start (i.e. next character is `{`), it doesn't validate it or even check if there's a matching `}`.

According to the debugger, in some cases the game crashes because `get_object()` throws an exception when it tries and fails to parse the object, but that exception isn't caught by anything.

Other cases were caused by missing check in Lua backtrace code, that should be fixed by #3187

**Comment by KheirFerrum** [comment]
> `test_object` only checks if an object is about to start (i.e. next character is `{`), it doesn't validate it or even check if there's a matching `}`.
> 
> According to the debugger, in some cases the game crashes because `get_object()` throws an exception when it tries and fails to parse the object, but that exception isn't caught by anything.
> 
> Other cases were caused by missing check in Lua backtrace code, that should be fixed by #3187

Then is there no way to prevent this from crashing? Or just deleting the file and restarting when it would otherwise crash?

**Review by scarf005 — COMMENTED** [review]
```
 DEBUG    : Json error: config/lastworld.json:2:23: missing comma

{
  "world_name": "Test"
                      ^
  "character_name": "Maribel Hearn"
}


 FUNCTION : void worldfactory::load_last_world_info()
 FILE     : /home/scarf/repo/cata/Cataclysm/src/worldfactory.cpp
 LINE     : 609
 VERSION  : BN 440e1342128
```

LGTM

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
