### PR TITLE
feat(balance): add support for clothing mods being modified by item volume, convert pocket mod to use that instead of thickness

### PR DESCRIPTION
**Pull request by chaosvolt**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

Lil thing I had in mind as an immediate follow-up to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5671, since coverage alone doesn't seem like an ideal control for adding pockets to clothes.

## Describe the solution

C++ changes:
1. In clothing_mod.cpp, updated `clothing_mod::load` to support `volume` as a valid modifier for clothing mod effects.
2. Also in clothing_mod.cpp, updated `clothing_mod::get_mod_val` so that volume modifiers work like thickness, except it bases it on the item's base volume in liters (should be rounded down if my understanding of the `int` definition is correct) instead of material thickness.
3. Added definition and default value of `volume_propotion` to definitions in clothing_mod.h.

JSON changes:
1. Nerfed the amount of storage `value` for the new pocket clothing mod from 3 to 1 (.75 liters to .25 liters), and changed it to use volume instead of thickness.
2. Per feedback, set encumbrance penalty to scale with volume and coverage, reduced baseline value from 2 to 1 now that it scales instead of being fixed.

Documentation changes:
1. Documented all three clothing mod modifiers in json_info.md, now with actual explainations of what each does.

## Describe alternatives you've considered

Making it base off weight instead, or adding support for clothing mods being proportioned by weight and just not using it yet.

## Testing

1. Checked affected JSON file for syntax and lint errors.
3. Compiled and load-tested.
4. Got the storage changes of several armor items before and after changing the clothing mod, found the results felt more consistent in my opinion. Lil survivor helms don't gain more storage than a full-on suit just because it's thicker, for example.
5. Confirmed that loading a tac vest with the bulkiest mags possible doesn't change how much storage it'd gain, only gaining .25 liters even after 4 thompson drum mags bumps its effective volume from 1.25 liters to 6.25 liters.
6. Checked affected C++ files for astyle.

Some examples:

Item | Vol gain, before | Vol gain, after
--- | --- | ---
MBR vest (ceramic) | +5.75 L | +1.5 L
Swat armor | +2.75 L | +3.25 L
Heavy survivor suit | +1.5 L | +3 L
Heavy survivor helmet |+2.25 L | +0.5 L

## Additional context

I just noticed while writing the PR text that `thickness_propotion `, `coverage_propotion ` and the like in the code misspells "proportion" derp.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Encumbrance and the bonus should scale with same things, otherwise it will be hard to balance it, because you'd need to check all items for outliers.

**Review by RoyalFox2140 — DISMISSED** [review]
Seems trivial enough. I'd like weight later but I don't specifically know how we'd use that.

**Comment by chaosvolt** [comment]
> Encumbrance and the bonus should scale with same things, otherwise it will be hard to balance it, because you'd need to check all items for outliers.

Fair enough, I toned the baseline encumbrance from 2 down to 1 and made it scale with relevant value as well as coverage, like all other encumbrance penalties tend to do.

**Review by RoyalFox2140 — APPROVED** [review]

**Comment by Cormac1991** [comment]
BN has pockets now? thats,,,, hilarious.

**Pull request merged**
