### PR TITLE
[WIP][Do not merge yet] Refactor

### PR DESCRIPTION
**Pull request by iillyyaa2033**
Trying to bring some order to source files.

Opening this PR with hope of getting some advice from those who are more experienced in CDDA/CBN developement.

## Now

Only CMake build system on Linux works properly. I'm not going to fix other build systems neither support other operating systems until everything is done properly.

Structure:
- `world`: game data and game mechanics -- code that holds game world and updates it;
- `display`: everything related to user interaction -- UI, user input, sounds;
- `utils`: utilitary functions;
- `/`: unordered yet.

## Future
- [ ] split `world` into game model and game mechanics;
- [ ] introduce `launcher` folder that handles game startup;
- [ ] reduce dependency interconnections quantity between subfolders;
    - [ ] move all translation stuff to `display`;
- [ ] completely split game world and UI;
- [ ] split `display` to `tiles` and `curses` and get rid of `-DTILES=ON`;
- [ ] compile subfolders as standalone dynamic libraries;

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
You understand this makes porting things between forks harder?

**Comment by Coolthulhu** [comment]
It sounds like it would do more harm than good.
Orderly code is good, but fork compatibility is better. Especially since many of the changes to DDA right now are optimizations.

**Comment by Firestorm01X2** [comment]
I guess it can be added as future task in planning.

**Comment by iillyyaa2033** [comment]
Understood.

**Pull request closed without merging**
