### PR TITLE
Remove useless items

### PR DESCRIPTION
**Pull request by Coolthulhu**
Obsoletes a bunch of items that served almost entirely as padding/flavor:
* Spork
* Foon
* Fork
* Spoon
* Plastic fork
* Plastic spoon
* Plastic straw
* Steel colander
* Splatter guard
* Ladle
* Spatula
* Whisk
* Rolling pin
* Can opener
* Peeler
* Garlic press
* Potato masher
* Carving fork
* Corkscrew
* Bottle opener
* Chopsticks
* Butter knife
* Plastic plate
* Glass plate
* Golf tee
* Golf ball
* Scorecard
* Salt lick
* Stopcock
* Puck
* Football
* Baseball
* Volleyball
* Bowling ball
* Mess tray

They are purged from item groups and so will only spawn if mods add them back.

Also adds some deconstruction recipes:
* Obsolete plastic items deconstruct into "plastic scrap" that can be used for plastic chunk recipe
* Disposable cells deconstruct into scrap (same amount as used to construct them in the recipe)
* Bathroom scale gives scrap and springs

If the deletion is too controversial, I could add the deconstruction recipes alone and a mod that just blacklists the useless items.

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
It's up to you, of course, but salt lick at the dairy farm is a important part of easter egg location, and despite it's essentially useless, it adds to the atmosphere of the location.

**Comment by Coolthulhu** [comment]
> easter egg location

I'll check.
I might replace it with table salt or rock salt if it's noticeably atmospheric.

**Comment by Night-Pryanik** [comment]
The thing is that salt lick block was used to smash man's head due to its weight.
rsz_larrydead

I doubt that rock salt or table salt would be a good substitute.

**Comment by Coolthulhu** [comment]
> I doubt that rock salt or table salt would be a good substitute.

Alright, I kept the reference. I fixed the problem of it being useless by allowing it to be uncrafted into 10 rock salts.
Having effectively infinite rock salts isn't unbalancing because they take as much time to process as salt water, which is infinite.

**Comment by dissociativity** [comment]
I actually find footballs and such a great source of clean leather

**Comment by Coolthulhu** [comment]
Clean leather is useful, but footballs weren't common enough to be a bulk source. Leather will be a bit less available, but there are still boots and leather pants in closets.

**Pull request merged**
