### PR TITLE
fix: No Hope megastore

### PR DESCRIPTION
**Pull request by 0Monet**
## Purpose of change
According to Vollch #3854 breaks a test in #3869 because "(" is not in the megastore palette in the No Hope mod.
## Describe the solution
Make the same modifications in #3854 on the No Hope megastore.
## Describe alternatives you've considered
None.

### CODE REVIEW

**Comment by chaosvolt** [comment]
What the fuck why isn't the "review changes" button working now.

**Review by scarf005 — APPROVED** [review]

**Comment by Vollch** [comment]
Welp. now there's "[" with no definition in palette: https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/7160740935/job/19495434235?pr=3869

**Comment by 0Monet** [comment]
Weird... in the palette "[" is defined as:
"[": "f_glass_freezer"

**Comment by Vollch** [comment]
It's not defined in no hope palette.

**Comment by scarf005** [comment]
i think it'd be safe to ignore `no_hope` for all mods test

**Pull request merged**
