### PR TITLE
sleeping bag now require 60 rags

### PR DESCRIPTION
**Pull request by Lamandus**
you could produce free rags with sleeping bags, this is the fix for it.

grafik

### CODE REVIEW

**Comment by chaosvolt** [comment]
If https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2142 gets merged, this will be redundant.

**Comment by Lamandus** [comment]
> If #2142 gets merged, this will be redundant.

what happens if you try to salvage a sleeping bag with your fix in game? As in, how much does it then produce?

**Comment by chaosvolt** [comment]
> what happens if you try to salvage a sleeping bag with your fix in game? As in, how much does it then produce?

Looks like expected yield should be 20 rags for unrolled version, 12 or 13 for the rolled-up version.

> Also, no hate, but your PR sits there for 3 months already.

It should be ready, though I'm a bit leery of the half-assed test from the source PR.

The above highlights a big problem here: for some wacky reason both the volume AND weight differs between rolled vs unrolled sleeping bags.

**Comment by Coolthulhu** [comment]
> It should be ready, though I'm a bit leery of the half-assed test from the source PR.

It's a bit heavy, but I'll try to look into it.

**Pull request merged**
