### PR TITLE
Canned tomatoes should no longer appear half-full

### PR DESCRIPTION
**Pull request by 0Monet**
## Summary
SUMMARY: "Canned tomatoes should no longer appear half-full in their sealed containers and with the wrong amount of calories"
## Purpose of change
Canned tomatoes appear 1/2 in 250 ml cans and 12/24 in 3L glass jars.
They also have 30 caloris in game, while in the other.json, 41 caloris are marked.

## Describe the solution
Remove "stack_size": 2, replace it with "charges": 2,
Changing caloris from 41 to 55 to get 41 in the game seems to work.

## Describe alternatives you've considered
Do nothing.

## Testing
Test on my game and nothing special happens.

## Additional context
In my game (cbn-windows-tiles-x64-2023-09-27-0719):
Before:
Capture d’écran 2023-09-27 145152

After:
Capture d’écran 2023-09-27 142941

### CODE REVIEW

**Comment by chaosvolt** [comment]
Uuuugh I hate the comestible tests, those are failing due to this. They probably should be set to 30 instead if that's what they have when made in-game, or left at 41 if that was keeping it from borking previously.

**Comment by 0Monet** [comment]
So, 41?

**Comment by chaosvolt** [comment]
Hmm, test is still failing. Maybe try 30, or maybe buffing raw tomatoes so that crafted canned tomatoes will correctly match their base value would be better, not sure. For all I know that might break some other obscure comestible that uses tomatoes, bleh.

**Review by scarf005 — APPROVED** [review]
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/c8fe194e0c5a1f1735a0a353ce31eb870f978879/data/json/items/comestibles/other.json#L533-L554

Canned Tomatoes now have 2 charges,

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/5774f160ee80afd6ce2c104576a836998982b9a0/data/json/recipes/food/veggi.json#L1886-L1903

and Sealed Jar Recipe makes 4 units of canned tomatoes.

Cataclysm: Bright Nights - dc43e235355_01

this caused 2 * 4 = 8 charges of canned tomatoes to be made.

Cataclysm : fish_01

reducing it to 2  made the tests pass.

**Comment by 0Monet** [comment]
@scarf005 thanks

**Pull request merged**
