### PR TITLE
add lua testing github actions configurations

### PR DESCRIPTION
**Pull request by ChainsawGarden**
#### Summary

SUMMARY: Infrastructure "Initiate the re-integration of Delta Fork's lua system to Bright Nights."

#### Purpose of change

To ultimately bring back Lua. Cataclysm's current JSON subsystem is great, however, Lua could do more, much easier. Both could be used in tandem with each other, though Lua allows for much versatile programming that JSON.

#### Describe the solution

This PR starts the re-integration of Lua into Bright Nights.

#### Describe alternatives you've considered

1. Continue using JSON
2. Keeping Lua on Delta Fork /s

#### Testing

None.

#### Additional context

N/A

### CODE REVIEW

**Comment by Coolthulhu** [comment]
There's nothing to test here right now.
I'll merge it when a branch using it is added.

**Comment by Zireael07** [comment]
I wonder how much use Lua is going to get. CDDA axed it because tbh there was only one mod using it.

**Comment by Coolthulhu** [comment]
I'm keeping this open because it doesn't seem to do anything until at least one Lua PR is opened. Is it needed for the work to start or more like "just in case"?

**Comment by ChainsawGarden** [comment]
> I'm keeping this open because it doesn't seem to do anything until at least one Lua PR is opened. Is it needed for the work to start or more like "just in case"?

This was made out of a misunderstanding of how pulls work (I thought you could push every commit you make). I'm still deep into fixing up my Lua commits, feel free to close this if you need to. I'll push the finished product once it's complete.

**Comment by scarf005** [comment]
you can push every commit you make. for example:
image

however, if this PR is still work in progress, you might want to convert to draft
image

**Comment by olanti-p** [comment]
Closing as stale.
Needs conflict resolution, plus nothing to test for now.

**Pull request closed without merging**
