### PR TITLE
Fix roofs appearing when you load

### LINKED ISSUE #1197: Built walls don't receive roofs until save+load
# Describe the bug

Built walls have no roof over them after construction, until save+load, when they receive the roofs set in their terrain type.

# Steps To Reproduce

1. Build/spawn log wall
2. Teleport over it
3. Fall
4. Save+load
5. Teleport over wall again
6. Don't fall

# Expected behavior

Fall never happens.

# Screenshots

# Versions and configuration

# Additional context

### PR DESCRIPTION
**Pull request by joveeater**
#### Summary

SUMMARY: Bugfixes "Add roofs on mapgen and map editing and fix megastore roof"

#### Purpose of change

Fixes #1197 #1810 #1136. Three changes. The map editor now creates roofs along with any terrain it creates. Map shifts now call add_roofs on newly generated submaps and the megastore's json has been fixed after what seems to be a palette mixup when the roof was added. 

#### Describe the solution

To avoid calling add_roof when it's not necessary loadn now returns a bool indicating if the map was generated or loaded and only maps that are generated have roofs added, though the roofs are added for every z level at that location.

The megastore json had " " defined to open air in the palette but then the roof maps seemed to assume it was unbound and would use the fill terrain. Space has been replaced with @ in the palette and the non-roof maps now use it instead. 

#### Testing

It was mentioned in one of the issues that the bug could be triggered via construction. I couldn't reproduce this by building a log wall. It had floor above as expected.

#### Additional context

It's a little annoying that we can't add roofs during the mapgen, but it's important that we finish the shift before starting to add them. It makes it a bit harder to be sure it's always being done, but with it reaching across z levels it's somewhat unavoidable.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
`Json error: data/mods/dda/../../json/mapgen/megastore.json:1894:36: format: rows: row 6 column 24: '@' has no terrain, furniture, or other definition`

**Comment by joveeater** [comment]
Yeah this is a weird one. It's like it's seen the changes to the maps but not the palette even though they're in the same file. This is the first time I've changed the json, is there some step of the process I've missed? Other than that I can't think what's wrong. The only thing I could think was some weird character encoding thing messing with "@" but it's used in other templates. I'll change it to "*" just to see what happens.

**Comment by Coolthulhu** [comment]
Still doesn't recognize it.
Do the tests pass locally?

**Comment by joveeater** [comment]
Yeah it works locally, even with the locale set to C.UTF-8. I honestly have no idea here. Have you even seen anything like this before or am I just cursed?

**Comment by joveeater** [comment]
Good catch! I'm not really sure why no hope is overwriting it at all. It doesn't seem meaningfully different but I've changed the palette there as well.

**Comment by Coolthulhu** [comment]
> Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1197 https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1810 https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1136

Looks like github only "caught" the first issue. That is, only the first got auto-closed when the PR was merged.
It's probably safer to add a separate line like "Fixes #num" per issue.

**Pull request merged**
