### PR TITLE
feat(balance): better ammo distribution in ammo vending machines

### PR DESCRIPTION
**Pull request by Lamandus**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
The amount of ammo you could get from a shooting range vending machine was far too much. This scales it down.

## Describe the solution
Using Binomial Distribution, a better calculation of drops per vending machine is achieved.

Pistol Ammo:
{E4AE0CC2-AA10-4507-8BF1-69295EE9078A}
0 and 8: 0,39%
1 and 7: 3,13%
2 and 6: 10,97%
3 and 5: 21,88%
6: 27,34%

Rifle and Shotgun Ammo:
{4DA23709-308C-4B3E-9E6F-CA66BC16E65F}
0: 16,81%
1: 36,01%
2: 30,87%
3: 13,23%
4: 2,83%
5: 0,24%

## Testing
Loads up as expected

### CODE REVIEW

**Comment by RoyalFox2140** [comment]
Why must we do this the very next day? https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5308

**Comment by Lamandus** [comment]
this is the fix for the vending machines I culled with. It has nothing to do with the addition of said machines. It is only a fix for their extreme high spawn...

**Comment by Coolthulhu** [comment]
This whole ammo vending machine thing resulted in a pretty heated discussion on discord, up to people requesting bans. Can we resolve it more peacefully? Ideally on discord, to avoid personal stuff on github, but github issues are still a possible last resort. Or github discussions - most people forget those exist.

From what I can tell, there's a disagreement on the role of vending machines: should they have all of the ammo or just some, should they be in all shops or just some (or none?).
We need to agree on those issues, at least agree enough to pick one option. If arguments aren't convincing the other side, we could vote. I don't see either side as being obviously right or wrong, so I'd rather not overrule.

Possible compromise: keep common ammo on shelves, lock away good stuff (rifle ammo).

As for this PR itself, it seems to address one issue (high variability), so it seems to be an improvement.

**Comment by Lamandus** [comment]
@Coolthulhu 
{F7736BA4-CE89-4E4D-882B-EE67ABC9FC1E}
I would, but i seems that I can't come back.

**Comment by RoyalFox2140** [comment]
>  I would, but i seems that I can't come back.

It's fixed.

**Comment by Lamandus** [comment]
I am in, Timeout is still in place.

**Comment by RoyalFox2140** [comment]
> I am in, Timeout is still in place.

Discord sucks, why do they allow both to be applied at the same time and only remove one after?

**Comment by Lamandus** [comment]
> > I am in, Timeout is still in place.
> 
> Discord sucks, why do they allow both to be applied at the same time and only remove one after?

so, you doubled down on me 😛

**Review by chaosvolt — DISMISSED** [review]
Okay so being made to look into this has made me absolutely hate the fact that the rare ammo itemgroups are used to spawn hot loads and other oddball chamberings of common ammotypes, which is completely the opposite of how the rare gun itemgroups are used.

But that is a whole-ass rabbithole that I do not want to deal with because it's going to play merry hell with a lot of ammo spawns if I ever try and fix that, and is moreover out of scope for this PR.

**Review by RoyalFox2140 — APPROVED** [review]
The item groups for ammo need to be fixed in a followup PR by Chaos at some point. Things like ratshot being in both rifle common and pistol common isn't really good.

**Comment by RoyalFox2140** [comment]
@Lamandus Since I merged your other PR there's a merge conflict.

**Review by chaosvolt — APPROVED** [review]

**Pull request merged**
