### PR TITLE
[DDA Port] Show number of monsters in sidebar compass

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
SUMMARY: Interface "[DDA Port] Show number of monsters in sidebar compass"

#### Purpose of change
One of the popular port requests, show # of monsters in the compass above the minimap.

#### Describe the solution
Cherry-pick https://github.com/CleverRaven/Cataclysm-DDA/pull/49737

#### Testing
image

#### Additional context
Surprisingly, it had no conflicts.

### CODE REVIEW

**Comment by RelMayers** [comment]
How this would affect like 120x30 compass behaviour?

**Comment by olanti-p** [comment]
What do you mean by that, @RelMayers? We don't have extensive sidebar customization from newer DDA versions, the widest it ever gets is 44 symbols.

**Comment by RelMayers** [comment]
i meant window size 120x30

**Comment by RelMayers** [comment]
> The only change this PR introduces is that each monster will have a number appended before its name. It will make each "symbol: meaning" pair take a couple more cells for the number, but that's expected.
> 
> I don't see any particular special behavior for when the window size is 120x30 image Before the change, for comparison: image It works same on 192x49 window size.

There seems to be using more space, but seems like there isn't any meaningful change due to already reserved space for it. Thank you for checking my concern I'm glad for it.

**Pull request merged**
