### PR TITLE
Change ammo belt link recipes

### PR DESCRIPTION
**Pull request by James792**
#### Summary

SUMMARY: Balance "Changes the amount of materials consumed to be more realistic while still keeping balance in mind."

#### Purpose of change
This makes it so that it takes less steel to manufacture ammo belt linkage. I noticed that manufacturing linkage would take
1 sheet metal/24 small metal sheets worth 13.23 pounds total to make 10 linkage worth 0.04 pounds of steel total, that is a loss of 13.19 pounds of steel.

#### Describe the solution
I made it so that it now gives a byproduct of 100 scrap metal worth 11.02 pounds of steel resulting in the loss of 2.17 pounds
a far more reasonable number while still keeping the balance,
only exception is 40mm grenade linkage which gives a byproduct of 180 scrap metal resulting in the loss of 6.4 pounds.

#### Describe alternatives you've considered
Another alternative would be to increase the weight of linkage or decrease the amount of sheets required and increase the charges made.

There is most likely other solutions.

#### Testing
Tested on latest experimental, should work.

#### Additional context
screenshotnewnew

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Links are very gun-specific, so having to craft a lot of them before you can do anything is restrictive. Those 10 charges and low time helped to make it easier to access.

If disappearing material is a problem for you, it would be better to produce scrap/chunks as a byproduct, but still keep the old material.

**Comment by James792** [comment]
ok

**Comment by KheirFerrum** [comment]
I'd personally suggest tweaking down the sheet metal requirements alongside adding byproducts, the scrap metal produced probably shouldn't exceed double the weight of the linkages, as that's _very_ inefficient as a process.

**Comment by Coolthulhu** [comment]
> the scrap metal produced probably shouldn't exceed double the weight of the linkages, as that's very inefficient as a process

It's OK for a process to be resource-inefficient when the resource is relatively common.
Belt linkages are reusable so you won't need to repeat the craft often. Early availability of linkages is more important than being able to mass-craft tons of them.

**Comment by KheirFerrum** [comment]
> > the scrap metal produced probably shouldn't exceed double the weight of the linkages, as that's very inefficient as a process
> 
> It's OK for a process to be resource-inefficient when the resource is relatively common. Belt linkages are reusable so you won't need to repeat the craft often. Early availability of linkages is more important than being able to mass-craft tons of them.

I don't like it because it forces using excessive materials for no reason, and downgrades what are decently common to somewhat rare materials into what is essentially ubiquitous or worthless. It encourages unintuitive crafting. You could argue that it represents an inexperienced person messing up and destroying the material, but that's badly represented by this, I'd sooner have a failure system ala DDA than arbitrarily force players to collect and waste more material than necessary.

**Pull request merged**
