### PR TITLE
Implement use of E_NO_POWER_DECAY on top-tier engines/motors

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Balance "Apply new E_NO_POWER_DECAY to gas turbines, enhanced/super motors"

#### Purpose of change

This implements the actual suggestion mused upon in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2721, so I can figure out which vanilla parts (if any) warrant being stackable with no power loss as a separate thing. Depends on that PR obviously.

Basic rationale as noted in the prerequisite PR:

> Kheir brought up a point: gameplay-wise and ignoring realism, the main benefit of the diminishing returns is to nudge the player to seek out better engines to upgrade a deathmobile instead of brute-forcing it with a million chainsaw engines or what-have-you. Based on this, the best candidates for this flag will probably by the top-tier, most powerful engines where there aren't really any options to upgrade any further. These will already have difficulties due to being power-hungry to begin with and weight will make it hard to stack them anyway, but at that point it might be reasonable to reward a player who's undertaken the commitment to make basically Ekarus' R-MCC and has run out of options for engine upgrades.

#### Describe the solution

Added the `E_NO_POWER_DECAY` flag to the following parts:
1. `gas_turbine_engine`, meaning the 1350 hp gas turbine engine, 1900 hp gas turbine engine, and 6000 hp gas turbine engine inherit the flag. Even the smallest variant is stated to have high fuel consumption, and has a `power` value in excess of a million.
2. Enhanced electric motor and super electric motor. These doesn't have as much raw power as the turbines, a good bit shy of 300k and 400k respectively (about V8 and V12 tier), but the idea here was these are the rare top-tier variants for electric power specifically, and are assumed to be the most optimized and beefy electric engines (with turbines in general being the most optimized and beefy combustion engines). This would accomplish a similiar effect of rewarding players for hunting down the top tier options in a particular engine category, turbines being combustion's top tier and the rare megamotors being the top-tier electric options.

Per feedback, also added mentions of this feature in the item and vehiclepart descriptions for the affected engines.

#### Describe alternatives you've considered

1. Adding big-ass steam turbine engines, ideally something craftable since the only craftable one currently is worse than all other combustion engines except scooter and motorcycle engines, so becoming a Captain Planet villain still allows access to an engine powerful enough to count as top-tier.
2. Adding some kinda sci-fi engine that justifies the flag in vanilla on its own. Presumably an adaptation of the minireactor into an engine instead of reactor would be the best candidate.
4. Deciding upon aset minimum level of power above with most engines will be granted the flag.

#### Testing

Checked affected files for syntax and lint errors.

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]
it'd be nice to have an extra item description code for `E_NO_POWER_DECAY` later like
`this engine is <green>powerful</green> and its power will not diminish even when multiple of them are installed.`

**Comment by chaosvolt** [comment]
Ah, could work it into either the item description, vehiclepart description, or both?

**Comment by scarf005** [comment]
yeah both would be good. tho it could be another PR.

**Comment by chaosvolt** [comment]
Just write it into the description or hardcode it in based off it having the flag?

**Comment by scarf005** [comment]
description would be better since it's more generic. tho hardcode is faster, so i say it's up to your choice.

**Comment by chaosvolt** [comment]
Sure, will in a sec then since easy enough to add. Gonna also test to see if color tag works in description here or not.

**Comment by chaosvolt** [comment]
Oh right yeah, I need to update the vehicle test still since looks like atomic sports cars have two engines.

**Pull request merged**
