### PR TITLE
Spring foraging

### PR DESCRIPTION
**Pull request by yay855**
#### Summary

SUMMARY: Content "Made blueberries, strawberries, and cherries harvestable in the spring instead of summer" 

#### Purpose of change

Because those fruits ripen in the (late) spring and springtime needs more easily accessible foraging.
Springtime is often not very good for foraging, especially early on, where you have low skill. Therefore, changing some of the foraged berries and fruits to be harvested in the spring makes surviving early on easier.

#### Describe the solution

Literally one word changed, from summer to spring, across three entries in the terrain-flora.json file.

#### Describe alternatives you've considered

There is also the option to add in new foraged items for the spring, which I wouldn't be against, but this seemed like a simple solution, and furthermore there really aren't very many springtime foraging plants you can find in the US that can be eaten straight.

#### Testing

There are no errors that I can find, though we'd have to change the tileset to account for the change in harvest time, which I'm not sure how to do. I would appreciate help.

### CODE REVIEW

**Review by scarf005 — CHANGES_REQUESTED** [review]
could you fill in PR body?

**Comment by yay855** [comment]
> could you fill in PR body?

I don't know what that means.

**Review by scarf005 — CHANGES_REQUESTED** [review]
| spring | summer |
|--------|--------|
| ![spring][spring] | ![summer][summer] |

while i agree this change is good for balance, it might be misleading to keep the tileset as-is. could you swap the tiles so the spring tiles use the one with the berries?

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/1670ee6adfcee0e4d91b6d3c01c6f07db625c408/gfx/MSX%2B%2BUnDeadPeopleEdition/tile_config.json#L34696-L34704

#2853 might help. also cc @chaosvolt 

[spring]: https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/acb04d91-f9c8-4c9a-a9c2-0865a54a6412
[summer]: https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/d8655dca-6160-4e1b-bde5-9f4b63e93476

**Comment by chaosvolt** [comment]
Okay, was able to figure out how to add it for blueberry and strawberry berries. Cherry tree may be a lil more complicated, will do in a sec.

**Comment by chaosvolt** [comment]
| spring | summer |
|--------|--------|
| image | image |

Much better.

**Comment by chaosvolt** [comment]
Per Scarf and Royal's advice on the BN discord, made the spring sprite a lt greener and added pink to the flowers to be more visible, leading to having to define a separate harvested sprite too.

**Comment by scarf005** [comment]
sorry, i should've said it more clear, i meant making spring sprite pink like above picture.

**Review by scarf005 — APPROVED** [review]
image
image

now that's what i'd call a cherry blossom!

**Pull request merged**
