### PR TITLE
Merge contents of MRE packs

### PR DESCRIPTION
**Pull request by Relgar**
#### Summary
SUMMARY: [Category] "[Merge contents of MRE packs]"

#### Purpose of change
MREs have always been annoying to open - they contain multiple packs within packs. True to reality, perhaps, but a massive pain to manage - 20 MREs would need you to apply or disassemble 60 times to gain access to all the contents. This PR combines all the contents of the Accessory and Dessert packs and removes them from the recipes. There are no existing places that spawn those packs on their own as well. I believe there were also comments in Discord about how the presence of MRE packs slowed down loading in general as well.

#### Describe the solution
Add contents of accessory and dessert packs to MREs.
Remove references to both those packs.

#### Describe alternatives you've considered
Creating a single MRE comestible, but this will leave out the things like water purification tablets and matches that may be of use to players. There will need to be further thoughts on how to provide these items without increasing the tedium.

#### Testing
Tested on new blank world, spawned in with no issues.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Good change.
Two things: one problem (easy fix, but has to be done), one suggestion (would be really good, but it's not 100% necessary):

When deleting an item, you should obsolete it or migrate it to some other item, so that saves with this item don't break.
Obsoletion is when you move the item definition to `data/json/obsoletion/items.json` instead of deleting it completely.
Migration is when you add an entry in `data/items/migration.json` for the deleted item to turn it into something new on save load.

You could make a `requirement` structure for those MREs you're inlining. See `data/json/requirements/cooking_components.json`, `mushroom_soup_ingredients` for an example.
You'd define contents in this requirement, then include it as a list like in `data/json/recipes/food/veggi.json`, search for `"result": "juice"`. That is, you'd have name of the `requirement` as one of the components, with a third parameter `"LIST"`, like:
```
"components": [
  [ [ "pur_tablets", 6 ] ],
  [ [ "mre_desert_requirement_id_here", 1, "LIST" ] ],
  ...
]
```
This way, if someone wanted to change the contents of desert "MRE subpack", it would be done in one place and automatically update all the others.
It would clean things up a lot.

**Comment by Relgar** [comment]
Thanks for the feedback, I'll take a look at this and update.

**Comment by Relgar** [comment]
As mentioned - I was unable to add requirements lists as it would only give the first item of the array - I've gone back to the previous arrangement with the added obsoletion.

**Comment by Relgar** [comment]
Have utilised using as advised - able to compress items now.

**Comment by Coolthulhu** [comment]
I tested it by spawning all MREs and disassembling them.
I noticed that they are nearly identical... Not the fault of this PR, of course. Just that someone didn't bother to make MREs any different when defining them.

**Pull request merged**
