### PR TITLE
Balance change to monsters carrying guns

### PR DESCRIPTION
**Pull request by RobbieNeko**
#### Summary

SUMMARY: Balance "Port over a version of the DDA itemgroups for guns being carried by monsters."

#### Purpose of change

As noticed by a member of the discord, loose ammo spawns alongside guns that also have mags can be a bit... over generous when it comes to monster drops. Plus, it doesn't make the most logical sense that they would be carrying around both mags and loose ammo with a gun. Thus, if this is merged, they will only carry mags **_or_** loose ammo. This also takes the pistols from military zombies out of the holsters, since otherwise the spawns don't work correctly. 

#### Describe the solution

1. Adds a new "everyday carry" json in the style of "nested_guns", in which the grouping has the mags **OR** the loose ammo (loose ammo for guns that don't have mags, mags for guns that do have mags).
2. Adds new itemgroups to guns.json containing the everyday carry variants
3. Swaps out the itemgroups in the obvious drop tables
4. Swaps the guns in the military.json for their everyday carry counterparts
5. Also takes pistols out of their holsters for the military zombies, since otherwise the itemgroups don't work

#### Describe alternatives you've considered

- Going for the straight up DDA itemgroups for this
The DDA version doesn't include mags or loose ammo for the carried versions, but I feel that would lead to the drops being disappointing again, particularly for the guns of rarer calibers

- Leaving it how it is
Just leaving it alone is an entirely valid option if it's believed that the loose ammo isn't actually that bad. However, following the reaction of a player in the past, and having gotten some recent personal experience with how it can play out, I felt that it was a good idea to at least present this PR as a possibility.

#### Testing

1. Loaded into the game after each stage to make sure no errors were occurring
2. Spawned in some of the relevant zombies
3. Smashed them with ol' reliable Lucerne Hammer
4. Checked to make sure that once their guns drop, they drop using the correct itemgroup

#### Additional context

image
image
image
image

BUG: Handguns for some reason are not behaving properly with the SWAT zombies, and I can't for the life of me figure out why.
image

Ferals have not been updated, as having to edit the military json file was annoying enough. It'd be a great candidate for a part two, along with any monster drop tables I missed

### CODE REVIEW

**Review by Firestorm01X2 — APPROVED** [review]
Ready

**Comment by Firestorm01X2** [comment]
Drop from military zombies seems somewhat more generous, but it may be unrelated to this PR.

**Comment by RobbieNeko** [comment]
> Drop from military zombies seems somewhat more generous, but it may be unrelated to this PR.

The drop in the image with a rifle and pistol just happened to be very lucky, nothing I changed would have made the rifle more likely to spawn. I suppose it did make for a better showcase of the drops.

**Comment by Firestorm01X2** [comment]
> The drop in the image with a rifle and pistol just happened to be very lucky, nothing I changed would have made the rifle more likely to spawn. I suppose it did make for a better showcase of the drops.

I've got this feeling during testing. But I think that is not exact. So everything is fine.
Still it would be interesting to see player feedback.

**Comment by RobbieNeko** [comment]
Oh definitely. It'll be interesting to see player feedback on this (and, to an extent, personal experience with it).

**Pull request merged**
