### PR TITLE
Remove dead obsolete mods

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
SUMMARY: Content "Removed dead obsolete mods"

#### Purpose of change
Remove dead obsolete mods that are present and maintained in Kenan's modpack or somewhere else.
This duplication has been causing various maintenance issues for modders and general confusion for the players.

##### Removed mods that are unneeded anymore
- Mapgen Demo (it's just a copy-paste from game files)
- Sleep Deprivation (it's been mainlined years ago)

##### Removed mods that are available in Kenan's modpack
Link to the modpack maintained by @Kenan2000 and community: https://github.com/Kenan2000/BrightNights-Structured-Kenan-Modpack

- Vehicle Additions Pack (aka blazemod)
- Folding Parts pack (aka DeoxyMod)
- Icecoon's Arsenal (aka EW_Pack)
- EZ-Mode Medical (aka fast_healing)
- DeadLeaves' Fictional Guns (aka FictionalWeapons)
- Garden Pots (aka Growable_pots)
- Roadheader and other mining vehicles (aka HeavyMining)
- Hydroponics
- Makeshift Items Mod
- More Locations
- Mutant NPCs
- Beta National Guard Camp
- Necromancy
- Mythological Replicas (aka NW_Pack)
- Salvaged Robots
- Bens GF recipes (aka Tolerate_This)

##### Removed mods that are available in other places
- ~~Dark Skies Above, available as Really Dark Skies maintained by @Zlorthishen here: https://github.com/Zlorthishen/Really_Dark_Skies~~ Undid the removal, since turns out it's not quite the same thing.
- More Survival Tools, available as MST_Extra maintained by @chaosvolt here: https://github.com/chaosvolt/MST_Extra_Mod
- Tanks and Other Vehicles, available as Tankmod: Revived maintained by @chaosvolt here: https://github.com/chaosvolt/cdda-tankmod-revived-mod
- Medieval and Historic Classes and Shields (aka Medieval_Stuff), available as Medieval Mod Reborn maintained by @chaosvolt here: https://github.com/chaosvolt/cdda_medieval_mod_reborn

##### Obsolete mods that have been kept
These are either required for the game, have hardcoded functionality supporting them or are not maintained anywhere else

- Crazy Cataclysm
- Fuji's More Buildings
- Larwick's Overmap (aka Graphical Overmap)
- Classes and Scenarios Mod
- Mundane Zombies
- My Sweet Cataclysm
- Classic Roguelike Classes
- All the No_* mods
- Modular Turrets
- TESTING DATA
- Urban Development
- Zombie Nightvision

#### Additional context
Check out `#mod-links` channel on our [official Discord](https://discord.gg/XW7XhXuZ89), it has many links to 3rd-party mods.

#### Testing
Should require no testing.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Medieval stuff mod also has a replacement being maintained as a third-party mod: https://github.com/chaosvolt/cdda_medieval_mod_reborn

Side note on that, one of these days I could drag MST Extra, Medieval Mod Reborn, and Tankmod: Revived over as in-repo mods should anyone request it. I might want to finish the prep work to do Arcana first though.

**Review by scarf005 — CHANGES_REQUESTED** [review]
we should probably wait until stable 0.3 for this to merge. it could be considered as breaking change to many users who does not use external mod sources.

also, players should be warned about this changes in-game before stable 0.3. for example, mods tab should link to this PR explaining why their saves may break in future, and how and where to install the 3rd party mods.

**Comment by Zlorthishen** [comment]
strictly speaking, Dark-Skies-Above and Really Dark Skies are different

**Comment by olanti-p** [comment]
> it could be considered as breaking change to many users who does not use external mod sources.

There is already a warning on obsolete mods, people using them _should_ expect them to break.

> for example, mods tab should link to this PR explaining why their saves may break in future, and how and where to install the 3rd party mods

If there is to be a warning, it needs to be a big one over the entire screen, and on game start, and preferably with countdown timer, otherwise people _will_ miss or skip it.

If we're considering this a breaking change, that I'd like to go ahead and break more things at the same time, to avoid making multiple small breakages.
First, move _all_ obsolete mods, not only the ones that are maintained elsewhere, into an external archive repository.
Second, introduce some versioning system so mods for experimental show up as incompatible with stable.

All of this, of course, after 0.3 stable rolls out and followed by the big warning on how to get old mods from new locations.

**Comment by scarf005** [comment]
that clarifies things. should i create stable 0.3 umbrealla tracking issue/milestone to keep this tracked?

**Review by scarf005 — APPROVED** [review]

**Comment by olanti-p** [comment]
> strictly speaking, Dark-Skies-Above and Really Dark Skies are different

Undid the removal of DSA for now.

> Medieval stuff mod also has a replacement being maintained as a third-party mod: 

Added to the removal list.

**Comment by Coolthulhu** [comment]
Has conflicts at the moment.

**Comment by olanti-p** [comment]
I had some issues with local repo, solved conflicts and re-opened the PR as #3026

**Pull request closed without merging**
