### PR TITLE
Submit bug report directly from game

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: Infrastructure "Submit bug report directly from game"

#### Purpose of change

it's often tedious to
1. open github BN repo page
2. create bug report
3. copy and paste Version and Config
4. paste it into bug report

#### Describe the solution

- 02dc4c426b0d9c91b75b07b91618093c889da987: add `url_utility.{cpp,h}` to handle opeing browser and encoding url
- 00cf6a934282f04061d664267f42ed1c5f378424: Add an option `DEBUG_BUG_REPORT (u)` to open github issue directly
- others: documentation changes

#### Describe alternatives you've considered
- post image directly on issue form but for some reason image gets broken

#### Testing
`open_url` is not tested outside linux; it may fail on other environment but haven't a clue how to test those.

#### Additional context
|  |  | 
| :----: | :----: | 
|  |  |

### CODE REVIEW

**Comment by RelMayers** [comment]
User should first check if issue is reported....

**Comment by Zireael07** [comment]
Agreed with @RelMayers - at the very least needs some sort of a reminder to check repo first to prevent people flooding the repo with duplicates

**Comment by scarf005** [comment]
I doubt we're that *flooding with issues* to worry for duplicates, tho.

**Comment by RelMayers** [comment]
> I doubt we're that _flooding with issues_ to worry for duplicates, tho.

we for sure have some duplicates... they are mostly probably not tagged

**Comment by Coolthulhu** [comment]
We're not using trailing return yet. It makes the code less readable to most potential contributors.
Would be better to use the classic C style.

**Pull request merged**
