### PR TITLE
Port over shelter 2 basecamp

### PR DESCRIPTION
**Pull request by DrPariah**
#### Summary

SUMMARY: Content: Port Over The Modular Shelter 2 Basecamp

#### Purpose of change

This is an attempt to bring over #44011 from a little while back on the mainline C:DDA branch. Somebody went to the trouble to put basecamp functionality in Shelter_2, and I finally got it working.

#### Describe the solution

Normally this should have been a simple plug 'n play port, but it wasn't. Somewhere along the line, not sure where, DDA got some kind of functionality that lets it automatically extrapolate requirements on recipes in the basecamp stuff. So, basically the person who submitted the original PR didn't have to put in full recipe details on the Shelter 2 stuff, even though it was all there for the other Shelter types. That meant a straightforward port would get you recipes without ingredients or any way to complete them in the Faction Camp menu (it'd tell you that building a bedroom was available, but would give no components and no completion time, etc.). Bottom line, I did a lot of copy 'n paste from existing recipes, as well as took out quilts and patchwork quilts from the options - those items got mainlined from Aftershock a while back, I think, but haven't been in BN yet.

#### Describe alternatives you've considered

Not doing it at all was the simple one. Also, trying to recreate it from scratch, but that struck me as duplicating effort for no reason.

#### Testing

Made sure that Evacuee starts could _only_ start in Shelter_2 for testing purposes. Loaded the files and did the updates and recipe stuff, linted everything via online JSONLint. Created a character, debugged the starting NPC to have appropriate skills for everything, debugged in a ton of supplies, successfully completed the main faction camp build (that's all the stuff inside the shelter itself, including the workbench and the like) without errors or game breaking. Did not test the modular field stuff because there's no difference between the modular field emplacements for the various Shelter types.
Prior to uploading files, used the jsonformatter.exe on them. I can't guarantee that these will not have something weird or stupid showing up, but everything else is showing them as clean. Just advise of errors and I'll do what I can to fix them.

#### Additional context

As a bonus, this also adds the ability to get your NPCs to make Heavy Wooden Beams and Wooden Panels. Handy little addition.

Mainline DDA has multiple additional types of Faction Camps available, including builds in Mansions, Pottery Barns (?), Sea Labs, and Helicopter Landing Pads (the Military ones with the turrets and tons of Soldier and Burner zombies in them). I haven't looked at them yet because I can't guarantee that the mapgens are the same any more, and some (the Sea Lab) aren't available in BN. They would all need the recipes to be detailed just like the Shelter 2 stuff, but there'd be a lot less available to copy from.

### CODE REVIEW

**Comment by Lamandus** [comment]
Interesting error. Autobilder somehow bugged out. Did you use objects, that aren't in the game? @Coolthulhu could you look too

**Comment by DrPariah** [comment]
Looks like the original PR got the same issue, but they resolved it...somehow?

[https://github.com/CleverRaven/Cataclysm-DDA/pull/44011#](url)

Also there was an update to the blueprint requirement checker in the following related PR:

[https://github.com/CleverRaven/Cataclysm-DDA/pull/44097](url)

**Comment by DrPariah** [comment]
Well, setting Blueprint Needs: False did get it to bypass the checks that were killing it.

**Comment by Coolthulhu** [comment]
Alright, I merged the changes. It doesn't show it and instead shows conflicts because I used tricks that github did not recognize.
Here's the commit with the changes in this PR:
https://github.com/cataclysmbnteam/Cataclysm-BN/commit/69df550885a093ce9bf4940d971336bec0b655fa
Here's my fix for the errors:
https://github.com/cataclysmbnteam/Cataclysm-BN/commit/bee8a496732177e7fc1cda11c57246048a1066a0

**Pull request closed without merging**
