### PR TITLE
Updating UDP tileset

### PR DESCRIPTION
**Pull request by thelonestander**
BN, is behind on a few updates so I thought id update them in game.

#### Purpose of change

I just wanted people to see the lovely new work that has been done with UDP. Lots of new tiles for buildings, plus we need it updated!

#### Describe the solution

Just updating the tileset. 

#### Describe alternatives you've considered

-Letting someone else do this
-None

#### Testing

Tested in game works fine. 

#### Additional context
Screenshot (578)

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
I'll remove arcana soon, since it is externally maintained, I just forgot to do so, since Chaosvolt has asked me about it in the past and since it is inside the mod itself there is no reason to keep it in tileset folders.

**Comment by chaosvolt** [comment]
Eventually I'll be able to do so for Cata++ too, and when its UDP portover and cleanup is actually finalized I'll likely try and remember to PR a cooresponding PR to the UDP repo.

**Comment by olanti-p** [comment]
Does this include changes done to BN version of the tileset, such as #1102, #1118, #1655?

**Comment by thelonestander** [comment]
Im going to close this for now, I messed up the initial PR. SO closing this so I can re do it the right way. I need to see if #1102, #1118, and #1655 are also included in UDP. Will get back to this.

**Pull request closed without merging**
