### PR TITLE
feat(balance): Martial Arts Book Spawn Chances

### PR DESCRIPTION
**Pull request by yay855**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

The chances for almost any martial arts book to spawn other than a select few, almost all of them unarmed, were abysmal, making most players unable to gain most martial arts styles outside of starting with them via a trait. Although it's true that most dojos IRL focus on a few specific styles (karate, taikwando, krav maga, ninjutsu), this feels fairly punishing towards melee focused players, and discourages melee further in a game that already prioritizes ranged combat... and which rewards unarmed combat heavily via the mutation system.

## Describe the solution

The chances for almost all martial arts magazines to spawn have been equalized, averaging out at around 15; there is now a very good chance to find any one of those manuals in a dojo or mansion.

## Testing

The dojos are now guaranteed to spawn a single martial arts manual each. If you think the type 1 dojo should spawn multiple, that can be easily edited.

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]
owo

**Comment by Lamandus** [comment]
We should consider spawning them in libraries and bookstores with a very low chance, just to give a chance to players

**Comment by scarf005** [comment]
wait, aren't martial arts book spawned in libraries?

**Comment by Lamandus** [comment]
> wait, aren't martial arts book spawned in libraries?

no, just dojos

**Pull request merged**
