### PR TITLE
[CR]Rewrite electric grids

### PR DESCRIPTION
**Pull request by Coolthulhu**
Related to #48, but doesn't implement plumbing.

New grids work as follows:
* Overmap buffer provides set of positions of connected overmap tiles (say, house+basement).
* This is turned into a `distribution_grid`, which holds positions of `active_tile_data` entities. Those are in absolute coords.
* When processing a turn, all `distribution_grid`s that cross current `map` are updated to current turn.
* Updating a grid is just updating all `active_tile_data` in it (currently per-element, meaning no production/consumption equilibrium is possible).
* `active_tile_data` knows only its own data, its absolute world coord and the grid it belongs to.

TODO:
* [X] Get it to do something (charge batteries, as before)
* [x] Save last update time per-grid-item, so that grids can be retroactively updates as one entity
* [x] Make electric ovens work as a hotplate with charges equal to charges in grid
* [x] Add a basic test (it's hard to test due to usage of `MAPBUFFER`)
* [x] Fix the part where it breaks crafting with water from toilets

Optionally:
* [ ] Code cleanup to avoid batteries and producers/consumers having to share code
* [ ] Clean up saves with invalid active furniture (it wasn't rotated)

I could really use code review from someone who has designed something of similar scope. I had to redesign this thing once, meaning I don't exactly know what I'm doing.

### CODE REVIEW

**Comment by olanti-p** [comment]
Could it be feasible to move `active_tile_data` from submaps into `distribution_grid`?
This could allow updating grids without necessarily loading the corresponding submaps, maybe to a point where it would be possible to extend grid update radius beyond radius of current `map` without heavy impact on cycles & memory.

**Comment by Coolthulhu** [comment]
> Could it be feasible to move active_tile_data from submaps into distribution_grid?

This would require the grid to store all the data and be saved somewhere. Currently grids are saved as overmap connections, which makes them pretty resilient to desyncs.

> This could allow updating grids without necessarily loading the corresponding submaps, maybe to a point where it would be possible to extend grid update radius beyond radius of current map without heavy impact on cycles & memory.

I'm trying not to optimize just yet, but submaps themselves aren't a big performance hog. If needed, they could be cached.
With proper caching, big grids would only cause trouble at load time.

**Comment by olanti-p** [comment]
> > This could allow updating grids without necessarily loading the corresponding submaps, maybe to a point where it would be possible to extend grid update radius beyond radius of current map without heavy impact on cycles & memory.
>
> I'm trying not to optimize just yet, but submaps themselves aren't a big performance hog. If needed, they could be cached.
> With proper caching, big grids would only cause trouble at load time.

I was thinking more in the lines of "by detaching grid data from submaps, it could be possible to keep all grids in the radius of, say, an overmap, active, and that could allow to get rid of the need to 'backwards update' these grids when player re-enters an area (e.g. their base)".

**Comment by Coolthulhu** [comment]
> keep all grids in the radius of, say, an overmap, active

That would be significantly more expensive than updating them retroactively.
Also, it's still possible to keep extra grids active with submaps.

**Comment by olanti-p** [comment]
> That would be significantly more expensive than updating them retroactively.

Most likely. But I was assuming there would be appliances for which retroactive update would be prohibitively complex, or appliances that need to be updated at long distances (e.g. radio transmitters).

> Also, it's still possible to keep extra grids active with submaps.

Yeah, now that I think about it again, these cases are quite rare, so even if the need would arise to keep far-away grids alive, keeping their submaps loaded wouldn't cause _that_ big impact on memory usage / save time...

**Comment by Coolthulhu** [comment]
H-h-here I go.
Only one test case (crafting) plus manual testing. At least it's most likely safe.

**Comment by Firestorm01X2** [comment]
Oh!

**Comment by Inglonias** [comment]
what

**Pull request merged**
