### PR TITLE
DDA port #53764: Add cursor navigation to the mutations UI

### LINKED ISSUE #1479: Not enough characters to represent all mutations
Version cbn-windows-tiles-x64-msvc-untranslated-2022-04-03-1526

My character has 83 mutations. There aren't enough characters in a-z, A-Z, special chars (total 72) to uniquely represent all mutations, resulting in the broken menu shown in the screen shot. 

image

### PR DESCRIPTION
**Pull request by SaintCirno9**
#### Summary

SUMMARY: [Interface] "Add cursor navigation to the mutations UI"

#### Purpose of change

To fix #1479

#### Describe the solution

Cherry-picked from https://github.com/CleverRaven/Cataclysm-DDA/pull/53764

#### Testing

Seems working fine.
GIF 2022-4-24 18-22-46

#### Additional context

https://github.com/CleverRaven/Cataclysm-DDA/pull/54204 is also included.

### CODE REVIEW

**Comment by SaintCirno9** [comment]
So Clang 9 test failed, but I can't really figure out why and cannot test it without corresponding environment.

**Comment by chaosvolt** [comment]
```
rng_test.cpp:19: FAILED:
  CHECK( stats.test_threshold( target_range ) )
with expansion:
  false
with messages:
  Goal: -1.1
  Result: -1.01
  Samples: 100
```

Looks unrelated to me.

**Comment by SaintCirno9** [comment]
Weird.
Is this Clang 9 test fail just happen randomly?
Pushed an empty commit then all tests passed.

**Comment by Coolthulhu** [comment]
Was a RNG error. I should probably just disable those tests, 99% of the time they break due to RNG alone.

**Pull request merged**
