### PR TITLE
Magiclysm Rebalance: Part 1

### PR DESCRIPTION
**Pull request by RobbieNeko**
#### Summary

SUMMARY: Mods "Various Miscellaneous Magiclysm Balance Changes, primarily to Monsters"

#### Purpose of change

Magiclysm is very much so abandoned for BN, and is in a terrible spot Balance-Wise. It's time for someone to pick up the task and bring this mod into acceptable balance. I have decided to volunteer to be said person, and thus this PR was born. In particular, all sorts of nasty monsters that could spawn Day 1 and obliterate a fresh character were in the mod. Now, they will be much less prone to doing so without the player actually fucking up. Demon Spiders were also due for a huge nerf, and may in fact still need a nerf in some aspects. This will hopefully ameliorate their disgusting state.

#### Describe the solution

1. Change the points for the "Druid" profession from 4 to 2 (It really doesn't give anything near the other 4 point professions, and is more at home back in 2 points.
2. Move certain Holy spells from Technomancer to Animist. _Why they were there in the first place, I have no clue. Animist is **clearly** supposed to be the category for holy and unholy magic_
3.  Change the aggression values of Owlbears, Oozes, Trolls, and most of the Golems to no-longer be immediately hostile towards the player. Additionally, add "PLAYER_CLOSE" and "HURT" as anger triggers to those lacking it. This is to hopefully prevent the ganking of new characters by these fiendishly common enemies. Plastic Golems are left alone because they don't spawn in the wild, only at towers.
4. Cut the damage dice number of Demon Spiders to a mere quarter, nerf the normal Demon Spider's HP by about 100, reduce the Queen's HP to about a quarter of its previous value, lower the melee skills of the spiders, nerf the Dodge stats to be more reasonable, and massively increase the cooldown of the Queen's spawning ability. Very slight buff to Demon Spider damage dice quality.
    Demon Spiders were incredibly strong, with the queen easily being the strongest monster that ships in-repo. This aims to make them less cancerous, and more able to be taken on by prepared players. It's now possible to take down normal Demon Spiders with even simple Biosilicified chitin armor, although in testing trying to take 2 back-to-back was disastrous. The Queen is now mostly kite-able to death with a Lucerne hammer, and likely would be full for an actually skilled character with strong strength. Alternatively, 7 pieces of dynamite, 14 shots of .50 BMG, or about 14 casts of max-level ice-spikes can kill her safely. The buff to the damage dice quality of Demon Spiders is to allow them to be just slightly more damaging, though their main damage source is their flaming hands spell.

#### Describe alternatives you've considered

- Letting the mod rot on the vine, and continue to be marked with some of the worst balance out of any mod
No thanks, I kind of like the concept of the mod and want to see it do better.

#### Testing

1. Loaded into game, confirmed the changes to Druid point cost worked
2. Loaded into game, confirmed that the relevant holy spells are no-longer Technomancer (If they were for some ungodly reason actually in a Technomancy book, they still need to be removed from there)
3. Loaded into game, extensively tested and made sure that owlbears only aggroed when I triggered an anger condition such as getting close to them.
- Sidenote: The exact effects of Aggression / how the values affect things beyond very low values making things not immediately hostile is **not** clear.
4. Loaded into game several times, testing combat between me, wearing full biosilicifed and wielding a mace, and the foul demon spiders. Confirmed that they were reasonably beatable. Tested each time I progressively made the nerfs bigger.
5. Same as 4, but with a Lucerne hammer and kiting the Queen. Also, once or twice, killed it via Max-level ice spikes. I was unable to avoid dying to the Spiderlings spawn, but with some extra armor and some extra skill it's likely you could win. Also, some extra strength.

#### Additional context

Hopefully there will be many more successful PRs regarding balancing Magiclysm in the future. There's so much more to do, and I'm already thinking on what I want / need to tackle next.

### CODE REVIEW

**Comment by RobbieNeko** [comment]
... respectfully, I doubt that build should be failing due to me changing something in Magiclysm.

**Comment by scarf005** [comment]
yeah, seems like overmap error on Lua side.

**Comment by chaosvolt** [comment]
So regarding changes to the spells being technomancer, luckily it's not too much to fix:
1. Bless isn't confined to any techomancer-specific spells, instead it's found in a generic holy magic spellbook and a spell scroll. In both cases, nothing player-facing says they're technomancer-specific, just JSON comments: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spell_scrolls.json#L611 and https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spellbooks.json#L91
2. Holy Blade's in the same boat, only referred to as such via JSON comments in its spell scroll and a paladin-themed book: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spell_scrolls.json#L620 and https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spellbooks.json#L108 (the latter also covers Spiritual Armor, as it's learned from the paladin book).
3. As mentioned, the paladin book's JSON comment covers Spiritual Armor, the comment saying its spell scroll is for technomancers is here: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spell_scrolls.json#L629

Oddly, no professions start with those spells and no references to technomancers I could find (like documentation or the trait description) give any mention of a holy theme,. This is probably just Korg haphazardly lumping all item-spawning spells in with technomancy, since several other spells it gets are more thematically appropriate and revolve around conjuring stuff.

**Comment by RobbieNeko** [comment]
> So regarding changes to the spells being technomancer, luckily it's not too much to fix:
> 
> 1. Bless isn't confined to any techomancer-specific spells, instead it's found in a generic holy magic spellbook and a spell scroll. In both cases, nothing player-facing says they're technomancer-specific, just JSON comments: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spell_scrolls.json#L611 and https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spellbooks.json#L91
> 2. Holy Blade's in the same boat, only referred to as such via JSON comments in its spell scroll and a paladin-themed book: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spell_scrolls.json#L620 and https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spellbooks.json#L108 (the latter also covers Spiritual Armor, as it's learned from the paladin book).
> 3. As mentioned, the paladin book's JSON comment covers Spiritual Armor, the comment saying its spell scroll is for technomancers is here: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Magiclysm/items/spell_scrolls.json#L629
> 
> Oddly, no professions start with those spells and no references to technomancers I could find (like documentation or the trait description) give any mention of a holy theme,. This is probably just Korg haphazardly lumping all item-spawning spells in with technomancy, since several other spells it gets are more thematically appropriate and revolve around conjuring stuff.

Good, I would have been surprised if it was actually in anything technomancer anyway

**Comment by RobbieNeko** [comment]
And yeah, looks like it gets a few spells that really ought to be either Magus or classless. Technomancer really is a mess, ngl

**Comment by chaosvolt** [comment]
Yep, looks like this is good to go, tweaking JSON comments can always be done whenever. Maybe at some point we'll either think up ideas or see what DDA's added that can be ported without too much screaming at C++...

**Comment by RobbieNeko** [comment]
> Yep, looks like this is good to go, tweaking JSON comments can always be done whenever. Maybe at some point we'll either think up ideas or see what DDA's added that can be ported without too much screaming at C++...

Yup, JSON comments are no big deal. And I can definitely take a more comprehensive look at spells and where they are later when I get around to mucking through spell balancing. I only fixed these because I felt them particularly egregious when I realized my Paladin Spellbook had two "Technomancer" spells in them.

**Review by chaosvolt — APPROVED** [review]

**Comment by sayke** [comment]
Aren't demon spider queens supposed to be effectively unkillable using standard weapons though? You had to use anti-tank weapons or magic

**Comment by RobbieNeko** [comment]
> Aren't demon spider queens supposed to be effectively unkillable using standard weapons though? You had to use anti-tank weapons or magic

Given its huge health pool, I doubt even those would have scratched it. _Especially the magic._ Also, if that was truly the intent, then I fundamentally disagree with the idea. It should take a lot to bring down, sure, but not **anti TANK munitions**

**Comment by sayke** [comment]
My usual approach against demon spider queens has been to hit them with anti-tank weapons: TOW missiles, Carl Gustav rounds, and 30mm autocannon and 120mm tank rounds from Tankmod.  

I've also taken them out with specialized ramming vehicles equipped with powerful engines, heavy frames, and road rollers. 

I've also taken them out with magic missile through the wall of the nest, with the help of a mask of insight to see through the wall - which works because magic missile does true damage, piercing all armor. 

I've also lured the demon spiders (including the queen) out into towns and used them to clear the town of zombies.

There are lots of ways to handle and even leverage creatures that cannot be killed through obvious means, but it makes the player think outside the box, you know?

**Comment by Ignaramico** [comment]
> Aren't demon spider queens supposed to be effectively unkillable using standard weapons though? You had to use anti-tank weapons or magic

IIRC the fact that they had that much HP was a typo, and no one corrected it; because of lazyness or giggles i dont know. that and the fact that the lairs arent that good loot wise

**Comment by RobbieNeko** [comment]
> It's a demon spider queen, so it has an excuse to be magically super tough. My usual approach against them has been to hit them with anti-tank weapons: TOW missiles, Carl Gustav rounds, and 30mm autocannon and 120mm tank rounds from Tankmod. You can even take them out with a .50 cal. That just takes a lot of ammo and attracts a ton of attention, which offers a tactical challenge to the player.
> 
> I've also taken them out with specialized ramming vehicles equipped with powerful engines, heavy frames, and road rollers.
> 
> I've also taken them out with magic missile through the wall of the nest, with the help of a mask of insight to see through the wall, which works because magic missile does true damage, piercing all armor.
> 
> I've also lured the demon spiders (including the queen) out into towns and used them to clear the town of zombies.
> 
> There are lots of ways to handle and even leverage creatures that cannot be killed through obvious means, but it makes the player think outside the box, you know?

I mean, it's not like it's *easy* to kill it now. 7 dynamites, 14 shots of .50, or 14 max-level ice spikes are not exactly cheap. Pretty sure its health is still the largest out of anything, especially shipping in-repo. Tis still a challenge, but at least now you can reasonably try and take it down *without* needing obscene anti-tank weaponry (or a tank itself)

> > Aren't demon spider queens supposed to be effectively unkillable using standard weapons though? You had to use anti-tank weapons or magic
> 
> IIRC the fact that they had that much HP was a typo, and no one corrected it; because of lazyness or giggles i dont know. that and the fact that the lairs arent that good loot wise

Given all the other laziness / unbalance in Magiclysm, wouldn't surprise me too much if it was somehow a typo that just never got fixed.

**Comment by chaosvolt** [comment]
If I recall, I'm fairly certain the original typo was giving it 56000 HP, with 5600 being actually intended (albeit wacky, that's still 600 more than Cata++'s Bio-Weapon Apophis has when he's actually MEANT to be tough as fuck and a major storyline boss, with both having similar armor levels, only really lacking Apophis' long-since-nerfed regen).

**Comment by sayke** [comment]
The demon spider queen having 56000 HP isn't an accident and isn't that hard to deal with.

Korg says he deliberately "put this monster in partly as a stretch goal for the kind of power level I would like the player to be able to deal with at the end game. And given the other comments in this thread, I have at least partly succeeded." (https://old.reddit.com/r/cataclysmdda/comments/oy87gi/demon_spiders_are_absolutely_busted_beyond_reason/h7xrxrq/)

What else are the copious amounts of anti-tank weapons you inevitably find actually useful for? 

What else actually presents a challenge for lategame character damage output capabilities?

It sounds to me like you just didn't think outside the box about how to deal with them.

**Comment by scarf005** [comment]
could we continue this in github discussions? closed pull requests are usually not great for prolonged discussions.

> It sounds to me like you just didn't think outside the box about how to deal with them.

also, it'd be really great if we'd tone down our words a little bit.

**Comment by chaosvolt** [comment]
> Korg says he deliberately "put this monster in partly as a stretch goal for the kind of power level I would like the player to be able to deal with at the end game. And given the other comments in this thread, I have at least partly succeeded." 

Considering that @foulman had to repeatedly remind him that his spells generally start off at "if you're lucky it will top double-digit damage" and eventually max out at "now it's still less useful than a gun", a lesson he repeatedly failed to heed, I'd say he only succeeded in adding the challenge that warrants said firepower but failed at delivering on the other end of it.

**Pull request merged**
