### PR TITLE
Finish ui_adaptor migration (part 2)

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
SUMMARY: Interface "Migrate some UIs to ui_adaptor (ported from DDA), clean up NPC dialogue UI"

#### Purpose of change
Finish migrating UIs to ui_adaptor

#### Describe the solution
Cherry-picked, almost without changes, PRs from DDA:

CleverRaven#40553
Advanced inventory menu [`/`], defense game menus.
Advanced inventory had text trimming issue when game window was very narrow (around 80), fixed that.

CleverRaven#40526
CleverRaven#40608
iuse games (accessable through handheld game system)

CleverRaven#40621
Live mouse view & npc dialogue window.
The dialogue window had a bunch of problems:
* Message history was saved as folded chunks of actual messages. That means, there was no way to re-fold messages when window was resized.
* At small game window heights (approx <40), NPC-related keybindings were not visible (a bug: they were printed out of visible area).
* Paging of responses worked weirdly, sometimes cutting responses in half (which it shouldn't do).

So I decided to refactor it a bit to mitigate those issues:
* Messages are now stored whole, and a separate vector stores folded chunks of those messages & separators. When game window is resized / new message is added, that vector is re-generated / updated.
* Previously, all responses were folded & treated as a continuous array of lines, and paging was done by indexing into this array. That led to some responses being split in 2. Now, responses are folded and then separated into pages, with only the current page being displayed.

CleverRaven#40727
Cherry-picked everything except changes to targeting ui (too many conflicts, and that ui needs a refactor anyway).

CleverRaven#40770
Character status screen [`@`].

#### Testing
Tested each screen by resizing game window.
Tested NPC dialogue window by browsing various entries, switching pages and resizing window.
Checked that zone manager still works.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I see `redraw` has been removed. How is it handled nowadays?

**Comment by olanti-p** [comment]
You mean `bool redraw` from advanced inventory that was removed in this PR or something else?

**Comment by Coolthulhu** [comment]
Yeah. I remember seeing it before in other places, now it's replaced with something else.
I see redraws being done in multiple different ways. Is there no single standard yet?

I'm not sure if I understand how does this new UI work, other than having events for resizing and redrawing.

**Comment by olanti-p** [comment]
>I'm not sure if I understand how does this new UI work, other than having events for resizing and redrawing.

You may want to ask Qrox for details, since all of that is my own research into the system and is likely to contain factual errors / incorrect assumptions, but here the gist of it:

From what I understand from the code, there is a global state controlled by ui manager that contains references to all existing `ui_adaptor` objects (basically UI layers: terrain + sidebar, or AIM with all its panels, or a popup).
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/dd73e8e5c48a2ba109556cc800be924a44dd0e79/src/ui_manager.cpp#L12-L14
When you create a new `ui_adaptor`, it automagically registers itself in the global state. Then, you give it 2 callbacks:
* `on_resize`, which initializes the layer: calculates sizes/position, (re-)creates curses windows, and
* `on_draw`, which draw the layer

When some function (usually input loop after each input) calls `ui_manager::redraw()`, the ui manager goes through each registered layer and
1. if it has not been initialized or has been invalidated, calls `on_resize` for that layer
2. calls `on_draw` for that layer

If the screen has been resized, all registered ui_adaptors are invalidated, and `ui_manager::redraw()` is called. If any `ui_adaptor` was destroyed, its reference is removed from the global state, and `ui_manager::redraw()` is called.

The `on_draw` callbacks are written in such a way that the drawing is done into internal curses buffer, and once all layers has been drawn, the ui manager displays the final composed result on screen. Due to a single "display" operation, there should be no UI flickering, and it's somewhat faster (since curses/terminal can optimize out redrawing of static parts of the screen) and somewhat slower (since you have to redraw each layer) than the old way.

The old way was to work only with the topmost layer, optimizing out extra draw calls by inventing various systems on a case-by-case basis (like that `bool redraw` which is set to `true` if there was a UI-changing input event, or after popup was closed and UI has to be redrawn). If there was a need for an underlying layer (like, say, terrain view in targeting ui right now), you had to manually draw that layer, and then draw your layer over it, and that often lead to flickering. Some popups (e.g. keybindings menu or debugmsg) are hard to detect, and UIs failed to redraw once that popup was closed, leading to mostly-pure-black screens (until an input event triggers a partial/full redraw). Handling game window resizes was another can of worms - the underlying UI doesn't always check if the game window has been resized when popup was active, and that leads to wonky behavior.

I tried writing a similar system myself (used ncurses with another programming language), and it turned out pretty much the same, so I might be mixing in some of the personal experiences. There were also mentions of writing documentation for `ui_adaptor` - don't know if there was any progress on that front.

> I see redraws being done in multiple different ways. Is there no single standard yet?

Yeah, that goes from the need/desire to invent a custom drawing system for each UI. Some of those systems go back to 2012, when the standard practice was to fill invalidated chunk of the screen with spaces and draw new data over these spaces - and there was often some custom redrawing code for each active element on the screen, which was kinda funny (I wasn't in the project in 2012, but out of curiosity studied latest version of the old [Cataclysm](https://github.com/Whales/Cataclysm)).

There are a few more PRs that migrate various UIs to ui_adaptor, and a couple more that go over all the drawing code and clean it up - once all of that is done, the drawing would be somewhat standardized to use `ui_adaptor::on_redraw()` callback for full layer redraw, `ui_adaptor::on_screen_resize()` callback for layer initialization and `ui_manager::redraw()` for full/partial redraw.

**Comment by Coolthulhu** [comment]
Thanks, that's pretty comprehensive.

**Pull request merged**
