### PR TITLE
Add inherit_flags to byproducts when crafting

### LINKED ISSUE #2646: Cracklins byproducts from human lard is not flagged as human flesh
### Describe the bug

When creating human lard, the cracklins byproduct isn't flagged as human flesh. When making cracklins directly from human fat, it is properly flagged as such.

The discord mentions this also happens with tainted lard giving cracklins but I've yet to verify that.

### Steps To Reproduce

1. Find chunks of human fat.
2. Try to cook human lard.
3. Notice that cracklins doesn't have the flag.

### Screenshots

Here is the screenshot of cracklins from human lard.
image
Here is the screenshot of cracklins made directly.
image
Here is a bonus screenshot of cracklins made from normal chunks of fat.
image

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro for workstations Build 19045
- Game Version: 0.2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    FoxMod for Bright Nights [FoxMod],
    Fuji's Military Profession Pack [fuji_mpp],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Bright Nights (wrapper) [dda],
    Cataclysm++ [Cata++],
    <color_cyan>Lones Soda mod</color> [coke_flavors],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Dorf Life [Dorf_Life],
    Fewer Farms [Fewer_Farms],
    SzQmod [SzQmod],
    Tankmod: Revived [Tankmod_Revived],
    No Addictions [No_Addictions],
    Nonperishable Overhaul [Nonperishable_Overhaul]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mythosmod**
#### Summary

SUMMARY: Content "Add inherit_flags to byproducts when crafting"

#### Purpose of change

To allow byproducts to inherit flags marked craft_inherit when crafting in the same way as primary product can - Fixes #2646

#### Describe the solution

Byproducts when created from the same ingredients do not currently inherit the same flags as the primary product - this led to cracklins when produced as a byproduct of making human lard to not be tagged with the CANNIBALISM flag in the same way cracklins made directly did - this has been changed by adding the inherit_flags function to the byproducts in crafting.cpp so they inherit the same flags as the primary product.

I had initially thought that some sanity checking would be required but this is already present within the jSON definition of the flags themselves in the craft_inherit setting (which defaults to false if not specified) - the currently inheritable flags in the main codebase are:

FILTHY
HIDDEN_HALLU
HIDDEN_POISON
BAD_TASTE
CANNIBALISM

None of the in-repo mods have a flag with craft_inherit set on searching through.

#### Describe alternatives you've considered

Creating individual items for each of human_cracklins, mutant_humanoid_cracklins etc. so they have the correct CANNIBALISM flag when created as byproducts.

Create separate byproducts_inherit entry for flags set to false to allow crafts to inherit properties that byproducts do not.

#### Testing

Loaded into base game and tested by creating human lard, byproducts are tagged as human flesh without having to specify a specific type of cracklins, cracklins as a byproduct of ordinary fat do not have the CANNIBALISM flag as ingredients do not

#### Additional context

image

### CODE REVIEW

**Comment by chaosvolt** [comment]
This runs into the exact same reason why https://github.com/CleverRaven/Cataclysm-DDA/pull/45812 is a bit half-baked: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/729b0cf01e3c22dd55ca5ca4b68f6adaf51f5b0e/data/json/recipes/food/meat.json#L524

There's a recipe to make cracklins directly as well, which allows use of any edible fat.

**Comment by mythosmod** [comment]
Yeah I think you are right it would be better to fix the issue at the byproducts stage rather than creating items to facilitate the shortcomings, I've been looking at the byproducts code and I'm sure there must be a way to add components to byproducts- as it stands, crafting cracklins directly with human fat correctly marks them as containing human flesh whereas if they are created as a byproduct of human lard it does not.

**Comment by chaosvolt** [comment]
Messing with the code would be ideal but a pain in the ass admittedly. The JSON-only solution would be easy enough as well, basically just defining a separate recipe for human cracklins and removing human fat from the allowed ingredients for regular cracklins.

**Comment by mythosmod** [comment]
OK, converting to a draft as I have added in for byproducts to inherit flags which marks the cracklins produced with the CANNIBALISM flag present on human flesh without having to create different cracklins byproducts for human lard, mutant humanoid lard etc. - doing some testing now though as there may need to be some sanity checking added (such as defining that byproducts should inherit component flags) as there are probably several cases where you wouldn't want this to be the case.

**Comment by mythosmod** [comment]
@chaosvolt A change of approach on this one, should hopefully be a more rounded solution if you have the time to review again 😃 not too much of a major change hopefully

**Comment by chaosvolt** [comment]
Nice, will try and get to this later today if I can.

**Review by chaosvolt — APPROVED** [review]

**Pull request merged**
