### PR TITLE
feat: add ammo vending machines to some grocery stores and gas stations

### PR DESCRIPTION
**Pull request by Lamandus**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
Add some possibility to spend some money on stuff. Ammo may spawn in ammo vending machines (those are reinforced). That was already a thing in shooting ranges but now grocery stores and gas station can have them too. They will however be mostly empty, if you have luck, they may have one or 2 ammo batches. Also some tweaking.

## Describe the solution
1. remove the "vending_guns" group, since it is obsolete and not used by anyone than my stuff.
2. Reduced the amount of ammo spawned in the ammo vending machines (the ones we already had) by a lot.
3. spawn ammo vending machines in gas stations and one grocery shop variant. The chance of actually having any ammo is around 22%. And even if, it won't be much.

## Testing
spawns and work.

## Additional context
https://www.telegraph.co.uk/us/news/2024/07/07/bullets-ammunition-vending-machines-three-american-states/

the future is near.

### CODE REVIEW

**Comment by chaosvolt** [comment]
I'm not sure if that's...that great an idea honestly? We already have plenty of places to get ammo at this point, we could probably be using reinforced vending machines for other valuable goods in other locations instead?

**Comment by RoyalFox2140** [comment]
Okay, on suggestion from Kheir, I will link back to PR https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5069 Where it was already decided we weren't adding more ammo vending machines to locations.

**Comment by RoyalFox2140** [comment]
I'm going to put in the chief complaint I have here as: 
3 3% chances of ammo, 2 6% chances, and 1 13% chance. The machines rarely have ammo.

So this is a two pronged issue
1. If it always has ammo, do we need more sources of ammo in the game right now, when we have so many?
2. If it doesn't have ammo most of the time, do we need useless alarm furniture in every grocery store?

Additional complaint: Reinforced machines are hard to interact with, we improved safes we need to look at how we'll deal with reinforced vending machines.

**Comment by VissValdyr** [comment]
Ok then we don't. If you wish. I already see the thumbs down of CV as well. I won't bother

**Comment by RoyalFox2140** [comment]
I was hoping to discuss it more over on the Discord about how we could convert the idea to different items, but I guess that can be a separate PR.

**Comment by chaosvolt** [comment]
> Ok then we don't. If you wish. I already see the thumbs down of CV as well. I won't bother

I would really rather you don't publically blame me for PRing something that prior discussion made reasonably clear was likely to be vetoed. Singling me out over this when multiple people gave their feedback about the flaws in this is also genuinely a dick move.

**Comment by Lamandus** [comment]
> I was hoping to discuss it more over on the Discord about how we could convert the idea to different items, but I guess that can be a separate PR.

I rarely look at Discord anymore, When I closed down, I wasn't aware of any discussion there

**Comment by RoyalFox2140** [comment]
> > I was hoping to discuss it more over on the Discord about how we could convert the idea to different items, but I guess that can be a separate PR.
> 
> I rarely look at Discord anymore, When I closed down, I wasn't aware of any discussion there

If you don't use Discord how can we collaborate or discuss your changes and how they might fit into the game better if we disagree with them? You're setting yourself up for them not being merged if you won't talk to us about your work. This is not CV or I holding a vendetta, this is stuff that people generally disagree with on the Discord and closing it before we can discuss improvements just stops anyone from helping you.

> Ok then we don't. If you wish. I already see the thumbs down of CV as well. I won't bother

We're NOT using Closed PR's as a place to argue with others or to be angry about criticism. I might catch flak for this (Probably not though) but I am locking this discussion. You're free to actually discuss your problems somewhere that isn't the Github. You need to cool it, publically singling out and blaming a single maintainer for disagreeing with your work because you REFUSED to accept criticism and immediately closed this is NOT going to be tolerated. None of us are happy with this, and the friction that has happened the past year when we've given feedback is tiresome. We've warned you how many times about this?

**Pull request closed without merging**
