### PR TITLE
fix(balance): add "COMPACT" to ammo satchel, fixing old errors of mine in encumbrance.

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
In a PR some days ago, I added the flag "COMPACT" (it makes the item wearable with others on the same layer) to many items, I missed the ammo satchel. Now it is added in. So it won't conflict with a leather belt for example.

Also I missed some encumbrance values not being set for some items. I defined "base" encumbrance which will lead to its max.

## Describe the solution
1. Give ammo satchel the tag "Compact"
2. give it a max encumbrance of 3 (was rigid 5 before)
3. added (max_)encumbrance to items missing it (or I deleted them and forgot to add them back)

### CODE REVIEW

**Comment by chaosvolt** [comment]
This follows up on my PR back in: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3792

Per the PR OP: `Mag pouches, wrist/ankle storage, and makeshift ammo satchels were left untouched for now.`

I think I left them untouched only really because I was already changing a bunch of items all at once already and didn't know how it'd be received. Looking at the file, the similar `"leg ammo satchel"` already got this flag at some point so it's probably reasonable consistency-wise to add it to this. This is a different slot but same item niche so.

**Comment by Lamandus** [comment]
> This follows up on my PR back in: #3792
> 
> Per the PR OP: `Mag pouches, wrist/ankle storage, and makeshift ammo satchels were left untouched for now.`
> 
> I think I left them untouched only really because I was already changing a bunch of items all at once already and didn't know how it'd be received. Looking at the file, the similar `"leg ammo satchel"` already got this flag at some point so it's probably reasonable consistency-wise to add it to this. This is a different slot but same item niche so.

yes #4464 got compact to those ammo pouches. Quivers had them already. Since ammo pouches were niche as you stated, giving them a reason to use, isn't too far off, especially since they have extremely limited use and only a very "low" encumbrance bonus to other items. It should be considered to "turn the file around" and give it a max_encumbrance like I did for the others. Give me a moment, please.

**Comment by chaosvolt** [comment]
Ah, whichever works then. Seems I didn't spot that PR.

**Comment by Lamandus** [comment]
I lowered the encumbrance to max 3, for making it somewhat useful. It had 5 enc. for the torso, so the nearly the same amount as a full survivor runner pack, which can hold 8 L (not just 1) and any object. So balance wise it would be also good to give it some edge.

**Comment by Lamandus** [comment]
I just noticed in the file, that some items were missing encumbrance altogether, probably my error. I added them back with "min"-"max" encumbrance in mind. File is now good to go from my side, no changes planed.

**Review by chaosvolt — APPROVED** [review]

**Comment by Lamandus** [comment]
thanks @chaosvolt please don't forget, that I am not capable of merging it anymore, so someone has to do it for me when the tests pass, thanks.

**Pull request merged**
