### PR TITLE
Multidrop code cleanup + optimization

### PR DESCRIPTION
**Pull request by olanti-p**
#### Purpose of change
1. Move all code related to inventory UI to `inventory_ui.cpp` and `game_inventory.cpp`, remove unnecessary includes of `inventory_ui.h`
2. Clean inventory UI code a bit
2.1. Untangle 2 methods responsible for column select-ability
2.2. Alias magic item pointers under a better name
2.3. Get rid of unnecessary `Character::item_tweaks` adaptor, pass list of item stacks directly
2.4. Make `max_chosen_count` static member into a constexpr, fix overflows
3. Get rid of multiple definitions of `drop_location`, unify with `iuse_location`
4. Get rid of `player_activity`->`drop_locations`->`std::list<pickup::act_item>`->`player_activity` conversions
4.2. As part of that, migrate ACT_WASH, ACT_STASH, ACT_DROP to actors
4.3. Remove activity migration code from 2016
5. Reorder items for dropping only once, on activity assignment, rather than every turn. According to benchmark from #830, when dropping many items 90% of the time is spent on re-reordering them.

#### Testing
Dropping 1000 rags on curses release build went down from 22.4s to 4.4s.

### CODE REVIEW

**Comment by Zireael07** [comment]
Would this fix https://github.com/CleverRaven/Cataclysm-DDA/issues/48937 if ported?

**Comment by olanti-p** [comment]
This speedup is for code related to "linked items" feature, which is exclusive to BN.

**Comment by Coolthulhu** [comment]
I don't like how it disables the ability to stop drop action with '.', but the performance improvement is noticeable.

**Comment by Coolthulhu** [comment]
Maybe we should have an option like "not suspendable but still cancelable".

**Comment by olanti-p** [comment]
> I don't like how it disables the ability to stop drop action with '.'

Oh, I didn't notice. Looks like it's caused by `drop_activity_actor` not assigning any value to `moves_left`, so the interrupt key check in `game::handle_key_blocking_activity()` is skipped as the code assumes activity to be already finished. Should be easy to fix.

**Pull request merged**
