### PR TITLE
fix(balance,port): evaporated milk quench

### PR DESCRIPTION
**Pull request by 0Monet**
## Purpose of change
Saw this: [Cataclysm-DDA/pull/69526](https://github.com/CleverRaven/Cataclysm-DDA/pull/69526)
So :
Evaporated milk quench to 10.
## Describe the solution
Change 25 to 10.
## Additional context
Capture d’écran 2023-11-30 195811

### CODE REVIEW

**Review by scarf005 — CHANGES_REQUESTED** [review]
Could we add [`Co-authored-by`](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) in commit, as this PR originates from DDA?

this means rebasing commits and adding `Co-authored-by` in commit body. if you're unfamiliar with command-line git (and rebasing), please let me know.

**Comment by AniDemi** [comment]
I don't know much about quench but does less water actually lead to less quench in this case or is it a misconception?

**Comment by 0Monet** [comment]
At first glance, less water means less quench.

**Review by scarf005 — APPROVED** [review]
I approve this change, rationale:
1. evaporated milk having less water sounds natural.
2. this 'nerf' only applies to a single item, and does not affect resource management around drinks since they are abdundant and waters are cheap.

**Pull request merged**
