### PR TITLE
Add seatbelts and 5-point harness items

### PR DESCRIPTION
**Pull request by RoyalFox2140**
SUMMARY: [Content] "[Briefly describe the change in these quotation marks]"

#### Purpose of change

I recently saw this pull https://github.com/CleverRaven/Cataclysm-DDA/pull/64834 and decided it was a good way of also adding a source of synthetic fabric. Now the seatbelts have an item AND we have a source of synthetic fabric. Thanks to @Fris0uman for the concept and much of the PR. 
#### Describe the solution

Adds seatbelts and 5-point harnesses, which are used for their vehicle parts. Adds a recipe to make a 5-point harness from 3 seatbelts plus hammering and cutting (My guess here is messing with the belt buckles, I figure you'd handle more on the installation side anyway), also adds an uncraft of seatbelt into synthetic fabric. In a separate PR I am merging lycra into nylon to remove this redundant material. Scarf suggested 3 nylon per seatbelt, so I went with that. Seatbelts are also used as a short rope for tying animals so you won't lose out on ropes

#### Describe alternatives you've considered

Make the seatbelts out of lycra because why not, don't add seatbelts, don't remove lycra but add a use for nylon.

#### Testing

Loaded changes into the game. Everything worked as expected. As Kheir suggested, I tested if tying a cow with a seatbelt would turn it magically into a short rope, but thankfully it didn't.

#### Additional context

Co-authored-by: @Fris0uman 
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2735

### CODE REVIEW

**Comment by RoyalFox2140** [comment]
Ok mass is fixed. Hooray for stumbling in the dark.

**Comment by RoyalFox2140** [comment]
converting to draft while I figure out why the tests fail.

**Review by scarf005 — APPROVED** [review]
<details><summary>New seatbelt and 5-point harness</summary>

Cataclysm: Bright Nights - cbn-experimental-2023-04-30-0326-3-g91274f02b516_01

Cataclysm: Bright Nights - cbn-experimental-2023-04-30-0326-3-g91274f02b516_02

Cataclysm: Bright Nights - cbn-experimental-2023-04-30-0326-3-g91274f02b516_03

</details> 

<details><summary>Confirmed that seatbelts and 5-point harnesses are (de)installable</summary>

Cataclysm: Bright Nights - cbn-experimental-2023-04-30-0326-3-g91274f02b516_04
Cataclysm: Bright Nights - cbn-experimental-2023-04-30-0326-3-g91274f02b516_05
Cataclysm: Bright Nights - cbn-experimental-2023-04-30-0326-3-g91274f02b516_06

</details> 

LGTM

**Comment by Fris0uman** [comment]
for future reference to add a co-author you need to format you commit message like this
```
[describe commit]


Co-authored-by: name <username@users.noreply.github.com>
```
WIth thetwo empty line lines

**Pull request merged**
