### PR TITLE
[WIP] Restore handmade weapons (like rail rifle)

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Restore handmade wepons

#### Summary

SUMMARY: Content "Restore handmade weapons (like rail rifle)"

#### Purpose of change
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/59

#### Describe the solution
Revert 
git log --all --grep='Obsolete scrap weapons'
commit b48eb09c669342b5e8a05f56ab422e0e5a41fbd3

#### Testing
1) Load game
2) Make sure resored wepons function properly

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Needs some rebalancing before it can get in.
Think of it as adding them rather than just bringing them back.
* Rail rifle and heavy variant look bad. Work-intensive ammo, needs UPS, high level. At this point they're just weird .50 rifles.
* Coilgun depends on UPS and has terrible damage. It looks like a skill grinding weapon and those shouldn't exist. Lmao at the comment in the json - the funniest thing is that it was written back then when you could throw glass shards for serious damage.
* Nail rifle is similarly terrible, except this time it's usable early, but only for grinding.
* Mininuke launcher is a meme.
* Pneumatics need their numbers checked. They look like they have unadjusted values for dispersion and loudness. They also need to be compared against crossbows and bows.

**Comment by Firestorm01X2** [comment]
Ok. Let's start with this:
https://github.com/CleverRaven/Cataclysm-DDA/pull/4151
>Adds craftable ferromagnetic rail rifle
>Uses 40 UPS charge per shot. Single-shot, noisy, and heavy recoil; but it makes up for it with DAMAGE.

Looks like rail rifle(and heavy rail life) should be really damaging. Not it is not the case for rail rifle.

**Comment by Firestorm01X2** [comment]
Rail rifles now will have damage output more than .50 Barret. Still rail rifles much less accurate.

**Comment by Coolthulhu** [comment]
I still don't see much use for it. What role is it supposed to have?
With its work-intensive ammo, it's expensive to use. When would anyone pick it over using the cheap ammo from military vehicles?

It would be better if you just picked one or two weapons for the PR. They all have some problems that need to be fixed, with no obvious solutions, so getting them in all at once would take a lot of time.

**Comment by Firestorm01X2** [comment]
>I still don't see much use for it. What role is it supposed to have?
High damage hand made weapon designed for experienced characters. Still is is cubersome and requre preparation, so it should not be everyday weapon

> With its work-intensive ammo, it's expensive to use. When would anyone pick it over using the cheap ammo from military vehicles?

Then I can make ammo less time investive

> It would be better if you just picked one or two weapons for the PR.

Picking things one by one will take too much time. It is better to handle it here to at least pasable state even if it will take more tome.

**Comment by Coolthulhu** [comment]
> High damage anti armor hand made weapon designed for experienced characters.

So far it doesn't really differ from heavy sniper rifles.
As for the "hand made" part, I'd rather see regular guns become craftable than having extra guns that only really differ in that they are craftable and have craftable ammo.
> Still is is cubersome and requre preparation, so it should not be everyday weapon.

But when would anyone use it? Heavy rifle at least has clip size above 1, but rail rifle has 1, giving it DPS below sniper rifles.
Also, we certainly don't need both the heavy and the regular one. Heavy variant is just plain better.

> Then I can make ammo less time investive

Currently, ammo crafting time is the only real late game limiter on rail gun usage. With it dropped to low values, what would prevent the gun from turning into "high caliber rifle but with cheap ammo"?

> Picking things one by one will take too much time.

It looks like you're trying to get them all in. This won't happen unless you redesign them - many of them have overlapping roles. And mininuke launcher just doesn't have a role.

**Comment by Firestorm01X2** [comment]
> It looks like you're trying to get them all in. This won't happen unless you redesign them - many of them have overlapping roles. And mininuke launcher just doesn't have a role.

Then it has to be done one by one.

**Comment by Coolthulhu** [comment]
Coil gun could get in if we had a way to hook up two magazines to it (ammo and battery). Early on, energy doesn't have enough (costly) uses. Requiring an UPS kills it, though.

Pneumatic bolter is just a high level crossbow with a clip. It may be salvageable, since lack of a clip is the biggest downside of crossbows.

**Comment by Firestorm01X2** [comment]
> Pneumatic bolter is just a high level crossbow with a clip. It may be salvageable, since lack of a clip is the biggest downside of crossbows.

So this means that Pneumatic bolter is first candidate for returning. Good.

**Pull request closed without merging**
