### PR TITLE
Complete reorganization of all recipes

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Infrastructure "Complete reorganization of all recipes into folders (category) and files (subcategory), correcting some on the way"

For example. 
image
can be found in
image
Rock in a sock is a bashing weapon. So it can be found in recipes/weapons/bashing.json 

#### Purpose of change
The recipe folder was a mess!

#### Describe the solution
I took hours to sort them into their correct files. Changed some errornous files.... now everything has a catergory, most fitting where they are now.

A lot of vehicle parts were located it parts, and not vehicle. While crafting parts (which this category actually is) weren't in any subcategory. that was changed as well.

#### Testing
It worked nearly right away. Yes, I was supprised too!

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Why capital letters in directory names?

**Comment by Coolthulhu** [comment]
Huge PRs like that are hard to process.

What exactly was your reasoning during the sorting? Why those categories?

**Comment by Lamandus** [comment]
The categories are the crafting categories. Like they are in the list, they are now in the files. I can remove the capital letter, no problem.

**Comment by Lamandus** [comment]
The old files were also sorted like this, but incomplete, and sometimes wrong. I fixed it. Like I mentioned before

**Pull request merged**
