### PR TITLE
Burst rebalancing: all burst shots have same accuracy

### PR DESCRIPTION
**Pull request by Coolthulhu**
Burst sucks. The only time it's worth it is when you're ambushed by a hulk and want to hit him with the "misses".

The new buffed burst works as follows:
* Every shot has the same accuracy
* This accuracy is like single shot minus "burst penalty"
* Burst penalty is based on recoil, decreased by skill (5% per level) and then by strength (20 dispersion points per str). Can be 0.
* Recoil doesn't depend on burst size. Single shot and full auto get same recoil. No realism here.

Also modified recoil mechanics a bit:
* Weight of the weapon, capped by strength, no longer lowers recoil
* Removed weird 5x multiplier applied silently to effective recoil. Recoil is now actually in dispersion units.
* Handling is now a linear divisor on recoil. Buffed it on guns and mods to compensate.
* Actually displaying the effective dispersion and recoil, so that the player doesn't need to guess it and make up weird myths.
* Decreased recoil on .50 to 5000 (was 12k) and 30-06 to 4000 (was 5300).

This should make bursts useful, especially on low caliber weapons.
It also makes them predictable, which should make it extra "useful" in an indirect, psychological way.

Fun fact: turrets are always perfectly aimed. No need for a scope.

Shooter | Weapon | Penalty
---|---|---
0 skill, 8/8/8/8 | "american_180" | 0
0 skill, 8/8/8/8 | "calico" | 150
0 skill, 8/8/8/8 | "m249" | 250
0 skill, 8/8/8/8 | "m4a1" | 350
0 skill, 8/8/8/8 | "ak47" | 700
0 skill, 8/8/8/8 | "m2browning" | 800
5 skill, 10/8/8/8 | "american_180" | 0
5 skill, 10/8/8/8 | "calico" | 50
5 skill, 10/8/8/8 | "m249" | 90
5 skill, 10/8/8/8 | "m4a1" | 125
5 skill, 10/8/8/8 | "ak47" | 270
5 skill, 10/8/8/8 | "m2browning" | 375
10 skill, 14/14/14/14 | "american_180" | 0
10 skill, 14/14/14/14 | "calico" | 20
10 skill, 14/14/14/14 | "m249" | 50
10 skill, 14/14/14/14 | "m4a1" | 65
10 skill, 14/14/14/14 | "ak47" | 150
10 skill, 14/14/14/14 | "m2browning" | 225

EDIT: Sample numbers and new recoil/handling

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
>Removed weird 5x multiplier applied silently to effective recoil. 
Kevin mentioned that is is some kind of scaling.

https://github.com/CleverRaven/Cataclysm-DDA/pull/27184
https://github.com/CleverRaven/Cataclysm-DDA/pull/27184#pullrequestreview-186785530
>That adjustment makes recoil the same as it was before rescaling dispersion. It is not an oversight.
If you want to fix it, you need to come up with a per-shot recoil number that makes sense, not just drop it by an arbitrary factor.

No, I dont fully understand it either. But it has some meianing.

**Comment by Firestorm01X2** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/27184#issuecomment-448917813
>It is temprary until a more nuanced rebalance can be applied. If you want to dig in and figure out whst that balance should be, feel free, but its the same kind of thing as the previous ranged balance, it's currently a fairly arbitrary number, but if you want to change it, it needs to be replaced with a non-arbitrary number.

**Comment by Coolthulhu** [comment]
Well, now it's not needed, because it roughly coincided with the weight/strength bonus of a 2.5kg weapon used by 8 str character.

**Comment by TrainTurningPoint** [comment]
I feel like a counter-nerf might be in order.
Last time I checked, aut cost of a burst was the same as the cost of a single shot.
It was _balanced_ by the fact nobody ever uses burst except for A7, but now that might be a problem. A machine gun with 50-round bursts and fixed recoil costing only 0.15 turns might be a bit too much.

Maybe add some movement cost depending on the burst size.

**Comment by Coolthulhu** [comment]
> A machine gun with 50-round bursts and fixed recoil costing only 0.15 turns to shoot might be a bit too much.

It would be incredibly inefficient to ever use it. Bursts aren't stopped early and bursts don't redirect, so you'd have to spend 50 rounds to wreck just one thing.
I'll probably want to rebalance the minigun later, because that 50 round thing makes it useless, and its accuracy is currently very poor unless you mount it on a vehicle and activate hydraulics.

Other guns cap at 6 shots, except for mech gatling laser. The recoil between bursts should keep things sane.

**Comment by TrainTurningPoint** [comment]
@Coolthulhu 
One can limit ammo consumption by only partially loading it. And while it might not be efficient ammo-wise, it would be pretty much a "delete this" button, almost instantly obliterating any opponent. 
Although maybe that's fine for a minigun.

**Comment by TheGrimMeeper** [comment]
Burst isn't actually that bad right now, with a properly built gun I can get three out of four hits pretty regularly. This right here seems like way too much of a buff, especially considering how plentiful ammo is. The mechanics could definitely use work (strength playing more of a factor is nice) but IMO burst fire only needs minor buffing if any.

**Comment by Coolthulhu** [comment]
> Burst isn't actually that bad right now, with a properly built gun I can get three out of four hits pretty regularly.

I'm mostly trying to buff light weapon bursts. The rifle caliber bursts may actually be nerfed here.

**Comment by Firestorm01X2** [comment]
> I'm mostly trying to buff light weapon bursts. The rifle caliber bursts may actually be nerfed here.

What about LMGs that locked to burst fire without other option? They are quite heavy.

**Comment by Coolthulhu** [comment]
> What about LMGs that locked to burst fire without other option?

Those suck a bit right now. They did it before as well, but they got the first good shot, now they have 4 crappy ones.
They're still usable with a bipod.

The options I see are:
* Buff the now-bad weapons by increasing their handling
* Have the formula give some leniency to burst-only weapons (hacky)
* Rework the penalty formula. Less skill-heavy, more dependent on... well, on what?
* Come up with some different penalty for large calibers. There is currently an aim speed cap based on volume, but that's ugly, hidden, not related to caliber

**Comment by Firestorm01X2** [comment]
> 
> 
> > What about LMGs that locked to burst fire without other option?
> 
> Those suck a bit right now. They did it before as well, but they got the first good shot, now they have 4 crappy ones.
> They're still usable with a bipod.
> 
> The options I see are:
> 
>     * Buff the now-bad weapons by increasing their handling
> 
>     * Have the formula give some leniency to burst-only weapons (hacky)
> 
>     * Rework the penalty formula. Less skill-heavy, more dependent on... well, on what?
> 
>     * Come up with some different penalty for large calibers. There is currently an aim speed cap based on volume, but that's ugly, hidden, not related to caliber
There is other option- make sure that bipods and mounted wepons has generally good burst shots. It may be even logical that LMGs only effective on bipods or then mounted. Or if player has insane strength.

**Comment by mrkybe** [comment]
Why are there weapons that can only burst fire?

**Comment by Firestorm01X2** [comment]
> Why are there weapons that can only burst fire?

It is about Light Machine guns or Heavy machine guns. Only burst modes represents that this weapon has very high fire rate so shooter physically can't just shoot single shots.

**Comment by Coolthulhu** [comment]
Could use some opinions:
What would be the maximum penalty for burst to still be useful? In units like "chance to hit%" or relative to dispersion from other sources. Can depend on gun/caliber.

My current implementation of burst penalty is: `recoil / ( skill + ( strength / 2 ) )`
It results in penalty comparable to gun's dispersion (after skill scaling).

**Comment by Firestorm01X2** [comment]
@Coolthulhu could ad test for LMGs on bipods? It is intresting case.

**Comment by Firestorm01X2** [comment]
For addtional info let me post this:
```
std::vector <int> Creature::dispersion_for_even_chance_of_good_hit = { {
        1731, 859, 573, 421, 341, 286, 245, 214, 191, 175,
        151, 143, 129, 118, 114, 107, 101, 94, 90, 78,
        78, 78, 74, 71, 68, 66, 62, 61, 59, 57,
        46, 46, 46, 46, 46, 46, 45, 45, 44, 42,
        41, 41, 39, 39, 38, 37, 36, 35, 34, 34,
        33, 33, 32, 30, 30, 30, 30, 29, 28
    }
};
```
It is dispersion for reaching effective range. So to reach effective range of 1 tile dispersion must be 1731
For 2 tiles 859 and so on.

**Comment by Coolthulhu** [comment]
> could add test for LMGs/HMGs on bipods?

Tested on 5 skill, 10/8/8/8 dude.
M2 Browning required adding the "add underbarrel slot" mod first because it doesn't have it by default.

Gun | Penalty
---|---
"m249" | 37
"m240" | 92
"m2browning" | 163
"m1918" | 165

> It is dispersion for reaching effective range. So to reach effective range of 1 tile dispersion must be 1731

It's very approximate and not that good at measuring

**Comment by Firestorm01X2** [comment]
> 
> 
> > could add test for LMGs/HMGs on bipods?
> 
> Tested on 5 skill, 10/8/8/8 dude.
> M2 Browning required adding the "add underbarrel slot" mod first because it doesn't have it by default.
> Gun 	Penalty
> "m249" 	37
> "m240" 	92
> "m2browning" 	163
> "m1918" 	165
> 
> > It is dispersion for reaching effective range. So to reach effective range of 1 tile dispersion must be 1731
> 
> It's very approximate and not that good at measuring

Thank you! So bipods more than halves recpoil. That is noticable.

And finally. About UI. It is not going to inform about changing chance to hit in bursts without reworking obviosly. And since even firts shot of the burst even affected by penalty- it may be somewhat misleading now. Just thing to consider.

Maybe first shot without penalty may stay?

**Comment by Coolthulhu** [comment]
> It is not going to inform about changing chance to hit in bursts without reworking obviosly.

Already done.
When you switch modes, you see the dip in accuracy.

**Comment by Firestorm01X2** [comment]
> When you switch modes, you see the dip in accuracy.

Then everything looks great. Thank you.
Still I am interested on why first shot uses penalty. Balance decision?

**Comment by Coolthulhu** [comment]
> Still I am interested on why first shot uses penalty.

?
All shots have the penalty.

**Comment by Firestorm01X2** [comment]
> ?
> All shots have the penalty.

Ops. I read it wrong. Everything is fine. It is working as expected.

**Pull request merged**
