### PR TITLE
Recipes make more use of other fabric and leather options for handle or backing components

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Balance "Make more use of alternative fabric and hide materials in recipes"

#### Purpose of change

This implements some crafting qualities for expanded use of fabric and faux fur in some recipes, letting some of the more underused materials have alternative uses for stuff like handle wraps or other cases where it doesn't impact what the end item would logically be made out of.

#### Describe the solution

1. Removed leather from `fabric_standard` requirement and clarified its usage. Idea is mainly if it's used for hand wraps, as part of a clothing item that isn't likely to be structurally important nor the main reason behind its item material, or if the recipe already sets the precedent for allowing leather as an alternative to something that comes out made of cotton.
2. Defined `fabric_hides_any` and `fabric_hides_proper` requirements. The former is for when faux fur is good enough to swap in, the latter is for leather armor type stuff where it has to be real hide but having to shave off some fur doesn't matter.
3. Phased in use of `fabric_standard` and `fabric_hides_any` for certain parts of animal armor.
4. Phased in use of `fabric_standard` and `fabric_hides_proper` for relevant armor recipes, and `fabric_hides_any` for a couple cases of non-protective uses. Main examples are for uses in survivor suit related items (except survivor clothes), medieval armor, chitin armor, and knee/elbow pads (which already allowed leather in place of cotton). Also includes some updates to some weird recipes for storage items, including standardization of material uses for pouch items and some updates to the bindle recipe (since it's a recipe that doesn't involve sewing).
5. Also covered usage of it in other folder.
6. And finally the weapon folder, making more use of the relevant requirements in handle materials mostly.

To still be done: Apply to/check on electronic, food, other, and weapon folders. Extensive use of the new requirements pus cured hides/pelts expected for weapon handles.

#### Describe alternatives you've considered

1. I noticed that bronze weapons allow rags, felt patches, and some other makeshift options. We could allow that for more handle wrap options in other recipes maybe.
2. I think DDA may have done something in this vein too, porting that over is also an option depending on how they did their material selection.
3. Allowing cursed hides/pelts for grip materials too.

#### Testing

1. Checked affected files for syntax and lint errors.
4. Load-test in compiled test build.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Possibly divisive issue: it will allow transmutation to cotton/leather in current form, at least for items that are cuttable.
This defeats the point of having faux fur be a separate option, since any leather item crafted from it will still have "leather" as the material.

**Comment by chaosvolt** [comment]
> Possibly divisive issue: it will allow transmutation to cotton/leather in current form, at least for items that are cuttable.
> This defeats the point of having faux fur be a separate option, since any leather item crafted from it will still have "leather" as the material.

I can go back and make sure it's not used for any items that actually use cotton or leather in the end material, sure.

**Comment by chaosvolt** [comment]
Removed `fabric_standard` from the light survivor items which have cotton in their material, while retained it for survivor suit variants where use of rags wasn't reflected in the item material.

One point of uncertainty though: most of the ammo pouch items already allowed the choice of rags versus leather patches, yet output would be specifically cotton or leather. Same applies to elbow and knee pads.

Adding `NO_SALVAGE` to those items in particular and making them all either reversible might be good, especially since a lot of them use other storage items in the recipe and salvaging them would likely lose materials in the process anyway. Same might go for survivor armor in fact, as cutting them up wastes a ton of materials you could be getting from the component items.

**Comment by chaosvolt** [comment]
And fixed merge conflicts on this.

**Review by Firestorm01X2 — APPROVED** [review]
Ready.

**Pull request merged**
