### PR TITLE
Remove bad ref

### PR DESCRIPTION
**Pull request by joveeater**
#### Summary

SUMMARY: Bugfix "Fix broken builds"

#### Purpose of change

Fix the msvc.

#### Describe the solution

Fix fix fix.

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]

**Comment by scarf005** [comment]
would it be that all these references were unsafe or MSYS2 is making false-positives?

**Comment by Qrox** [comment]
> would it be that all these references were unsafe or MSYS2 is making false-positives?

Probably a GCC13 bug, see CleverRaven/Cataclysm-DDA#65449.

**Comment by scarf005** [comment]
thank you! in that case, we should follow DDA's solution and disable the warning.

**Comment by joveeater** [comment]
Yeah, most of these are junk and we will need to disable this warning in the end. That said, some of them are correct. So I'm gonna go through and "fix" them all and keep track of which ones really need fixing. So far it's just the string_util ones that have been an actual problem but I want to go through them all.

**Comment by joveeater** [comment]
Alright that's all of them. It was only string utils that's a problem.

**Pull request closed without merging**
