### PR TITLE
feat(content): Cabin lockers can spawn guns

### PR DESCRIPTION
**Pull request by Lamandus**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
Cabins now have a rare chance to spawn guns. Why locker? Because sometimes when you life in the woods, you don't care for having a fancy gun safe. Who should come and try to steal it, right?

Spawnchances:
10% for a rifle (with ammo, etc)
5% for a shotgun
1,6% for a pistol

## Describe the solution
1. Add new group locker_cabin. It has guns (rifles/shotguns/pistols) and/or tools, it have a slim chance for a gun mod.
2. Move all storages for guns in itemgroup into own file.
3. Add locker_cabin to the cabin palette.

## Testing
Should work as intended.

### CODE REVIEW

**Comment by Lamandus** [comment]
I don't know why it fails... strange.

**Comment by Lamandus** [comment]
or not.

**Comment by Lamandus** [comment]
I am out of ideas of why it is not building.

**Comment by Lamandus** [comment]
@scarf005 @chaosvolt , can you check why it is not working? I am out of ideas.

**Comment by Lamandus** [comment]
had to log in into my account on git desktop, maybe that will help

**Review by chaosvolt — APPROVED** [review]
All I saw was an unreleated random test failure, the change itself is aight. Tying this to specific lockers might be better but can tinker with this whenever I get around to implementing rural gun itemgroups.

**Pull request merged**
