### PR TITLE
Voltmeter & pH meter rebalancing

### PR DESCRIPTION
**Pull request by RoyalFox2140**
## Summary

SUMMARY: [Balance] "Voltmeter & pH rebalancing"

## Purpose of change

Voltmeters are much smaller IRL and I think it belongs on a toolbelt. I added the "BELT_CLIP" flag so it can be put on a toolbelt so it won't be lost easily. I also toned down its size and weight to suggestions on the discord. pH meters are also much smaller IRL, and it was suggested by Chaosvolt to change that in the same PR as well.

## Describe the solution

I added the "BELT_CLIP" flag. It can now be on a toolbelt. Also, it is 500 grams 750mL as real life examples follow this size.
Chaosvolt changed the pH meter stats to also be more reflective of the real world.

## Describe alternatives you've considered

Losing my voltmeter in a lake.

## Testing

Loaded game, game worked. Voltmeter can be placed in toolbelt. It works.

## Additional context

image
image

### CODE REVIEW

**Review by scarf005 — DISMISSED** [review]
interesting, both tool belt and webbing belt cannot store voltmeter because for some reason voltmeter is 1.5L and 3kg.

**Comment by RoyalFox2140** [comment]
> interesting, both tool belt and webbing belt cannot store voltmeter because for some reason voltmeter is 1.5L and 3kg.

Whoops I should've tried it with the toolbelt and not my modded holsters. We should add XL toolbelts in another PR with greater encumbrance and storage.

**Comment by RoyalFox2140** [comment]
@scarf005 As per @chaosvolt suggestions, the voltmeter is more realistically sized at 500 grams 750 mL I have made said change and I will update PR description.

**Review by chaosvolt — APPROVED** [review]
1. Ported changes over to test build.
2. Spawned in a voltmeter and tool belt.
3. Can put it in the belt.

image

**Pull request merged**
