### PR TITLE
fix: `magic_light` throwing `wind_resist` error

### LINKED ISSUE #2518: Magiclysm mod magic light error popup.
### Describe the bug
```
 DEBUG    : Called item::wind_resist on an item (<color_c_light_green>|| </color>magic light (997 turns) [magic_light]) made of nothing!

 FUNCTION : wind_resist
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\item.cpp
 LINE     : 6774
 VERSION  : BN 0.2
```

### Steps To Reproduce

Cast magic light with the magiclysm mod
error pops up

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 0.2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    No Fungal Monsters [No_Fungi],
    Craftable Gun Pack [craftgp],
    Magiclysm [magiclysm]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chrsrns**
Adds a new material `contentrated_mana`.
Adds a material field on `magic_light` entry containing `concentrated_mana`.

## Purpose of change

Fixes #2518.

## Describe the solution

Done by adding a new material `concentrated_light` which `magic_light` can use. The values were adapted from DDA's `concentrated_mana` material entry.

## Describe alternatives you've considered

None.

## Testing

1. Cast spell `Magical Light.
2. Move to see if the error pops up.

### CODE REVIEW

**Comment by Lamandus** [comment]
you need to correct the title, it cut it in half.

**Comment by scarf005** [comment]
image
also please note that [it's dangerous to directly commit on `main` branch](https://docs.cataclysmbn.org/en/contribute/contributing/#guidelines); it's recommended to work on a separate branch.

**Comment by chrsrns** [comment]
> image also please note that [it's dangerous to directly commit on `main` branch](https://docs.cataclysmbn.org/en/contribute/contributing/#guidelines); it's recommended to work on a separate branch.

Sorry I honestly didn't think to read the guidelines first. Would I need to open a new pull request?

**Comment by chrsrns** [comment]
> also please note that [it's dangerous to directly commit on `main` branch](https://docs.cataclysmbn.org/en/contribute/contributing/#guidelines); it's recommended to work on a separate branch.

Sorry I honestly didn't think to read the guidelines first. Would I need to open a new pull request?

**Review by chaosvolt — APPROVED** [review]
Note that it's usually just that not creating a separate branch for your PRs means you're stuck working on one thing at a time until the current PR is merged, but every so often it causes some weird obscure problem because github is weird. Assuming that doesn't happen it should be fine, just good to remember to create a branch next time just in case. :3

**Pull request merged**
