### PR TITLE
feat(balance): percentage-based resistance for active power armor

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

This was something @Coolthulhu requested, noting that while making power armor less of a pain to find and use may be a good thing, the passive armor values are so high that you're basically immune to everything in even light power armor, and suggested the use of percentage-based damage reduction as a way to potentially make it more balanced.

The direction I went with, after some reworking, was to try to target a combination of material thickness and percentage damage reduction that'll render most rifle rounds survivable but still deal scratch damage through the armor.

## Describe the solution

1. Implemented an enchantment for power armor to use that cuts stabbing and balllistic damage by 80%, and an active-only version for RM13 armor.
2. Added the above enchantment to power armor and power armor helms, including salvaged power armor.
3. Reduced the base material thickness of power armors to compensate. Now against most rifle rounds they'll consistently deal low but survivable damage as opposed to being useless against higher-tier rifle rounds. There's still some tiering here though, both light and medium power armor will still take grievous wounds from .50 BMG, medium power armor takes no damage from 5.56, and heavy power armor gains immunity to 7.62 while reducing .50 BMG to annoying but survivable.
4. Reworked descriptions of power armor to clear out some clunky bits that imply you can't fit through doors in power armor (it doesn't make you count as Large so not true).
5. Made sure salvaged power armor's passive protection isn't higher than what light power armor has now.
6. Added the active-only version of the enchantment to RM13 armor, and reduced active version's thickness by a layer so its ballistic stat is close to that of light power armor.
7. Per feedback, set it so that power armor only gets its maxed-out EP when active, and reduced EP of salvaged power armor to no longer be reliably immune to smoke.

## Describe alternatives you've considered

1. Reworking things to balance around it instead negating bullets but only when active, like what RM13 now does but up to 11. This is basically what I did at first because it felt easier to balance, but Coolthulhu insisted I try to make it work tolerably as a pure passive bonus.
2. Lowering bash resist of layered carbide a bit to increase vulnerability in general melee.
3. Making it so salvaged power armor doesn't get the enchantment.

## Testing

1. Spawned in light power armor. Takes around 5 damage from 5.56, around 10 damage from 7.62, and around 20 damage from .50 BMG.
2. Spawned in medium power armor. No longer takes damage from 5.56, takes about 5 damage from 7.62, still takes about 20 damage from .50 BMG.
4. Spawned in heavy power armor. Immune to 5.56 and 7.62, takes about 10 damage from .50 BMG.
5. Tested RM13 armor. While active it performs similar to light power armor.

## Additional context

Mood: https://www.youtube.com/watch?v=asdKLrtm6gw

Power armors (depowered, light, medium, heavy, and active RM13 respectively) before:
before 1
before 2
before 3
before 4
image

Power armors (depowered, light, medium, heavy, and active RM13 respectively) after:

image

Things that could also be done, as related PRs I maybe oughta work on:
1. Porting over https://github.com/CleverRaven/Cataclysm-DDA/pull/64119 will allow the enchantment to show on the item screen, making it more obvious to the player that their ballistic protection stat isn't the only thing protecting them.

### CODE REVIEW

**Comment by scarf005** [comment]
image
[conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) are case sensitive, made it lowercase.

**Comment by Coolthulhu** [comment]
I'd much prefer it to be visible to the player ASAP, but other than that, looks good.

Holy shit enchantment code is so unintuitive. "ARMOR_x" multiplier is actually a multiplier on "bonus to damage received" and defaults to 0.
So the damage formula CHANGE from enchantment looks like this:
```C++
damage_from_enchant = get_value_flat( ARMOR_CUT ) + incoming_damage * get_value_mult( ARMOR_CUT );
final_damage = incoming_damage + damage_from_enchant;
```

Whose idea was it to name anti-armor "armor"?

**Comment by chaosvolt** [comment]
> Whose idea was it to name anti-armor "armor"?

@korggent's enchantment code in a nutshell. So in that case, I'll start work on porting over the visible enchantments code in a bit.

**Comment by chaosvolt** [comment]
Realization: I've been using `ARMOR_X` which applies damage resistance to the entire body, not `ITEM_ARMOR_X` which applies it to just the body parts covered, lemme mark this as draft while I re-test to ensure the intended damage negation still happens.

Will likely also implement some form of UI change that will make armor modification from enchantments visible too, dunno if it'll be in the form of porting that PR or more direct UI code just yet, will see what's easier.

**Comment by chaosvolt** [comment]
So I'm looking into the code here, and the big problem is that percentage-based damage reduction basically HAS to be applied in the same step as all the other armor calculations. This doesn't really make it feasible to implement Coolthulhu's idea of "all bullets will deal scratch damage" because what reduces one tier of bullet down to scratch damage will still be a hard counter to a weaker bullet, while also letting much higher damage values through.

Only real option to make that work as intended would be if I really nerfed the hell out of the armor's ballistic values and then applied a much higher damage resistance enchant. That would basically mean that most if not all bullets are being reduced down to basically no damage and then still being high enough to mostly ignore the armor's ballistic protection.

**Comment by chaosvolt** [comment]
Okay did get the outcome expected so far, now had been a bit stumped on the UI issue. If I get time tomorrow might look at it more but not yet sure what the best method is:
1. Porting the enchantment reveal code. Main issue I see with that is, looking at it, some of the code divergences here are likely to make porting it a hassle, plus it's a fair bit more complex than it needs to be. It wastes several lines of space for what functionally doesn't need to be much more complex than what flag descriptions are.
2. Figuring out how to directly add it to the UI via checking `get_value_multiply` and feeding it to armor UI right above protection values. The hard part is, what'd be the most elegant way to go "if active enchantment matching this value is found to be non-zero, print this extra line" for the sake of displaying said info?

**Comment by chaosvolt** [comment]
Closed in favor of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3758 for the time being.

**Pull request closed without merging**
