### PR TITLE
Port body part code from DDA up to May 4

### PR DESCRIPTION
**Pull request by Coolthulhu**
No new features, but it will be useful in the future.
DDA code all by Fris0uman, plus some BN-specific fixes from me.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Question: does this only affect the bodypart IDs of CBMs and mutations, or is clothing affected too? Recent test revealed that CBMs seem to now consider the DDA-style lowercase ID to be required or else it'll fail to recognize, would need to make sure what all I'll need to fix for third-party mods besides CBMs.

**Comment by Coolthulhu** [comment]
> Recent test revealed that CBMs seem to now consider the DDA-style lowercase ID to be required or else it'll fail to recognize, would need to make sure what all I'll need to fix for third-party mods besides CBMs.

Clothing has one ugly edge case at the moment: you need uppercase for one-side items.

**Comment by chaosvolt** [comment]
> Clothing has one ugly edge case at the moment: you need uppercase for one-side items.

That's what I was suspecting yeah, since DDA defines switchable items in a very different way. For now it looks like CBMs are the only case where lowercase BP IDs are mandatory now, but I'll try to keep an eye on things and update third-party mods accordingly.

**Comment by Coolthulhu** [comment]
> That's what I was suspecting yeah, since DDA defines switchable items in a very different way.

I'll want to port it since it's next to trivial. It's just not done yet, since I didn't want to bundle it with ports.

**Comment by chaosvolt** [comment]
No worries, hope it goes well.

**Pull request merged**
