### PR TITLE
Update  MSX++UnDeadPeopleEdition

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Update  MSX++UnDeadPeopleEdition
Updated from here:
https://github.com/SomeDeadGuy/UndeadPeopleTileset

#### Summary
SUMMARY: Content "Update  MSX++UnDeadPeopleEdition"

#### Purpose of change
Update  MSX++UnDeadPeopleEdition
Zombie nurses included!

screenshot 2020-10-05 001ded

#### Describe the solution
Update tileset.
**Warning!**
I have to edit 
`NAME: UNDEAD_PEOPLE_BASE `
to
`NAME: UNDEAD_PEOPLE`
in tileset.txt
as it was before in BN to avoid bothering people with switching tilesets after update

#### Testing
1) Make sure that tileset selected
2) Game load in works with MSX++UnDeadPeopleEdition

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
**Warning!**
I have to edit 
`NAME: UNDEAD_PEOPLE_BASE `
to
`NAME: UNDEAD_PEOPLE`
as it was before in BN to avoid bothering people with switching tilesets after update

**Comment by Coolthulhu** [comment]
The diff shows a ton of deletions and very little additions. Are you sure this PR contains the actual tileset?

**Comment by Firestorm01X2** [comment]
> 
> 
> The diff shows a ton of deletions and very little additions. Are you sure this PR contains the actual tileset?

I'll check again. 
But it is working. I've load my pevious save and teleported into city. No issues.

**Comment by Firestorm01X2** [comment]
Looks like it is it:
https://github.com/SomeDeadGuy/UndeadPeopleTileset
>UNDEAD_PEOPLE (NEW VERSION) - latest updated version of the tileset. On **it's own it only covers main game** and do not supports any mods (which comes with the game or located in other places). T**o get graphics for mods you will need to enable mods with the same name** as mod what are you going to use plus "- UndeadPeople Tileset" in it's name under "graphical" category.

>UNDEAD_PEOPLE_LEGACY - old version of the tileset. It does supports mods out of the box like before, but is no longer updated due problems with performance.

**Pull request merged**
