### PR TITLE
standardise chitin armor crafting levels, adding leather.

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY:  Balance "standardise chitin armor crafting levels, adding leather."

#### Purpose of change
Chitin armor is quite good. It has only the caveat of being 95% coverage, which makes it a bit worse than a survivor suit. So it shouldn't be harder to craft than it counterpart.
The armor made of acid ants also got a little faster to craft.
All parts of the armor is now unlocked in the same time. So all chitin parts are available at lvl 6 instead of being spread between different levels.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
The weird thing about chitin armor is that it is made from just two ingredients, one of which is ultra common and other is not really uncommon. Kill ant, weave grass, suddenly armor. This makes it looks more like a lvl 4 recipe than lvl 6, except for good stats on the result.
Would be good if there was some secondary component to make antgrass armor less about grinding ants/roaches and more about adding some ants to some base, like lammellar armor.

How about:
* Skill level down to 5 (maybe 4?)
* Half of chitin cost replaced with leather. Or even get inspiration from real lamellar armors: allow cured hide in place of leather
* Change arm guards to tailoring, because everything else is

**Comment by Lamandus** [comment]
adding leather lead to following change of values (and raising thickness as well)
old:
image
new:
image

**Comment by Coolthulhu** [comment]
Issue: now that it uses leather, it should involve proper sewing, not grass cordage.

**Comment by chaosvolt** [comment]
This might be one of the few cases where the awl tools inherited from the half-finished sewing rework would have a valid use, were we to want to retain the use of cordage.

**Pull request merged**
