### PR TITLE
feat: redirect damage dealt to broken limb into torso

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: Features "Redirect damage dealt to broken limb into torso"

#### Purpose of change

melee with NPCs are tiresome because their broken limbs act as shield with infinite durability. 

#### Describe the solution

redirect some of the damage to torso. when limb hp
- is lower than 15% hp, 1/4 of the damage is split to torso.
- is 0% hp, it will send 50% of the damage to torso.

numbers are arbitrary and may be adjusted.
also add message so player know how much damage is inflicted.

#### Describe alternatives you've considered

it's 2:37am and i can't think clearly. maybe use random?

#### Testing

spawned a npc and whacked them.

### CODE REVIEW

**Comment by KheirFerrum** [comment]
Would probably be better if we could figure out how the hell they're blocking with broken arms.

**Comment by scarf005** [comment]
> Would probably be better if we could figure out how the hell they're blocking with broken arms.

actually they can't block with broken limbs. https://github.com/cataclysmbnteam/Cataclysm-BN/blob/9fc83b65af76cda0cde8aff177d76dea6d739ec6/src/melee.cpp#L1665-L1670 it's just that most of the time the part that gets hit is arms and legs and they sock up damage indefinitely

**Comment by KheirFerrum** [comment]
> > Would probably be better if we could figure out how the hell they're blocking with broken arms.
> 
> actually they can't block with broken limbs.
> 
> https://github.com/cataclysmbnteam/Cataclysm-BN/blob/9fc83b65af76cda0cde8aff177d76dea6d739ec6/src/melee.cpp#L1665-L1670
> 
> 
> it's just that most of the time the part that gets hit is arms and legs and they sock up damage indefinitely

Actually I think there's a bigger issue.

**Comment by scarf005** [comment]
looks like #2535 handles the issue better than this PR.

**Pull request closed without merging**
