### PR TITLE
feat: install wind turbines to produce grid electricity

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
We have wind turbines for vehicles, but not for our own grid system. This allows the placement of wind turbines near our bases to produce electricity.

## Describe the solution
1. Add construction for normal and xl turbine.
2. shallow pit are needed for both (like the wind mill), to make it outside only and as a use for a "pseudo" foundation.
3. uses same sprite as the wind mill (since we don't have a good alternative yet)
4. a regular wind turbine produces constant power, since the wind itself can't be used to be calculated for furniture.
5. the amount of power for one regular windmill is the same as the consumption of 1 fridge
6. xl version generates the same energy as 2,5 fridges

## Describe alternatives you've considered
Creating a convoluted source code to make it really depend on wind. On the other hand, it will just be realism for realism sake.

## Testing
Wind turbines produce electricity as they should.

## Additional context
grafik

### CODE REVIEW

**Comment by chaosvolt** [comment]
Now that I'm looking at it, I wonder if it'd be feasible to crib code from `iexamine::quern_examine` to make proper functioning windmills. Even so I guess it could be made as a followup to this...

**Comment by Lamandus** [comment]
> Now that I'm looking at it, I wonder if it'd be feasible to crib code from `iexamine::quern_examine` to make proper functioning windmills. Even so I guess it could be made as a followup to this...

I don't follow. Wind mills are already properly working? I only made wind turbines working on grid

**Comment by chaosvolt** [comment]
Typo on my part, I meant we could later on take the way windmills check for proper conditions and use that for wind turbines.

**Review by scarf005 — APPROVED** [review]
image

**Comment by Lamandus** [comment]
> Typo on my part, I meant we could later on take the way windmills check for proper conditions and use that for wind turbines.

windmills have a hard set timer for milling, they don't use wind as calculation, as far as I read it right.

**Comment by chaosvolt** [comment]
> windmills have a hard set timer for milling, they don't use wind as calculation, as far as I read it right.

The main thing I was looking at was they have a function call that we'd likely want to check for in the future, `is_sheltered`: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/main/src/iexamine.cpp#L5780

So basically in the future we could rig it so that wind-powered grid furniture can be set to check `is_sheltered` and if true, not put out power. Likewise for water wheels, right above is a function used for that called `is_water_shallow_current`.

**Pull request merged**
