### PR TITLE
feat: residential front lawn nested chunks

### PR DESCRIPTION
**Pull request by LilShiningMan**
## Purpose of change
Add nested chunks for residential front lawn features. This will make for more dynamic,  more interesting house spawns.

## Describe the solution
Create nest container for residential front lawns. Currently there are only 2 variants, to make it easier to review. More will be coming in the future. Using this nest container will make it easy to add more variants down the road without updating individual house files, and also control global spawn rates of variants.

## Describe alternatives you've considered
Not adding these and letting houses be more stagnant.

## Testing
linted file and spawned both variants in-game.

## Additional context

These two chunk variants aren't overly exciting on their own, but with more variants added, I think this could be more interesting overall than having set map features for specific houses.
frontlawn-bbath
frontlawn-stump

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]
:D

**Comment by chaosvolt** [comment]
wha

**Comment by chaosvolt** [comment]
Why'd you close and delete it, it wasn't merged yet?

**Comment by LilShiningMan** [comment]
Oh no! oops. Thought it was successfully merged

**Comment by chaosvolt** [comment]
approval =/= merge

I was gonna wait and make sure all the tests passed just in case I missed something, just to be safe :<

**Comment by LilShiningMan** [comment]
2 PRs and 2 mistakes today. Github isn't my strong suit

**Pull request merged**
