### PR TITLE
feat(content): Added a furniture type overhead light

### PR DESCRIPTION
**Pull request by Skas8825**
### Required

- [ ] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [ ] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
The overhead light tile in the refugee center is not buildable making the currently avaible options to light a room with electricity standing lamps or similar furniture.

## Describe the solution
Added a furniture type overhead light that the player can build to imitate the refugee center lighting style.

## Additional context
image

### CODE REVIEW

**Comment by Skas8825** [comment]
I named it install ceiling lamp at one point i think, i changed for consistency between the id's, though i could change it back.

About electronics 0 idk, i just copied the skill requeriments from the standing lamp and the stepladder requeriment is so the player needs to use a stepladder (-1 is the charge consumed and the stepladder doesn't have )



> I'd suggest calling it a "ceiling lamp" instead of an "overhead light".

I named it install ceiling lamp at one point i think, i changed for consistency between the id's, though i could change it back.

> Also in the construction recipe you put in `"electronics", 0` as a skill requirement, and `"stepladder", -1` as a tool, which doesn't seem quite right.

About electronics 0 idk what's the purpose, i just copied the skill requeriments from the standing lamp.
 And the stepladder requeriment is so the player needs to use a stepladder (-1 is the charge consumed and the stepladder doesn't have any), i don't know if theres another way of adding the stepladder as a requeriment without qualities.
 
In the end the recipe looks like this:
image

**Comment by Skas8825** [comment]
I changed the name to ceiling lamp 👍.

**Comment by Proxiehunter** [comment]
I'm not sure how to find this information in the files, I tried looking but I don't see anything that jumped out as giving this information. I just want to make sure that it requires there to be a _roof_ and you can't just install this light in the sky as long as you have a floor (which I _did_ see in the json when I looked last night) and a ladder.

**Comment by Skas8825** [comment]
> I'm not sure how to find this information in the files, I tried looking but I don't see anything that jumped out as giving this information. I just want to make sure that it requires there to be a _roof_ and you can't just install this light in the sky as long as you have a floor (which I _did_ see in the json when I looked last night) and a ladder.

I set it to look for the "INDOORS" flag on the terrain, it also says that in the screenshot i send fo the recipe.

**Review by chaosvolt — DISMISSED** [review]
Looks good I think. Having to tie the construction to the `INDOORS` flag is definitely annoying but not many other good options currently.

If at some point I get around to adding support for a construction function that lets it check that the tile above isn't empty, I'll convert this recipe to use that function, but for now this works well enough.

**Review by chaosvolt — APPROVED** [review]
:>

**Pull request merged**
