### PR TITLE
Adding combat skill Flag to dodging

### PR DESCRIPTION
**Pull request by Drugitechnik**
Summary

Bugfixes "Fix for Predator line of mutations"
Purpose of change

Fixing drop of focus while having predator mutation, which states that no focus loss should occur while fighting.
Describe the solution

Adding flag combat_skill to dodge, as dodging skill is one causing drop of focus while fighting.
With that tag dodging skill will no logner incur focus loss
Describe alternatives you've considered

changing description.
I considered addittional crafting failure malus for predator mutations as balancing measure.
Testing

Add mutation spawn monster check when focus loss occures.
Do same after changes.
Additional context

This change will affect Pacifists making them have slower training on dodging skill, I'm fully aware of that fact.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It also affects pacifist trait, which should train dodge normally. I assume that's the whole reason dodge wasn't given the tag before.

There should be some distinction between combat-defensive and combat-offensive.

**Comment by Drugitechnik** [comment]
Bonus exp is based on premise of enjoyment of fight.
Would pacifist enjoy being attacked?
From my testing and from information i read, this tag affects only combat exp, books still work normally, so dancing books would be unaffected.

**Comment by RelMayers** [comment]
Would this change fix #914?

**Comment by Drugitechnik** [comment]
Closed.
Keeping it as it is.

**Pull request closed without merging**
