### PR TITLE
korean `README.md`

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: I18N "add korean README.md"

#### Purpose of change

image

There is a community of Korean roguelike players, and providing language support for development resources could be an effective way to encourage their participation in BN.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
@scarf005 I recommend to use fancy pictures, like here:
https://github.com/jonatasemidio/multilanguage-readme-pattern

We most likely going to have more version or Readme in nearest future.

**Comment by Firestorm01X2** [comment]
@scarf005 I recommend to add "en" language shield to default readme as well  just like in example.

**Comment by scarf005** [comment]
...oh, alright. how should i do for other languages? e.g ko:

1. show both `ko` and `en` badge
2. only show `en` badge like in example

**Comment by Firestorm01X2** [comment]
> 1 feels easier to manage across languages.

Same thoughts. Let's do it that way.

**Pull request merged**
