### PR TITLE
Port over stamina modifier PR from DDA

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Features "Port over DDA PR making max stamina mutations affect stamina regen"

#### Purpose of change

Ports over a minor stamina-related PR that juuuust barely missed getting into BN due to being merged on the exact same day as the nested containers update.

#### Describe the solution

1. Added relevant changes to character.cpp causing max_stamina_modifier to affect stamina_multiplier.
2. Per discussion on the modder discord, changed point cost of Languorous.

#### Describe alternatives you've considered

Honestly, it'd be perfectly viable to do a JSON version of this by adding stamina regen modifier to traits that modify max stamina. More visible to people tweaking mutations, too.

#### Testing

1. Compiled and load-tested.
2. Started a character with Languorous.
3. Ran around, pulped zeds, etc to ensure no odd behaviors or errors cropped up.

#### Additional context

PR being ported over: https://github.com/CleverRaven/Cataclysm-DDA/pull/39994

Relevant excerpts for PR OP to explain rationale for change, and resulting impact of said changes:
> To normalize the time needed to recover stamina to 500 turns regardless of maximum stamina, and make certain traits make more sense in terms of time to recover stamina. Previously, languorous only needed 375 turns to recover all max stamina, and indefatigable required 625. Realistically, it makes no sense for an "unfit" person to recover faster than a "fit" person.

> This also affects walking stamina regeneration, where indefatigable would gain 10 stamina instead of 5, and languorous would be at 0 net stamina from walking. The numbers for walking emulate fit/unfit stamina more realistically this way. Sprinting and crouching are barely affected.

> Stamina regen are as follows:
> no mutation: 20 (net 5 stamina gain when walking)
> Languorous: 15 (net 0 stamina loss when walking)
> indefatigable: 25 (net 10 stamina gain when walking)

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Not sure if desirable.

**Comment by chaosvolt** [comment]
I'd guess it'd depend on one's thoughts on the discussion that was in the PR. One thing that did crop up was the issue where, in practice, characters with Indefatigable effectively regain full stamina slower than normal characters, and characters with Languorous recover full stamina faster than normal.

Personally that point seems more like a visual anomaly, but I agree the resulting outcome looks odd. Net effect of this change either way essentially makes Indefatigable more valuable and Languorous more punishing. This likewise led to discussion in the PR over whether that justifies changing their point costs, final answer they settled on ended up being not to change it.

Porting this PR over, porting it over while also changing point costs, mainlining the rebalance from Stamina Regen Buff mod, whatever shift seems best, if any.

**Comment by Firestorm01X2** [comment]
Well it it will not break any kind balance and made it more explainable to understand for players, then why not?

**Comment by Coolthulhu** [comment]
I noticed that stamina traits don't explain that they affect stamina regeneration.
It doesn't seem to be hinted anywhere else.
I think they should have an "and regeneration" somewhere in the description.

**Comment by chaosvolt** [comment]
That's another reason I find the source PR's hardcoded change to be a little odd. I'll go ahead and add that, then.

**Comment by chaosvolt** [comment]
Updated mutation descriptions for affect mutations, and added entries for `stamina_regen_modifier` and `max_stamina_modifer` in the mutation documentation, with the latter explaining that it implies `stamina_regen_modifier` as well. Had to write it up since DDA's version of JSON_INFO didn't have those documented either.

**Comment by chaosvolt** [comment]
Thank you for the merge.

**Pull request merged**
