### PR TITLE
feat: add construction of wind turbines on roofs

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
This adds the possibility to construct wind turbines on roofs. It require (imaginary) bolts and metal frames for securing it up there.

## Additional context
grafik

### CODE REVIEW

**Review by chaosvolt — COMMENTED** [review]
Uuuugh that looks hacky, you've got to specify multiple redundant construction entries for every possible variation of roofs and you didn't even get them all in the process. Plus this falls apart for any building that has outdoor floors instead of roof tiles.

**Comment by Lamandus** [comment]
> Uuuugh that looks hacky, you've got to specify multiple redundant construction entries for every possible variation of roofs and you didn't even get them all in the process. Plus this falls apart for any building that has outdoor floors instead of roof tiles.

which one did I miss? and yes, there is no good other way to deal with it, the hacky thing is something you can't circumvent. And there are rarely roofs with regular tiles. So that works out for now.

**Comment by Lamandus** [comment]
> Uuuugh that looks hacky, you've got to specify multiple redundant construction entries for every possible variation of roofs and you didn't even get them all in the process. Plus this falls apart for any building that has outdoor floors instead of roof tiles.

This is what happens if you use "copy-from":
image


There is no way to define an array of pre-terrains. If anyone can provide this kind of solution, I would use it, CV.

**Review by scarf005 — CHANGES_REQUESTED** [review]
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/596091331acc4bb55a32fae53e8f1d479464995a/doc/src/content/docs/en/mod/json/reference/json_info.md#L863

this PR adds many duplicate entries, maybe we could remove `pre_terrain` and replace it with `pre_flags`?

**Comment by Lamandus** [comment]
@scarf005   ```
 {
    "type": "terrain",
    "id": "t_flat_roof",
    "name": "flat roof",
    "description": "A flat, gray section of rooftop.",
    "symbol": ".",
    "looks_like": "t_concrete",
    "color": "dark_gray",
    "move_cost": 2,
    "flags": [ "TRANSPARENT", "FLAT" ],
    "bash": { "str_min": 30, "str_max": 210, "sound": "crash!", "sound_fail": "whump!", "bash_below": true }
  },
```

the problem is, we don't have a "hard roof" flag. Because a roof tag isn't enough, you shouldn't place it on a thatched roof

**Review by scarf005 — APPROVED** [review]
image

**Pull request merged**
