### PR TITLE
feat(balance): revamp throwing damage

### PR DESCRIPTION
**Pull request by scarf005**
image

(throwing rocks for 30 damage, and javelins for 70 damage @ STR 16, throwing 10)

### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

- fix #2571

## Describe the solution

made extra throwing damage proportional to strength and skill level. the formula for damage is:
```math
speed = \log_2\left(\max(1, \text{throwing skill level})\right) + \log_2\left(\max(1, strength)\right)
```
```math
damage = 0.5 \times \frac{\text{weight}}{1\ \text{kilogram}} \times speed ^2
```

## Testing

graph: https://www.desmos.com/calculator/eej5a9mzo2

extra throwing damage bonus for javelins at 1kg @ throwing 10 (x: strength)
| throwing 0 | throwing 5 | throwing 10 |
| :-: | :-: | :-: |
|image |image |image|

## Additional context

feel free to edit formula.

Todo in later PR: add quick-throw hotkey

### CODE REVIEW

**Review by chaosvolt — COMMENTED** [review]
While interesting, this does lead me to some things I'm not sure about:
1. How's this stack up against slings and other throwing-skill ranged weapons? If the baseline damage and range of buffed hand-thrown weapons outpaces the same rock from a sling then it probably wouldn't be ideal, especially when throwing can already potentially scale up to outpace throwing ranged weapons while they currently don't get any real damage or range scaling like they probably oughta.
2. By far in my experience the biggest issue with early-game throwing isn't the damage or range, it's the accuracy. You can't actually aim throwing like you can ranged attacks, so it's very hit-or-miss. And miss. And miss, and miss...this is most well-known with the whole "oops I exploded because that grenade I threw caught on the wall I'm standing next to and literally landed at my feet" issue.

**Comment by NobleJake** [comment]
I can tell the main difference between throwing with brute force and throwing with a device like a sling is stability and accuracy. Slings provide more consistent accuracy than hand throwing. In terms of stability, the sling still has the edge.

I would focus on "non-growable offense" rather than accuracy. Keeping throws stuck at a low damage output relegates them to being used only briefly in the early game. Despite the existence of items like throwing daggers, they're pretty much useless, as they're just a shiny new gimmick to say "hey, we have a throwing weapon". No matter how good you get at throwing, there's no growth potential - you can still bounce off a wall and have a throwing weapon land at your feet, but I want throws to at least have enough damage to be a mainstay in the late game.

**Comment by NobleJake** [comment]
@chaosvolt 

If the throwing system were to be overhauled to allow for strength proportional buffs, throwing equipment such as slings would need to change their damage mechanics to match.

I would focus on "non-growable offense" rather than accuracy. Keeping throws stuck at a low damage output relegates them to being used only briefly in the early game. Despite the existence of items like throwing daggers, they're pretty much useless, as they're just a shiny new gimmick to say "hey, we have a throwing weapon". No matter how good you get at throwing, there's no growth potential - you can still bounce off a wall and have a throwing weapon land at your feet, but I want throws to at least have enough damage to be a mainstay in the late game. In other words, wouldn't people be annoyed if an New England-alpha-supercybermutant with 20 Strength threw a rock and did single-digit damage?

**Comment by chaosvolt** [comment]
Fair enough, yeah. I just figure that we'd want to be careful about overtuning the damage scaling too much since buffing thrown ranged weapons to match will be harder, and I figured the baseline floor for throwing accuracy at low levels might be worth looking into.

**Review by chaosvolt — CHANGES_REQUESTED** [review]
1. Compiled and load-tested.
2. Set up a character with baseline stats and no skills.
3. Throwing range of a rock is 24 tiles, and base damage when tossed at a debug monster is 8-9. Compare a test I did on an earlier build where range was 16 and base damage was 7-8.
4. Tested a basic sling, range is 18 tiles and listed base damage is 13.
5. Set all skills to 10, range of hand-thrown rocks goes up to 32 and base damage against a debug monster becomes 15-16. Compare previous behavior being 16 range and 10-12 damage.

So, the damage is okay at level zero but as can be seen, hand-throwing a rock with no skills whatsoever dramatically outranges using a sling, and it only gets more extreme at max level. 

Long-term solution would be to make throwing ranged weapons take the stats of throwing the ammo by hand into account, but we can save that for another day. For now I'd say either sanity-check the range calculations a bit and/or increase the range bonuses of slings to compensate.

Also reminder: We really should also look at how it determines throwing dispersion at zero skill, and seeing whether we can afford to adjust it. In my experience "oops my grenade throw was off by 90 degrees and I clipped the wall next to me, guess I'll die" has traditionally been a far bigger obstacle to throwing than the damage or range. We can save this for a later PR if desired however.

**Comment by RoyalFox2140** [comment]
> So, the damage is okay at level zero but as can be seen, hand-throwing a rock with no skills whatsoever dramatically outranges using a sling, and it only gets more extreme at max level.

This is an ammunition issue as slings need better and more ammo progression, but the stats can also be adjusted on relevant weaponry too.

**Comment by scarf005** [comment]
> So, the damage is okay at level zero but as can be seen, hand-throwing a rock with no skills whatsoever dramatically outranges using a sling, and it only gets more extreme at max level.

haven't gave much thought to ranges, reverted at [`093a892` (#5088)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5088/commits/093a892838740f9413265aeafcda7d25cc870a25). could visit this in later PR.

> Also reminder: We really should also look at how it determines throwing dispersion at zero skill, and seeing whether we can afford to adjust it.

could be done in future PR. seems to be out of the scope of this PR.

**Review by chaosvolt — APPROVED** [review]
I might look into how to make slings take the stats you'd get out of hand-throwing the ammo later today, for now this should be aight then.

**Review by RoyalFox2140 — APPROVED** [review]
That's a lotta math, who do you think I am?

(Tests pass, code is probably fine. We'll playtest it and revisit it if there's issues.)

image

**Pull request merged**
