### PR TITLE
Debug cbm generator is too weak

### PR DESCRIPTION
**Pull request by 12347654**
#### Summary

Increase the energy output so that you can go to the plus even when you turn on all possible bionics

#### Purpose of change
There used to be a mutation for infinite energy, but now I cant find it

#### Describe the solution
I fixed a few values in json

#### Describe alternatives you've considered
cope

#### Testing
That's works

### CODE REVIEW

**Comment by KheirFerrum** [comment]
This is not the purpose of the debug generator CBM. The debug generator CBM's purpose is to test and confirm that perpetual power generating CBMs increment bionic power correctly. Increasing this to such high values will make testing very difficult.

In general, the purpose of debug mutations and tools is to facilitate our ability to test content and systems so that we can confirm they're working, they're not designed to be cheat codes. It would be better if you just created a personal mod for this particular change.

**Comment by scarf005** [comment]
I think @12347654 and @KheirFerrum is both right here, that
- there needs to be an infinite powergen debug
- current CBM is needed to test perpetual powergen

However, I'm more leaning to @KheirFerrum because to me the root cause is that there's no way to permanently generate CBM power in revamped CBM debug menu. Maybe we should add a new menu entry (and a new fake CBM to handle that) that would set debug powergen amount instead. It'd be a pain to implement, tho.

@KheirFerrum, do you think it'd be doable to implement said feature (in relatively painless way)?

**Comment by joveeater** [comment]
We could just take the easy path and add a second debug bionic with these stats.

**Comment by scarf005** [comment]
Yeah that'd be better, adding an item wouldn't cause any tech debts.

**Review by scarf005 — APPROVED** [review]
Cataclysm: Bright Nights - -128_02
Cataclysm: Bright Nights - -128_03

sorry, forgot to review it. took jove's approach and added debug fuel cell CBM with infinite powergen.

**Pull request merged**
