### PR TITLE
feat(balance,port): battery consistency updates part 2

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

Follow-up to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3836 in which I finally mess with vehicle batteries.

## Describe the solution

Ported over changes to power capacity, weight, and volume of storage batteries and car batteries from DDA, modernizing the power ratios of storage batteries based on more modern levels of power density. Went ahead and used their figures for power densities, targeting the ~0.667 kJ/g that standard tool batteries in the source PR use as well as also used by standard tool batteries in BN now. Figured this would keep them at reasonably more bulky and make the overall rarer high-capacity batteries retain that feeling of being top of the line.

Main differences I went with:
1. Volume used matches that of kJ value as standard batteries use, instead of half that of kJ capacity.
2. I went ahead and made the smallest size 2000 kJ, and thus one-fifth that of the next size up instead of one-tenth. Reason being this makes it a size that's actually different from tool battery sizes and makes it worth adding to the UPS' battery options. :3
3. Went ahead with selecting a size for motorbike batteries that lets it stay 20% the size of car batteries instead of 15%, with small motorbike battery adjusted accordingly.

Summary of changes:

Item | Capacity | Weight | Volume | kJ/g | Strength to install
--- | --- | --- | --- | --- | ---
Small storage battery | 500 -> 2000 | 2.5 kg -> 3 kg | .5 L -> 2 L | 0.2 -> ~0.667 | 1
Medium storage battery | 7000 -> 10000 | 35 kg -> 15 kg | 6.25 L -> 10 L | 0.2 -> ~0.667 | 3 -> 1
(Large) storage battery | 40000 -> 50000 | 200 kg -> 75 kg | 25 L -> 50 L | 0.2 -> ~0.667 | 20 -> 7
(Very) large storage battery | 80000 -> 100000 | 400 kg -> 150 kg | 50 L -> 100 L | 0.2 -> ~0.667 | 40 -> 15
Small motorbike battery | 150 -> 300 | 1.5 kg -> 2 kg | 750 mL -> 1 L | 0.1 -> 0.15 | 1
Motorbike battery | 500 -> 600 | 4 kg | 1.25 L -> 2 L | 0.125 -> 0.15 | 1
Car battery | 2500 -> 3000 | 18 kg -> 20 kg | 6.25 L -> 10 L | ~0.139 -> 0.15 | 1 -> 2

Misc changes:
1. Also ported over the name changes that help make it more clear what size storage batteries are.
2. Updated recipes, uncrafts, and bash results accordingly to ensure that ratios of storage batteries were preserved, with bash results of grid batteries and vehicle batteries made a bit more consistent.
3. Allowed UPS to accept small storage batteries, with mag well updated accordingly.
4. Updated names, descriptions, and power capacities of grid batteries.

## Describe alternatives you've considered

1. Using the 1 kJ/g power density of high-capacity batteries instead.
2. Making the largest size of storage battery hold 250000 kJ so that all storage batteries have a delicious 5:5:5:5 ratio.
3. Making smallest size use 1000 like the DDA PR does, making them functionally no different from heavy batteries.
4. Leaving small storage batteries at only 500 kJ and instead making them no different from medium batteries.
5. Bothering to add in high-capacity equivalents to storage batteries like tool batteries have.

## Testing

1. Checked affected files for syntax and lint errors.
2. Load-tested and checked that constructions and vehicle parts have the correct names, to check strength requirements, etc.

## Additional context

DDA PR, by @batekulve: https://github.com/CleverRaven/Cataclysm-DDA/pull/57193

### CODE REVIEW

**Comment by chaosvolt** [comment]
Weird, tests didn't report as failed even though I forgot those.

**Review by scarf005 — APPROVED** [review]

**Review by scarf005 — APPROVED** [review]

**Comment by YeOldeMiller** [comment]
There's a bit of a problem with small storage batteries being 4 times larger than they used to be: some small robotics like manhacks include them. An entire manhack is just 0.75L, so the entire machine was 2/3 battery as it was, now where does the battery even fit?

**Comment by chaosvolt** [comment]
Hecc, I didn't realize manhacks were smaller than the batteries, I assumed all the bots were big enough to justify fitting it somewhere. Lowering small storage batteries back down to a small amount would work if needed, only issue is as above it makes small storage batteries overlap with the same niche as medium/heavy tool batteries.

An alternative would be to change any sufficiently wacky robot recipe to instead use a medium battery since that would fit the exact same volume and capacity as the battery it formerly called for.

**Comment by YeOldeMiller** [comment]
> issue is as above it makes small storage batteries overlap with the same niche as medium/heavy tool batteries

I think it's fine in this case. As I said, they're building blocks and are supposed to not be very useful individually.

> An alternative would be to change any sufficiently wacky robot recipe to instead use a medium battery

That would make me more reluctant to spend one-use robots like grenade manhacks, with medium batteries being actually pretty valuable and useful for the player. If I need more small storage batteries, I can just gut another storage assembly from a solar car and get a shitload of them, but if I need more mediums, they're harder to get in large quantities.

**Comment by chaosvolt** [comment]
True, mediums are annoying to get. :/

**Pull request merged**
