### PR TITLE
Fix Active Perpetual Power Gen and Charge Timer Handling

### PR DESCRIPTION
**Pull request by KheirFerrum**
#### Summary

SUMMARY: Bugfixes "Fix Active Perpetual Power Gen and Charge Timer Handling"

#### Purpose of change

Was reminded to look into power gen, originally to check if Joint Torsion Ratchet actually works and why the Atomic Battery CBM from Cata++ doesn't work when active.

#### Describe the solution

Adds a consideration in `bionics.cpp` for active perpetual power gen that isn't sunlight/wind. Fixed how charge timers are reset for power generators based on `attempt_recharge()` so that `"time": 1` means it gives power every turn, which is the intended approach as seen by how every other power drawing bionic uses that convention and 0 means it never recharges.

#### Describe alternatives you've considered

- Leave broken for kicks
- Alter the Joint Torsion Ratchet efficiency
Balance thing, best kept separate from bugfixes.

#### Testing

Installed the Cata++ mod, edited it to have `fuel_efficiency` and removed `passive_fuel_efficiency`, checked that it powered when on, didn't charge on the first turn and charged on every turn after that.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> Installed the Cata++ mod

What's the minimal example to test it in core?

**Comment by chaosvolt** [comment]
If an in-repo test example is needed, going ahead and updating JTR in the same PR could achieve that if desired.

**Comment by Coolthulhu** [comment]
It can be in debug-only items, but I'd like to have something that verifies that it works. Actual items that would be used are preferred, since they also act against bitrot.

**Comment by KheirFerrum** [comment]
> It can be in debug-only items, but I'd like to have something that verifies that it works. Actual items that would be used are preferred, since they also act against bitrot.

I could add a power gen bionic that uses some random perpetual fuel we may have lying around with different active and passive fuel efficiencies.

**Pull request merged**
