### PR TITLE
fix: unnecessary map settings overwrite on No Hope

### PR DESCRIPTION
**Pull request by RoyalFox2140**
## Purpose of change

Partially fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3993 by removing the offending file in No Hope. I found no notable differences in this file beyond missing content from vanilla.

## Describe the solution

Removes regional_map_settings.json from No hope.

## Describe alternatives you've considered

Adding missing entries.

## Testing

Removing won't cause issues as it will use vanilla's map settings

## Additional context

pain

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]
78mls4

**Comment by RoyalFox2140** [comment]
> 78mls4

I'm saving that.

**Comment by chaosvolt** [comment]
```
 Warning: Failed to download action 'https://api.github.com/repos/ammaraskar/gcc-problem-matcher/tarball/d1fed1fac9e94d30e23b5a82dba4e2963e71d2e7'. Error: nodename nor servname provided, or not known (api.github.com:443)
Warning: Back off 12.922 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/ammaraskar/gcc-problem-matcher/tarball/d1fed1fac9e94d30e23b5a82dba4e2963e71d2e7'. Error: nodename nor servname provided, or not known (api.github.com:443)
Warning: Back off 25.466 seconds before retry.
```
Weird tho

**Comment by scarf005** [comment]
image
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/7428665314/job/20220473942?pr=4062

looks like a temporary network failure. rerunning works.

**Pull request merged**
