### PR TITLE
port(DDA): spawn guns and related mags together

### PR DESCRIPTION
**Pull request by RobbieNeko**
#### Summary

SUMMARY: Balance "Port 'Spawn guns and related mags together' from DDA"

#### Purpose of change

From what I can tell this change is highly requested, and is a good change. Realistically, guns are generally stored with one or two magazines at least and some ammo for them. This also makes getting a gun drop or finding a gun safe much more impactful and fun, as players won't have to worry as much over whether they have ammo and mags for the fancy gun they just picked up.

#### Describe the solution

1. Port over nested_ammo.json and nested_guns.json from DDA (original / initial DDA PR https://github.com/CleverRaven/Cataclysm-DDA/pull/56191)
2. Remove ammo and guns that are not found in BN
3. Change the relevant groups in the guns itemgroup json to use the correct groupings of firearm, magazines, and loose ammo

#### Describe alternatives you've considered

1. Not doing this change whatsoever
This change seems like a reasonable balance change, and also one that is oft requested.
2. Write our own itemgroups to serve a similar purpose to nested_guns and nested_ammo
Considering how much time this already took, I did not find this feasible. Besides, what point is there in reinventing the wheel when their solution works just fine?

#### Testing

1. Added in the nested_ammo json first, removing the calibers that we don't have
2. Fixed any errors that the game threw at me regarding non-existent ammo types
3. Added in the nested_guns json, doing my best to remove guns we didn't have and fix any obvious naming discrepancies
4. Loaded into the game, determined errors that arose due to non-existent magazines, non-existent random Stanag mags item group, and fixing the variants of some guns that were listed in the DDA method rather than the BN one. Also handled any other name-errors I missed earlier
5. Modified the guns itemgroup to use nested guns when relevant
6. Loaded into game, fixed any errors that the game spit out
7. Checked a few police station supply rooms, confirmed that it appears to be working
8. Linted guns.json for obvious reasons relating to formatting
image
image
image
image

#### Additional context

As we have some guns that DDA does not, and as such not every gun has a grouping of it, it's mags, and loose ammo. Also, launchers and flamethrowers do not have these groupings. Also, unlike DDA, we do not have Civilian Everyday Carry groups in guns.json, and as such monsters and such are just as likely to drop mags and ammo. These could make good follow-ups in the future.

Big thanks to krwak for their advice and assistance in locating the relevant DDA json.

### CODE REVIEW

**Comment by RobbieNeko** [comment]
Damnit, I thought I ran it through the linter. Must not have picked up on the fact that I had updated it on my end.

**Review by Coolthulhu — APPROVED** [review]

**Comment by scarf005** [comment]
Thanks for the PR! may i ask to

- add in the description which DDA PR does this PR ports?
- use alternative phrasing like "spawn gun and its matching ammo together" over "nested guns", as the latter might be confused with nested containers(DDA pockets)?

**Comment by RobbieNeko** [comment]
> Thanks for the PR! may i ask to
> 
> * add in the description which DDA PR does this PR ports?
> * use alternative phrasing like "spawn gun and its matching ammo together" over "nested guns", as the latter might be confused with nested containers(DDA pockets)?

Hello, I've added a link to the original PR behind the relevant json files in DDA, and I've changed every mention of "nesting / nested" that isn't referencing the json files themselves. Is this sufficient?

**Comment by scarf005** [comment]
Yes, this looks good, thank you! Could you allow me to also rename the title and summary to "Port 'spawn guns and related mags together' from DDA"?

**Comment by RobbieNeko** [comment]
Oh, of course!

**Comment by scarf005** [comment]
thanks! I'll merge the PR as Coolthulhu already approved it.

**Comment by scarf005** [comment]
also I should really get some time to work on that "bot should auto format then commit so contributors shouldn't have to press 100 `commit suggestion` button"

**Pull request merged**
