### PR TITLE
De-obsolete rail rifles

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Content "Re-implement half-obsoleted rail rifles"

#### Purpose of change

It was pointed out in the BN discord that metal rails still exist in vanilla as ammo that can even be crafted, but the actual weapons to use them are all mod-shifted. A real basic look through the JSON confirms this done in a real half-finished manner, not only is the ammo still 100% vanilla and craftable, but it's also still present in some itemgroups and the vehicleparts can still be seen in the install menu since they were obsoleted but not deleted/migrated.

#### Describe the solution

1. De-obsoleted the rail rifle and heavy rail rifle as vanilla weapons, now with inheriting from the `guns_magnetic` weapon class. Additionally, per feedback the heavy rail rifle has been reworked to be a bit heavier overall and uses the `MOUNTED_GUN` flag. Now with the following rebalances:
 * Steel rail: Reduced damage from 65 to 50, reduced arpen from 40 to 30, reduced range from 50 to 30, increased dispersion from 0 to 100.
 * Rebar rail: Reduced damage from 70 to 60, reduced arpen from 25 to 10, reduced range from 40 to 20, increased dispersion from 150 to 200.
 * Heavy rail rifle: Increased UPS cost from 100 to 120, reduced range from 40 to 10, increased dispersion from 100 to 200.
 * Ferromagnetic rail rifle: Increased damage from 0 to 20, increased UPS cost from 40 to 60, increased dispersion from 90 to 100.

Loadout | Effective Damage (Damage + Arpen) | Total Range | Total Dispersion | UPS Efficiency Vs Effective Damage
--- | --- | --- | --- | ---
Heavy rail rifle (steel) | 145 -> 120 | 90 -> 40 | 100 -> 300 | 145% -> 120%
Heavy rail rifle (rebar) | 135 -> 110 | 80 -> 30 | 250 -> 400 | 135% -> ~91.67%
Rail rifle (steel) | 105 -> 100 | 50 -> 30 | 90 -> 200 | 262.5% -> ~166.67%
Rail rifle (rebar) | 95 -> 90 | 40 -> 20 | 240 -> 300 | 237.5% -> 150%

2. Moved the recipes for them from No Hope back into vanilla, with a couple adjustments. In particular I widened the skill gap between them, with the rebar rifle being level 8 electronics instead of 9, and lowered the craft times from a massive 6 and 12 hours down to 4 hours 30 minutes and 6 hours, respectively. Additionally made it possible to learn them a bit earlier via lab journal-Herrera.
3. De-obsoleted the mounted gun vehicleparts.
4. Obsoleted Aftershock's version of the makeshift rebar rifle and its recipe, now that craftable railguns will be back in vanilla.
5. Removed redundant recipe for rebar rails from No Hope since already present in vanilla.

#### Describe alternatives you've considered

1. Either axing computer skill requirement for heavy rail rifle or adding `coding_standard` to the recipe.
2. Rebalancing rail rifles and ammo to shift more of the damage from the ammo to the weapon, maybe towards a 60/60 split for heavy rail rifle plus steel rails, most likely buffing the direct damage of rebar rails accordingly and bumping up UPS cost of both weapons.
3. Possibly giving rebar rails an armor multiplier that makes them less effective against whatever their arpen doesn't get past, similar to how makeshift arrows and blunderbuss ammo have been balanced.
4. Making the recipes for rail ammo more granular, i.e. using only 1 rebar to make 5 rebar rails and 2 `steel_standard` to make 5 steel rails, in half the current time and and forging cost (for the latter).

#### Testing

Checked affected files for syntax and lint errors, along with poking around for references to the ammotype or items themselves in mods folder.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Old restore attempt for the reference:

**Comment by chaosvolt** [comment]
Ah, wasn't aware of this. This looks like it got heavily changed to beef it up into even more of an anti-material rifle, when I feel that it could afford to potentially take a nerf to its top-tier damage in exchange for making the damage spread out better between the gun and ammo, and between different variants. Plus trying to introduce a bespoke new ammotype on top of that instead of reworking the existing one that hasn't even been removed yet seems like a recipe for trouble.

**Comment by Firestorm01X2** [comment]
> This looks like it got heavily changed to beef it up into even more of an anti-material rifle,

I think it is not neccesary to follow exactly that path - balance concerns

**Comment by Coolthulhu** [comment]
> Heavy rail rifle plus steel rail: effective damage of 145, dispersion of 100, range of Yes (90)
> .50 AM rifle plus standard .50: effective damage of 139, dispersion of 250, range of Hell Yes (155)

So the rail rifle is more accurate here?
With those stats, they're nearly identical, except for lengthy craft times for rail rifle vs uncraftable gunpowder for .50.

The statblock below is similarly un-different. The only notable difference is inability to snipe at huge range, which is not much.

Start with the role for the new item, then figure the stats out. "De-obsoleting" is effectively adding a new item, just that it's heavily based on an old one.

**Comment by chaosvolt** [comment]
> So the rail rifle is more accurate here?

Those were counting up the comparison before the change. As for its current role, the idea here is it still hits decently hard but at a shorter range. It's meant to be a high-damage, anti-armor weapon that requires a good bit of investment tech-wise to build and to keep running, namely all the electronic costs and needing a UPS. Material cost per shot meanwhile is overall far less complex than firearms, being just some metal with an improvised option.

In addition, .50 has much better ability to pierce armor, so it's meant to still win out against armored targets, as the rail rifles can only really compete when they have the best ammo paired with the best weapon. The gap between the two is widened a bit at least, from 6 higher effective damage to 19 lower effective damage. And this was only comparing that combo vs. baseline .50 BMG, AP ammo will have even higher effective damage.

**Review by scarf005 — CHANGES_REQUESTED** [review]

**Comment by Coolthulhu** [comment]
> In addition, .50 has much better ability to pierce armor, so it's meant to still win out against armored targets, as the rail rifles can only really compete when they have the best ammo paired with the best weapon.

That's not a big difference.
It's still mostly just ".50 that's cheaper, but you have to carry UPS".
There needs to be a difference in combat usage. Shorter range could be it, but that only really starts mattering below 25 tiles or so.

There should be a reason to use the rail even if .50 is available. Even if we assume ammo costs the same.

**Comment by chaosvolt** [comment]
Hmm. The range has already been cut down a fair bit, and I'm not sure what else to add to it. Worth noting also that the different in effective damage jumps from 19 to 38 if you load that .50 rifle with AP, the previous comparison was only with best combination of rail rifle ammo vs. AMR with basic .50 ammo.

Anything else besides range that would make the difference meaningful? I feel like nerfing it so the strongest available rail rifle plus steel rails topping out at 25 tiles might look a bit inconsistent, given some crossbows will likely outrange that.

**Comment by scarf005** [comment]
> Hits hard and at range, but can only be used when mounted (MOUNTED_GUN, which allows using window frames and dirt mounds)

> Hits just as hard as regular .50, takes only half of the gunpowder to reload, but uses much more UPS power (500?)

these two options from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/745#issuecomment-893246331 looks good

**Comment by chaosvolt** [comment]
Hmm. Making it mounted could work, moreso for the heavy rail rifle since that seems the most fitting, though the regular rail rifle logically would be better off staying shoulder-fired.

Second idea seems unfeasible because wasn't the entire idea of the railgun using UPS power and metal? That one only works with the preceding PR's somewhat weird attempt to mesh firearm cartridges with railgun ammo by making a new ammotype, instead of the current idea of giving ammo that already exists in the game was never properly dummied out a use.

**Comment by chaosvolt** [comment]
Aight, per the above suggestion I went ahead with adding `MOUNTED_GUN` to the heavy rail rifle, as that does seem like a fitting chance. Bumped weight up a bit from 12 to 15 kilograms to further justify it (the weight of components would allow us to afford increasing as high as 19 kg without breaking conservation of mass if desired) and updated description as well.

**Comment by scarf005** [comment]
now that heavy rail rifle is mounted only which is a huge penalty, maybe it could provide better damage, range and dispersion than AM rifle?

**Comment by chaosvolt** [comment]
Possibly? Though rails are overall much easier to keep fed once you've got a working setup to use UPS with, not sure if buffing the damage to be even higher would be good or not.

**Comment by chaosvolt** [comment]
I'll have to tinker with this when I get home I guess, not sure exactly what damage would work best in that case.

**Review by Firestorm01X2 — APPROVED** [review]
Step in the right direction. No need to delay more. Somel balance correction can be done later.

**Pull request merged**
