### PR TITLE
Port over DDA Pull Request #65561: Wandering Hordes prefer to wander and recruit in open terrain, and #58611: Peek over ledges

### PR DESCRIPTION
**Pull request by Empyrean-Heaven**
#### Summary
SUMMARY: [Balance] "Wander Spawns will now tend to not phase through matter, at least in theory; also, peek over ledges"

#### Purpose of change

This is pretty much a direct port of DDA #65561 and #58611.
https://github.com/CleverRaven/Cataclysm-DDA/pull/65561
https://github.com/CleverRaven/Cataclysm-DDA/pull/58611
The following is the former's claims.

'At the moment, wandering hordes move around and recruit zombies almost indiscriminately, mostly ignoring the terrain they are on.

This leads to unrealistic scenarios such as zombies appearing inside empty buildings when they wander in, and zombies that should be inside buildings (such as prison inmates) mysteriously teleporting to the open field when they become part of a horde.

This PR adds a check to a zombie's location before horde recruitment, to check if they are in open terrain before recruitment. Also the horde move to preference is tweaked to much prefer open terrain (roads and fields) and everything else has a reduced preference. A horde will still path through difficult terrain in order to reach cities and noises however.'

The latter is thus.

'Being able to see where you're going before climbing or jumping down a ledge seems like something you should be able to do. This is made possible by the ability to peek Z-levels when on stairs.'

#### Describe the solution
1. The first change is a check added to zombie horde recruitment to pass a check, which is;

Does the overmap terrain this zombie is currently on ;
contain the string "field" or "road" (to also check for farm field, dirt road)
be prefixed by "swamp" or "road" (to cover all road types)

If it passes any one of these 4 checks, the zombie becomes eligible for wandering horde recruitment.

The second change is to the wandering horde's movement chance onto an overmap tile algorithm, which is ;

Deleting the old code, and using the more versalite is_ot_match() function to iterate through destination checks,
starting from the most preferred (1) (and common, for least overhead) terrain type to least preferred (25),

Does destination overmap tile string contain "road"? Set preference to 1 if so,
Does destination overmap tile string contain "field"? Set preference to 3 if so,
Is destination overmap tile string prefixed by "forest"/"swamp"/"bridge"? Set preference to 6 if so,
Else does the destination tile have the prefix "river"? Set preference to 10 if so.
All other overmap destinations (which will most likely be a structure or obstacle) will be set to a preference of 25.

2. It reuses the climb down code, but peeks instead of moves.

#### Describe alternatives you've considered

Leaving it as it is.

#### Testing

I am on mobile, so I can't exactly test this. Would appreciate it if somebody does.

#### Additional context

Hope everyone is doing great!

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
For the future:
It is strongly recommneded not to mix things that doing thematically different thing in one PR.

**Comment by Empyrean-Heaven** [comment]
Yeah, sorry. I apologize for this. I was unfamiliar wit Github. Just now did I realize that branches were a thing. I'll be using them from now on. Sorry about that.

**Comment by Empyrean-Heaven** [comment]
If this struggles to build or pass through, i'll close it.

**Comment by Firestorm01X2** [comment]
There are indeed build errors. So it is need fixing.
I recommend to create separate PRs and fixing it separately.

**Pull request closed without merging**
