### PR TITLE
More welcoming debug help menu

### LINKED ISSUE #2357: make debug help messages more welcoming
### Discussed in https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/2162

<div type='discussions-op-text'>

<sup>Originally posted by **scarf005** November  5, 2022</sup>
image

well it's a [meme](https://www.bbc.com/news/technology-47900904) but its context gets lost in translation, therefore making debug help message generic (no memes) will help.

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: [Interface] "More welcoming debug help menu"

#### Purpose of change

- fixes #2357 

#### Describe the solution

before:
```
Debug Functions - Using these will cheat not only the game, but yourself.
You won't grow.  You won't improve.
Taking this shortcut will gain you nothing.  Your victory will be hollow.
Nothing will be risked and nothing will be gained."
```
after:
```
Debug Functions - Manipulate the fabric of reality!
You can use them to fix a bug or test something.
most importantly, have FUN!
```

#### Describe alternatives you've considered

I didn't take much time thinking up new help text so it may have some more room for improvement.

#### Testing

text changes only.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Warning that they can break things depending on use could also be a potential thing to add to it (though some of the dangers commonly cited are a bit overblown, quit-without-save is famously often regarded as a concern but rarely causes problems unless used midway through death cleanup).

**Comment by scarf005** [comment]
alright, i'll add a line describing possible dangers related to debug functions.

**Comment by chaosvolt** [comment]
Seems fitting, yeah.

**Comment by Coolthulhu** [comment]
It was supposed to be a meme reference.

I don't think the menu needs a description other than the title.

**Comment by scarf005** [comment]
should i just keep it short and leavy only "Debug functions"?

**Comment by Firestorm01X2** [comment]
> should i just keep it short and leavy only "Debug functions"?

I recommend to remove
"most importantly - HAVE FUN"
Since debug is for debugging and not intended to be used by players.

Other lines sound fine to me,

**Comment by scarf005** [comment]
i think it's ok for players to use debug features while playing the game, but yes. the line could be removed.

**Pull request merged**
