### PR TITLE
Allow ducks to be tamed with birdseed

### PR DESCRIPTION
**Pull request by Proxiehunter**
Category "Features"
Purpose of change

Ducks seem to be untameable currently. Since real life farmers have been known to keep ducks for duck meat, duck eggs, and feathers it seems that they should be tameable in game the same way chickens are. Birdseed seems the most logical way to do that.

Consider also applying to geese which are also sometimes kept by real life farmers.

This would increase players access to eggs for both cooking and mutagen creation.
Describe the solution

Replace the current entry for ducks under the bird.json with this one:

"id": "mon_duck",
"type": "MONSTER",
"name": { "str": "duck" },
"description": "A mallard duck, often seen around rivers and other bodies of water. It feeds primarily on insects, seeds, roots, and, pre-Cataclysm, bread scraps.",
"default_faction": "small_animal",
"bodytype": "bird",
"categories": [ "WILDLIFE" ],
"species": [ "BIRD" ],
"volume": "750 ml",
"weight": "1 kg",
"hp": 4,
"speed": 140,
"material": [ "flesh" ],
"symbol": "v",
"color": "brown",
"aggression": -99,
"morale": -8,
"melee_dice": 1,
"melee_dice_sides": 1,
"melee_cut": 0,
"dodge": 4,
"harvest": "bird_small",
"fear_triggers": [ "SOUND", "PLAYER_CLOSE" ],
"death_function": [ "NORMAL" ],
"reproduction": { "baby_egg": "egg_duck", "baby_count": 3, "baby_timer": 5 },
"baby_flags": [ "SPRING" ],
"flags": [ "SEES", "HEARS", "SMELLS", "ANIMAL", "PATH_AVOID_DANGER_1", "WARM", "FLIES", **"BIRDFOOD"** ]

The bold indicating the only change to the entry. As I understand it this would allow ducks to be tamed with bird seed.
Describe alternatives you've considered

Alternative solutions are to either use something else to tame them (not sure how that works, could BREAD be added or is just limited to the typical ones like bird food, cat food, dog food, and cattle fodder?) or continue to not allow players to tame ducks.
Testing

I have not tested but this is a solution I've seen offered when a player wants to tame a creature that was not initially designed to be tamed and this simple edit should not cause errors. I can test it in the next few days if need be.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Looks like you picked wrong branches for the PR.
You want to merge from your own fork's branch into BN's "upload" branch.

**Comment by Firestorm01X2** [comment]
Also now there is tutorial on how to work with both DDA and BN at the same time:
https://github.com/cataclysmbnteam/Cataclysm-BN/wiki/Working-with-both-BN-and-DDA-in-git

**Comment by Proxiehunter** [comment]
Thanks. I'll get on that later today or tomorrow, today promises to be a long day. You guys are a lot better about my mistakes than the reaction when I accidentally posted it to mainline cata the first time.

**Comment by Coolthulhu** [comment]
Closing this for now, because it will probably be faster to recreate it from scratch than to try to fix this PR.

**Pull request closed without merging**
