### PR TITLE
Obsolete sole_rubber

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Content "Rubber soles had no purpose, they probably never will."

#### Purpose of change
Uncraftable, no recipe using them, no spawn. They were just "there" so I remove them.

### CODE REVIEW

**Comment by Zireael07** [comment]
I can easily imagine a thread+rubber sole recipe for a basic flip-flop instead of removing it.

**Comment by Lamandus** [comment]
Feel free to add and bring it back from obsolation. It has no recipes, no itemgroup, no spawn. Until then, it should be removed.

**Comment by Coolthulhu** [comment]
Has conflicts

**Comment by Lamandus** [comment]
New, I reckon. I deal with it

**Pull request merged**
