### PR TITLE
feat: prettier ear/tail mutation graphics

### LINKED ISSUE #3202: ☂️ anime kemonomimi ear mutations
### Is your feature request related to a problem? Please describe.

- animal ear mutation gives ugliness, which is not realistic.
- it is scientifically proven (citation: me) that animal ears are cute.
- its tiles representation should be cuter
- having _accurate_ depiction of animal ears is critical to roleplay _cybernetically enhanced bionic catgirl warlord_.

### Describe the solution you'd like

- add anime ears to external tileset <https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/external_tileset/>
- give prettiness(negative ugliness) to existing animal ear mutations

### Additional context

- prior work done: https://github.com/Zupercharged/CDDA-Alternate-ear-graphics
- note to self: should move https://github.com/cataclysmbnteam/Cataclysm-BN/blob/6f24bb37142dccbd601548eb236d80c249ebbf8e/data/json/external_tileset/External%20Tileset%20Info.md to official docs alongside lang/notes as well.
```[tasklist]
### Tasks
- [x] ask permission to mainline CDDA-Alternate-ear-graphics
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3267
- [x] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3268
```

### LINKED ISSUE #3267: add alternative ear mutation to external tileset

### PR DESCRIPTION
**Pull request by scarf005**
## Summary

SUMMARY: Content "Prettier ear/tail mutation graphics"

## Purpose of change

- resolves #3202
- resolves #3267

## Describe the solution

after

drew new sprites for animal ear and tail mutation. (mouse ear drawn by @NobleJake)

## Describe alternatives you've considered

enjoy old graphics

before

### CODE REVIEW

**Comment by Zireael07** [comment]
The ears are not noticeably prettier BUT they moved from where a person has ears to top of head

**Comment by chaosvolt** [comment]
Where the ears should go is a bit of a meme, but I think it does accomplish an improvement to recognition. You can actually tell it's an ear an not a weird horn. Tails also seem not changed much but having them on the same side is probably good for consistency.

**Comment by chaosvolt** [comment]
Also might be worth adding to the documentation before I inevitably forget.

This also reminds me that I could probably afford to split the main image's contents up into related images, since it'd make it easier to tell at a glance what the external tileset is adding stuff to, and make it more likely that two people will be able to work on separate PRs without running into each other's efforts.

**Comment by scarf005** [comment]
image
done.

**Review by chaosvolt — APPROVED** [review]

**Comment by scarf005** [comment]
image

...hecc

**Pull request merged**
