### PR TITLE
feat(UI): also capitalize spell name for Spellcraft

### PR DESCRIPTION
**Pull request by chaosvolt**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

Tiny followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5523

## Describe the solution

Capitalized skill name of spellcraft in Magiclysm. Bonus dose of {}ifying the name like vanilla skills.

## Describe alternatives you've considered

Punishing it with lowercase skill name for its crimes.

## Testing

Used my eyes.

### CODE REVIEW

**Comment by RoyalFox2140** [comment]
I should've checked mods. Whoops

**Review by RoyalFox2140 — APPROVED** [review]

**Comment by Proxiehunter** [comment]
> I should've checked mods. Whoops

Speaking of mods, was the Arcana skill from the Arcana mod included?

**Comment by RoyalFox2140** [comment]
> > I should've checked mods. Whoops
> 
> Speaking of mods, was the Arcana skill from the Arcana mod included?

It's not in repo, use the issue template on Arcana's repo if it wasn't.

**Comment by chaosvolt** [comment]
> Speaking of mods, was the Arcana skill from the Arcana mod included?

I fixed Arcana in this commit: https://github.com/chaosvolt/cdda-arcana-mod/commit/7269ee67273685702088e8c6c25412bdd064cc19

**Pull request merged**
