### PR TITLE
perf(port): cache NPC goal

### PR DESCRIPTION
**Pull request by End3r991**
## Purpose of change
One of the PR ported for #3073.

## Additional context
Source PR: Performance: Cache NPC goal, by @dseguin: https://github.com/CleverRaven/Cataclysm-DDA/pull/54312

### CODE REVIEW

**Review by chaosvolt — COMMENTED** [review]
Before:


After:


It compiles and tests past, variation is really too small to say what it's doing. Might need to spawn a fuckload of dynamic NPCs instead I assume, instead of testing refugee center? I dunno.

**Comment by scarf005** [comment]
commits are missing co-authors despite being ported from DDA. could we attribute the original authors with this?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by chaosvolt** [comment]
Worth a try yeah. Last time I checked their branch out and amended last commit, and it instead created a new commit with the crediting added...

**Review by scarf005 — APPROVED** [review]

**Comment by scarf005** [comment]
image

command used: `perf record -e 'cpu-cycles:u' -ag -- sleep 10`

i guess it the performance got improved?

**Pull request merged**
