### PR TITLE
fix: add `UNSAFE_CONSUME` to all raw meat items

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

Fix getting parasites from having raw fish in your auto-eat zone:
image

Along the way I decided to just also add the relevant flag to all raw items that can grant parasites. While the low fun value may stop auto-eat due to the code checking the fun level, it doesn't stop you from hitting the wrong key and instantly getting parasites from that.

## Describe the solution

1. Set the `flesh` abstract to have `UNSAFE_CONSUME` on it.
2. Converted raw fish, and  to add `SMOKABLE` to its flag list via `extend` instead of fully overriding the flags.
3. Set pickled and canned offal, jerky, salted fish, various cooked offal items to delete `UNSAFE_CONSUME` from flags.
4. Added `RAW` and `UNSAFE_CONSUME` to raw fat like tainted fat has.
5. Misc: Fixed cooked meat scraps lacking `EATEN_HOT`.

## Describe alternatives you've considered

screm

## Testing

Checked affected files for syntax and lint errors.

### CODE REVIEW

**Comment by KheirFerrum** [comment]
Is there a reason RAW doesn't do this by default?

**Review by Lamandus — APPROVED** [review]

**Comment by chaosvolt** [comment]
> Is there a reason RAW doesn't do this by default?

Most likely because `RAW` is commonly used on a lot of veggy items that don't have parasites or otherwise cause any harm when eaten, and its only effects are a calorie reduction.

**Comment by KheirFerrum** [comment]
> > Is there a reason RAW doesn't do this by default?
> 
> Most likely because `RAW` is commonly used on a lot of veggy items that don't have parasites or otherwise cause any harm when eaten, and its only effects are a calorie reduction.

How does it affect raw meat but not raw veggy? Is it a tandem effect?

**Comment by chaosvolt** [comment]
> How does it affect raw meat but not raw veggy? Is it a tandem effect?

Because uncooked meat has a non-zero `parasites` value defined and uncooked veggies don't. It has nothing to do with the `RAW` flag itself.

**Comment by KheirFerrum** [comment]
> > How does it affect raw meat but not raw veggy? Is it a tandem effect?
> 
> Because uncooked meat has a non-zero `parasites` value defined and uncooked veggies don't. It has nothing to do with the `RAW` flag itself.

🤔 Couldn't we use that then?

**Comment by chaosvolt** [comment]
> 🤔 Couldn't we use that then?

Checking for non-zero parasites could also work, just requires hardcoding it in, whereas this was a relatively quick JSON solution.

**Comment by KheirFerrum** [comment]
> > 🤔 Couldn't we use that then?
> 
> Checking for non-zero parasites could also work, just requires hardcoding it in, whereas this was a relatively quick JSON solution.

Fair, may be a good idea to do that someday.

**Pull request merged**
