### PR TITLE
feat: removal of lobster related fluff

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
Lobster and its recipes were very strange to begin with. It was just one animal that dropped this meat (lobster) and its meat was only used in lobster recipes, nothing else. It was bloat from DDA, I removed it, and the lobster now spawns fillet of fish, as other crayfish.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Making crayfish and razorclaws use this meat (or possibly a mutie variant for the latter if we were so inclined, I wish we had a way to make harvest entries inject added vitamins into yields like they can with flags and faults) could be a viable alternative too though, hmm.

**Review by scarf005 — CHANGES_REQUESTED** [review]
I think we should contact @arvay5 as the lobster additions aren't DDA bloat but (their contribution)[https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4251].

**Comment by Lamandus** [comment]
> I think we should contact @arvay5 as the lobster additions aren't DDA bloat but [their contribution](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4251).

It is. It was ported but not credited correctly. https://github.com/CleverRaven/Cataclysm-DDA/pull/56121

**Comment by chaosvolt** [comment]
New irritating complication I've just been made aware of: it seems like the PR was indeed been an uncredited port from DDA after all: https://github.com/CleverRaven/Cataclysm-DDA/pull/56121

**Review by chaosvolt — APPROVED** [review]
In light of that I'm tentatively approving the removal, the rationale behind this PR was a touch half-baked in my opinion but if @arvay5 wants it back in it would be better to have it actually be a complete implementation this time (initial PR didn't even have the actually nessecary harvest entry, plus as mentioned dehydrated lobster was only half-implemented due to lack of a recipe), and more importantly **_credit your ports blyat_**

A link to the source PR or mention that it's a port would've been a reasonable bare fucking minimum, with co-auth in the commit being ideal but not always doable since it's only really easy to do in github desktop specifically and only right before a commit.

**Pull request merged**
