### PR TITLE
Overhaul NPC AI weapon compares

### PR DESCRIPTION
**Pull request by KheirFerrum**
#### Summary

SUMMARY: Infrastructure "Overhaul NPC AI weapon compares"

#### Purpose of change

- Follows up on #2742 

Goal is to update how NPCs choose weapons to engage enemy, while also reducing the number of multipliers in `gun_value` so there's not such a massive disparity between melee and ranged weapon values.

#### Describe the solution

Weapon comparison in `wield_better_weapon()` for ranged weapon is now based on two things. DPS of gun (based on time taken to perform a regular aimed shot, with considerations for reloading), and range of weapon relative to distance of target.

NPCs will now filter down their list for a gun that allows them to shoot the enemy, moving toward the enemy until the enemy is within the range for their longest range weapon, and swapping weapons if the range allows a different weapon with a higher DPS.

Add new function `check_toggle_cbm()` which returns a list of fake weapon/bionic_ids for applicable weapons that the NPC may evaluate in `wield_better_weapon()` mainly so that compares are centralized, can't really do this with active CBMs yet.

Move cost limitation is basically non-existent for NPCs switching weapons, so the system derived seems to work pretty well.

An issue here is that gun_value doesn't use the same system, because it values dispersion/range while `wield_better_weapon()` only cares if the weapon's range exceeds the distance to target.

Gun value now mainly considers two values, raw DPS (including reload) and dispersion. This reduces the difference in value between melee and ranged, and somewhat better accounts for ranged weapons ability to hit at distance. Not fully satisfied with the interval values, but I don't really want to touch this too much.

#### Testing

-Mind control an NPC, delete all their items, have them wear a backpack.
  -  Spawn an m4a1 and install a combat knife onto it as a bayonet, make the NPC carry the m4a1, spawn a remington competition onto them, a katana, 2 stanag magazines and 10 shotgun shells.
  -  Set all their stats to 8, all their skills to 5, then set their shotgun skill to 0.
- [x] Attack them and piss them off. Check that they will wield their m4a1 at range 12+, wield their shotgun at range 5-11, and wield their m4a1 again at range 3-4.
  - [x] Check that they will aim and fire their guns within those ranges
  - [x] Check that they will reload their guns when out of ammo, using only magazines for the m4a1, and shells for the remington.
    - [x] Check that once out of ammo for their m4a1 they will move to range 11 to wield their shotgun, and once shotgun is out of ammo they will move to range 2 to wield their m4a1 as a bayonet.
- [x] Check that the NPC will use their bayonet at range 2, then swap to their katana at range 1.
  - [x] Check that they will not throw their guns you if you wield a loaded m4a1.
- [x] Repeat above with a bionic shotgun.

#### Additional context

When reloading m4a1 NPCs will take a step forward before realizing they're in correct range, don't yet know what the issue is, but as problems go it's fairly minor.

### CODE REVIEW

**Comment by scarf005** [comment]
could you provide saves to make testing easier?

**Comment by KheirFerrum** [comment]
> could you provide saves to make testing easier?

[save.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/11520949/save.zip)

Note, you need to wield the m4a1 before NPCs will shoot at you, since they won't shoot at you from distance if you're not considered dangerous enough.

**Review by scarf005 — CHANGES_REQUESTED** [review]
tested with `Shotgun Test` world from provided save.

<details><summary>Tests that worked</summary>

>  Check that they will wield their m4a1 at range 12+,
image

> wield their shotgun at range 5-11
image


> wield their m4a1 again at range 3-4. 
image

> Check that they will reload their guns when out of ammo, using only magazines for the m4a1, and shells for the remington.

image

> Check that once out of ammo for their m4a1 they will move to range 11 to wield their shotgun,
image

</details> 

> once shotgun is out of ammo they will move to range 2 to wield their m4a1 as a bayonet.

image

> Check that the NPC will use their bayonet at range 2, then swap to their katana at range 1. 

> Check that they will not throw their guns you if you wield a loaded m4a1.

1. NPC wields katana instead of M4A1 with bayonet.
2. NPC throws said M4A1 at range 1

**Review by scarf005 — APPROVED** [review]
# Regular shotguns
image
image

they work as intended.

# Bionic shotguns
image

**Pull request merged**
