### PR TITLE
feat: More engine recipes

### PR DESCRIPTION
**Pull request by Berehenia**
Added recipes for v6, v8, v12, inline and their counterparts for diesel. Added engine block recipes, added all 3 gas turbine recipes as well.

### Required

- [ ] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [ ] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### CODE REVIEW

**Comment by karxi** [comment]
Bluntly, I don't think turbines should be craftable. They're not terribly hard to find (the sole exception being osprey engines); they're located in military helipads. At most, I'd suggest limiting it to the smallest turbine engine.
Unless we're planning to allow players to craft turbines for high-efficiency generators, in which case my objections hold less weight. (Which I don't think is a terrible idea, but I'm not the one doing an energy rework.)

**Comment by Coolthulhu** [comment]
Yeah, turbines should be effectively "non-renewable", using something uncraftable and high level as ingredient.
V12s could be craftable, but they should probably consume some semi-rare, uncraftable component. Not sure what would be a good candidate.

I recall there being some sort of sci-fi fabricator machine in one of the collapsed buildings. If I remember correctly, it uses rare, uncraftable "unobtainium containers" to create things.
I'd be fine with turbines being craftable using something from that fabricator, plus a couple of superalloy plates.

**Comment by Berehenia** [comment]
The nanofabricator is kinda rare as all hell

Its not guaranteed to be the lab finale
its not guaranteed to have the nanofab template for it (iirc you can only craft from nano canisters there so it'd take 400 kilos or around 30 of them) 
So that would be a lot more lab or sarcophagus diving than anything else in the game

Its a bit too brutal of a requirement
The main point of this recipe suggestion is to **kill off RNG even if you need to grind your ass off**

The small turbine is 7 in fabrication as main stat and 7 in mechanics, and 3 alloy plates (36 sheets total) 
The largest one eats 6 superalloy plates and requires 10 in fab (probably more annoying than mechanics by a long shot) and mechanics plus a massive engine block which is either taking apart a v12 or crafting one (6 mechanics is what i suggested for it, im down for number adjustments (and i think it could be bumped to 8 easily) )

The 6k one also doesnt have a uncraft while the vehicle part breaks into 4-6 plates and **only** a bunch of steel

Hell, I wouldn't mind adding electrics as an requirement as well or making the recipe far more annoying 

What do y'all think?

**Review by yay855 — CHANGES_REQUESTED** [review]
The large turbine recipe should be removed at the very least, in order to get players to seek it out for their supercars and helicopters. I personally also think the larger regular engine recipes should be removed as well, but not every dev agrees with me on that, so I won't push it.

**Review by yay855 — APPROVED** [review]

**Review by RobbieNeko — APPROVED** [review]
Looking good!

**Pull request merged**
