### PR TITLE
feat(mods/pride_flags): add an in-repo mod for pride flags

### PR DESCRIPTION
**Pull request by RobbieNeko**
## Purpose of change

Pride flags seemed like an appropriate thing to add in an in-repo mod and based on our community, it seemed like it would be appreciated.

## Describe the solution

- Adds transgender, aromantic, asexual, bisexual, intersex, lesbian non-binary, pansexual, gay (men), and genderfluid pride flags as well as the original rainbow flag.
- Adds recipes for the above flags (adapted from the recipe for a blanket)
- Adds an itemgroup containing these flags to the major itemgroup containing American flags

## Describe alternatives you've considered

- Making it mainline instead of a mod
Considering our lack of a variants system and how we all saw the drama that came up in the DDA PR to add pride flags to their mainline, I believe an in-repo mod is a better solution.

- Adapt the DDA uncraft recipe as our crafting recipe for the pride flags
7 sheets just looked really excessive to me.

## Testing

The game loads, pride flags show, the crafting is a go, and the itemgroups behave as usual.

## Additional context

image
image
image

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]

**Comment by chaosvolt** [comment]
Semantic PR titles continue to baffle me, hecc

**Comment by RobbieNeko** [comment]
Ehh, oh well. Semantic PR is gonna get caught up over semantics

**Comment by scarf005** [comment]
semantic PR complains because `semantic.yml` isn't updated yet.

**Review by scarf005 — COMMENTED** [review]
```diff
- transFlag
+ trans_flag
```
a bit of a nitpick, but generally mod id and item ids follow [`snake_case` convention](https://en.wikipedia.org/wiki/Snake_case).
it's not a rule set in stone, but being consistent is nice.

**Comment by SilearFlare** [comment]
Hold on a second this isn't the DDA repo

**Comment by RobbieNeko** [comment]
Figured, haha. I'm just used to using camel case. Will go on ahead and change it to snake_case on your suggestion

**Comment by scarf005** [comment]
also don't worry about semantic PR failing, it'll fail till it's merged (because the check is done using `main` branch's `semantic.yaml` not this PR's `semantic.yaml`)

**Comment by RobbieNeko** [comment]
There, the case should now hopefully be appropriately snaked
Including the modid, so might want to adjust it in that semantic.yml file again

**Comment by scarf005** [comment]
thanks, one more tiny nitpick: directory name isn't `snake_case` but `Kebab-Case`.

**Comment by RobbieNeko** [comment]
To be fair, the directory names seem to have more variance with regards to that. But I will gladly comply

**Comment by scarf005** [comment]
@chaosvolt i think it'll be ready to kerge after loadtest, failure in smeantic PR check can be ig ored (due to limitation it always fail when adding new mod)

**Review by chaosvolt — DISMISSED** [review]
1. Load-tested with mod.
2. Spawned in the last flag sprited in the mod_tileset to confirm it was the expected sprite.
image
Layering will as always make me screm but there's nothing one can really do to fix that, you wear your messenger bag over blankets and US flags too and the layering looks equally odd anyway:
image

**Comment by RobbieNeko** [comment]
Oops, chaos accidentally revealed that that sprite got offset on the y-axis somehow
Lemme just fix that, sorry

**Comment by RobbieNeko** [comment]
Good thing Chaos happened to choose that one specific flag to test with, given that only it had its y-axis wonky xD

**Comment by RobbieNeko** [comment]
@chaosvolt So sorry, could you please re-review this? Your testing just happened to reveal that the genderfluid flag's sprites somehow got offset on the y-axis, so I had to fix that real quick

**Review by chaosvolt — APPROVED** [review]

**Review by scarf005 — APPROVED** [review]
image

**Pull request merged**
