### PR TITLE
fix: use correct itemgroup ID for default `digging result` of soil

### PR DESCRIPTION
**Pull request by chaosvolt**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

Another thing I borked in an earlier PR.

## Describe the solution

Set mapdata.h to use the itemgroup ID `digging_soil_loam_200L` as the default `digging_result` for terrain that doesn't have an override specified. I could've sworn I updated that in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5409 but nope.

## Describe alternatives you've considered

screm

## Testing

1. Used my fucking eyes.
2. Compiled and load-tested.
3. Dug a deep pit, depositing the yield of each step in a different tile.
4. It actually produces dirt, about 200 liters from a shallow pit and about 400 for a deep pit, as expected.

image

### CODE REVIEW

**Comment by RoyalFox2140** [comment]
This is what I get for saying I'll playtest things.

**Comment by chaosvolt** [comment]
I playtested it too, just I tested everything I changed and forgot that I overlooked something very important that I didn't change... :<

**Review by scarf005 — APPROVED** [review]

**Review by RoyalFox2140 — APPROVED** [review]
Just waiting for tests now.

**Comment by chaosvolt** [comment]
Test faster aaaaaaa

**Pull request merged**
