### PR TITLE
fix: Erased the npc Alonso from history (the game)

### PR DESCRIPTION
**Pull request by AniDemi**
## Summary
SUMMARY: Bugfixes "Removed the npc Alonso from the game"

## Purpose of change
"Alonso wants to be the town bicycle, but isn't getting as much interest as he'd hoped.  He'll trade a morale bonus for condoms." This is the character description. The entire point of this npc is to be horny and this doesn't mesh well with the rest of the game and would be much better to just delete or delegate to an adult mod.

## Describe the solution
1. Moved Alonso to the npc obsoletion file
2. Created a new file for obsoleted npc dialogue
3. Did the same in a mod for mod dialogue
4. Removed references to the npc in dialogue

## Describe alternatives you've considered
Rewrite the character to be charming rather than cringe

## Testing
Loaded the npc before changes and confirmed that his dialogue still works after being moved to obsoletion, also tested that the correct dialogue options pop up when the dino mod is on.

## Checklist

If this is a PR that removes JSON entities:
- [x] The removed JSON entities have new entries in `data/json/obsoletion/` folder.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Eh, making his dialogue better seems like the better option to me. Removing things instead of fixing them is pretty solidly the DDA way of doing things.

**Comment by RoyalFox2140** [comment]
> Eh, making his dialogue better seems like the better option to me. Removing things instead of fixing them is pretty solidly the DDA way of doing things.

This character offends a large number of players in the community when it comes up on the Discord. I see no reason to salvage offensive content.

**Comment by KheirFerrum** [comment]
> Eh, making his dialogue better seems like the better option to me. Removing things instead of fixing them is pretty solidly the DDA way of doing things.

I'm not sure this works though, we'd pretty much have to create a whole new character, and Alonso in nothing but name. Alonso as is doesn't contribute anything to the player experience except being a walking "funni nymphomaniac", so I think obsoleting him will be the right call. Leaving in bad unfinished things so that other people will fix him is also kind of a DDA way of doing things.

**Comment by chaosvolt** [comment]
That said, obsoleting him and re-adding later when someone has the time and energy to rework him to have better dialogue, likely as part of general dialogue improvements and other NPC stuff, is an option too that can follow from this.

If nothing else I'd want to remove the optional sexual encounter until after we at least have the ability for NPC dialogue to check character age, to have him go "nope" to underage characters (or just remove the character age option entirely since its original purpose was just for BMI stuff that's no longer present).

**Comment by LyleSY** [comment]
I agree with the DinoMod changes if the overall PR is merged, they appear to be consistent and shouldn't break anything. From a DinoMod perspective, there is only Alonso content because Alonso is part of the vanilla experience and DinoMod is intended as much as possible to mesh nicely with the vanilla content.
To the larger question (looking at the Design Doc here https://github.com/cataclysmbnteam/Cataclysm-BN/wiki/Design-document ), I see support for Alonso to the extent that he is fun and liked (my view, but clearly not universal) and problems to the extent that he is unfinished, useless, and not fun and not liked. I have no strong opinion either way, I think BN will be good with or without Alonso.

**Comment by Krwak** [comment]
Please remove Alonso, it's about time that this controversial character is obsoleted.

**Comment by Unrepentant-Atheist** [comment]
> This character offends a large number of players in the community when it comes up on the Discord. I

Large? You got some numbers....? Just because some active players are offended, does not constitute a large player base. Sorry, but no.

That said, if the entire point of this character is to be a...fuck toy...obsolete it or no, don't care either way.

**Comment by RoyalFox2140** [comment]
> > This character offends a large number of players in the community when it comes up on the Discord. I
> 
> Large? You got some numbers....? Just because some active players are offended, does not constitute a large player base. Sorry, but no.
> 
> That said, if the entire point of this character is to be a...fuck toy...obsolete it or no, don't care either way.

https://discord.com/channels/830879262763909202/830916511416975401/891517992670736474
https://discord.com/channels/830879262763909202/830916329053487124/892111602843779094
https://discord.com/channels/830879262763909202/831347917809909803/892829076115578900
https://discord.com/channels/830879262763909202/830916451517857894/948164413104484403
https://discord.com/channels/830879262763909202/830916329053487124/948165843102101584
https://discord.com/channels/830879262763909202/830916451517857894/948356952898019469
https://discord.com/channels/830879262763909202/831347917809909803/967855233147478078
https://discord.com/channels/830879262763909202/831347917809909803/988607763968040980
https://discord.com/channels/830879262763909202/831347917809909803/988608700996526161
https://discord.com/channels/830879262763909202/831347917809909803/1020484890178895893
https://discord.com/channels/830879262763909202/831347917809909803/1024778347089231882
https://discord.com/channels/830879262763909202/830916415182733322/1166574619751350302

You are very quick to glomp onto discussions and issues to make offtopic jokes but this time you're just doing on research on the topic. Either you want crude vulgar humor that most of the time when it's brought up people dislike, or you're trolling. This was a quick cursory search with just the keyword Alonso.

**Comment by chaosvolt** [comment]
I would prefer we do not turn this into a heated argument over an NPC in a video game, and keep things on-topic here rather than stirring drama over how many people complain about it or for why, thanks.

**Comment by scarf005** [comment]
for further discussion, please visit #3584.

**Review by chaosvolt — APPROVED** [review]
1. Load-tested JSON changes, no errors.
2. Spawned in the refugee center, still no errors.

**Comment by scarf005** [comment]
image

since overwhelming amount of votes were pointing `YES`, @olanti-p decided to merge this in advance. however, this doesn't invalidate poll result; if in the remaining days the vote result is reversed, this PR will get reverted.

**Pull request merged**
