### PR TITLE
feat: remove Ugly/Deformed from Feline/Lupine mutation path

### PR DESCRIPTION
**Pull request by DoubleBullfrog**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.
## Purpose of change

Feline and Lupine have both Ugly/Deformed and Pretty/Beautiful in their mutation categories, so often instead of advancing other mutations they will swap back and forth between Pretty and Ugly and waste your mutagen.

## Describe the solution

Pick either being pretty or being ugly. I picked pretty.

## Describe alternatives you've considered
Cat and Dog mutants could be ugly instead, but we've got a bunch of ugly mutants and not a lot of pretty ones.

## Additional context
image

### CODE REVIEW

**Comment by chaosvolt** [comment]
Ah the eternal saga of tests being weirdly specific in what they're expecting, uuuugh

**Comment by chaosvolt** [comment]
So I'm looking at this and...somehow, it considers plant mutation to be too strong because cats and wolves can no longer become ugly? That's uh...weird.

I dunno what kinda JSON solution would work to fix that. I feel like the flaw here might be that it's very unlikely that "test to" is even remotely needed for the test, because unlike "chance is too low" I see no obvious downside to it being too high.

**Review by chaosvolt — APPROVED** [review]
1. Load-tested on compiled test build.
2. Chugged a fuckload of feline mutagen, then eventually tried some serum.
3. Took a few tries but still got the threshold, seems that was more because there were a TON of feline traits already and it just kept wanting to give me a few more instead of breaching the threshold even after mutation category strength was well over 100.
4. Repeated test with lupine mutagen, same general result. Lot of mutations to grant so threshold needing some extra help seems to just be RNG. I'd gotten "straining" messages indicating the mutagen was trying to breach a threshold too
5. A second test with lupine mutagen, this time stopping when I saw a straining message to check category strength, showed that lupine was as expected the highest category, but only at a mere 64. Feline was second-closest at 45.
6. Just in case did a plant mutagen test, it triggered the threshold immediately after only 10 doses of mutagen.

My rough guess is eventually, if I ever get around to overhauling mutation categories with more interlocked mutation chains and/or more specialized traits, the mammal categories in general will need more specialization.

**Comment by Unrepentant-Atheist** [comment]
But what aboot 
image

**Pull request merged**
