### PR TITLE
Prying doors with makeshift crowbar, take 2

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Balance "Changes to allow prying doors and windows with makeshift crowbar once more"

#### Purpose of change

Picking up where @Lamandus left off, to revive the initial project of making makeshift crowbars work on doors again, including some feedback that was added during discussion of their PR.

#### Describe the solution

1. Per suggestion, set it so that doors and windows can be pried with prying 1 instead of 2. Door difficulty increased from 8 to 11, so that the effective difficulty is completely unchanged for prying tools of quality 2 and up.
2. Ported over description change from previous PR, plus a slight tweak to remove a now-extraneous conjunction.
3. Ported over recipe change making it so makeshift crowbar requires hammering 2 to make instead of just 1.

#### Describe alternatives you've considered

1. Lamandus' own take on it was to entail raising prying quality of makeshift crowbar to 2, which has the minor disadvantage of making the makeshift crowbar compete with the claw bar.
2. Lowering window difficulty by 1 maybe, to meaningfully distinguish them from doors? That'd be about as low as it can be allowed to go unless we test how the function parses a difficulty of zero, as it'd be a diff of 1 with halligan bar.

#### Testing

1. Checked affected files for syntax and lint errors.
2. Ported file changes over to test build.
3. Can attempt to pry open locked doors and windows with makeshift crowbar.

#### Additional context

Previous attempt at this: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/835

As noted, here's the odds for standard doors: https://anydice.com/program/25639 Success rate table: 

Context | 8 Strength | 12 Strength | 16 Strength | 20 Strength
------------ | ------------- | ------------- | ------------- | -------------
Prying 1 (Difficulty: 11) | 20.64% | 56.25% | 79.83% | 90.6%
Prying 2 (Difficulty: 8) | 46.98% | 81.34% | 93.26% | 97.17%
Prying 3 (Difficulty: 5) | 84.29% | 96.53% | 98.9% | 99.55%
Prying 4 (Difficulty: 2) | 99.51% | 99.9% | 99.97% | 99.99%

The chances for prying quality 2+ are identical to vanilla due to the extra +3 base difficulty.

And chance of breaking doors/windows: https://anydice.com/program/265af Breakage rate on failure table:

Context | Breakage Chance, Mechanics 0 | Breakage Chance, Mechanics 5 | Breakage Chance, Mechanics 10
------------ | ------------- | ------------- | -------------
Pry 1, Str 8 (Diff 11) | 72.28% | 26% | 8.97%
Pry 2, Str 8 (Diff 8) | 47.59% | 8.19% | 2.25%
Pry 3, Str 8 (Diff 5) | 6.83% | 0.06% | 0.01%
Pry 4, Str 8 (Diff 2) | 0% | 0% | 0%
Pry 1, Str 20 (Diff 11) | 15.67% | 4.49% | 1.52%
Pry 2, Str 20 (Diff 8) | 8.14% | 1.32% | 0.36%
Pry 3, Str 20 (Diff 5) | 1.09% | 0.01% | 0.00%
Pry 4, Str 20 (Diff 2) | 0% | 0% | 0%

### CODE REVIEW

**Comment by Coolthulhu** [comment]
What's the damage chance?

**Comment by chaosvolt** [comment]
Will write up damage chance math when I get home, sorry for forgetting that.

**Comment by chaosvolt** [comment]
Added table for breakage chance. As with prying roll success table, odds should be unchanged for qualities 2 and up.

**Comment by chaosvolt** [comment]
Is this missing anything important? Far as I can tell it should be ready, lacks merge conflicts, and the only feedback request was for a roll table for breakage chance which is currently in the PR OP.

**Pull request merged**
