### PR TITLE
[WIP] [CR] Implement vitamin effects take 2

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Implement vitamin effects
Another take on: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/598

#### Summary
SUMMARY: Content "Implement vitamin effects"

#### Purpose of change
https://github.com/cataclysmbnteam/Cataclysm-BN/projects/5#card-52246130

#### Describe the solution
From start I've got PK-Rebalance solution, since it is very close to my original ideas:
https://github.com/dissociativity/PKs_Rebalancing/blob/master/pk_effects_override.json#L461

Now vitamin effects of deficiency actually going to do something.
I've intended to use existing effects.

- [ ] Vitamin A deficiency ("A lack of vitamin A in your diet will progressively worsen your vision.") ("VitA deficiency", "Poor vision", "Night blindness" ) - Reduce perception and intellect.
- [ ] Vitamin B deficiency ("A lack of vitamin B12 in your diet will affect your ability to heal." ) ("B12 deficiency", "Slow healing", "No healing") - Reduce stamina. Chance of pain (TODO: Reqwork)
- [ ] Vitamin C deficiency (Scurvy) ("A lack of vitamin C in your diet will result in progressively worse symptoms of scurvy.") ("Early scurvy", "Scurvy", "Bad Scurvy") - Reduce all stats. Reduce stamina. Chance of pain.
- [ ] Hypervitaminosis (too many vitamins) ("An excess of vitamins has badly affected your metabolism." ) - Increase hunger. Reduce stamina and speed.
- [ ]  Calcium deficiency (Hypocalcemia ) ("A lack of calcium in your diet will make your bones progressively weaker." ) ( "Hypocalcemia", "Weak bones", "Brittle bones") - Reduce speed and strenght.
- [ ] Iron deficiency (Anemia) ("A lack of iron in your diet will result in progressively worsening anemia.") ("Iron deficiency", "Early anemia", "Anemia") - Reduce speed, stamina and increase fatigue.

#### Describe alternatives you've considered
Get rid of vitamins

#### Testing
1) Change player vitamin needs
2) Observe player stats

#### Additional context
I am trying to use exisitng effects instead of creating totally new.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Remainder from BroadFlatNails:

> I'd say the stat penalty total should be:
> lvl 1 should only lower one stat by 1, maybe two stats if it does nothing else
> lvl 2 should lower 3 in total stat count (1+1+1, 1+2, or just one stat by 3) or 2 in stats and some other effect (not sure what)
> lvl 3 up to 5 in stats
> Not all effects need stat penalties
> And not all effects need non-stat penalties
> Speed penalty is a good way of adding something painful but not deadly

**Comment by Coolthulhu** [comment]
I think you should start with 1 or 2 effects and ensure they are properly balanced: possible to take care of without having to take pills for them, but likely to happen if the player has a monotonous diet for a week or so.

I'd say that Calcium and Vit C look easiest here.
Both of these should be workable both for carnivores and herbivores without using pills.

Would be nice to have a challenge scenario where you start deficient on all vitamins. Can't be done with json alone, though.

Until we have all vitamins properly balanced, I'd say the no-vitamins mod should be in `data/mods/default.json`
Well-working vitamins could be a nice addition to the game, but vitamins that only work halfway-well could be really annoying.

**Comment by Firestorm01X2** [comment]
> Until we have all vitamins properly balanced, I'd say the no-vitamins mod should be in `data/mods/default.json`

There is problem with that approach, since this way there will be no player feedback. And  That  could lead to situation that vitamins never going to be enabled. Just like NPC Needs.

**Comment by Firestorm01X2** [comment]
> I think you should start with 1 or 2 effects

Considering number of effects- there are 6 effects - it is not that huge numbers. It is potentially could be handled at ones.

**Comment by Coolthulhu** [comment]
> Considering number of effects- there are 6 effects - it is not that huge numbers.

It may take a long time to balance all 6 at once enough for it to be good as default.
At the minimum, I'll want an example diet that satisfies all of:
* kcal not more than 2500/day
* All the vitamins satisfied at least 100%
* No food that can't be crafted from common ingredients (multivitamins can't be crafted)
* No farming, milking cows, or ingredients that are only available at start of the game and then rot away

Additionally, characters with one dietary restriction should still be playable:
* Meat intolerance
* Vegetable allergy
* Carnivore
* Herbivore

I don't think the current vitamin values guarantee that it's achievable.

**Comment by chaosvolt** [comment]
> TODO: Recall @chaosvolt advices.

I'd have to look up what thoughts I gave last time as well, but above comment about sanity-checking the existing vitamins was related to it if I recall. It's a lot better than it was early on when vitamins were first implemented, but always worth poking through comestibles as you work on each vitamin to see what could use an update.

Or even just a quick search for common sources of said vitamin in real life to make sure all such foods cited as common examples (of those present in-game) have said vitamin, likely the fastest way to root out any obvious holes in coverage without distracting too much from the actual main effort.

**Comment by Frost-wood** [comment]
The problem with vitamins, is that there is no way of knowing until the effects actually occurs, which is why it's a unpopular feature.

At the very least it should start with no "base-mods" to give the player a warning period.  The scale-up should also be slower-vitamin deficiency isn't a fast process, especially in the case of B12.

**Comment by Firestorm01X2** [comment]
> At the very least it should start with no "base-mods" to give the player a warning period.

After some thinking I've decided that it it going to be better option for now. If feature is not balanced at all- then likely it has to be checked from the scratch. And I am not even sure it is worth effort.

**Comment by Firestorm01X2** [comment]
After all DDA disabled this feature after all those years.

**Comment by chaosvolt** [comment]
Take your time, work on improving any parts that'd make it less problematic when the mood strikes, and over time the mechanic should get better.

**Pull request closed without merging**
