### PR TITLE
feat(balance): Reduce RNG that can produce necromancers and masters in the early game.

### PR DESCRIPTION
**Pull request by RedPine91**
## Purpose of change

- closes #3863

Make Zombie Masters and Necromancers more rare, by making them evolutions of the already rare Zombie Hollow.

## Describe the solution

Regular unevolved zombies have a small chance of upgrading into Hollow zombies.
Hollow zombies evolve into Necromancers with a half life of 30 days.
Necromancers evolve into Masters with a half life of 60 days.
Masters evolve back into Hollow zombies with a half life of 15 days.

## Describe alternatives you've considered

1) Creating new zombie groups, that existing zombie groups have a chance of upgrading into.  IE, Group_Zombie_Upgrade has a chance of evolving into a T2 zombie, that T2 zombie has a chance of evolving into any Group_Zombie_Upgrade2 zombie, this group has a chance of evolving into a T3 zombie, etc.

2) Creating "clones" of existing zombies with identical stats to the original, but custom evolution paths.  IE, an ordinary zombie can evolve into zombie(Necro-5), which can evolve into zombie(Necro-4), etc., where zombie(Necro-1) can finally evolve into a zombie necromancer.

## Testing

I haven't figured out how to test PR's yet, this is my first one.  Have mercy.

## Additional context

I encountered a single Zombie Master on day 5.  By day 6, it had spawned another zombie master and other nasties.  The evolution pool that zombie masters use to upgrade monsters is the same one that turns ordinary zombies directly into zombie masters (with a small chance).  

By adding additional steps between ordinary zombies and masters, the odds of freakishly bad RNG is reduced but not eliminated.

## Checklist

- [ ] Test changes in game.  Find out if my change produces a desirably ratio of hollow/necro/master zombies at years 1, 5, 10.
- [ ] Document the changes in the appropriate location in the `doc/` folder.
- [ ] If documentation for this feature does not exist, please write it or at least note its lack in PR description.
- [ ] If applicable, add checks on game load that would validate the loaded data.
- [ ] If it modifies format of save files, please add migration from the old format.

### CODE REVIEW

**Comment by RedPine91** [comment]
Constructive criticism wanted.  I can already think of some better ways to do this, but I'd like feedback before going back to the drawing board.

**Comment by RedPine91** [comment]
Closing this PR, as a quick discussion in the BN Discord showed a few flaws with this approach.

**Comment by RedPine91** [comment]
Reopening in case anyone has advice on how to approach this issue.  To rehash the discussion on discord:

1) Zombies shouldn't devolve, that's now how evolution is supposed to work (from both a gameplay and immersion perspective)
2) Hollow Zombies should be on a separate path from Necromancers and Masters.
3) Zombie evolution in general could use a rework, since it currently allows tough zombies to turn back into regular zombies.  This is silly, and a waste of processing power.

**Comment by chaosvolt** [comment]
As mused upon in the discord:
```
[7:22 PM]Chaosvolt: Possible alternative: look at how elite survivor zombies and ferals tend to get introduced to monster groups. If you don't want masters and/or necros to appear when normal zeds get zapped by other zombie masters, one could take masters out of the upgrade monstergroups outright, and then put them back into normal monstergroups at a reasonably low weight whether standard zeds spawn, with a starts value roughly consistent with how long they'd take to start showing up under default evolution scaling.
[7:23 PM]Chaosvolt: Noting of course if you go that route that starts is counting hours since that world's start-of-cataclysm date (which is by default 7ish days before game start on default world settings and scenario).
```

**Review by chaosvolt — CHANGES_REQUESTED** [review]
So I kinda stand by my suggestion:
1. Don't have zeds that can evolve normally evolve into necros or masters, since that means the problem you aim to fix just becomes rarer instead of vanishing.
2. Instead move the instances of necros and masters out of the upgrade monstergroup, and place them into monstergroups where zombies normally. Use weights that match how often they'd show up with upgrades (so by default that'd by 8 for necros and 2 for masters, if a monstergroup consists of literally nothing but zeds), and add a `starts` timer to both of about 1000 or so.

**Comment by chaosvolt** [comment]
Alternative solution PR'd in: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3863

**Comment by scarf005** [comment]
Hello @RedPine91, thanks for the first PR! However, I think #3863 might work as a better solution. Thanks for the contribution nonetheless, it helped us making the monster spawn rates.

**Comment by RedPine91** [comment]
Thanks @scarf005 .  I'm new to PR's in generally and I don't have the spare brainpower to do more yet.  I'm just happy I was able to play a small part in the discussion.

**Pull request closed without merging**
