### PR TITLE
fix: remove the sidewalk around the prison

### PR DESCRIPTION
**Pull request by 0Monet**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
Remove the sidewalk around the prison, it is not a city building, so there is no need to put sidewalk on the surrounding roads.
## Describe the solution
Remove the SIDEWALK flag used for the prison.
Remove some of the sidewalk near the entrance of the prison.
## Describe alternatives you've considered
none
## Additional context
Before:
image1
After:
image2

### CODE REVIEW

**Review by scarf005 — COMMENTED** [review]
>Purpose of change
> Remove the sidewalk around the prison

could you explain why the sidewalk needs to be removed? the purpose of change doesn't explain why.

**Comment by 0Monet** [comment]
The reason is that the prison is not a city building, so there is no need to put sidewalk on the surrounding roads.

**Comment by scarf005** [comment]
> The reason is that the prison is not a city building, so there is no need to put sidewalk on the surrounding roads.

please put this on `purpose of change`. current purpose of change only describe what this PR does and does not describe why this change is needed.

**Comment by 0Monet** [comment]
done

**Review by chaosvolt — APPROVED** [review]
Edited it into the PR OP, so yeet.

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
