### PR TITLE
[WIP] Solution to Baking Alive in Summer

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Solution to Baking Alive in Summer

#### Summary
SUMMARY: Rebalance "Rebalancing effect of hot weather to player speed"

#### Purpose of change
Fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/110

#### Describe the solution
Reduce global temperature by changing
`"base_temperature":`
In regional_map_settings.json

#### Describe alternatives you've considered
Changing BODYTEMP_HOT (in weather.h)
Changing effect of the hot weather to player stats

#### Testing
1) Start with basic survivor class.
2)  Move time to Summer
2) It should be less hot in summer.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Considering temperature in summer. I've got temeprature around 28-30 C. So looks like it "Realstic". 
But at the same time player slowed down way too extremely.

**Comment by Firestorm01X2** [comment]
With reduced effect it is even fits more with effect description. Effect of slowdon reduced to 50%.
By effect description player only starting to swet on "Very hot". On "Hot" is only starting feel warm. It we teak into account other effects- reduced slowdown should be fine.

Ready.

**Comment by Coolthulhu** [comment]
I wouldn't say it fixes the problem.
The speed nerf reduction is fine as its own thing, but the problem of naked characters still overheating will require weather changes.

**Comment by Firestorm01X2** [comment]
> The speed nerf reduction is fine as its own thing, but the problem of naked characters still overheating will require weather changes.

Considering thermometer stats temperature could be raising up to 30 C. It is believable that is is uncomfortable even for naked person.
But yes- it is not complete fix. Weather should be rebalanced. Or instead there is
```
#define BODYTEMP_FREEZING 500   //!< More aggressive cold effects.
#define BODYTEMP_VERY_COLD 2000 //!< This value means frostbite occurs at the warmest temperature of 1C. If changed, the temp_conv calculation should be reexamined.
#define BODYTEMP_COLD 3500      //!< Frostbite timer will not improve while below this point.
#define BODYTEMP_NORM 5000      //!< Do not change this value, it is an arbitrary anchor on which other calculations are made.
#define BODYTEMP_HOT 6500       //!< Level 1 hotness.
#define BODYTEMP_VERY_HOT 8000  //!< Level 2 hotness.
#define BODYTEMP_SCORCHING 9500 //!< Level 3 hotness.
///@}
```
In weather.h

**Comment by Firestorm01X2** [comment]
Or there is even simplier solution:
```
weather_generator weather_generator::load( const JsonObject &jo )
{
...
    ret.summer_temp_manual_mod = jo.get_int( "summer_temp_manual_mod", -5 );
..
}
```

**Comment by Coolthulhu** [comment]
You added a weird default for summer temperature. That wouldn't do any good at all.
Actual temperature can be modifed in `data/json/regional_map_settings.json`.
Lowering the average temperature would be fine, winters are currently very forgiving unless you're just starting out.

**Comment by Firestorm01X2** [comment]
> 
> 
> You added a weird default for summer temperature. That wouldn't do any good at all.
> Actual temperature can be modifed in `data/json/regional_map_settings.json`.
> Lowering the average temperature would be fine, winters are currently very forgiving unless you're just starting out.

That is working.  I've reverted my changes to hot speed effect - it is not neccesary now.
Ready.

**Comment by Firestorm01X2** [comment]
Side effect of change- player actually has change to freeze to death in spring at night without proper clothes if he is doing nothing but staying outside.
But I consider this a good thing.

**Comment by Firestorm01X2** [comment]
I think now it is ready.

**Comment by Firestorm01X2** [comment]
TODO:
Test Winter

**Pull request merged**
