### PR TITLE
[CR]Vehicle<->grid connector

### PR DESCRIPTION
**Pull request by Coolthulhu**
A furniture part that connects a vehicle to a non-vehicle power grid.

Current limitations that need to be fixed:
* [x] Includes a horrible hack regarding positioning. May require some redesigning to fix.
* [x] No "load balancing" between grid batteries and vehicles
* [x] Jumper-cable-connected vehicles not supported
* [x] Vehicles don't "push" excess power to grid
* [x] Vehicle "finding" code is slow and duplicates existing `vehicle::find_vehicle` (I wish I checked existing code first - it has exactly what I wanted)
* [x] Jumper cable connection to the connector is hacky and disables regular "out of possession" cable handling
* [x] Out-of-bubble processing

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
@Coolthulhu are you going to enable power grid by default now or sometime later?

**Comment by Coolthulhu** [comment]
Probably with this PR, but it might take a while to get it to work.
I'm basically connecting "jumper cable grid" and building grid into one system here and it has multiple quirks.

**Comment by Coolthulhu** [comment]
Alright, this is pretty near completion.
Anyone willing to help with the code quality? I probably made a bunch of questionable decisions in there.

**Comment by Coolthulhu** [comment]
OK, I fixed all the problems I could find.
Grids are currently rather bare feature-wise, so there may be bugs that will only show later, when real features show up.

I tested it like this:
* Spawned a bunch of vehicles and connectors, connected them into a long line (long enough to exclude at least one from the bubble)
* Spawned laser-turret-equipped vehicle and used it to drain the battery
* Confirmed all vehicles have drained batteries
* Turned engine on one of the vehicles
* Waited for a long while
* Confirmed that batteries and vehicles outside of the bubble got charged

Plus there's some test backing, but less extensive than my manual test. It might be worth adding a long chain test, but this thing is already over 2 weeks old, so I'd rather just get it in and fix it later.

Comments requested, especially code quality hints.

**Comment by Coolthulhu** [comment]
Experimentally giving it a go

**Pull request merged**
