### PR TITLE
feat(UI, port): Port hiding clothing from DDA

### PR DESCRIPTION
**Pull request by RobbieNeko**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

- [x] This PR ports commits from DDA or other cataclysm forks.
  - [x] I have attributed original authors in the commit messages adding [`Co-Authored-By`](https://docs.github.com/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) in the commit message.
  - [x] I have linked the URL of original PR(s) in the description.

## Purpose of change
Desired change by many, given how you might like the stats of an item but not want to actually see it on your character.

## Describe the solution

Ports the feature from DDA https://github.com/CleverRaven/Cataclysm-DDA/pull/52054

## Describe alternatives you've considered

- Wait for someone else to do it

## Testing

Loaded in, figured out where it is. It works,
**BUT**
It currently has a visual bug regarding it printing the 'H' indicator on the wrong line. The correct item is still hidden.
Unsure of how to fix, hence the draft
image

## Additional context

Help with figuring out how to fix the visual bug is appreciated

### CODE REVIEW

**Comment by scarf005** [comment]
following fixes have been made after initial PR:
- https://github.com/CleverRaven/Cataclysm-DDA/pull/56362
- https://github.com/CleverRaven/Cataclysm-DDA/pull/58257

**Review by scarf005 — APPROVED** [review]
image

seems to work well after porting https://github.com/CleverRaven/Cataclysm-DDA/pull/58257.
now we only need to add hiding bionics...

**Comment by RobbieNeko** [comment]
Thank you for your assistance!

**Review by RoyalFox2140 — DISMISSED** [review]
Seems to be fine but the problem is we're all Linux users. @chaosvolt >:(

**Review by chaosvolt — CHANGES_REQUESTED** [review]
1. Compiled and load-tested.
2. Spawned in as a shelter baby, tried to hide my shirt...

Default keybind is showing as unknown and trying to manually set it to h is causing this error:
image

It still binds it successfully though afterward, and stays bound after a save/load.

3. Successfully can mark my shirt as hidden, it remains hidden after save/load.

But then it now crashes every time I try to start after testing whether it'd retain it after closing and re-opening...

Gonna try cleaning solution and rebuilding just in case to see if the problem is just on me.

**Comment by chaosvolt** [comment]
Debug contents:
```
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\cataclysm-bn-tiles.exe'. Symbols loaded.
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Program Files\Avast Software\Avast\aswhook.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\mscms.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\coloradapterclient.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\icm32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\MMDevAPI.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\avrt.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\hid.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\dinput8.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Gaming.Input.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\msxml6.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\igd10iumd64.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ncrypt.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ntasn1.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\igdusc64.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\dcomp.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\AudioSes.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\umpdc.dll'. 
'cataclysm-bn-tiles.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. 
Exception thrown at 0x00007FFAA85D3E49 in cataclysm-bn-tiles.exe: Microsoft C++ exception: JsonError at memory location 0x0000008E364FDFE8.
Exception thrown at 0x00007FFAA85D3E49 in cataclysm-bn-tiles.exe: Microsoft C++ exception: std::runtime_error at memory location 0x0000008E364FEFD8.
The thread 0x28dc has exited with code 0 (0x0).
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\igdusc64.dll'
The thread 0x366c has exited with code 0 (0x0).
The thread 0x252c has exited with code 0 (0x0).
The thread 0x3e84 has exited with code 0 (0x0).
The thread 0x70ec has exited with code 0 (0x0).
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\ntasn1.dll'
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\ncrypt.dll'
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\igd10iumd64.dll'
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\d3d11.dll'
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\dcomp.dll'
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\dwmapi.dll'
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\dxgi.dll'
'cataclysm-bn-tiles.exe' (Win32): Unloaded 'C:\Windows\System32\avrt.dll'
The thread 0x52f4 has exited with code 0 (0x0).
The thread 0x4ccc has exited with code -999 (0xfffffc19).
The thread 0x6680 has exited with code -999 (0xfffffc19).
The thread 0x5c88 has exited with code -999 (0xfffffc19).
The thread 0x6e2c has exited with code -999 (0xfffffc19).
The thread 0x4bf4 has exited with code -999 (0xfffffc19).
The thread 0x2c68 has exited with code -999 (0xfffffc19).
The thread 0x6020 has exited with code -999 (0xfffffc19).
The program '[16280] cataclysm-bn-tiles.exe' has exited with code -999 (0xfffffc19).
```

**Review by chaosvolt — APPROVED** [review]
1. Compiled and load-tested, shirt still correctly hidden.
2. Tested changing the keybind, no weird errors like last time.
3. Tested dropping a shirt and putting it back on after it was hidden, it retained its hidden marking. Magic. :o
4. Spawned in a new shirt, it doesn't stay hidden by default.
5. Drop it and grab my old shirt, it's still hidden and in fact will be hidden while the other one is correctly still unhidden. Wizardry!

It wasn't until I dropped both shirts, noticed they didn't stack, and saw a flag text on one of them that I realized how it works, heh. :>

**Pull request merged**
