### PR TITLE
feat(content): bungalow 25

### PR DESCRIPTION
**Pull request by LilShiningMan**
## Summary
SUMMARY: Content "bungalow 25"

## Purpose of change
increase house spawn variety

## Testing
linted, spawns correctly

## Additional context
bungalow 25

bungalow 25 roof

## Checklist

If this is a C++ PR that modifies JSON loading or behavior:
- [ ] Document the changes in the appropriate location in the `doc/` folder.
- [ ] If documentation for this feature does not exist, please write it or at least note its lack in PR description.
- [ ] New localizable fields need to be added to the `lang/bn_extract_json_strings.sh` script if it does not support them yet.
- [ ] If applicable, add checks on game load that would validate the loaded data.
- [ ] If it modifies format of save files, please add migration from the old format.

If this is a PR that modifies build process or code organization:
- [ ] Please document the changes in the appropriate location in the `doc/` folder.
- [ ] If documentation for this feature or process does not exist, please write it.
- [ ] If the change alters versions of software required to build or work with the game, please document it.

If this is a PR that removes JSON entities:
- [ ] The removed JSON entities have new entries in `data/json/obsoletion/` folder.

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]
is the hole in the second floor intentional?

**Comment by LilShiningMan** [comment]
It's actually a skylight. Not sure why it doesn't appear, but when you cursor over it, it displays it as a skylight
skylight

**Comment by chaosvolt** [comment]
Because internally, skylights have to have ledges and are basically open space in all but name pretty much, in order for the light propagation code to work right.

**Comment by LilShiningMan** [comment]
Looking for advice here. Is this good to go or should I make changes?

**Comment by Vollch** [comment]
If you can work with c++ you could port proper skylights implementation, it's just a few lines of code: https://github.com/CleverRaven/Cataclysm-DDA/pull/57551
If not... not a huge deal really. - it can be fixed later on, along with other skylights we currently have.

**Comment by LilShiningMan** [comment]
I'm not much of a coder unfortunately. I'm happy to have this one merged as is.

**Pull request merged**
