### PR TITLE
feat(content): Biodiesel Fuel for Gasoline Engines

### PR DESCRIPTION
**Pull request by yay855**
## Purpose of change

IRL, gasoline powered engines can be modified to accept alcohol as fuel. It had been discussed some time ago that making ingame gas engines able to use ethanol would be acceptable.

## Describe the solution

Gasoline powered engines now are able to use ethanol, methanol, and denatured alcohol as fuel.

## Testing

I've tested it ingame myself, the fix was quick and easy and works fine. Ethanol already had a fuel efficiency number, and methanol and denatured alcohol used copy-from from Ethanol, so it plugged in just fine.

### CODE REVIEW

**Review by scarf005 — DISMISSED** [review]
image
image

wish it could run on vodka

**Comment by KheirFerrum** [comment]
I think making it use alcohols is a bad solution in that it trivializes fuel sourcing and makes bio-diesel essentially obsolete, as bio-diesel is the further processed form of alcohol specifically for fuel usage. In this case, I'd say we eschew realism and make gasoline engines also run off bio-diesel, to prevent gasoline from becoming the new best option by a landslide because you can loot alcohol _everywhere._

**Review by scarf005 — APPROVED** [review]

**Comment by YeOldeMiller** [comment]
Not sure I like the idea of using biodiesel. Burning ethanol in stock unmodified gas engines may be an acceptable stretch, but this is downright unrealistic.

And as for using spirits being unbalanced: sure you can find them everywhere, but in what quantities? If we're talking about regular alcohol, it still needs to be distilled to make usable, greatly reducing the initial volume. Biodiesel, on the other hand, is 100% processed fat. Alcohol is used in its production as a reagent, not as a burnable substance, and in relatively small quantities. Personally I'd still prefer using biodiesel even with ethanol as readily available fuel because of how much easier it is to source large amounts of oils/fats.

**Comment by chaosvolt** [comment]
Worth noting that while plain alcohol is in abundanance, ethanol takes additional time, resources, and tools to set up.

It also has like half the fuel value of biodiesel: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/items/fuel.json#L21

I would say that should've been a reasonable tradeoff for the method to make it being overall simpler (but not really dead simple) than biodiesel.

**Pull request merged**
