### PR TITLE
feat: smoking rack can cure skins

### PR DESCRIPTION
**Pull request by NappingOcean**
## Purpose of change
Make a smoking rack to cure hides or furs.

## Describe the solution
Simply add a `smoking_result` field and `SMOKABLE` flag on the skins.
Those code would make them what I expected.

## Describe alternatives you've considered

~~Gently weeps.~~ Trying it after smoking rack or some iexamine JSONized.

## Additional context

image

image

image

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]
I hate semantic PR title :D

**Comment by Zireael07** [comment]
I think the PR is borked, there are unrelated commits listed

**Review by scarf005 — CHANGES_REQUESTED** [review]
> I think the PR is borked, there are unrelated commits listed

I'll go home and rebase it. Marking it temporary as changes requested in order to prevent accidental merge.

**Comment by scarf005** [comment]
> I hate semantic PR title :D

i hate capital letters :D

**Comment by NappingOcean** [comment]
My mistake. Sorry. Github is too hard for me.

**Pull request closed without merging**
