### PR TITLE
feat(content): Set `3D field of vision` to True by default

### PR DESCRIPTION
**Pull request by Zlorthishen**
## Describe the solution
changes the  `3D field of vision` value to true by default, changes some wording

## Testing
image

### CODE REVIEW

**Comment by chaosvolt** [comment]
>casually doesn't notice that issue is already closed

Yeah about that, we already made z-level behavior mandatory, 3D vision is a different thing entirely.

**Comment by Zlorthishen** [comment]
[anothersimulacrum](https://github.com/anothersimulacrum) should be removed from author. i had left them in from the last pull request i started

**Review by chaosvolt — APPROVED** [review]
Bit belatedly, I'm not sure if there's any major bugs we're missing with the feature, but this is only setting it on as default rather than making it mandatory, so it's probably alright. That said, I'll leave this for @Coolthulhu or @scarf005 to advise on this just in case before merging.

**Review by scarf005 — APPROVED** [review]
i think it'd be ok to turn this on for now, no major bugs i think

**Comment by Unrepentant-Atheist** [comment]
No major bugs, but major lags with it turned on. That's a no-no from me.

**Pull request merged**
