### PR TITLE
Port over crafting UI improvements from DDA

### PR DESCRIPTION
**Pull request by chaosvolt**
Co-Authored-By: Gordon Watt <15700895+Theundyingcode@users.noreply.github.com>

#### Summary

SUMMARY: Interface "Port over changes from DDA allowing crafting menu to show product stack size, amount of product already nearby"

#### Purpose of change

Finally set aside time to port over a thing Lamandus had been asking me about, allowing the crafting UI to show you how many of an object you have nearby, and make it more clear how many items a recipe will make.

Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/449

#### Describe the solution

1. Ported over changes to crafting_gui.cpp, including inventory.h and added if statements to `select_crafting_recipe`.
2. Ported over addition of `inventory::count_item` to inventory.cpp and inventory.h.
3. Ported over addition of `recipe::makes_amount` to recipe.cpp and recipe.h. Converted the function to use BN's handling of item stuff instead of find_type, not sure what DDA PR added that.

#### Describe alternatives you've considered

1. Making Lamandus cry by putting this off even more.
2. Axing the "how many does this recipe make" feature and only porting over the "how many are already nearby" feature, because the item UI already does it better (see below).

#### Testing

1. Compiled and load tested.
2. Checked a mundane shelter to see that clean water was reported as being nearby.
3. Spawned in an absurd amount of something craftable, confirmed the UI nopes out if you have over 9000.
4. Also checked that recipes like arrows, fuel, etc show default stack size in the crafting menu too. See below.

One thing I discovered, for example if you select batch crafting pebbles: it still only shows the default amount made per item, not the grand total that instance of batch-crafting will make. I can't actually tell if this is a bug or just an oversight. Pinging @Theundyingcode for clarity, if they'd be able to confirm what's intended behavior here.

I assume this is because either `if( charges.has_value() )` or `makes = charges.value();` is not actually valid in a way that doesn't cause a compile failure, I searched DDA's source code and noticed that the file change from the source PR was the ONLY hit for `charges.value` so I wonder if that's the case. I tested in DDA as well and confirmed that the version as implemented there does this too, so it's not something BN-specific.

#### Additional context

Source: crafting UI updates, by Theundyingcode: https://github.com/CleverRaven/Cataclysm-DDA/pull/43393

Nearby stuff:
image

What it displays when you almost crash the game attempting to hydrate the gods themselves:
image

Stack size shown in both sections, everything seems normal:
image

And then the part where source PR's implementation does something weird, tested in compiled branch and in DDA:
image

### CODE REVIEW

**Comment by Lamandus** [comment]
> And then the part where source PR's implementation does something weird, tested in compiled branch and in DDA: image

about the last thing: It is actually a bit of a misunderstanding. Recipe makes: 10 PER BATCH. That's why the amount on the right changes, but the "recipe makes" does not.

**Comment by chaosvolt** [comment]
That's what I suspected, that it's an oversight rather than a bug, it just feels really weird for the numbers to disagree on the UI.

**Comment by Lamandus** [comment]
But yes, it is an oversight. Because, the time to craft changes when you change the batch size. So why shouldn't the amount displayed there? Rather have the amount on the right side stay static ... Or maybe kill off one of those numbers, since they are the same

**Comment by chaosvolt** [comment]
Yep, just not sure how to fix that.

**Comment by Lamandus** [comment]
> Yep, just not sure how to fix that.

Maybe change the description. 1x of recipe makes:

**Comment by Lamandus** [comment]
> Yep, just not sure how to fix that.

Maybe change the description. 1x of recipe makes:

**Pull request merged**
