### PR TITLE
feat: sausage casings can be made with plastic and spawngroups

### PR DESCRIPTION
**Pull request by VissValdyr**
## Purpose of change
Since my change suggestions weren't implemented, I did it myself on my old phone again.

## Describe the solution
1. Make plastic bags as alternative for casing production, just remove before eating
2. Added into spawn groups
3. Changed description.

## Additional context
Still pain on my phone.

### CODE REVIEW

**Comment by VissValdyr** [comment]
I hate my phone for doing automatic capital letters.

**Comment by VissValdyr** [comment]
@chaosvolt or @scarf005 . I can't tell why it is failing on me this time. Can you check?

**Comment by chaosvolt** [comment]
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
Error: Process completed with exit code 100.
```
¯\\_(ツ)_/¯

**Comment by VissValdyr** [comment]
> ```
> E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
> Error: Process completed with exit code 100.
> ```
> 
> ¯\_(ツ)_/¯

@chenz

**Comment by VissValdyr** [comment]
> ```
> E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
> Error: Process completed with exit code 100.
> ```
> 
> ¯\_(ツ)_/¯

@Coolthulhu or @olanti-p is there a quick fix for it?

**Comment by VissValdyr** [comment]
Seems to work now. No changes planned anymore. Testing worked fine.

**Comment by KheirFerrum** [comment]
Don't think using plastic for sausage casings is a great idea. My suggestion if this is to allow artificial casings would be to use some collagen based stuff. An example recipe can be seen in our discord discussions [here](https://discord.com/channels/830879262763909202/1232723990943109191).

**Comment by VissValdyr** [comment]
> Don't think using bag plastic for sausage casings is a great idea. My suggestion if this is to allow artificial casings would be to use some collagen based stuff as we do irl. An example recipe can be seen in our discord discussions [here](https://discord.com/channels/830879262763909202/1232723990943109191).

I can't connect to discord for the next 2 weeks. But the problem is follows, there are plastic made sausage castings. You can check wish and other sides. So yes, those exists. The main function of them is to keep the sausage "meat" inside a "container".

How should the collagen stuff work anyway? And this result at least give us the chance to make it without stomachs.

It also took a lot of work me to create. So I would be more comfortable if it gets in the game, and if someone has a better idea in solving the recipe, can do it afterwards or directly here.

**Comment by VissValdyr** [comment]
> Don't think using bag plastic for sausage casings is a great idea. My suggestion if this is to allow artificial casings would be to use some collagen based stuff as we do irl. An example recipe can be seen in our discord discussions [here](https://discord.com/channels/830879262763909202/1232723990943109191).

Screenshot_20240425-083436_Opera


It exists, so I created it. A collagen version can be added later.

**Comment by VissValdyr** [comment]
@chaosvolt so since you seem to be online here. Is there anything against the addition? I would be happy for a merge.

**Comment by VissValdyr** [comment]
What is still missing here?

**Comment by VissValdyr** [comment]
> We probably don't need the collagen version to be a completely separate item to be honest, it could instead be an alternative way to make the normal sausage casings instead. Which I figure it's fine to save for a followup PR if need be.
> 
> I'm also not really sure if the plastic version really needs to be a separate item either for that matter? Aside from, what, the need to add a plastic mold to the recipe? Also I was busy basically most of yesterday and got distracted once I finally got home. :V

All good. The reason for it being a separate item is: the material. Plastic version is made of plastic, the other one of flesh. We don't have veggy sausages yet, but if they get into the game, we need a non flesh alternative for vegetarians. That was the reason to make a separate item.

**Review by chaosvolt — APPROVED** [review]
Fair I suppose, material is a tricky thing. I guess main reason it isn't super important is that the end product can't really vary based off input material anyway, and even if it could we don't currently have veggy sausages so it doesn't yet have any gameplay effect whether you use real casings or sausage casings.

Doesn't really mandate insisting the file changes be reverted or anything since it's just a flavor thing all around, so ¯\\_(ツ)_/¯

**Comment by VissValdyr** [comment]
> Fair I suppose, material is a tricky thing. I guess main reason it isn't super important is that the end product can't really vary based off input material anyway, and even if it could we don't currently have veggy sausages so it doesn't yet have any gameplay effect whether you use real casings or sausage casings.
> 
> Doesn't really mandate insisting the file changes be reverted or anything since it's just a flavor thing all around, so ¯\_(ツ)_/¯

I will probably work on a veggy sausages recipe, probably when I get home and get reminded.

**Comment by Unrepentant-Atheist** [comment]
Mmmhmmmmm microplastics in BN, yummy!

**Comment by VissValdyr** [comment]
> Mmmhmmmmm microplastics in BN, yummy!

Only the best plastic!

**Pull request merged**
