### PR TITLE
feat(balance): [CR] Sanity-checking salvage yield of clothing, part 1

### PR DESCRIPTION
**Pull request by chaosvolt**
## Summary

SUMMARY: Balance "Alter item weights and crafting requirements to reduce material loss from salvaging, part 1"

## Purpose of change

So, it is time for suffering. Clothing recipes have had basically zero sanity-checking over the years and whatever the iteminfo test in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2142 is supposed to do, it doesn't seem to be of any help for finding cases where an item is massively out of wack between its salvage yield and recipe requirements so auuuugh fuck I have to do this manually.

This will likely take up multiple PRs, so I'm gonna start with all-cotton items, possibly a few closely-related items here and there. A lot of it is just instances where the items could reasonably afford to just be heavier, while a few use abnormally large amounts of material in their recipes, honestly it's a druken clusterfuck of inconsistencies with no obvious easy answer aaaa

Strap in lads.
Cata++ Be Like

## Describe the solution

1. Increased number of yarn required for a felt patch from 80 to 100 grams, as felt patches are 100 grams while yarn only weighs 1 gram each.
2. Increased weight of arm warmers from 32 grams to 300 grams, putting it closer to the weight of 4 rags.
3. Increased weight of tentacle socks from 360 grams to 1200 grams, reduced required amount of rags from 40 to 16.
4. Decreased number of rags required for stockings from 8 to 4, increased item weight from 90 to 300 grams.
5. Bumped up weight of wool stockings from 125 grams to 320 grams, matching amount of yarn used in its recipe.
6. Bumped up weight of cord sandals from 68 grams to 140 grams, matching amount of thread it's made from.
7. Increased weight of tabi socks from 50 grams to 150 grams, reduced rags required from 3 to 2.
8. Increased weight of footrags from 56 grams to 250 grams, reduced rags required from 6 to 4. Them being looser and less efficient than sewn socks is reasonable, as is them being more lossy than the norm since they have a super-easy reversal, but still warrants a lil tweak.
9. Increased weight of wool footwraps from 56 grams to 350 grams (felt patches are 100 grams each), reduced number required to make from 6 to 4. General consistency with rag version.
10. Increased weight of regular socks from 32 grams to 100 grams.
11. Increased weight of wool socks from 44 grams to 120 grams, increased amount of yarn required to make from 80 to 120. This makes them stay heavier than regular socks.
12. Increased weight of ankle socks from 25 grams to 80 grams.

WIP as hell because there are a lot of items I'm gonna have to sift through, plus I'm strongly uncertain about the best approach going forward due to just how much work and hassle this is turning out to be. There are multiple ways to accomplish this and the above shows a mix of some of the ways to do it, but I'd like feedback on what others feel is the least shitty way to do it.

See alternatives as well.

## Describe alternatives you've considered

1. If we change the weight of threads to 625 mg, we can justify lowering the weight of rags down to 50 grams and making this slightly less CBT to balance out. It'd mean even more sanity-checking of basically every standard clothing recipe in the game but I'm kinda already doing that so...
2. Alternatively, porting over DDA's idea of salvaging cloth items into more granular cotton scrap items would make this a bit less CBT to implement. Salvaging would still be horrifically lossy and I don't really like their half-baked implementation of it currently.
3. Saying "fuck it" and ignoring consistency in favor of only bumping item weights up to a reasonable enough value to approximate how much salvage they uses to give by volume, and relying solely on supplanting cutting items up with uncrafts for anything that's too small to really justify a giant increase in weight, like underwear items already tend to do.
4. Saying "fuck it with extra fuckening" and reverting salvage-by-weight because it's a been pain in the dick in one form or another since first commit.
5. Making basically every especially bothersome recipe reversible, matter compression be damned. On the plus side it'd make craft-grinding tailoring involve 200% less slowly skimming through the menu for a reversible recipe for efficient grinding, but my preferred solution for that would just be to someday make the tailoring and other repair use actions (though moreso ESPECIALLY mechanics interactions) grant skill EXP at a rate that isn't a comically dogshit fraction of crafting EXP.
6. Giving up, reopening https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3414 and begging Alli to suffer the agony of having to sanity-check every recipe in the game instead. With each rag being an eighth the weight of the amount of thread required to make it, making it consistent is probably going to be even more effort than half the other solutions I could favor though.
7. Making yarn weigh 125 mg each to avoid the above weirdness with felt patches generating mass when knitted together. This would warrant a second pass on the amounts of yarn used in recipes where items are knitted directly from yarn.

## Testing

Testing of syntax and lint to ensue as implementation continues.

## Additional context

Nomex, fur, leather, and such will have to be covered in a part two.

### CODE REVIEW

**Comment by YakumoChen** [comment]
Noticed evening gown gave a lot more than it took when I crafted it for xp, if it helps

**Comment by chaosvolt** [comment]
It will, yeah. There are a couple PRs tackling similar flaws with this that I'll likely want to wait on, plus when I return to this I'm likely gonna revert a lot of the "beef up weight of tiny items" changes I started to make in favor of using uncrafts into thread.

**Comment by YakumoChen** [comment]
Is it possible to have recipes simply refer to the weight of the items in rags in some ratio, like salvaging in reverse? Plus a little extra.

**Comment by chaosvolt** [comment]
Closing for now, I'm gonna have to redo this some anyway.

**Pull request closed without merging**
