### PR TITLE
feat(balance): define itemgroups for bandit armor and weapons

### PR DESCRIPTION
**Pull request by chaosvolt**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

This finally actually defines itemgroups for bandit and thug NPC items, so they favor more biker and Mad Max style gear instead of mostly using the same itemgroups as generic NPCs.

## Describe the solution

1. Defined a new NPC class `NC_BANDIT`, which is similar to `NC_THUG` except getting a broad focus on ranged skills instead of melee.
2. Set generic ranged bandits to use `NC_BANDIT` instead of `NC_SCAVENGER`.
3. Defined a bunch of accompanying itemgroups for bandit armor. Generally leans a lot more towards the expected biker and Mad Max asthetic as you'd expect with less normal clothes. Their "extra" items also include less jewelry but a better variety of such when they do spawn it, allowing for a few other alternatives like elbow+knee pads or even shields.
4. Rigged it so that `NC_THUG` automatically gets the same armor choices as `NC_BANDIT` where relevant.
5. Defined a proper, full set of relevant weapon itemgroups for `NC_BANDIT` and `NC_THUG`. They're also rigged such that thugs that choose to spawn with a ranged weapon will randomly pick either bandit weapons or nothing, and vice-versa with melee bandits only sometimes rolling the thug's weapon list.
6. Misc: Adjust the weights of saigas in `guns_shotgun_obscure` and `carried_guns_shotgun_obscure` because it was odd that the .410 variant was more common than the 12 gauge one, and I wanted it to stay consistent with the rate of appearance in bandit inventory.
7. Misc: Fixed crude rocket launcher not being present in `guns_launcher_improvised`.
8. Misc; Set two tacoma ranch NPCs to use different NPC classes that were set to count as thugs, a random farmer and a construction worker.

## Describe alternatives you've considered

Defining these via overrides instead to use a giant collection for their armor items.

## Testing

1. Checked affected files for syntax and lint errors.
2. Load-tested in compiled test build.
3. Debugged in a bandit camp and warped there.
4. No errors, looked at their items and they seem to more or less fit expectations.
5. Debug-killed them all to examine inventory contents, also more or less as expected.

<details><summary>Screenshots:</summary>

body1
body2
body3
body4
body5

</details>

One thing I noticed however is I still sometimes see masks and vests only present in the default NPC itemgroups, which I assume happens when it tries to spawn a null result for that slot?

### CODE REVIEW

**Comment by RoyalFox2140** [comment]
Up next on the list of things Chaosvolt did while failing to fall asleep!

**Comment by chaosvolt** [comment]
eepy

**Review by RoyalFox2140 — APPROVED** [review]

**Comment by chaosvolt** [comment]
Forgot that there were two NPCs using the thug class that likely shouldn't be.

**Review by RoyalFox2140 — APPROVED** [review]
Okay, if there's no more last minute changes.

**Comment by chaosvolt** [comment]
I will note that switching to an overriding collection for worn armor would've probably fixed my weird issue I was having, but in return the drawback of that is losing the automatic hardcoded ability to add different armor itemgroups based on NPC gender. Female bandits get very little real use out of this anyway though (no change in jewelry, at most sometimes they get corsets or skirts instead of shirts and pants, and of course using the standard NPC underwear variation) so that could be reasonable to do in a followup PR maybe.

**Pull request merged**
