### PR TITLE
Weapon mods don't affect aim time because of their volume.

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Balance "Weapon mods don't affect weapon performance by their shear volume."

#### Purpose of change
Weapon mods rarely made weapons better. Their volume made the gun less reliable and problematic. This changes the code to only consider base volume.

the Aim cap is not affected by this change and is probably something we have to tackle further on. But this is something I can live by.

#### Testing
Weapon with mods before:
image
image

this is after:
image
image

### CODE REVIEW

**Comment by Lamandus** [comment]
if anyone can see how I can elegantly fix the errors in the test, would be nice

**Comment by chaosvolt** [comment]
Let's see...it seems what it's complaining about that needs to be changed is the `hit_rate` used in some of the tests in `tests/ranged_balance.cpp`. It seems to get `hit_rate` and add 0.3 to get `hit_rate_cap`. So that should mean...
Change:
```
    SECTION( "an unskilled shooter with an inaccurate rifle" ) {
        arm_character( shooter, "m1918" );
        test_shooting_scenario( shooter, 5, 9, 25 );
        test_fast_shooting( shooter, 80, 0.2 );
    }
```
to:
```
    SECTION( "an unskilled shooter with an inaccurate rifle" ) {
        arm_character( shooter, "m1918" );
        test_shooting_scenario( shooter, 5, 9, 25 );
        test_fast_shooting( shooter, 80, 0.4 );
    }
```

Then:
```
    SECTION( "a skilled shooter with an accurate rifle" ) {
        arm_character( shooter, "ar15", { "tele_sight" } );
        test_shooting_scenario( shooter, 10, 22, 48 );
        test_fast_shooting( shooter, 85, 0.3 );
    }
```
To:
```
    SECTION( "a skilled shooter with an accurate rifle" ) {
        arm_character( shooter, "ar15", { "tele_sight" } );
        test_shooting_scenario( shooter, 10, 22, 48 );
        test_fast_shooting( shooter, 85, 0.7 );
    }
```

Then:
```
    SECTION( "an expert archer with an excellent crossbow" ) {
        arm_character( shooter, "compcrossbow", { "holo_sight" }, "bolt_cf" );
        test_shooting_scenario( shooter, 12, 20, 100 );
        test_fast_shooting( shooter, 50, 0.4 );
    }
```
To:
```
    SECTION( "an expert archer with an excellent crossbow" ) {
        arm_character( shooter, "compcrossbow", { "holo_sight" }, "bolt_cf" );
        test_shooting_scenario( shooter, 12, 20, 100 );
        test_fast_shooting( shooter, 50, 0.5 );
    }
```

**Comment by Lamandus** [comment]
thanks a lot!

**Comment by leoCottret** [comment]
If someone see this review and wonder why it's not merged (I wasn't the first), here are Coolthulhu explanations on Discord:

"I don't think it really solves the problem. It makes gun mods stronger, but does nothing for unmodded guns, makes gunmods free, keeps the faulty formula with all its flaws."

"I'd like a solution that improves the gunmod thing. It can be simple, but it has to meet some criteria:
* Don't just use base gun volume (no gunmods) for aim cap - many guns are at the cap already
* Completely turn aim times upside down - unless the PR explains it well what the new values are, if there are edge cases, how does it change gameplay
* Can't be arcane to player (hidden, secret knowledge). Current state counts as arcane, so it's easy to meet this bit.
* Has a stated goal and explanation how it moves the design closer to it.
I think the simplest way would be to get rid of the cap altogether and just use volume to penalize aim times."

**Comment by Lamandus** [comment]
no solution can be found by me. Someone else is free to take over.

**Pull request closed without merging**
