### PR TITLE
Mainline Stone Chisel

### PR DESCRIPTION
**Pull request by RobbieNeko**
## Summary

SUMMARY: Content "Mainlined Stone Chisel from Magiclysm"

## Purpose of change

The stone chisel wasn't actually in vanilla BN, with Magiclysm having me totally fooled and thinking it was already in vanilla. I see no good reason for vanilla to only have tools with chiseling 3. This will allow for more variety in chiseling requirements in recipes and constructions. I see no good reason for this to not be a vanilla BN item.

## Describe the solution

Adds the stone chisel found in Magiclysm to the list of tools, alongside its recipe. (placed in woodworking due to that being the major use-case I can see)

## Describe alternatives you've considered

None

## Testing

Made sure the game didn't explode in awe of the stone chisel, and confirmed that it is in fact craftable (after fixing the fact that it explicitly said difficulty 0, which the game didn't like)

## Additional context

image

### CODE REVIEW

**Comment by chaosvolt** [comment]
Seems aight, only issue is what would warrant chiseling 1 that isn't already covered by just using cutting quality, I wonder...

**Comment by RobbieNeko** [comment]
> Seems aight, only issue is what would warrant chiseling 1 that isn't already covered by just using cutting quality, I wonder...

A fair question. I will note that, for rocks and similar things that aren't wood (which the chisel (at least by the description) is also intended for.), cutting likely wouldn't be right, but we also wouldn't have a need for  the might of chiseling 3.

**Comment by RobbieNeko** [comment]
Plus, irl there's clearly a reason why chisels are used in woodworking as opposed to merely cutting instruments. Though of course, something being done irl is never necessarily a good argument for doing it in a game. If I had to hazard a guess, I'd posit that chisels allow for better precision.

**Comment by RobbieNeko** [comment]
I'd think that there are some things you simply can't do whittling for. Such as putting certain notches in things, or carving out only very small sections.

**Review by chaosvolt — APPROVED** [review]
Note to self: think up more valid uses for a makeshift chiseling tool. More stone working stuff like the one vanilla example would work.

**Comment by RobbieNeko** [comment]
Aye, some more stoneworking could definitely work. Or some more complex wood crafts.

**Comment by RobbieNeko** [comment]
Plus hey, now it justifies the chiseling requirements I gave the advanced deconstructions a while back xD

**Review by scarf005 — APPROVED** [review]
image

**Review by scarf005 — APPROVED** [review]

**Pull request merged**
