### PR TITLE
feat(port): UI, accessibility updates, tweaks

### PR DESCRIPTION
**Pull request by Kenan2000**
Ports these pull requests

CleverRaven/Cataclysm-DDA#40961,
CleverRaven/Cataclysm-DDA#41866,
CleverRaven/Cataclysm-DDA#47263,
CleverRaven/Cataclysm-DDA#56212,
CleverRaven/Cataclysm-DDA#46796,
CleverRaven/Cataclysm-DDA#55152,
CleverRaven/Cataclysm-DDA#57266,
https://github.com/CleverRaven/Cataclysm-DDA/pull/47584,
https://github.com/CleverRaven/Cataclysm-DDA/pull/47585,
https://github.com/CleverRaven/Cataclysm-DDA/pull/58609,
https://github.com/CleverRaven/Cataclysm-DDA/pull/51447,
https://github.com/CleverRaven/Cataclysm-DDA/pull/59035, 
https://github.com/CleverRaven/Cataclysm-DDA/pull/50892,
https://github.com/CleverRaven/Cataclysm-DDA/pull/41605,
https://github.com/CleverRaven/Cataclysm-DDA/pull/47229, 
https://github.com/CleverRaven/Cataclysm-DDA/pull/57361,

This also includes pull requests #4627, #4623 by @chaosvolt for easier mergeability. This depends on #4634,  https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4635, so it cannot be merged until these are merged 

Though, pull requests 
https://github.com/CleverRaven/Cataclysm-DDA/pull/53069,
https://github.com/CleverRaven/Cataclysm-DDA/pull/65767,
https://github.com/CleverRaven/Cataclysm-DDA/pull/67847, were initially ported but they were reverted because of errors essentially 

So all of errors have been fixed thanks to help of @Coolthulhu, game has been compiled, built, debugged, thanks to explanations of how to do that made by Coolthulhu, @olanti-p, @OrenAudeles, @AlecWhite, @yay855, it works correctly 

Coauthors have been linked properly via GitHub Desktop built-in function to do this work hopefully

### CODE REVIEW

**Comment by Coolthulhu** [comment]
```
Error: src/character_display.cpp:542:30: error: ‘join’ was not declared in this scope
  542 |     const std::string desc = join( s, "\n" );
```

You have to `#include "string_utils.h"` in the include section (top of the file).

```
Error: src/character_display.cpp:1281:24: error: unused variable ‘effect_win_size_y_max’ [-Werror=unused-variable]
 1281 |     const unsigned int effect_win_size_y_max = 1 + static_cast<unsigned>( effect_name_and_text.size() );
```

Just delete the unused variable.

**Comment by Coolthulhu** [comment]
Minor bug:
"Effects" box is not enclosed, but goes down to the bottom of the screen

Screenshot from 2024-05-24 10-50-04

**Comment by Coolthulhu** [comment]
Got a hang-up while drinking water on a fresh save. I don't know if it's from this PR or another, but I can't OK this one until this issue is resolved.

**Comment by Kenan2000** [comment]
So, I want to thank @Coolthulhu for having patience with me learning how to compile, how to build, how to debug game clearly, for helping to fix lots of errors that were present in initial state of this port, @olanti-p for his initial help with fixes, @OrenAudeles for building explanations, @AlecWhite for building explanations, @Zlorthishen for motivation, eagerness to build, @yay855 for great motivation, incredibly quick building, providing explanations of how to install libraries to be able to build, @Zlorthishen for motivation, eagerness to build, so, I also want to thank Qrox who is the author of majority of pull requests in this port for his great accessibility work which gives all of us a great hope that video games along with games in general can be accessible to all of us hopefully as well

**Comment by chaosvolt** [comment]
Wait why was this approved before the other two PRs if it's dependant on them and why did it pass all tests on its own aaaahhh

**Pull request merged**
