### PR TITLE
feat(balance): add `POWERARMOR_COMPATIBLE` flag to most `SKINTIGHT` and `RESTRICT_HANDS` items

### PR DESCRIPTION
**Pull request by chaosvolt**
## Purpose of change

Extends the `POWERARMOR_COMPATIBLE` flag to more stuff. General criteria is allowing it for underwear if it might reasonably seem not excessively bulky, and allowing it for armor where you carry it by a handle since power armor doesn't preclude wielding anything. Also some jewelry items and aura/spell items in mods where relevant.

## Describe the solution

Added `POWERARMOR_COMPATIBLE` to:
<details>
<summary>List:</summary>

* Swimming booties
* Flame-resistant socks
* Socks
* Ankle socks
* Bowling socks
* Wool socks
* Stockings (and wool stockings by proxy)
* Tabi
* Gi tabi
* Glove liners (and wool liners by proxy)
* Flame-resistant gloves
* Tinfoil hat
* Helmet liner
* Flame-resistant hood
* Diamond dental grill
* Garnet dental grill (and other grills by proxy)
* Gold dental grill
* Platinum dental grill
* Diver's watch
* Gold watch
* Silver watch
* Fancy watch
* Platinum watch
* Wrist watch
* Hot pants
* Fur hot pants
* Leggings
* Balaclava
* Union suit
* Moisture retention suit
* Wetsuit
* Wetsuit hood
* Spring suit
* Leotard
* Camo tank top
* Bikini bottom
* Bikini top
* Leather bikini top
* Fur bikini top
* Boxer briefs
* Boxer shorts
* Boy shorts
* Bra
* Briefs
* Camisole
* Long underwear bottom
* Long underwear top
* Sleeveless underwear top
* Panties
* Thermal shirt
* Sports bra
* Tank top
* Tights
* Compression top
* Compression shorts
* Undershirt
* Unitard
* Wooden shield
* Large wooden shield
* Riot shield
* Ballistic shield
* Leather-reinforced shield (and large version by proxy)
* Banded shield (banded shields and large version by proxy)
* Welded shield
* Buckler
* Laundry basket
* Bindle
* Briefcase (and HK briefcase by proxy)
* Violin case
* Hide bag
* Tainted hide bag
* Plastic shopping bag
* Straw basket
* Suitcases
* Thermal socks
* Thermal suits
* Thermal gloves
* Thermal balaclavas
* Thermal outfits
* Ski masks
* Smart watch
</details>

Updated the following items in mods to have the flag:
<details>
<summary>List:</summary>

* Cyropod bodygloves (Aftershock)
* Titanium watch (Aftershock)
* C.R.I.T. fingerless glove liners (C.R.I.T.)
* Acid resist auras (Magiclysm)
* Aura of protection (Magicylsm)
* Flesh pouch (Magiclysm)
* Frost armor (Magiclysm)
* Ice shield (Magiclysm)
* Icy coating (Magicylsm)
* Magic lamps/lights (Magiclysm)
* Magic rings (Magiclysm)
* Obfuscating aura (Magicylsm)
* Overcharge burn hax (Magicylsm)
* Stone gauntlets (Magiclysm)
* Stoneskin coating (Maglclysm)
* Stormfist (Magiclysm)
</details>

Additionally:
1. Updated descriptions for power armor items to say they only exclude MOST clothing, and hint at what is permitted.
2. Gave power armor soldier profession underwear.

## Describe alternatives you've considered

Making a blanket exception in the hardcode for `SKINTIGHT` and `RESTRICT_HANDS` items. I figured some things like mutant clothing and more protective/bulky under-layer items (corsets, kevlar) might reasonably be considered too beefy for this.

## Testing

1. Checked affected files for syntax and lint errors.
2. Load-tested and started as power armor soldier.
3. Underwear spawns correctly, can be taken on and off.

### CODE REVIEW

**Comment by scarf005** [comment]
image

a bit of explanation on why the list formatting went off: inline HTMLs are delimited by empty newlines, thus to render markdown inside html tags, it must be separated via newliens.

https://spec.commonmark.org/0.18/#example-108

**Comment by chaosvolt** [comment]
Yep, fixed that a lil moment ago.

**Comment by chaosvolt** [comment]
Augh fuck, the power armor test failure still cropped up.

**Review by scarf005 — APPROVED** [review]
while i approve that being able to wear more stuff under PA is good, i think it's not feasible to manually managing allowlist like `POWERARMOR_COMPATIBLE`. I suggest using `material_thickness` in the future.

**Pull request merged**
