### PR TITLE
Lower Nomad Gear and Scavenger Gear Warmth

### PR DESCRIPTION
**Pull request by RobbieNeko**
## Summary

SUMMARY: Balance "Lower the warmth values for nomad gear and scavenger gear"

## Purpose of change

40 warmth was an absurd number not supported by the components used to make nomad gear. Additionally lowered the scavenger gear's warmth by a smaller amount.

## Describe the solution

Lowered the nomad gear's warmth to 20, and the scavenger gear's warmth to 30.

## Describe alternatives you've considered

30 warmth for the nomad gear; Technically supported by the cargo pants + duster warmth on the legs, but not for the rest of the body.

Leaving it how it is: I love the concept of nomad gear, but not how oppressively hot it is.

## Testing

This is just a value change for the warmth, I see no real need for testing

## Additional context

There are likely numerous other clothing items with overtuned warmth values for anyone who cares to look at them in the future.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Don't forget:
1. Nomad cowl (35 warmth)
2. Scavenger cowl (40 warmth)

**Comment by RobbieNeko** [comment]
> Don't forget:
> 
> 1. Nomad cowl (35 warmth)
> 2. Scavenger cowl (40 warmth)

Ah, very good point yes. Let me just get those real quick

**Comment by RobbieNeko** [comment]
Cowls gotten

**Review by chaosvolt — APPROVED** [review]

**Comment by chaosvolt** [comment]
Value of 15 for nomad cowl seems fine since light nomad gear has 10, nomad gear has 20, and there's no light variant of the nomad cowl so it fills the same role in either set.

**Comment by RobbieNeko** [comment]
Yup, exactly.

**Pull request merged**
