### PR TITLE
fix: non-threshold mutation Genetically Unstable purifiable

### LINKED ISSUE #3667: Genetic Chaos mutation cannot be removed with purifier
### Describe the bug

The Genetic Chaos mutation, once you get it, cannot be removed. Neither normal purifier nor purifier serum have any effect. A purifier smart shot cannot even be taken if it's your only mutation, it gives a message that "You don't have any mutations to purify."

Since it's not a post-threshold mutation, it should be reversible.

### Steps To Reproduce

1. Drink mutagen until you obtain Genetic Chaos (Chimera mutagen is faster, but you can also get it from normal mutagen)
2. Drink purifier until all your other mutations are gone
3. Genetic Chaos remains, and cannot be removed

### Screenshots

_No response_

### Versions and configuration

- OS: Windows 10 Pro N
- Game Version: 0.4 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MoonlitRiverlight**
## Purpose of change

Fixes #3667: Non-threshold mutation Genetic Chaos being unpurifiable. 
Genetic Chaos has two pre-requisites: Metallassomaiphile (post-threshold) and Genetically Unstable (pre-threshold) and allows acquiring Genetic Chaos without having both at the same time. Genetic Chaos itself isn't a post-threshold mutation but has the unpurifiable flag.

## Describe the solution

Removed _purifiable: false_ from Genetically Chaos in Mutations.json.

## Describe alternatives you've considered

Making it a post-threshold mutation or making both its pre-requisites post-threshold.

## Testing

1.Generated a character.
2.Granted Genetically Chaos via DEBUG.
3.Used a Purifier Smart Shot. Was able to target and purify Genetically Chaos.

### CODE REVIEW

**Comment by KheirFerrum** [comment]
Not really sure this is actually a bug. Genetic Chaos is part of the entire theme of Chimera, and while it doesn't require both pre-requisites it requires one of the two. Allowing you to purify it essentially grants the player free mutations with no drawback whatsoever if we allow you to just purify it away. Would need some testing to see how easy it is to even get Genetic Chaos.

If one considers this to be an unacceptably common state of affairs, then making it require the Chimera threshold would be a better option in my opinion.

**Review by scarf005 — CHANGES_REQUESTED** [review]
[BN uses conventional commits format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/). please check the PR title

**Comment by MoonlitRiverlight** [comment]
> Not really sure this is actually a bug. Genetic Chaos is part of the entire theme of Chimera, and while it doesn't require both pre-requisites it requires one of the two. Allowing you to purify it essentially grants the player free mutations with no drawback whatsoever. Would need some testing to see how easy it is to even get Genetic Chaos (The first of my test characters drank 57 doses of Chimera mutagen to get it).
> 
> If one considers this to be an unacceptably common state of affairs, then making it require the Chimera threshold would be a better option in my opinion.

It isn't too likely, but I've myself had a past playthrough where I had Chaos evolve from Unstable that I acquired to begin with from mutation rays, before I could get any purifier to attempt to clear it. While Unstable is a great way to generate a unique story for a character, it being able to terminally evolve itself into Chaos, which can get you Deteriorating and others over time, takes the game away from your hands.

**Review by Coolthulhu — APPROVED** [review]

**Comment by Coolthulhu** [comment]
I think it's better to have it purifiable. If you can gain it through random mutations, it's not good to have it be "sticky".
Ideally, chimera would have it as a prerequisite and we'd keep prerequisites "locked in" as long as the traits that require them are present.

**Pull request merged**
