### PR TITLE
Add utility vest recipe

### PR DESCRIPTION
**Pull request by SzQ1**
# Purpose of change

Fix lack of recipe for Utility vest. 

# Describe the solution

Add Utility vest recipe.

# Testing

It looks good.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
It seems too good to be craftable at such a low cost. When fitted, it's 3L at 2 encumbrance.
Compare:
* Fanny pack 1.5L at 2 enc
* Leather pouch 1.5L at 3 enc
* Drop leg pouches 2L at 2 enc

While using a more important slot can be considered a balancing factor, it should still be at least as hard to craft as leg pouches are.

**Comment by Coolthulhu** [comment]
Bumping tailoring to 6 makes it a "skill grind" recipe, but doesn't actually increase the cost of crafting it.
Compare with drop leg pouches, which require a plastic crafting set and have 4 tailoring: this is higher cost than this recipe, but not as useful for grinding.

**Comment by SzQ1** [comment]
```
    "id": "fanny",  "fanny pack" 
    "weight": "272 g",
    "volume": "250 ml",
    "covers": [ "TORSO" ],
    "coverage": 10,
    "encumbrance": 2,
    "storage": "1500 ml",
    "material_thickness": 1,
    "flags": [ "WAIST", "WATER_FRIENDLY" ]
    NO RECIPE
```
    "id": "leather_pouch", "leather pouch "
    "weight": "610 g",
    "volume": "500 ml",
    "covers": [ "TORSO" ],
    "coverage": 15,
    "encumbrance": 3,
    "storage": "1500 ml",
    "material_thickness": 1,
    "flags": [ "WAIST", "OVERSIZE", "WATER_FRIENDLY" ]
    RECIPE
    "skill_used": "tailor",
    "difficulty": 2,
    "skills_required": [ "survival", 1 ],
    "time": "10 m",
    "autolearn": true,
    "qualities": [ { "id": "SEW", "level": 1 } ],
    "components": [ [ [ "leather", 6 ], [ "tanned_hide", 1 ], [ "fur", 6 ], [ "tanned_pelt", 1 ] ], [ [ "filament", 10, "LIST" ] ] ]
```
   "id": "legrig", "pair of drop leg pouches"
    "weight": "205 g",
    "volume": "500 ml",
    "covers": [ "LEGS" ],
    "coverage": 20,
    "encumbrance": 5,
    "storage": "2 L",
    "material_thickness": 2,
    "flags": [ "VARSIZE", "WATER_FRIENDLY", "BELTED" ]
    RECIPE
    "skill_used": "tailor",
    "difficulty": 4,
    "skills_required": [ "fabrication", 2 ],
    "time": "20 m",
    "autolearn": true,
    "using": [ [ "sewing_standard", 15 ] ],
    "tools": [ [ [ "surface_heat", 5, "LIST" ] ], [ [ "mold_plastic", -1 ] ] ],
    "components": [ [ [ "rag", 10 ] ], [ [ "plastic_chunk", 2 ] ] ]
```
    "id": "vest", "utility vest"
    "weight": "516 g",
    "volume": "1 L",
    "covers": [ "TORSO" ],
    "coverage": 60,
    "encumbrance": 5,
    "storage": "3 L",
    "warmth": 5,
    "material_thickness": 2,
    "flags": [ "VARSIZE" ]
    RECIPE
    "skill_used": "tailor",
    "difficulty": 5,
    "skills_required": [ "fabrication", 2 ],
    "time": "45 m",
    "autolearn": true,
    "qualities": [ { "id": "SEW", "level": 1 }, { "id": "CUT", "level": 1 } ],
    "using": [ [ "sewing_standard", 50 ] ],
    "tools": [ [ [ "surface_heat", 10, "LIST" ] ], [ [ "mold_plastic", -1 ] ] ],
    "components": [ [ [ "rag", 12 ] ], [ [ "plastic_chunk", 4 ] ] ]
    
Later i will try to make it more comparable.

**Comment by Coolthulhu** [comment]
Looking at nearby recipes, utility vest should be lvl 4, not 5. Lvl 5 all has higher cost, like lots of leather.

**Pull request merged**
