### PR TITLE
feat(balance): allow scrapping a few more items, more ways to obtain rubber

### PR DESCRIPTION
**Pull request by chaosvolt**
### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [X] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [X] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

This allows taking apart a few more assorted items that I found piling up in some of my recent playthroughs.

## Describe the solution

1. Added an uncraft for scissors, so that first aid kits don't leave you with an ever-growing pile of them.
2. Changed dust masks to be made of paper instead of cotton, and added an uncraft to get some paper and string out of them instead of cutting them up into rags.
3. Added an uncraft for unsealed cartons.
4. Set mining helmet recipe to be reversible.
5. Increased weight of rubber gloves from 20 grams to 150 grams since these are generally flavored as kitchen gloves, so that they can yield rubber chunks when cut up. Same general weight ratio relative to rubber boots that leather gloves and regular boots have.
6. Changed material of medical gloves, clown nose, and condom from plastic to rubber.
7. Added a recipe for making rubber chunks from rubber items otherwise too small to cut up into chunks.
8. Increased weight of rubber slug from 2 grams to 8 grams to make more sense in the above recipe, plus that fits in ranges I could find from some rough googling.
9. Per feedback on the discord, allowed uncraft whistles, dog whistles, and whistle multitools.

## Describe alternatives you've considered

Screaming.

## Testing

Checked affected files for syntax and lint errors.

### CODE REVIEW

**Review by RoyalFox2140 — APPROVED** [review]

**Comment by blot-runner** [comment]
>Changed material of medical gloves, clown nose, and condom from plastic to rubber.
Out of curiosity - AFAIK clown noses are made from the polyurethane foam (at least, the ones I've worn were - a dark and troubled part of my biography, don't ask). The closest thing in the game, material-wise, would be sponges and roll mats, both are presently Plastic. Are there any plans on turning them into Rubber too?

**Comment by chaosvolt** [comment]
I definitely have plans to add more uses for rubber, actually. One of these days salvaging that rubber-sole idea from DDA would help distinguish regular boots from leather armor boots better for starters, and existing rubber ideas likely should be craftable at some point in the long run (rubber hoses are extremely useful for crafting and siphoning for example, and leather hose isn't a valid substitute for all applications).

**Comment by RoyalFox2140** [comment]
Repairing wheels.

**Comment by blot-runner** [comment]
> I definitely have plans to add more uses for rubber, actually. One of these days salvaging that rubber-sole idea from DDA would help distinguish regular boots from leather armor boots better for starters, and existing rubber ideas likely should be craftable at some point in the long run (rubber hoses are extremely useful for crafting and siphoning for example, and leather hose isn't a valid substitute for all applications).

Understood, thank you for the clarification.
While we're at it - according to the Wikipedia, one of the C-4 variants (they do differ a bit by the manufacturer) is ~90% RDX and ~10% polyisobutylene, which is also a rubber. Just saying)

**Pull request merged**
