### PR TITLE
feat(UI): New run/crouch icons

### PR DESCRIPTION
**Pull request by thedyze**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional
- [x] I have documented the changes in the appropriate location in the `doc/` folder.

## Purpose of change
Current icons for run and crouch are almost as large as the player. The crouch icon doesn't very clearly communicate `crouch`.

## Describe the solution
This change adds new, smaller and simplified icons for crouch and sprint.

run

crouch

### CODE REVIEW

**Review by RoyalFox2140 — APPROVED** [review]

**Comment by Zireael07** [comment]
Why close?

**Comment by RoyalFox2140** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5674
https://discord.com/channels/830879262763909202/830916451517857894/1304995310044713050

**Comment by thedyze** [comment]
> Why close?

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5702

**Comment by thedyze** [comment]
> Why close?

See mention above :)

**Pull request closed without merging**
