### PR TITLE
Make more fields for bodyparts optional and copiable

### PR DESCRIPTION
**Pull request by KheirFerrum**
#### Summary

SUMMARY: Infrastructure "Make more fields for bodyparts optional and copiable"

#### Purpose of change

- #2482 added essential field to body parts and I learned that @thelonestander had a mod that broke because it overwrote the body parts entirely.
- While looking into fixes for it, learned that copy-from for body-parts is severely limited due to the huge amount of mandatory fields. 

#### Describe the solution

Through use of assign and optional make copy-from less of a pain in the ass for body parts, which should be useful if we further extend body part stuff later on to where modding them becomes more widespread.

#### Describe alternatives you've considered

- Leave copy-from to require 15 different mandatory fields
  - At that point just copy the whole thing.

#### Testing

Use the attached revised CBM Slots mod and check that only mod slots have changed, nothing else.
- Test encumbrance text by wearing two heavy survivor suits and an ANBC suit.
- Test opposite sides are copied properly by wearing a holster and changing sides from the + menu and checking it swaps from one leg to another and not to an arm or something silly.
- Testing hit size is difficult, and subjective. Get hit 100 times while invincible and compare numbers against regular upload branch.

#### Additional context
[Lones CBM slots rebalance.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/11418037/Lones.CBM.slots.rebalance.zip)

### CODE REVIEW

**Review by scarf005 — CHANGES_REQUESTED** [review]
> Use the attached revised CBM Slots mod and check that only mod slots have changed, nothing else.

image

1. installed attached revised CBM Slots mod.
2. failed to create a new player due to errors in slots.

I'm sorry, but i was unable to go through the test due to lack of clear instructions. Could you provide
- detailed instructions to follow
- screenshots comparing before and after the PR that the fields of bodyparts have same value (or in other words, copy-from correctly works for optional fields)?

**Comment by scarf005** [comment]
also changed the title to be more... family friendly

**Comment by KheirFerrum** [comment]
> > Use the attached revised CBM Slots mod and check that only mod slots have changed, nothing else.
> 
> 1. installed attached revised CBM Slots mod.
> 2. failed to create a new player due to errors in slots.
> 
> I'm sorry, but i was unable to go through the test due to lack of clear instructions. Could you provide
> 
> * detailed instructions to follow
> * screenshots comparing before and after the PR that the fields of bodyparts have same value (or in other words, copy-from correctly works for optional fields)?

Can't replicate your error. hit_size was changed to use assign, which makes it impossible for that error to be thrown, you may be using the wrong branch.

**Comment by scarf005** [comment]
i'm testing on your branch.

**Review by scarf005 — APPROVED** [review]
test 1 and 2 is working, so i guess it'd be okay.

**Pull request merged**
