### PR TITLE
Fix PARROT_AT_DANGER attack, proper quotes for new feral lines

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Bugfixes "PARROT_AT_DANGER monster attack can now be triggered when targeting the player, added quotation marks to new feral speech lines."

#### Purpose of change

Dumb thing I forgot in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2809 hecc

In addition, a side effect of this is Scarf discovered that PARROT_AT_DANGER doesn't work if the monster is after the player, they can only see monsters it seems.

#### Describe the solution

1. Fixed new feral lines not having the second layer of quotes so that they'll properly be depicted saying the lines in-game.
2. Updated `mattack::parrot_at_danger` to actually check for if target of the monster has a target they're after (and not a hacky-as-fuck-looking check of all monsters), then if it has a valid target it can see proceeding with the parrot attack.

#### Describe alternatives you've considered

Screaming "I am the night rider!" at the code until it fixes itself for me.

#### Testing

1. Checked affected JSON file for syntax and lint errors.
2. Load-tested in compiled test build.
3. Debugged in a feral biker for a nice, well-lit basement conversation.
4. Correctly got screamed at by the Night Rider (also shot).
5. Tested from stealth that a feral with scream powers stayed silent when left alone, but would yell at monsters spawned for them to get shouty at too.
6. The new lines were also in quotes as expected,.
7. Checked affected C++ file for astyle.

### CODE REVIEW

**Review by scarf005 — COMMENTED** [review]
maybe we should change parrot_common to auto-wrap speech in quotation mark

**Comment by chaosvolt** [comment]
> maybe we should change parrot_common to auto-wrap speech in quotation mark

Problem is some parrot lines are descriptive instead of a quote, like `a little girl screaming!` and such.

**Comment by scarf005** [comment]
oh, alright in that case.

**Review by scarf005 — CHANGES_REQUESTED** [review]
built and spawned two ferals yet got no screm, could you check again?
image

**Comment by chaosvolt** [comment]
Odd, though part of it could be due to the 1-in-20 element of it buried in the code? Either that or I do see the deafened symbol on that character.

I didn't seem to get any hearing impairment from the feral biker's shotgun while testing, but those craters and the mininuke launcher in your character's hands look like a strong hint that something else might've deafened you in a previous test.

**Comment by chaosvolt** [comment]
I did however remove one extra bit of jank I noticed while testing:
image

Given the player's flashlight only gives a light radius and all the ferals described as having a flashlight have luminance already, I think them calling the searchlight special attack as a flavor ability is maybe not worth the weird behavior it can cause.

**Review by scarf005 — APPROVED** [review]
image

silly me, forgor to remove deafness effect after firing that funni nuke

**Pull request merged**
