### PR TITLE
Convert paper from comestible to stackable generic

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Bugfixes "Paper now counts as stackable generic, not comestible"

#### Purpose of change

As Lamandus pointed out, it's a bit weird that paper was still an inedible comestible when by all rights it could reasonably just be ammo or generic instead.

#### Describe the solution

1. Moved item entry for paper from misc comestibles to the file for generic stationary items, and converted it from a comestible to generic with `stackable` set to true. Item size also reduced to 5 mL so that 50 of them still equals 250 mL (due to stack size not being valid with generic stackables.)
2. Since this no longer defines a default stack amount anymore, updated itemgroups, mapgen spawns, and mods accordingly. Most spawns of a single stack now vary a bit more, clutter/trash spawns favor from 1 to 50, while spawns that demanded multiple whole stacks have been translated directly.

#### Describe alternatives you've considered

Also converting bleach, lye, and the like to liquid ammo or what-have-you. Depends on if we want drinking bleach to stay a valid option or not. Also depends on if it correctly queries the player before letting you drink it. If it just lets you chug with no prompt absolutely should be inedible in some way.

#### Testing

1. Checked affected files for syntax and lint errors.
2. Ported JSON changes over to test build.
3. Loaded up a save that had some paper nearby and inventory.
4. Also removed copy-from override that was buried in Nonperishable Overhaul for reasons I'm 90% sure where a joke at the time so the override actually takes.
5. Confirmed via checking beforehand that I still had 3 paper in inventory and 3 paper on the ground afterward, and that no errors ensued on loading.

#### Additional context

Quoth a JSON comment in Nonperishable Overhaul:
```
    "//": "Why in the name of Armok, god of blood, is this even a comestible in the first place?",
```

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Can't it be `GENERIC`?

**Comment by chaosvolt** [comment]
> Can't it be GENERIC?

It could, but then every spawn of paper in itemgroups and elsewhere that doesn't have `charges` or `count` defined will go from spawning 50 to only 1, every spawn of them that uses `count` will need to be multiplied by 50 to produce the same amount, and fairly certain every spawn of them that uses `charges` will have to be converted to use `count` instead.

**Comment by Coolthulhu** [comment]
> will go from spawning 50 to only 1

`"stackable": true`

**Comment by chaosvolt** [comment]
Hmm. Guess I could do that if you'd prefer? Thing is, does that actually allow the default stack size of 50 to still apply? Otherwise that's still going to be a lot of itemgroups that need adjusting.

**Comment by chaosvolt** [comment]
Ah, I'll try and work on this when I get wifi later today then.

**Comment by chaosvolt** [comment]
Okay getting a bit of time to look at this, and problem is I don't see any examples of items that's both type generic, set to stackable, and have a default stack size defined. I'd need to actually test this when I'm out and about since I don't think I'll have time while getting ready, otherwise it'd only work as generic if every spawn in the itemgroups specifies charges. See `ammo_casings_bulk` for an example of a stackable generic being spawned in bulk this way.

**Pull request merged**
