### PR TITLE
make makeshift crowbar great again

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Balance "let the makeshift crowbar pry doors and windows once again!"

#### Purpose of change
Now you can use the makeshift crowbar to pry doors and windows again, like it was back then.

#### Describe alternatives you've considered
there can't be an alternative!

#### Testing
pries well!

### CODE REVIEW

**Comment by SzQ1** [comment]
Right now lockpicks have use beyond opening safes. With makeshift crowbar opening doors lockpicks will barely have any reason to remember to have them. Also makeshift crowbar is too easy to be made if it will have prying 2.

**Comment by Night-Pryanik** [comment]
Making makeshift crowbars being able to pry open doors and windows again would make sense _only_ if they are crafted not from some soft metal pipe you can flatten with a random rock. If crowbar if sturdy enough to withstand heavy pressure you're rendering on it when prying doors and windows, then one shouldn't be able to flatten it with his own hands.

**Comment by chaosvolt** [comment]
>Making makeshift crowbars being able to pry open doors and windows again would make sense only if they are crafted not from some soft metal pipe you can flatten with a random rock. If crowbar if sturdy enough to withstand heavy pressure you're rendering on it when prying doors and windows, then one shouldn't be able to flatten it with his own hands.

You're not flattening a pipe with your bare hands. You're repeatedly banging a pipe down to shape with a heavy object, rather obviously implied to be using concrete or any available surface as an anvil 90% of recipes that involve makeshift metal items made using a hammering quality of 1.

Given the use of pipes to gain additional leverage on a wrench, used as an improvised form of breaker bar, there is already real-world precedent for using pipes as a lever. These ARE considered a potential safety hazard given breaker bars can allow the user to output the kind of torque that would basically ensure something yields eventually (be it the stuck bolt, the wrench, or the pipe) but this entails a degree of force considerably greater than what a wooden doorframe would be able to tolerate.

The realism argument here seems nonsensical to me. Even if it didn't, this is BN where playability and game balance take priority over realism. From that perspective, lockpicks being both super easy to craft but also not that useful is a bigger issue than trying to make makeshift crowbars not useless.

Which right now they are, a dedicated crate-opener is astoundingly pointless given crates rarely show up in areas were being subtle matters, only glass items are at risk if you simply smash the crates, there's no use in having an intact open crate like with an intact door or window, and there's no such thing as a "crate with alarm system" that can summon eyebots (unlike with doors and windows).

More useful ways to nerf the makeshift crowbar:
1. Make it take a hammering quality of 2, implying that the added leverage of a handle is needed to get enough force to flatten the head to a usable degree, which in turn implies the pipe is more robust and thus eliminates the realism problem, and requires the player to build up the most basic level of tools without pushing the makeshift crowbar past the point where it'd be useless to players by the time they can make one.
2. Ensure that pickable metal doors either can't be crowbared open, or require a higher prying quality to do so, if this isn't already implemented (uncertain).

**Comment by Night-Pryanik** [comment]
> The realism argument here seems nonsensical to me.

You seem to think that makeshift crowbar is crafted from sturdy metal pipes - the plumbing ones. IRL they have 2.3+ mm thick steel sides. They are indeed sturdy and suitable for makeshift crowbar that won't break or bend when prying. And I'm not sure if these pipes could be easily flattened by a random rock, no matter if you're doing it on a concrete floor or on an anvil.

Too bad these pipes also drop from smashing lockers or floor lamps. Pipes like these are most likely soft aluminum ones, with a fraction of millimeter thick sides. Pipes like these are easily bended even with bare hands, but they won't keep the shape when trying to pry a door.

> BN where playability and game balance take priority over realism

Makeshift crowbars crafted from soft metal pipes makes finding genuine crowbars and similar tools unneeded. And crafting makeshift crowbar which can pry open doors and windows from materials available right from the start makes all locked door no more than a nuisance even for a completely new character. In my opinion this completely breaks the balance where high-level tools are the things sought after.

> More useful ways to nerf the makeshift crowbar:
>1.
>2.

3. Add another variant of a pipe, a steel plumbing one. Make it spawn in hardware stores, construction sites and other suitable locations. Make these pipes drop when smashing certain plumbing. Make makeshift crowbar require these sturdy pipes, and no nerf at all would be necessary.

**Comment by chaosvolt** [comment]
That would be part of a substantial overhaul of not just all sources of pipes in the game, but also all recipes using pipes. It'd also quickly become a mire of quibbling over which individual furniture should realistically have steel pipes vs. aluminum or lead ones.

But since logically sinks and other water fixtures should realistically have plumbing, then making this idea realistic would go right back to making makeshift crowbars readily available before you've left the shelter. So you can't have it be realistic while also nerfing access to steel pipes.

As for competition with crowbars, there is some value in the success rate of higher quality. A good expansion to fleshing out a rebalance of crowbars would be for prying quality to have more of an impact on success rate, time taken, and possibly chance of accidentally breaking the target terrain and making noise. This would also be a fair bit of effort, but probably less effort than overhauling every spawn of pipes in the game just for the sake of nerfing a single item.

**Comment by SzQ1** [comment]
It's prying 2 that simply opens doors too easily, you very rarely fail, you should often fail at prying 2 so getting actual crowbar with prying 3 would be meaningful.
obraz

**Comment by chaosvolt** [comment]
Looking into this further, and upon double-checking the JSON change, I do see that doing this the JSON way would be slightly problematic. I was mistaken in terms of how the crowbar nerf was actually implemented and how it's being reverted.

Looking into it further, there are two possible ways to go about this:
1. Allowing doors to be opened with prying of 1. This has some problems in that hammers and other tools have prying 1 as well. However, a claw hammer would plausibly have the leverage and strength to do the job, so it might be acceptable. Makeshift hammers lack prying quality, so this would mean the makeshift crowbar would be competing with hammers, a tool that has superior tool qualities in all other respects (in particular being vital for metalworking). The main thing to watch out for would thus be to check what ELSE has prying 1, to ensure there isn't some other tool where this would be too OP.
2. Retaining the current status quo of prying quality 2 being the minimum needed to pry doors, retaining the bump in quality this PR pursues, but rebalance the time taken and success rate so that prying 2 will be less of a step up, which is the gist of SzQ's suggestion. More complex but probably doable without too much hassle, only real complication is this makes compactness the only advantage the claw bar would have over the makeshift crowbar, it would effectively nerf claw bars (i.e. the compact prying-2 ones).

> Also adding another type of pipe seems unnecessary complicating the thing, instead of soft and hard pipes just make makeshift crowbar require anvil 1 and hammering 2. Adding new types of item just for the sake of one item is nonsense that will require additional work, like rubber chunks that were not used anywhere.

I agree with needing hammering 2 to make, disagree on anvil 1. Anvil quality of 1 is a giant hassle to get ahold of, and very few recipes that need hammering 1 and 2 need any anvil quality at all. As mentioned in my first post, it's implied that any available hard surface is being used as an anvil for recipes like this.

**Comment by SzQ1** [comment]
`Anvil 1` is a hassle because it was never needed, we always jump straight on 3 instead of having some use for `anvil 1` that can be obtained by adding `anvil 1` to workshops, steel frame, boulders and probably few other things.

**Comment by chaosvolt** [comment]
It's both underused and not very accessible, I'd say. Boulders are the most accessible option but new players will have trouble figuring that out on their own unless they think to examine the boulder from the `;` menu.

If more flat items made of stone or harder (like bricks, maybe?) listed anvil quality of 1 it'd be more intuitive to players and less of a restriction. This WOULD actually go quite well with one of my misc. to-do entries being to sanity-check what all uses anvil 3 and make more stuff use lower-tier anvil quality, but it would definitely be best applied with a good hard look at what all could plausibly be used as a crude anvil but currently can't.

IRL the bar is set rather low, people have done backyard metalworking with stuff as soft as tree stumps as anvils.

**Comment by Night-Pryanik** [comment]
> make makeshift crowbar require anvil 1 and hammering 2

It doesn't matter if you're using a rock or a hammer to flatten the ends of a pipe. If you're able to flatten and bend it with your hands, then the resulted thing is too soft to be used as a crowbar as it will un-bend upon use.

> Adding new types of item just for the sake of one item is nonsense

What's nonsense here is converting soft aluminum pipe from a locker into a hard steel crowbar through crafting.

**Comment by SzQ1** [comment]
That's partially why, thanks to CV, we adjust prying. Playability first, then we adjust the reasonability.

**Comment by Night-Pryanik** [comment]
And that's why I will never play BN.

**Comment by Firestorm01X2** [comment]
PR, that nerfed makeshift Corwbar for the reference:
https://github.com/CleverRaven/Cataclysm-DDA/pull/36435

**Comment by Night-Pryanik** [comment]
> Then why are you here starting arguments with people over something you're not going to be affected by?

Because I have some thoughts on the matter of this PR I wanted to share?

>Please drop the hostility.

There is no hostility on my side.

**Comment by Coolthulhu** [comment]
Makeshift crowbar doesn't seem like an important item and it seems that opinions are mixed.
I'd need a good gameplay reason.
At the moment I don't see any. Being able to open doors/windows from outside is not a huge deal, but it's still essentially the defining trait of non-makeshift crowbars.

**Comment by chaosvolt** [comment]
I'd say the main advantage of being able to pop open doors is the ability to close them afterward. If you plan to use that building it saves on time and effort fixing a hole in the wall, and if not it preserves the option of being able to close it behind you to block sightlines and slow down approaching monsters.

Buffing the makeshift crowbar makes the item itself actually useful for that purpose, when otherwise it's superfluous. The main balance is indeed that it makes non-makeshift crowbars less unique, which was why the proposal to magnify the impact of prying quality came up. This makes it so that higher prying quality offers more of an advantage, overall taking less time to render a potentially-important entry or escape.

The other disadvantage, as noted, is that makeshift lockpicks will need to be balanced in a follow-up PR to make their respective advantages and disadvantages more distinct.
1. Bashing is loud, fast if you have good stats and gear, slow if if you don't (and a minimum of two hits even at best, if targeting doors), and doesn't preserve the terrain for later use.
2. Prying is loud but usually not as loud as smashing stuff, fast with better tools (which the companion PR aims to make more important), and will usually preserve the terrain for later use (unless you fail at targeting a window).
3. Lockpicking is quiet, slow (less so with good tools and skill), and preserves the terrain for later use.

This rather neatly fits prying as an option in between smashing your way in and picking the lock, both of which presently have methods an early-game player can obtain. There was talk on the BN server, if I recall, of proposed changes to lockpicks that would probably compliment this balance further?

**Comment by Lamandus** [comment]
> Makeshift crowbar doesn't seem like an important item and it seems that opinions are mixed.
> I'd need a good gameplay reason.
> At the moment I don't see any. Being able to open doors/windows from outside is not a huge deal, but it's still essentially the defining trait of non-makeshift crowbars.

it is in my opinion a very important item. Like Chaosvolt said, it changes the way of looting the city. Especially when using draggable vehicles early on.

**Comment by SzQ1** [comment]
Opening doors and windows without destroying them is very important to me, because i can close them behind me which is often crucial in situations when horde spot me.

**Comment by Noctifer-de-Mortem** [comment]
How about having the makeshift crowbar have limited number of uses or have a chance to break? They can be crafted quickly and that way once you find a normal crowbar then that item would be a great find, no longer will you need to craft more makeshift crowbars before heading out.

As for lockpicks, they have their niche being silent and they can open some metal doors like the ones in the gun stores when no crowbar can open those. I use them in my stealth builds to avoid the hordes of the dead.

**Comment by Coolthulhu** [comment]
> How about having the makeshift crowbar have limited number of uses or have a chance to break when opening doors and windows?

As long as it is quickly crafted from cheap materials, limiting uses leads to tedium.
Improvised lockpicks already suffer from this problem and the solution is usually to craft a bag of them. Makeshift crowbars have the "advantage" of being bulky, but you could still carry a spare.

Now, if it used more expensive materials that you can't just get in bulk by deconstructing common furniture, limited use would be fine.

**Comment by Lamandus** [comment]
since @chaosvolt did changes to prying, this may get attention again? Or should it stay at lvl 1 as before

**Comment by chaosvolt** [comment]
I was told to go ahead and add https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1098 as a followup specifically for this, so would hope so.

**Comment by Coolthulhu** [comment]
Sounds like it may be better to make easily pryable stuff only require prying 1. Plus adjustment for difficulty.
@chaosvolt is it possible to adjust difficulty without changing the requirement?

**Comment by chaosvolt** [comment]
> @chaosvolt is it possible to adjust difficulty without changing the requirement?

I'm assuming you mean something like lowering prying requirement to 1 for doors, then messing with difficulty and/or pry_bonus_mult so that the success rate with prying 2 is still about the same as before? I could rig up an anydice calculation for that if you want I guess.

**Comment by chaosvolt** [comment]
Ah! If pry_bonus_mult is 3 for example, as it is in doors right now, just increasing difficulty by 3 should do it: https://anydice.com/program/25639

Chances of success if you raise difficulty to 11 and lower prying quality needed to 1:

Context | 8 Strength | 12 Strength | 16 Strength | 20 Strength
------------ | ------------- | ------------- | ------------- | -------------
Prying 1 (Difficulty: 11) | 20.64% | 56.25% | 79.83% | 90.6%
Prying 2 (Difficulty: 8) | 46.98% | 81.34% | 93.26% | 97.17%
Prying 3 (Difficulty: 5) | 84.29% | 96.53% | 98.9% | 99.55%
Prying 4 (Difficulty: 2) | 99.51% | 99.9% | 99.97% | 99.99%

**Pull request closed without merging**
