### PR TITLE
feat(content): Fully Update MMA

### PR DESCRIPTION
**Pull request by Empyrean-Heaven**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [ ] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
MMA had been neglected for the longest time. A semi-updated version could only be downloaded from Kenan's modpack. I have gone ahead and further improved the mod by converting all the weapon requirements for the martial arts into Weapon Categories.

## Describe the solution
No more copying and pasting each update!

## Describe alternatives you've considered
Perhaps Panzer Kunst is okay by itself...

## Testing
Works fine. No errors.

## Additional context
Hope everyone is doing lovely today.

### CODE REVIEW

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by Empyrean-Heaven** [comment]
Hmm, I made the changes to the main branch unfortunately. Should I close this PR or hope it works out since this only impacts the MMA mod?

**Comment by scarf005** [comment]
it'd be appreciated if a new PR could be created, but it's not a hard requirement (just suggestion so it would be easier to pull in updates from main branch later)

**Comment by Empyrean-Heaven** [comment]
> it'd be appreciated if a new PR could be created, but it's not a hard requirement (just suggestion so it would be easier to pull in updates from main branch later)

Okie dokie. Will be back in a jiffy with a new PR.

**Pull request closed without merging**
