### PR TITLE
[CDDA PORT] Adding House 33 from CDDA TO BN

### PR DESCRIPTION
**Pull request by LilShiningMan**
#### Summary
SUMMARY: Content "[CDDA PORT] Adding House 33"

#### Purpose of change

Adding more content to BN by porting over house from CDDA. 

#### Describe the solution

Added entries for house_33. This was originally from Fuji Structures Mod, updated and added to CDDA mainline by curstwist
[Original CDDA commit](https://github.com/CleverRaven/Cataclysm-DDA/pull/40648).

#### Describe alternatives you've considered

Adding nothing

#### Testing

Added house entries to BN. It spawned in game and looks fine, no editing required.

#### Additional context

Linted files via web de-linter. 

Co-authored-by: [curstwist ](<curstwist@users.noreply.github.com>)

### CODE REVIEW

**Comment by Fris0uman** [comment]
If you can't use cherry pick at leat give credit to the oroginal author by adding them as co author. You can do that by editing the commit message with two empty line after the commit description followed by `Co-authored-by: name <username@users.noreply.github.com>`
See proper format below
```
[describe commit]


Co-authored-by: name <username@users.noreply.github.com>
```
If you can't do that either at the  very least link to the original PR in the description of your PR. Cdda  license is very permissive but you have to give proper attribution.

**Comment by chaosvolt** [comment]
If you're using github desktop, you can also click this bit here to add co-authors to a commit:
image

Not sure if it's possible to add the formal co-authorship to a commit that's already been committed and pushed.

**Comment by LilShiningMan** [comment]
I admit I'm not very handy with github so I did as suggested above and added the info to the description.  Thanks for the heads up on the option to add co-authors from desktop, I'll do that next time

**Comment by Coolthulhu** [comment]
I added the co-author in merge commit, just to be sure.

**Pull request merged**
