### PR TITLE
ci: fix matrix (yet again^2)

### PR DESCRIPTION
**Pull request by scarf005**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

fix those constant failing matrix builds

## Describe the solution

see commits

## Describe alternatives you've considered

~~do proper fix instead of skill issue band-aid~~
yes, it's yet another missed out executable rename in #4989 
i blame myself as it's me who approved the PR

## Testing

worked on ubuntu 24.04 docker. will test in CI matrix

### CODE REVIEW

**Comment by chaosvolt** [comment]
This time I'm remembering to not approve until all tests pass, so...
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/10181842704/job/28163017433?pr=5117

**Comment by scarf005** [comment]
dunno why it fails on tests despite there being no errors
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/10181842704/job/28163017433?pr=5117#step:16:2034

**Comment by chaosvolt** [comment]
I don't see anything in there either. Is it a sign that one more exe update is needed buried in there somewhere, or? I don't know. D:

**Comment by chaosvolt** [comment]
image
3 minutes to fail my ass, I've been waiting like an hour hoping all tests would pass so I could merge this AAAAAAA

**Comment by scarf005** [comment]
@chaosvolt mac is another issue so i say nerge this first (at least 1 less test failure) then fix the macos build later

**Review by chaosvolt — APPROVED** [review]
I cri

**Pull request merged**
