### PR TITLE
Remove AoE from buckshot and flechette ammo until it's fixed

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Balance "Remove AoE cone effects for buckshot and flechette ammo for now"

#### Purpose of change

Discovered while testing, shotgun AoE cones are in a bad state right now and not suitable for use with standard ammo in its current form. Its flaws aren't severe enough to be a problem with birdshot (which no sane person is going to use on NPCs anyway since even if it was function the base damage is too low to be worth it), but for buckshot it's a big problem.

Relevant bugs are:
1. https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2791, this is the big one that makes this feature unsuitable for use with buckshot.
2. https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2756, this would be a good reason to revert this from dragon's breath shells too, but I feel this is less severe of a problem because players are also quite unlikely to use dragon's breath on NPCs that often either.

#### Describe the solution

Reverted use of AoE cone for all buckshot ammo, giving it its old stats. I left the abstract inheritance from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2619 in for now instead of just reverting the PR wholesale, because it'll be useful to us to have those abstracts so it's less work to re-implement this when it's fixed.

I kept the nerf to flintlock flechette ammo since it having 60 range (having inherited from the base ammo with no range override) seems like a mistake, but I did not keep the massive boost to paper shot's range since that seems to be a copypaste issue. Then again, it seems AoE ammo ALSO doesn't gain anything from range bonuses on the gun (a third bug for me to report it seems) so it having double the range of regular paper ammo may have been partially intentional, since that would equal the range of paper cartridge through a flintlock musket.

#### Describe alternatives you've considered

1. Removing AoE from dragon's breath, if we decided the second bug related to it is annoying enough to justify not using the feature until it's fixed.
2. Making AoE used only for debug ammo until either or both bugs are solved.

#### Testing

1. Checked affected file for syntax and lint errors.
2. Load-tested in compiled build.
3. Blasted a naked NPC 1 tile with a shotgun after granting myself 10 in all skills, they take 78 damage to the head and barely survive.
4. Follow this up with two unaimed shots, both hit the torso for standard damage and this is adequate to kill them.

#### Additional context

Relevant PR, this partially reverts changes from: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2619

### CODE REVIEW

**Comment by scarf005** [comment]
we could wait for a week until a fix comes out.

**Comment by chaosvolt** [comment]
It depends on how hard it'd be to actually fix the underlying issues, I suppose?

**Comment by Firestorm01X2** [comment]
For now I recommend to keep it hold until @Coolthulhu decision.

**Comment by Coolthulhu** [comment]
I'm fine with removing AoE effects from "real ammo", it's still in "not done yet" phase.

**Review by Firestorm01X2 — APPROVED** [review]
Ready

**Pull request merged**
