### PR TITLE
[DinoMod] The Bone Wars

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary

SUMMARY: Mods "More skeletal and brute dino evolutions"

#### Purpose of change

Greater enemy diversity and challenge, lots of new enemies that aren't incredibly weak against guns, more mid and late game interest

#### Describe the solution

Apply skeletal template against all dinos. Create, update, and enable evolution groups to spawn them. Fill in missing dino brutes. Update fungal dinos to override new evolution groups. Rework juvenile sauropod zombies and pterosaur zombies into their own separate builds to fix evolution copy errors. Pterosaur zombies drop feathers now.

#### Describe alternatives you've considered

Shady hulks, skeletal hulks, more regular hulks.

#### Testing

World builds, existing features are already tested

#### Additional context

"Praise the bones!" -Willow

### CODE REVIEW

**Comment by LyleSY** [comment]
Javelin throwing Travis error does not appear related to this monster mod

**Comment by Coolthulhu** [comment]
Yep, it's a random error that I need to fix someday. I'll restart the build.

**Comment by LyleSY** [comment]
Anything further needed on this?

**Comment by Coolthulhu** [comment]
Sorry, I totally forgot it's ready. Somehow missed it. Will test in next batch.

**Comment by Coolthulhu** [comment]
Most of the critters seem to be made of 2-3 templates, with one base monster.
I'm thinking of a possible way to make it more elegant.
If `copy-from` could be a list, it would be possible to load it as, say, `[ "t-rex", "zombie", "brute", "fungal" ]`.

**Comment by LyleSY** [comment]
> Most of the critters seem to be made of 2-3 templates, with one base monster.
> I'm thinking of a possible way to make it more elegant.
> If `copy-from` could be a list, it would be possible to load it as, say, `[ "t-rex", "zombie", "brute", "fungal" ]`.

Yes, that would make this work way easier and better. That's what I'm trying to do in a hacky way.

**Pull request merged**
