### PR TITLE
Obsoletion and removal of useless bathroom fluff

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: Content "Removal of bathroom clutter that served no purpose"

#### Purpose of change
There were still items lying around that didn't have any reason to be there. in vain of the kitchen clutter removal, it was time to get rid of the clutter inside the bathrooms, that either never spawned, or rarely (only mansions spawned toothbrushes, those snobs!) and don't have a reasonable uncraft recipe. 

Toilett paper is gone now...

#### Describe the solution
Removal of said clutter.

#### Describe alternatives you've considered
Give the clutter a reason to exist, but I couldn't find any good use for it, to be honest.

#### Testing
toilett paper is gone.

#### Additional context
grafik

### CODE REVIEW

**Comment by Lamandus** [comment]
I can't tell why clang tidy threw an error

**Review by scarf005 — APPROVED** [review]
clang tidy error could be ignored since this is pure json changes.

**Comment by Lamandus** [comment]
thatÄs the thing usually it does skip them

**Comment by Lamandus** [comment]
Think is ready to merge. Errors seem non related

**Review by olanti-p — APPROVED** [review]

**Pull request merged**
