### PR TITLE
feat(port): Add horse breeding

### PR DESCRIPTION
**Pull request by ekaratzas**
## Purpose of change

Add the ability for horses to reproduce and add monster type for baby horse (foal).

Original PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/55907

## Describe the solution

Add monster type for foal and fields for horse to reproduce.

I did end up removing fields from foal because they don't seem to exist in our fork: biosignature and petfood.

## Testing

Spawn horse. Make it reproduce via debug menu. See foal. Try it again with tamed horse. Result: many horses

foal

### CODE REVIEW

**Comment by scarf005** [comment]
```diff
- feature(port): Add horse breeding
+ feat(port): Add horse breeding
```

please [check guideline](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/) for details

**Comment by LordZanos** [comment]
petfood is what DDA uses to determine what tames it. We still have that based on flags, so foal should have CATTLEFODDER to match horses.

**Comment by ekaratzas** [comment]
@LordZanos good point i m on it

**Comment by RobbieNeko** [comment]
Yup, caddlefodder is what the adult horses use too if one looks at it

**Comment by ekaratzas** [comment]
Just added CATTLEFODDER flag to foals as well.

**Review by chaosvolt — APPROVED** [review]
honse

**Pull request merged**
