### PR TITLE
Police station minor map changes

### PR DESCRIPTION
**Pull request by metalheimer**
#### Summary

SUMMARY: Content "Changed jail wooden doors to bar doors. Changed few windows. Reassigned bed symbol."

#### Purpose of change

Jail doors shouldn't be wooden doors when bar doors are available.

#### Describe the solution

I'm guessing wooden doors were a temp fix that never got fixed properly. Locked bar doors apparently had the same symbol assigned ("4") as downspout elsewhere. Locked bar doors are now "B" in police stations. Later discovered "B" was already for assigned for beds - there were a couple of those in one cop station map. Panicked and changed bed symbol to "E". Also changed some windows to barred glass versions instead of being just glassless metal bars.

Made the changes locally and uploaded the file. Not sure why the differences show up as a completely changed file, as in all lines changed. Ran the edited file through the in-game JSON formatter.

#### Testing

Spawned each building I touched, walked around in them, picked the locks on some bar doors. Seemed fine.

### CODE REVIEW

**Comment by KheirFerrum** [comment]
You duplicated the contents of the file.

**Comment by metalheimer** [comment]
Idk what's going on here. Linted version has no differences. Why am I not able to lint this? Why is this crap not accepted when it works perfectly fine in the game?

**Comment by casswedson** [comment]
the json formatter just does not like your line endings, it looks nonsensical but the correction is as the infrastructure prefers it aka correct

**Comment by chaosvolt** [comment]
If you make a minor change or some other commit to nudge the bot into re-evaluating it, it should work right afterward now that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2484 has been merged. nUpdating the branch from upstream may or may not also be needed, not sure.

Basically the lintbot was set to handle newline-at-end-of-file the opposite of how the project normally does it.

**Comment by scarf005** [comment]
@metalheimer, i've fixed CRLFs into LFs. git forced me to 'add' LF changes, so i'm confident that there would be no furthur lint errors.

**Review by scarf005 — APPROVED** [review]
large number of changed lines was due to CRLF issues. now it's only 23 lines of changes, and they look OK to me.

**Pull request merged**
