### PR TITLE
Add debug overlay for submap & overmap tile boundaries

### PR DESCRIPTION
**Pull request by olanti-p**
A few times I've had the need to easily check layout of submaps / overmap tiles in relation to the avatar, and this PR implements debug overlay for that.

It uses single lines to indicate submap boundaries, double lines for omt boundaries.
Submaps are also color coded:
green - part of `g->m`
cyan - loaded in the `MAPBUFFER`
blue - neither
Also includes commit https://github.com/CleverRaven/Cataclysm-DDA/commit/23ce399f37c1c00335a3c4c7949296779569c23b from DDA to minimize number of future conflicts.
borders
image

### CODE REVIEW

**Comment by Coolthulhu** [comment]
That "performance" fix removes the ability to view multiple overlays at a time. Is that intended?

**Comment by Coolthulhu** [comment]
It works. If that single overlay limitation is intended and not just an artifact of cherry picking, it's good to go. I'll wait for confirmation.

**Comment by olanti-p** [comment]
Turns out it's already impossible to view multiple overlays at a time, since they would print text over each other and that would be a mess.
I changed the grid overlay to use a separate boolean, now it can be used with others.

**Comment by Night-Pryanik** [comment]
@olanti-p @Coolthulhu do you mind if this PR would be ported to DDA?

**Comment by Firestorm01X2** [comment]
> 
> 
> @olanti-p @Coolthulhu do you mind if this PR would be ported to DDA?

Considering license you don't have to ask. BN license exactly match DDA license, so I see no coflicts.
https://creativecommons.org/licenses/by-sa/3.0/

> 
> You are free to:
>  Share — copy and redistribute the material in any medium or format
> Adapt — remix, transform, and build upon the material
> for any purpose, even commercially. 


> Under the following terms:
> 
>     Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
> 
>     ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
> 
>     No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
>

**Comment by Coolthulhu** [comment]
@Firestorm01X2 It's about opinion, not law.

Personally, I'm fine with ports that credits the author. Cherry pick or explicit credit in commit of a "manual cherry pick".

**Comment by olanti-p** [comment]
I'm fine with it too. I regularly port bugfixes/features from DDA, so imo it's fair that some BN bugfixes/features would be ported back.

**Pull request merged**
