### PR TITLE
Revert "Gate 3+ engines behind DEBUG_HS"

### PR DESCRIPTION
**Pull request by AngelicosPhosphoros**
#### Summary

SUMMARY: Features "Restore ability to add more than 2 engines to vehicles"

#### Purpose of change

I think, building monster trucks is one of the funniest thing in the game so we should allow create vehicles with a lot of engines.

#### Describe the solution

This reverts commit bc6f0263700480a90374581ac4a38068cc202aae.

#### Testing

Haven't tested yet (do I need if this is just revert?).

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
> do I need if this is just revert?).
You definitely need to do at least basic tests to make sure that everything fine. There are always can be surprises.
Make sure, that feature was actually reverted and game works properly.
If you have questions about building or using debug menu - feel free to ask on any discord or even here.

**Comment by AngelicosPhosphoros** [comment]
> If you have questions about building or using debug menu - feel free to ask on any discord or even here.

How I build it on Windows?

I see, that Travis built a Windows build on PR, maybe it is possible to download it somehow?

**Comment by AngelicosPhosphoros** [comment]
I would try [this guide](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md) tomorrow.

**Comment by Firestorm01X2** [comment]
> I would try [this guide](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md) tomorrow.
Feel free to contact me, or other contributors on
Unofficial DDA modding community discord also has a BN channel:
https://discord.gg/B5q4XCa
if you encounter problems.

**Comment by Coolthulhu** [comment]
Check out #389

I'd prefer to fix the problem correctly.
The revert might be good enough to merge on its own, but it has its own problems.

**Comment by olanti-p** [comment]
The issue've been solved in #722

**Pull request closed without merging**
