### PR TITLE
Added Bordered scenario

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
SUMMARY: Content "New 'Bordered' scenario"

#### Purpose of change
To add a new challenge type.
I'm working on another location, for which I created this border location, but I think it could be used as a new challenge type, implemented as a new scenario. You are limited only to your initial overmap, the loot is limited too. Limited resources should provide different experience of survival as you can't simply go to adjacent overmap when the loot on initial overmap is exhausted (or it wasn't very good from the start) anymore.

#### Describe the solution
- This scenario creates a 24-tiles width walls of solid rock on borders of initial overmap. This wall doesn't respect terrain it's placed upon, so it actually could "cut" cities, rivers, and roads.
- The scenario is based on evacuee scenario, with evac shelters as possible starting locations. It earns 2 points to the player.
- The `rock_border` location won't spawn naturally, only through the use of `BORDERED` scenario flag.
- Rock border could be successfully pickaxed or jackhammered if player is stubborn enough, but it's not the intended way to play this scenario.

#### Describe alternatives you've considered
- Make border consist not from solid rock, but instead of some (new) indestructible terrain type. I just wanted not to add redundant matter.
- Replace evac shelters as starting locations with some other locations, or maybe instead add some other locations to the list.
- Increase or decrease points earned from selecting this scenario. Make it cost 0 points.

#### Testing
Created a new world. Selected new scenario. Started the game. Checked the existence of the Wall.

#### Additional context
изображение

изображение

изображение

изображение

### CODE REVIEW

**Comment by olanti-p** [comment]
As a note, player is forbidden from spawning in the same overmap as the lab with BN's winning condition (line 214):
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/77f9aa72350084cd6dad139fb761bd0161d1daab/src/start_location.cpp#L207-L228
so this scenario locks the player out of winning the game the usual way.

Not sure on what's the best way this could be dealt with. The endgame room is hardcoded to be the deepest lab finale found inside overmap `(0,0)`, it can't be "just placed" like an overmap special - at least not without refactoring, or creating a separate oms. On the other hand, restricting player spawn area to om `(0,0)` may result in endless "unable to generate a valid starting location" errors...

The easiest "solution" would probably be to stick a warning in scenario description (or are there some plans on an alternative WC?).

**Comment by Night-Pryanik** [comment]
Any quest outside of the Wall will be actually unavailable too. I know of all limitations of this scenario. This challenge is more for sandbox gameplay with no end goal except for surviving.

> or are there some plans on an alternative WC?

No, there ain't, at least for the moment.

**Comment by chaosvolt** [comment]
Looking at the code, it doesn't seem to actually restrict any code interactions like missions from being placed outside the border? Unless the rocks were made of an unbreakable material, it'd be feasible for a player to view breaking out of the border as a viable long-term goal, especially if a mission placed their target outside the wall.

Unless I'm mistaken in my reading here, the only way it'd actually break any element of normal gameplay would be for it to cut through part of a vital mission location, via the sheer bad luck of that location spawning right up against the overmap edge, and that's assuming worldgen allows overmap specials to rub right up against overmap edges (unsure).

Note also that slapping a stepladder up will potentially let you trivialize the wall entirely, depending on if the walls successfully generate the roofs most walls and indoor terrain are set to have. Assuming that feature still works, it might still need a save/load cycle with part of the wall in the reality bubble to successfully trigger it.

**Comment by Night-Pryanik** [comment]
> Looking at the code, it doesn't seem to actually restrict any code interactions like missions from being placed outside the border?

Yes, it doesn't restrict anything.

> Unless the rocks were made of an unbreakable material

I could make the Wall consist of unbreakable material, but I'm not sure if I should really make the getting out impossible, or should I left the possibility as a part of challenge itself.

> Note also that slapping a stepladder up will potentially let you trivialize the wall entirely

The Wall is 10 z-levels high, stepladder won't help here.

**Comment by chaosvolt** [comment]
Ah, that answers my questions on it, yeah. If it's full height then yeah, the stepladder cheese isn't an issue.

That leaves mining, explosives, letting a hoard of monsters and/or a digging monster at it, any source of ter-transform spells in mods that can affect solid rock, the `pulse` spell effect in mods would work if it wasn't bugged last I checked, getting lucky with a random teleport (presumably from a spell source in mods that has enough range, all vanilla sources of teleport would fall short), and possibly the quantum tunneling CBM if you have enough power to get through 24 tiles (with the current power cap I don't think you would, but there is a PR in the works to change that).

So I do feel it probably would be best as a challenge for players to try and break out of if they want to, especially if it becomes possible for a mission objective to give them an extra reason to want to breach it.

**Comment by Coolthulhu** [comment]
I think it's a cool idea, but at the moment, the destructible wall sounds better than indestructible because of the win condition and missions in general.
"Break out of the rock cube" sounds like a nice midgame goal, since you need a jackhammer with enough fuel.

**Pull request merged**
