### PR TITLE
feat: make animals be able to carry heavier weight

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: Balance "make animals be able to carry heavier weight"

#### Purpose of change
port https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/34 by [Night-Pryanik](https://github.com/Night-Pryanik). omitted test becuase it had a bit of conflicts

#### Describe Solution

- increased default mountable_weight_ratio to 0.3 (30%)
- increased horse weight to 750kg
- increased cow weight to 1000kg

### CODE REVIEW

**Comment by chaosvolt** [comment]
Nice. Another possibility that's been raised in the past would be giving cows a `mountable_weight_ratio` that allows them to carry more. This would also have the effect of giving them a different mount niche relative to horses, as they're much slower than horses, but animal-powered vehicles determine power by both the animal's speed and weight ratio, so a higher weight ratio would make them provide a slower max speed but be able to maintain that speed with heavier wagons.

**Comment by scarf005** [comment]
> giving cows a mountable_weight_ratio that allows them to carry more

that's a nice suggestion. do you have any specific number in your mind?

**Comment by chaosvolt** [comment]
> that's a nice suggestion. do you have any specific number in your mind?

Let's see, if we're considering wagon-pulling in particular, they would need a minimum `mountable_weight_ratio` of ~0.47 to match how much vehicle power horses provide before this PR, ~0.81 to match the vehicle power horses will provide with this PR (as a ratio of 0.35 means horses will provide 75% more vehicle power than before). This assumes their speed is entirely unchanged, as it's currently 130 (compare 300 for horses)

If we're considering weight capacity as a mount instead, cows already have ~24% higher weight capacity than horses have without this change, but would need a mountable ratio of ~0.39 to match the carry weight capacity of horses with the current changes. This, likewise, assumes that the weight of cows is unchanged, currently their weight is 680.388 kilograms (compare 750 for the proposed weight change to horses).

**Review by chaosvolt — APPROVED** [review]

**Comment by Unrepentant-Atheist** [comment]
On a side note: Why are there only horse and cows in vanilla game as mounts?

**Comment by chaosvolt** [comment]
> On a side note: Why are there only horse and cows in vanilla game as mounts? Need more animals/mounts.

You can also mount (or install a wagon):
1. Wild boars (these don't seem to be tamable though, we should either remove that flag or at least allow taming wild boar piglets).
2. Most varieties of dog (only useful if you're small enough).
3. Moose (again, we'll need to add a way to tame them).
4. Pigs (actually tameable both as piglets and adults, so just gotta be probably below-average size).

You can also hitch grocery bots and the utility hauler bot to wagons, but can't mount them (though hypothetically, I wonder if it'd be acceptable to allow mounting the utility bot now that it's statted after Big Dog instead of Spot).

Not counting options in other mods, in-repo or otherwise.

**Pull request merged**
