### PR TITLE
chore: re-license the project to GPLv3

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: Infrastructure "Re-licensed the project to GPLv3 to ensure its source code distribution is shared under same license"

#### Purpose of change

> We recommend against using Creative Commons licenses for software.

Creative Commons licenses are [not suitable for softwares][cc]. see https://github.com/CleverRaven/Cataclysm-DDA/issues/18095 for details.

[cc]: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

#### Describe the solution

changed the license to `CC-BY-SA 3.0` -> `CC-BY-SA 4.0` -> `GPL v3`.

#### Additional context

I'm not a lawyer, so i'm not 100% certain this is legally correct. It may take years to sort this up.

### CODE REVIEW

**Comment by Zireael07** [comment]
CDDA wanted to do the same - but legally you need EVERYONE who contributed to agree. IIRC some contributors are no longer reachable, so... forever impossible.

**Comment by scarf005** [comment]
you could make all new contributions enfoce it to be GPLv3.

**Comment by Zireael07** [comment]
IANAL but I don't think it's possible to double-license like this (CC for past and GPL starting from some point)...

As I said, from the CDDA discussion it turned out that relicensing is simply not possible because even if one contributor doesn't agree (or isn't available to state he agrees) you can't relicense

**Comment by scarf005** [comment]
of course contacting all contributors to agree on re-licensing is not possible. also IANAL but if my understanding is correct new contribution could be done in CC-BY-SA 3.0, which is one-way compatible to GPLv3.

**Comment by AniDemi** [comment]
If we are lucky, it's just a case of DDA giving up too early and not a impossibility

**Comment by Zireael07** [comment]
@AniDemi @scarf005 You're wrong. I googled and here's a StackOverflow on the topic: https://opensource.stackexchange.com/questions/33/how-can-a-project-be-relicensed

**Comment by Night-Pryanik** [comment]
Answers indicated that, yes, but I didn't see any sources for their words (or maybe I mislooked them).

Also, what happens if re-license occurs without 100% approval? Someone comes to court? And with what accusation?

**Comment by Zireael07** [comment]
My approach is: in absence of any proof to the contrary, it's better to follow others.

As to your question: you run a risk of someone taking you to court. Oracle vs Sun is literally mentioned in that SO link

**Comment by Qrox** [comment]
> new contribution could be done in CC-BY-SA 3.0, which is one-way compatible to GPLv3.

IANAL, but my understanding is that the "SA" in CC-BY-SA 3.0 disallows relicensing derivative works with additional restriction such as the source distribution requirement of GPLv3, therefore it is never compatible with GPLv3, even if you use the CC-BY-SA 3.0 -> CC-BY-SA 4.0 -> GPLv3 route. Unless, of course, you get all authors to relicense their contribution, which is the authors' right.

Again, IANAL, but from my understanding of what I have been reading, I think if you're willing to ship-of-theseus the code base, brand new contribution could be double-licensed under both CC-BY-SA 3.0 and GPLv3, and once all code has been replaced, you could simply stop updating the code under the CC-BY-SA 3.0 license and only update the code under the GPLv3 license. Before that though the GPLv3 code will likely be incomplete and unusable. Other people are still free to distribute the old code under the CC-BY-SA 3.0 license so it does not violate the license's requirements.

Of course, that is only in theory, and I'm not sure if it is possible in practice to replace all legacy code in a community project like this. And it's also hard to define what is "brand new contribution" that can escape the CC-BY-SA 3.0 requirement. That seems to be not worth the effort TBH.

**Comment by scarf005** [comment]
feels it's not feasible at the moment.

**Pull request closed without merging**
