### PR TITLE
feat(balance): Smart watch now gives 2 ultra-light batteries on uncraft

### PR DESCRIPTION
**Pull request by yay855**
Smart watch now gives an ultra-light battery when uncrafted.

## Purpose of change

The regular wristwatch gives an ultra-light battery when uncrafted, but the smartwatch, which has 120 UPS power capacity, gives zero.

## Describe the solution

The smart watch now gives two ultra-light batteries when uncrafted.

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]
Light cell has 100 capacity so there's some mismatch, but is still an improvement.

**Comment by VissValdyr** [comment]
The reason for it is the same why other UPS items don't give any batteries. The lore in question was that those batteries were not replaceable. That's why laptops, smartphones, or here smart watches don't give any batteries.

**Comment by VissValdyr** [comment]
Now we have the dilemma of one of the items actually giving 2 batteries.

**Comment by VissValdyr** [comment]
See #1062 , @yay855 and @chaosvolt

**Pull request merged**
