### PR TITLE
fix: remove conflicting `games` itemgroup

### PR DESCRIPTION
**Pull request by RoyalFox2140**
## Summary

SUMMARY: Bugfixes "Stops game breaking bug from pull https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3469 by merging games itemgroup"

## Purpose of change

When the games item group was ported from DDA we left in an itemgroup from Fuji's structures. This causes the game to crash on loading old saves.

## Describe the solution

I merged any missing items from the mainline group and destroyed the mod's item group to maintain backwards compatibility.

## Describe alternatives you've considered

The future is now man.

## Testing

It loads. Any other bugs is from Sierra Madre mod in Kenan's pack and being handled by Kenan.

## Additional context

We all scream for bugs (and ice cream)

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]

**Review by scarf005 — CHANGES_REQUESTED** [review]
```
 DEBUG    : item id cards is unknown (in item in games)

 FUNCTION : virtual void Single_item_creator::check_consistency(const std::string &) const
 FILE     : /home/scarf/repo/cata/Cataclysm/src/item_group.cpp
 LINE     : 126
 VERSION  : BN 9fd976a84ee6
```

it errors due to missing `cards`, could we also mainline them?

image


https://github.com/RoyalFox2140/Cataclysm-BN/blob/201eefaf4d6b8c731eb87332dec2b39babd62424/data/mods/Fuji_Structures/items/items_games.json#L34-L49

**Comment by RoyalFox2140** [comment]
> ```
>  DEBUG    : item id cards is unknown (in item in games)
> 
>  FUNCTION : virtual void Single_item_creator::check_consistency(const std::string &) const
>  FILE     : /home/scarf/repo/cata/Cataclysm/src/item_group.cpp
>  LINE     : 126
>  VERSION  : BN 9fd976a84ee6
> ```
> 
> it errors due to missing `cards`, could we also mainline them?
> 
> image
> 
> https://github.com/RoyalFox2140/Cataclysm-BN/blob/201eefaf4d6b8c731eb87332dec2b39babd62424/data/mods/Fuji_Structures/items/items_games.json#L34-L49

I thought Zlor did in the PR for all those other game items. I will get it mainlined.

**Comment by RoyalFox2140** [comment]
This was my bad for not catching it but upon inspection @Zlorthishen has mainlined every game item in this mod. I have subsequently deleted this offending file to avoid the situation where it overwrites them without a reason.

**Review by scarf005 — APPROVED** [review]
image

game loads without error. also code removal good

**Pull request merged**
