### PR TITLE
feat(content): add Lua bindings for spell types

### PR DESCRIPTION
**Pull request by karxi**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
Further work on expanding what Lua scripts are capable of in Cataclysm~

## Describe the solution
This is a set of Lua bindings that allow spells to be cast through Lua. While there's room for expansion, it means that the varied and powerful effects spells offer are now possible to invoke through Lua! (They still need a spell defined through JSON; this isn't quite *that* magical.)

## Describe alternatives you've considered
Binding every single type that spells touch and modify so people don't need to work through spells.  
To be clear, that's still my ideal end goal for Lua; spells are (in my humble opinion) clunky and annoying to work with. But they allow a range of effects that simply aren't possible with the current tools (such as spawning items), so this seemed like the natural next step.

## Testing
Here are some basic tests:
```lua
avvy = gapi.get_avatar(); pos = avvy:get_pos_ms()
spid = SpellTypeId.new("lava_bomb_main")            -- A disruptive, painful, and possibly lethal spell
SpellSimple.prompt_cast(spid, pos)                  -- Blow ourselves up
```
image

The longer form invocation makes it clearer what's going on here, and allows more control:
```lua
spid = SpellTypeId.new("invisibility")              -- Get a spell's ID
spobj = SpellSimple.new(spid, true)                 -- Set up 'Invisibility' to be cast on self
spobj:cast(avvy, pos, spobj:max_level())            -- Cast Invisibility from us, on us, at max level
```

A list of all spells can be retrieved via ``SpellTypeRaw``, e.g.:
```lua
for k,v in pairs(SpellTypeRaw.get_all()) do print(k, ': ', v) end
```
...so go nuts~

image
image

## Additional context
Two things of import:
1. The first example uses an AoE spell that can hit the player. This is intentional—it's easiest to use the player as a test dummy, but a lot of spells refuse to let the player select themself as a target. If you have an NPC (or monster) to bully, your options expand significantly—just plug another ``Creature``'s ``get_pos_ms()`` into ``:cast``. (Or plug another ``Creature`` in as the first argument, and *the player's* position—both should work.)
2. The C++ code behind spells is strange and arcane and I do not particularly care for it. It's not the worst thing in Cataclysm, not by a wide margin, but I wish things were neater.

### CODE REVIEW

**Comment by RobbieNeko** [comment]
> The C++ code behind spells is strange and arcane and I do not particularly care for it. It's not the worst thing in Cataclysm, not by a wide margin, but I wish things were neater.

Welcome to our (magic mods) world :)

**Review by RobbieNeko — CHANGES_REQUESTED** [review]
Testing on Linux:
- It builds and loads!
- The provided invisibility and lava bomb examples work
image
image
- Summoning items works, and the water prompt actually popped up while still in the console lol
image
image
- What I thought would be a curveball, pain split, also worked!
image
- What **didn't work**, however, was cure light wounds ("light_healing")

It clearly recognized the spell ID, but did not actually heal me for anything (test was done before pain split, but it didn't work after that either)
image

For reference, how I inputted the custom spell tests (literally just exchanging invisibility's ID for other spell ids in Magical Nights since I had an MN test world already)
image

**Comment by karxi** [comment]
Really? This worked fine for me:
image
image
This character was uninjured, then shot with a heavy rail rifle, then healed significantly (from yellow health to light green).
(Also, today I learned that heavy rail rifles can set things on fire.)

**Comment by RobbieNeko** [comment]
Additional findings:
Mind over pain ("recover_pain") doesn't appear to work either.
Phase door **does work** despite not even having a valid target in the first place in JSON

**Comment by RobbieNeko** [comment]
> Really? This worked fine for me: image image This character was uninjured, then shot with a heavy rail rifle, then healed significantly (from yellow health to light green). (Also, today I learned that heavy rail rifles can set things on fire.)

huh, interesting. When using that method it does work, but when using the one used for invisibility it *doesn't*

**Comment by RobbieNeko** [comment]
And same with the recover_pain!
Evidently some spells only work with specific syntax?

**Comment by karxi** [comment]
**For the record:** If a spell has ``"valid_targets": [ "self" ],`` and you aren't in the square designated by ``pos`` by the time you cast it, it may break. If you want to be safe in the prior examples, use ``avvy:get_pos_ms()`` or ``gapi.get_avatar():get_pos_ms()`` (the latter is overkill, but sometimes it pays to be extra-cautious).

Under the given circumstances, it arguably **should** break (a spell that with ``valid_targets`` requirements that aren't being met *should not cast!*), but the code behind spells is a mess, and sometimes they'll go off despite that.

**Review by RobbieNeko — APPROVED** [review]
Turns out I am a silly goober and moved after I set `pos`. So long as you actually, you know, **have the position variable stay correct by not moving after setting `pos`** everything works perfectly fine!

... it's just that somehow, most of the spells actually work in spite of moving off of that tile?!? Magic code is hecking weird, man.

**Review by chaosvolt — APPROVED** [review]
1. Compiled and load-tested.
2. Started up a world with Magiclysm added.
3. Entered first command shown in testing section.
4. Died from going "I don't care how big the room is, I CAST FIREBALL"

**Pull request merged**
