### PR TITLE
Fix path to latest release page in readme

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Fix path to latest release page

#### Summary
SUMMARY: Infrastructure "Fix path to latest release page in readme"

#### Purpose of change
Link to "latest" release shows latest stable 0.2 but not latest experimental.

#### Describe the solution
Change link in readme

#### Testing
1) Go to https://github.com/Firestorm01X2/Cataclysm-BN/tree/feature/latest-release-fix
2) Click latest.
3) You must see experimental version but not stable.

#### Additional context
None

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
It is not working anywore. Something changed. WIP

**Comment by Firestorm01X2** [comment]
Ok. It is working, but now for some reason it shows 0.2 on top, but not experimentals. It was not few days ago,

**Comment by olanti-p** [comment]
I just edited the text of the 0.2 release to hide the huge changelog under a spoiler, clicked "save", and the release has moved by itself onto the 2nd page in https://github.com/cataclysmbnteam/Cataclysm-BN/releases

The links on the homepage have also fixed themselves, I think?
image
Must be some GitHub thing.

**Comment by Firestorm01X2** [comment]
> The links on the homepage have also fixed themselves, I think?

No still
изображение

But after my PR it will show:
изображение

So, PR is still needed

**Comment by olanti-p** [comment]
Oh, you're right here. LGTM

**Review by scarf005 — APPROVED** [review]
also LGTM

**Pull request merged**
