### PR TITLE
Allow crafting splints at start

### PR DESCRIPTION
**Pull request by Muffindrake**
Rationale: The fuck? (Translation: Oh my, what strange happenings.)

Actual Rationale: The only items that can mend broken limbs are locked behind frustrating grind walls.

Imagine a situation where a new character gets either limb broken - a player would assume that he'd need to stay safe and avoid combat. No, fat chance - he has to get out there and kill and pulp those zombies, or get mooserized out in the woods with little chance to fight back.

Fighting with mending broken limbs still incurs severe penalties and healing is hampered by possibly getting the limb hit, but a player shouldn't be required to kill himself further to get to that state.

### CODE REVIEW

**Comment by kevingranade** [comment]
The player wanting to do something isn't a rationale for giving it to them.  It's perfectly fine for a broken limb to be a death sentence for an unprepared player.

**Comment by Muffindrake** [comment]
I seem to have pushed a partial change, this last commit actually does what the PR title suggests.

**Comment by Coolthulhu** [comment]
One thing I'm mildly worried about: splints were a method to booklessly grind first aid from 1 to 2. Is there such an option now?

**Comment by Muffindrake** [comment]
@Coolthulhu Since the skill for both splints is currently set to first aid for both arm and leg splints while the difficulty is 0, you are able to grind first aid from 0 to 1, however you gain no experience beyond level 1 with this recipe. I just tested this now.

**Pull request merged**
