### PR TITLE
Add science tower lab start location 

### PR DESCRIPTION
**Pull request by Firefox13**
#### Summary
Features: Adds science lab tower starting location to lab escape challenges

#### Purpose of change
Lab Towers is the only type(barring microlabs) of labs that you can't spawn in as lab escape challenge. I find them pretty cool and they make nice starting and (probably) safe base if you can bear all the noise coming from first floor.

#### Describe the solution
Added lab tower terrains to start_locations.json and added those locations to scenarios.json

#### Describe alternatives you've considered
Not doing this PR

#### Testing
Create a new character, select one of the escape lab challenge, select "Top of the science lab tower" or "Science lab tower" and spawn it.
Spawning at the top(finale room) gives an error message that it couldn't spawn me in but it went fine neverthless, the start_location.cpp mentions that it happens in exotic locations(read:deep of a science lab) for some reason.

#### Additional context
None

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> the start_location.cpp mentions that it happens in exotic locations(read:deep of a science lab) for some reason

The spot checking function tries to avoid putting player in a place from which there is no escape. But it only understands being able to reach end of the bubble or stairs up. It wasn't written with stairs down in mind, because it was implemented for underground labs.
It would be easy to modify it to check for downstairs when above ground and upstairs when below.

**Comment by Coolthulhu** [comment]
The JSON validation can be fixed by running the file through https://dev.narc.ro/cataclysm/format.html

I should probably make the json validator upload properly formatted file as a public artifact. I'm not sure if public artifacts are doable with free github actions, though.

**Comment by anothersimulacrum** [comment]
https://github.com/I-am-Erk/CDDA-Tilesets/pull/798/checks?check_run_id=3288445092 has public artifacts.

**Comment by Coolthulhu** [comment]
Needs formatting.

As for the top tower: if you removed it for now, it could get in. Otherwise someone would have to implement the C++ part of it.

**Comment by Coolthulhu** [comment]
Closing as stale

**Pull request closed without merging**
