### PR TITLE
feat(content): add house_fence10

### PR DESCRIPTION
**Pull request by LilShiningMan**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
more houses

## Describe the solution
add another house

## Testing
linted and spawned in game

## Additional context
I also upped the weight of all the house_fence series of houses. I still want them to be a  little less likely to spawn than other houses, but I figure they should have more like spawn rate 30 than 20. 

image
basement a

image
basement b

image
ground

image
second floor

image
roof

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]

**Comment by Relgar** [comment]
Love the work @LilShiningMan , are you considering houses which have voids in future contributions? I feel this adds variety.

**Comment by LilShiningMan** [comment]
sorry, not sure what you mean by "voids"?

**Comment by chaosvolt** [comment]
I'm guessing he's referring to some houses that might still have big empty patches in them. Not sure how common that is compared to basements which have been more well-known for their emptiness, but you've also tackled those so I'm not sure how common that is anymore either. Good work in any case. :D

**Comment by Relgar** [comment]
A void in building construction is a space on the 2nd story that lets you look down on to the 1st/ground floor, similar to the below:

https://www.mindfood.com/wp-content/uploads/2021/07/MET2773_Riviera_Heroes_368-002.jpg

This lets the house look bigger and adds some verticality to the house, which may be interesting if you have zombies on the 2nd floor who see the player sneaking about. Typically have glass barriers.

**Comment by LilShiningMan** [comment]
Ah, ok. Yes, I've added at least two houses (more?) which have voids so far

image
2Story02

image
2StoryModern05

 I find that layout interesting and I'd like to add more. I'd like to get away from the 1 story and focus more on verticality going forward.

**Pull request merged**
