### PR TITLE
Slower, weaker, more medical zombies

### PR DESCRIPTION
**Pull request by LyleSY**
#### Summary

SUMMARY: Content "Medical zombie rebalance and custom death drops"

#### Purpose of change

Make medical zombies, especially nurses, more balanced against other similar zombies, make them feel more unique and interesting

#### Describe the solution

Slows down all variants to a little faster than regular zombies but much slower than runners (they were previously the fastest day one zombies in the game), reduces HP to standard and then scales with military zombies. Adds new special death drops.

#### Describe alternatives you've considered

Just make them spawn only in medical areas and put them on a spawn timer so day one spawns in medical areas aren't impossible. Make them more rare outside of medical areas. Make them no longer an upgrade target for vanilla zombies. Give them a 10% chance of rarer medical loot

#### Testing

Game loads no errors. Possible to walk away from a nurse. Possible to beat one to death day one with a rock with a random starting character.

image

#### Additional context

Hellooooo nurse! -Animaniacs

### CODE REVIEW

**Comment by LyleSY** [comment]
This is the idea, still need to test to make sure the new death drops work as intended

**Comment by Coolthulhu** [comment]
Evolution into nurses is pretty important.
I'd rather have them be harvestable for medical bits than have them be limited to specific zones.
Alternatively, they could drop standard zombie stuff, but also have some medicine on them, handwaved as "they collect this stuff because reasons".

**Comment by LyleSY** [comment]
> Evolution into nurses is pretty important.
> I'd rather have them be harvestable for medical bits than have them be limited to specific zones.
> Alternatively, they could drop standard zombie stuff, but also have some medicine on them, handwaved as "they collect this stuff because reasons".

I guess I'm confused about the lore on this monster. Is this a human with medical training who has been tainted with the blob, so has medical stuff and medical zombie powers, or is this a regular human who just randomly got medical powers from the blob, like skeletons and shadows? Either is fine but both is difficult to implement and balance

**Comment by Coolthulhu** [comment]
> Is this a human with medical training who has been tainted with the blob, so has medical stuff and medical zombie powers, or is this a regular human who just randomly got medical powers from the blob

Currently, as in pre-your-PR, it's any zombified human, with some preference for medical personnel.
In your PR, it's just medical personnel.

I'd prefer if it was any human, because that allows random evolutions.
The rewards could be implemented as one of:
* The zombie has some chemical/medical/drug drops, in addition to normal zombie drops. In the lore, it could be explained as them starting as medical personnel in some cases, but in others, the zombie just randomly collecting chemical stuff because of some personality aspect (junkie/medical interest) that the zombification amplified.
* The zombie has some organs that can be harvested (with surgery) for medicine. Not sure what could that be.

**Comment by LyleSY** [comment]
Ranged attack test failure looks unrelated

**Comment by Coolthulhu** [comment]
Ranged test fails randomly, it's unrelated, yes. I'll need to fix it someday.

With the drops you set for them, the nurse line looks like an evolution of hazmat zombie.
This could be considered, since as far as I recall hazmat zombies don't evolve.
Either way, their drops should be more like previous zombie drops + meds, not completely different ones. That is, the drop group for evolved version should have the drop group for the earlier one included.

**Pull request merged**
