### PR TITLE
Shields can interact with ranged attacks, add some vanilla shields

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Features "Shields can interact with ranged attacks, add 3 shields to demonstrate"

#### Purpose of change

A long time ago, when I implemented the BLOCK_WHILE_WORN mechanics, a long-standing failure of mine had been that shields

To finally implement this, I had to basically implement code for the ability for shields to passively intercept attacks that hit bodyparts they don't cover, independent from normal blocking behavior. Thanks to Kheir this soon led to realizing it'd be better to find the relevant ranged function and add something modeled off blocking.

#### Describe the solution

C++ changes:
1. In character.cpp, implemented `Character::block_ranged_hit` as the real meat and potatoes of the suporting code changes. The function checks for if you're using a valid shield item (`BLOCK_WHILE_WORN` flag plus one of the `WBLOCK_X` techniques), and if so generates a random chance that said shield will provide its armor value to a body part it otherwise doesn't cover.

The chance is a multiplier of the item's coverage percent that scales with what blocking technique the shield has, better shields are assumed to be bigger and more as passive cover, and therefore the chance is a higher proportion of their base coverage. Hits to the legs also have an additional lower chance of being intercepted by a shield, how much worse compared to the penalty for other bodyparts depends on the block technique it has (`WBLOCK_3` shields are assumed to mainly be tower shields and the like that have decent coverage for the legs, while the lower block tiers have progressively worse coverage for the legs). It also has a hard exception for the feet, on the basis that the player is unlikely to protect those with any standard shield purely passively.

Damage is then reduced by the relevant armor values of the item as if the item counted as armor on the affected body part, with the code being able to take into account damage multipliers, armor penetration, armor multiplier and such. Has debug messages that print current chance of a successful interception, when an interception fails, and the expected damage before the shield intercepts. Also like with melee blocking, it prints a standard message when an interception is completed, stating how much damage was shaved off (capped at the base damage if it blocked all of it), with the message changing if arpen caused the shield to have zero impact on the attack.

2. In creature.cpp, added call to block_ranged_hit to `Creature::deal_projectile_attack`.

3. Necessary misc changes to character.h, creature.h, monster.cpp, and monster.h for the above function changes to work.

JSON changes:
1. Added wooden shields and large wooden shields, mainlined in from Medieval Mod Reborn. Made some stat adjustments to modernize it a bit and balance with the new shield mechanics in mind. Thicker and heavier than the riot shield, so slightly better against bashing damage but weaker to cutting and bullets, and both have 90% coverage so even the large variant will intercept ranged attacks less often than the riot shield.
2. In addition, added riot shields and ballistic shields. The former is simple, high block ability and low weight but actual protection isn't that high, only really good for feral human rocks and such. The latter is fittingly heavy and tweaked to have enough protection to make 9mm FMJ painful but not deadly, while having three times the encumbrance. On top of that, their use of `WBLOCK_2` means the ballistic shield is less reliable.
3. Added recipes for the wooden shield and large wooden shield. Again mostly just a slightly updated copy of the Medieval Mod Reborn recipes.
4. Added itemgroup enties adding wooden shield and large wooden shield to `medieval`, `museum_armor`, `survivorzed_extra`
5. Added riot shield to `survivorzed_extra`, `swat_gear`, `mon_zombie_swat_death_drops` (swat zombies don't call the preceding itemgroup so this gives them a reasonable chance of dropping a riot shield, but for balance reasons no chance of a ballistic shield, always damaged), `mon_zombie_cop_death_drops` (lower rate than swat zombies, always damaged), `pawn`, and `prison_armor`
6. Added ballistic shield to `mil_armor`, `mil_accessories`, `survivorzed_extra`, `swat_gear`, `mon_zombie_bio_op_death_drops` (so that regular soldier zombies are unlikely to drop one, but bio-operators have reasonable odds of it, always damaged), and `spider`.
7. Also added a `soa_shield_mail` itemgroup for `soa_mail` to use, granting a 50% chance of spawning a generic wooden shield or large wooden shield together with the mail armor
8. Per Scarf's request, updated JSON documentation.

#### Describe alternatives you've considered

1. Allowing crouching players to recoup some of the coverage penalty on the assumption they're turtling up.
2. Rigging the messages in such a way that it doesn't stand out as much when a ranged attack hits you in a part the shield covers naturally, since that won't print the intercept message due to just using normal armor mechanics.
3. Torturing myself further by making coverage penalties something that can be set completely at the armor level instead of derived in this manner.

#### Testing

1. Checked affected JSON files for syntax and lint errors.
2. Compiled and load-tested.
3. Spawned in and put on a riot shield.
4. Confirmed that feral human rocks bounce off when the intercept triggers, diplaying the message and stating that absorbed damage maxed out at 6 (the max damage of the feral's no-crit rock attack).
5. Replaced the feral with a light turret, confirmed that even when it triggers the shield prints a message stating the shot went right through.
6. Swapped shield out for ballistic shield. Debug messages confirmed it had a lower intercept chance, successful shield hits reduced the damage down to a survivable level.
7. Checked that failed intercepts were also being reported as such by the relevant debug message.
9. Tested riot shield vs. crossbow feral. Base damage as stated by the debug message tended to be 35-40 instead of hovering at 30, confirming that the 1.25 damage multiplier from using carbon-fiber bolts seemed to be being taken into account.
10. Also tested wielding the shield instead of wearing it, something the player might do if they didn't know how `BLOCK_WHILE_WORN` works. Confirmed this was still valid for intercepts, as it will count as the player's best blocking tool, and still has the requisite properties to trigger successful intercepts.
11. Confirmed that wearing arm guards would not prompt any intercept-related messages.
12. Checked affected C++ files for astyle.

Item | Protection | Encumbrance | Coverage % | Block technique | Intercept chance (base) | Intercept chance (legs)
--- | --- | --- | --- | --- | --- | ---
Wooden shield | 9/6/6 | 15 | 90% | WBLOCK_2 | 72% | 45%
Large wooden shield | 9/6/6 | 25 | 90% | WBLOCK_3 | 81% | 67.5%
Riot shield | 8/8/8 | 10 | 100% | WBLOCK_3 | 90% | 75%
Ballistic shield | 12/30/42 | 30 | 100% | WBLOCK_2 | 80% | 50%

#### Additional context

Literally over 7 years in the making: https://github.com/CleverRaven/Cataclysm-DDA/pull/15055

The lack of worn sprites for these might be further motive for me to start work on that "external tileset" idea soonish...

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]
<details><summary>Testing</summary>

> Confirmed that feral human rocks bounce off when the intercept triggers, diplaying the message and stating that absorbed damage maxed out at 6 (the max damage of the feral's no-crit rock attack).

image

> Replaced the feral with a light turret, confirmed that even when it triggers the shield prints a message stating the shot went right through.

image

image

> Swapped shield out for ballistic shield. Debug messages confirmed it had a lower intercept chance, successful shield hits reduced the damage down to a survivable level.

image

> Checked that failed intercepts were also being reported as such by the relevant debug message.

image

as ballistic shield protected the shot from light turret i checked with
riot shield

> Tested riot shield vs. crossbow feral. Base damage as stated by the debug message tended to be 35-40 instead of hovering at 30, confirming that the 1.25 damage multiplier from using carbon-fiber bolts seemed to be being taken into account.

image

> Also tested wielding the shield instead of wearing it, something the player might do if they didn't know how BLOCK_WHILE_WORN works. Confirmed this was still valid for intercepts, as it will count as the player's best blocking tool, and still has the requisite properties to trigger successful intercepts.

image

> Confirmed that wearing arm guards would not prompt any intercept-related messages.

image

</details> 

LGTM

**Comment by chaosvolt** [comment]
And now with sprites in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2853

image

**Comment by scarf005** [comment]
i think good to merge then

**Comment by chaosvolt** [comment]
Sorry about undoing the approval, spotted a small mistake in the recipes.

**Pull request merged**
