### PR TITLE
Obsolete unused laboratory fluff

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Obsolete "Clean out and obsolete some unused fluff items from science tool spawn"

#### Purpose of change

As mentioned in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2740 it'd be a good idea to obsolete items that're commonly used by science tool spawns but have zero use, unless we decide that it's actually important to give them a use. This will accordingly make tool spawns in places like microlabs more consistent and make it easier to mess with how common or rare an actually-useful item in it happens to be.

#### Describe the solution

Obsoleted the following items for having no use action, tool quality or recipe/uncraft usage, removing them from itemgroups:
* Spectrometry cuvettes. The related spectrophotometer item implies this SHOULD have a use, and that item DOES have recipe usage, but this is in fact unused fluff.
* Microcentrifuge tube trays. Again an item that implies a relation to an existing item that is useful but is in fact unrelated.
* Burettes. You'd think the absurd reference to getting this tattooed on you would imply this is important.
* Test tube racks, stand rings and stand ring clamps. 100% pure useless fluff.

Additionally obsoleted the following items that didn't even spawn:
* Vacuum ovens. These seem to have some sort of hacky "fill it and transform like a charcoal kiln" idea designed for them but this went nowhere, and it doesn't spawn so.
* Vacuum pumps, closed loop extractors, makeshift oil extractors, and filter papers. These all have crafting qualities defined but the items go unused and don't spawn, and DDA's only apparent uses for them don't really justify keeping them around.

Additionally checked for any usage of those items in the mods folder, didn't find anything.

#### Describe alternatives you've considered

A couple items were retained for having at least some marginal use, but could also be axed if desired:
* Electrophoresis trays don't have any recipe or tool usage, but they can be uncrafted into stuff.
* Same with dissecting microscopes, it's useless as-is but remains a source of delicious lenses.
* Small glass tubes are particularly borderline, I only kept them because uncrafting a pH meter gives them and the vastly more useful voltmeter, making it possible to craft pH meters would be a vast improvement here (on top of making analysis sets less annoying to get by making another of its components craftable).
* Glass prisms and light detectors are also borderline, only kept because the vastly more useful spectrophotometer yields these when uncrafted. Unless we decided it reasonable to be able to craft a spectrophotometer, we could easily axe those from the uncraft outright, or replace with closest comparable vanilla items.
* Vortex device likewise retained because it's trash but can be uncrafted into other stuff, though the items from it are all in the "useful but reasonably available via other sources" category.

Hydrogen and nitrogen tanks are also not that useful outside of hydrogen tanks being usable to make hydrogen fuel in Cataclysm++, but I kinda want to at some point tweak it so they have a valid use in vanilla too. Being able to use hydrogen tanks as a direct substitute for plasma canisters for CVD machines is a future no-brainer, mainlining hydrogen gas as a fuel source from Cata++ is another possibility too. Butane tanks also seem like they'd make way more sense as a way to refuel lighters.

Making an uncraft to turn filter paper into paper also came up but Kheir and I are both leery of it since paper is reasonably common in lab settings already and it'd be easy to un-obsolete it if we actually decide to add a use for them, and as above several items are already on the edge of the chopping block for having "can be trashed for stuff that's not actually useless" as their only current reason to exist.

#### Testing

Checked affected files for syntax and lint errors.

#### Additional context

Test tube racks, microcentrifuge tube trays, burettes, cuvettes ring stands, and ring stand clamps are still not used in anything in DDA to this day, as of a check in build 2023-04-26-0511. Again amusing given the lavish effort that went into the description for burettes, also still present in DDA. The following items do have some uses in DDA not present in BN:
* Vac ovens got reworked from some kinda hackery resembling the charcoal kiln filling item to just being used as a tool, but only for refining weed products. Seems like a waste to me since it's an excessively complex and detailed crafting chain for something you could've just smoked.
* Recovery pumps got implemented in recipes for closed loop extractors, which again are used solely to make cannabis needlessly complicated.
* Same deal as above with filter papers and vacuum pumps.

### CODE REVIEW

**Comment by DarianLStephens** [comment]
Regarding that part, 

> This will accordingly make tool spawns in places like microlabs more consistent and make it easier to mess with how common or rare an actually-useful item in it happens to be.

Would it work to create 2 separate, independent pools? One for the actual worthwhile stuff, and another for the 'fluff'?
That way you can still have the items for deconstruction or whatever, instead of getting rid of them outright, while also being able to directly control the spawn rate of the useful things. Even moreso if the useful things always get priority in spawning, so the space in containers couldn't be taken up by a particularly generous helping of other stuff.

The fluff items could be useful in making locations feel more lived-in with objects that aren't particularly useful anymore, filling up shelves when nothing else appears so it doesn't always look as barren.

**Comment by chaosvolt** [comment]
This could be done, though it would also require adding uncrafts to all of the items I obsoleted. This is why I actually left the stuff that's useless but can be uncrafted for now, since that's still a bare-minimum level of usefulness over the stuff that was complete junk.

**Comment by Lamandus** [comment]
Anything that has absolutely no use should be removed. I would say try to make stuff useful before outright removing it. Same with the XLR music stuff, try to make somewhat good uncraft recipes. The rest can be culled

**Comment by chaosvolt** [comment]
Hmm, I could add uncrafts to some of it but a lot of it is fluff of small size and questionable use.

**Comment by Lamandus** [comment]
The small size fluff can go. You can try to transform the canisters to useful ones, maybe for bomb crafting or for storage.

**Comment by chaosvolt** [comment]
> The small size fluff can go. You can try to transform the canisters to useful ones, maybe for bomb crafting or for storage.

Could work, lemme look again to see what all I could afford to try and salvage. Honestly I'd be fine with this useless fluff being just obsoleted outright so it won't dilute item spawns anymore but.

**Comment by chaosvolt** [comment]
So, current thoughts on this:
1. Filter paper would've been good to replace with paper spawns, but those never actually spawned anywhere. I'm a bit bugged I didn't notice that sooner, one brief point of contention was "should filter papers be retained so you can use them as a source of paper" but that's completely irrelevant if they never spawn in the first place.
2. Likewise, I'd just discount outright all of the useless items that never actually spawned. The only uses DDA ever bothered to give them were just for weed meme stuff, and if we really want to give them a use we can always just de-obsolete them.

So that leaves the actual stuff that had item spawns that got removed. Of those:
1. Burettes as-is aren't really worth keeping. Its main use is precision measurements, something that doesn't really factor into recipes currently. It could be useful as a standin for a syringe for recipes that use it for dispensing measured amounts of something, but I don't recall if there even are any recipes that use it that don't also require a syringe specifically because it can inject stuff too. Even then, for this to be a useful alternative you'd need locations where it makes sense for burettes to spawn but not syringes. Schools perhaps, but even then this seems marginal.
2. Cuvettes in their current form should just not exist as-is. The reason is, it says they're specifically spectrometry cuvettes, but they're currently a completely separate item from the already-existing spectrophotometer and having them does not affect your ability to craft the analysis kit with them. That item is already an assortment of fairly annoying components to get, so keeping cuvettes requires either making that recipe require one more annoying thing to collect, or else causing player confusion where they mistake a useless item for being related to an item that's actually useful.
3. Test tube rack is literally just plastic scrap. It'd be good for maybe a single plastic chunk as it currently is. Given plastic chunks are easy to come by, I don't feel that it fills that "item can be scrapped into something useful is worth keeping" criteria. I already noted that the vortex device is on the edge of being obsoleted because the items you can get from it aren't as hard to come by as some of the other useless stuff I opted not to obsolete, and even that is infinitely more useful than a single plastic chunk.
4. The microcentrifuge tube tray is in the same boat as spectrometry cuvettes. They shouldn't be kept because the player might assume they're needed for applications involving the microcentrifuge. And like the test tube rack, it's also functionally scrap plastic. Since the centrifuge can't be crafted and isn't used in any more complex recipes that might justify pairing it with the centrifuge, that also gives it even less potential utility compared to the cuvettes.
5. Stand rings and stand ring clamps are more misc "how you keep stuff in place" things that, like burettes, aren't really simulated in recipes. They'd only really be good for scrap metal, again a common resource that's not worth diluting an uncommon itemgroup (one you're hoping for something useful to show up in because it's basically the only itemgroup that spawns a few items that certain advanced recipes are completely softlocked without) with literally just scrap metal

I don't see what you were talking about with canisters, because none of the items that were removed from itemgroups could really be replaced with an empty canister, though adding empty canisters and maybe a small stack of paper (to represent filter papers in abstract) to `tools_science` or other itemgroups could be done for flavor, it's not really directly related to the items being removed having no real justification for being in those itemgroups.

**Comment by Lamandus** [comment]
I am okay with these points. Removal of those items is a good idea

**Review by Firestorm01X2 — APPROVED** [review]
It is time to do it.

**Pull request merged**
