### PR TITLE
Remove rubber from boots

### PR DESCRIPTION
**Pull request by Lamandus**
#### Summary
SUMMARY: [Category] "[Briefly describe the change in these quotation marks]"

#### Purpose of change
Boots were having "rubber" as material. Since it isn't used for them to craft i removed them. Another reason for it is, that the values for protections now shifted to more "realistic" values. Because they were treated as "50% leather, 50% rubber". Which doesn't make sense of course. Also uncrafting recipes were absolutly bonkers. They produced over 5 liter (!) of rubber!

#### Additional context

Old boots:
image
new boots:
image

leather armor boots: 
image

as seen it also was a good way to balance it all.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
I'll need stat comparisons for affected items. Preferably as a table, but plain text armor values are also good.

**Comment by Lamandus** [comment]
Ok! You got boots right now, rest will follow

**Comment by Lamandus** [comment]
Turnout boots old:
image

Turnout boots new:
image

Combat boots old:
image

Combat boots new:
image

Expensive Flip Flops old:
image

Expensive Flip Flops new:
image

Lowtop tennis shoes old:
image

Lowtop tennis shoes new:
image

Sneakers old:
image

Sneakers new:
image

**Comment by Coolthulhu** [comment]
It's a pretty big nerf to their stats, except the fire resistance which isn't used much.

**Comment by Lamandus** [comment]
Well, yeah, because they don't have good stats. These are sneakers and such. Check armored boots for example.

**Comment by Lamandus** [comment]
That is what volt is trying to fix... I think the nerfs are more than justified

**Comment by chaosvolt** [comment]
Keep in mind, the material thickness for boots with rubber soles were reduced by 1 in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/847 specifically due to the rubber sub-material adding a ton to their bash protect (in particular making leather armor boots pointless).

So long as the end result still comes out to below what leather armor boots now have, reverting the layer reduction should be fine.

**Comment by Lamandus** [comment]
> Keep in mind, the material thickness for boots with rubber soles were reduced by 1 in #847 specifically due to the rubber sub-material adding a ton to their bash protect (in particular making leather armor boots pointless).
> 
> So long as the end result still comes out to below what leather armor boots now have, reverting the layer reduction should be fine.

we tweaked a bit more, so now it should be fine anyway.

**Pull request merged**
