### PR TITLE
Overwriting empty Gunshop with full one.

### PR DESCRIPTION
**Pull request by SzQ1**
Edit done by PoshOctavia

#### Purpose of change

Remove irritating bit of a game and Tefnuts mental health.

#### Describe alternatives you've considered

Removing the broken and empty gunshops from the game and mapgen all together. Maybe in the future i will look into it.

#### Testing

It works for Octavia.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
> It works for Octavia.

It could use a bit more testing then...
I'll test it before merge, but mapgen tests are always somewhat RNG-dependent.

**Comment by SzQ1** [comment]
Tested, works fine.

**Comment by SzQ1** [comment]
How do I fix this GCC 8 Ubuntu fail?

**Comment by Coolthulhu** [comment]
> How do I fix this GCC 8 Ubuntu fail?

Shit, OoM kill is still happening.
It's not your fault and you can't fix it from your side, I'll ignore it here.

**Comment by Coolthulhu** [comment]
It seems to replace two of the gunshop mapgens with a copy of the third.
If that's what it does, then it shouldn't be done like this, but rather by deleting the two or altering their weights so that they are rarer.

**Comment by SzQ1** [comment]
I will see if i can do it properly

**Comment by SzQ1** [comment]
Forgot about this one. Later I will just delete these changes and edit weight settings so the empty one almost don't spawn.

**Pull request merged**
