### PR TITLE
feat(UI): Fast travel sprite replaced on overmap

### PR DESCRIPTION
**Pull request by thedyze**
Replaces the default ('&') sprite to the fast travel path on the overworld map

### Required

- [X] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [ ] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [X] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### Optional

  - [X] I have documented the changes in the appropriate location in the `doc/` folder.

## Purpose of change

To add a proper sprite to the  overmap fasts travel path.

## Describe the solution
Current sprite on the left, new on the right:
image

I have added a new file in the external tileset for maptiles, with the intent of adding more replacements sprites, e.g overmap buildings.

The tile is now 'fg' instead of 'bg', so potentially the blinking effect can be removed.

### CODE REVIEW

**Comment by thedyze** [comment]
Tried the PR Title Generator, but had some problems finding a proper title for when only adding/overriding sprites

**Comment by RoyalFox2140** [comment]
Semantic title is mad for some reason

**Comment by thedyze** [comment]
> Semantic title is mad for some reason

Simplified the PR name. But perhaps some category should be added to the PR Generator for when you only add or override graphics?

**Comment by RobbieNeko** [comment]
My best guess for the scope would be UI, so `feat(UI)`

But of course, just `feat` with no scope works just as well

**Comment by thedyze** [comment]
> My best guess for the scope would be UI, so `feat(UI)`
> 
> But of course, just `feat` with no scope works just as well

Yeah kinda works for this particular sprite. But building sprite changes, or other general tileset changes, doesn't really match with UI?

**Comment by RobbieNeko** [comment]
Ehh, I'd say that the map tiles are generally UI. It's certainly the *best* fit for now

**Comment by thedyze** [comment]
> Ehh, I'd say that the map tiles are generally UI. It's certainly the _best_ fit for now

Ok, adjusted.

**Comment by thedyze** [comment]
Searching through the code I just realized this PR might have to be set on hold. It seems the id "unknown" is a fallback tile for when no existing one is found.

From cata_tiles.cpp:
// If the ID string does not produce a drawable tile
 // it will revert to the "unknown" tile.
 // The "unknown" tile is one that is highly visible so you kinda can't miss it :D

So the best way forward seems to be to create and assign an id for a fast travel sprite, and then assign that id to this sprite.
And though I am a developer, I've never touched C++, so if an existing developer could do this it would be great.

**Comment by RoyalFox2140** [comment]
> Searching through the code I just realized this PR might have to be set on hold. It seems the id "unknown" is a fallback tile for when no existing one is found.
> 
> From cata_tiles.cpp: // If the ID string does not produce a drawable tile // it will revert to the "unknown" tile. // The "unknown" tile is one that is highly visible so you kinda can't miss it :D
> 
> So the best way forward seems to be to create and assign an id for a fast travel sprite, and then assign that id to this sprite. And though I am a developer, I've never touched C++, so if an existing developer could do this it would be great.

Shouldn't be hard theoretically. I can bug someone about where it's defined.

**Comment by thedyze** [comment]
> > Searching through the code I just realized this PR might have to be set on hold. It seems the id "unknown" is a fallback tile for when no existing one is found.
> > From cata_tiles.cpp: // If the ID string does not produce a drawable tile // it will revert to the "unknown" tile. // The "unknown" tile is one that is highly visible so you kinda can't miss it :D
> > So the best way forward seems to be to create and assign an id for a fast travel sprite, and then assign that id to this sprite. And though I am a developer, I've never touched C++, so if an existing developer could do this it would be great.
> 
> Shouldn't be hard theoretically. I can bug someone about where it's defined.

Thank you

**Comment by thedyze** [comment]
@RoyalFox2140 , @chaosvolt If you find/create an id I think we can basically just close this PR.
Found a more or less identical sprite in normal_stuff.png, so better to assign the id to that.

**Comment by chaosvolt** [comment]
Apologies, had been busy juggling IRL stuff lately. Not familiar with most of the tiles code so we'd have to wrangle a PR for it, hecc

**Comment by thedyze** [comment]
> Apologies, had been busy juggling IRL stuff lately. Not familiar with most of the tiles code so we'd have to wrangle a PR for it, hecc

No worries.
'auto_travel_mode' seems to be the name of action. Can't find anything for setting a tile id for the action

**Comment by thedyze** [comment]
Closing this since we found the root cause. Will open a new PR for the fix.

**Pull request closed without merging**
