### PR TITLE
perf(port): do not copy regional settings for overmaps

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: Performance "DDA Port: Stop copying regional settings for every overmap"

#### Purpose of change

performance gainz

#### Describe the solution

port https://github.com/CleverRaven/Cataclysm-DDA/pull/59313 by @jbytheway 

#### Testing

i trust DDA and CI pipeline.

### CODE REVIEW

**Comment by scarf005** [comment]
image
errrrr

**Comment by scarf005** [comment]
welp, can't reproduce so i'm good

**Comment by Firestorm01X2** [comment]
Works for me as well

**Review by Firestorm01X2 — APPROVED** [review]
Ready

**Pull request merged**
