### PR TITLE
fix: Sanity check worldname at input instead of confirmation

### LINKED ISSUE #4816: Crash when creating world + inability to name worlds ( [Curses] experimental 2024-06-xx,tested up to experimental 2024-05-30)
### Describe the bug

Tried downloading the latest experimental (curses, linux, x64) game says 0x9 (tab) is an invalid character and stops me from generating a world. Tested experimental curses linux x64 version from 2024-05-30, the bug does not show up and world can be created safely, so it happened in the last couple weeks.
image

This happens with any kind of world, this is what happens when I get a randomly generated name by just moving forward with worldgen. Throws an 0x9 character error, deletes one character from the world's name, refuses to continue. 
If I continue to press tab to continue, it eventually reaches this stage where it actually breaks into the console's prompt for world name `(world nam :)`
image

### Steps To Reproduce

look

### Screenshots

_No response_

### Versions and configuration

up

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KheirFerrum**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change

- Related to #4713.
- Revert #4918 (for the modifications to `is_char_allowed()` were better at silencing errors than catching true issues) update the game so that we now have a way to feed the string input popup printable, file/foldername safe characters only through `ANY_PRINTABLE` (name subject to change)
- Hopefully resolve #4816 (Hopefully because I don't know how to even produce the error, so maybe someone like scarf can test it) If it does, please link it back to this PR as fixed by, thank you.

## Describe the solution

~~Use new input context `ANY_PRINTABLE` that acts like `ANY_INPUT` except when it comes to text output. It prevents non-printable and non-file/folder name safe characters from being printed into textboxes to prevent world names from being impossible to save.~~

Give `query_string()` another variable to define if it should only allow printable characters. Should be much simpler than the old solution I was doing after being awake for about 14 hours.

Tear out the check at the confirmation end, it wasn't doing it's job and it shouldn't be doing it's job so late to begin with.

## Describe alternatives you've considered

- Kill myself.

## Testing

- [x] Type word salad Chinese into the world name box, as I cannot see what characters I am selecting, only the pinyin. Check that it allows me to save the world properly.
- [x] Check that [forbidden characters](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) are not allowed in worldname (Linux has fewer but I don't really know how to make them differ by version)
- [x] Test that you also cannot paste forbidden characters.

image

### CODE REVIEW

**Comment by chaosvolt** [comment]
Will likely need Scarf to test that it fixes the error I assume, since linux stuff.

**Comment by fakepass** [comment]
This seems to work for me.

**Comment by scarf005** [comment]
i'll also check whether it works on linux IME (ibus) when i get home.

**Comment by Qrox** [comment]
> Revert https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4918 (for the modifications to is_char_allowed() were better at silencing errors than catching true issues)

I don't think there was any silencing of errors. `char` is either signed or unsigned, and in both cases `is_char_allowed` rejects unprintable characters in the 0-127 range while allowing utf-8 bytes in the 128-255 range.

Also, if you revert that PR, you should probably check if creating a world named `テスト` on Windows writes the save correctly, because before that fix DDA rejected valid utf-8 names on Windows, due to the fact that `std::is_print` is undefined for negative input values.

**Comment by KheirFerrum** [comment]
> > Revert #4918 (for the modifications to is_char_allowed() were better at silencing errors than catching true issues)
> 
> I don't think there was any silencing of errors. `char` is either signed or unsigned, and in both cases `is_char_allowed` rejects unprintable characters in the 0-127 range while allowing utf-8 bytes in the 128-255 range.
> 
> Also, if you revert that PR, you should probably check if creating a world named `テスト` on Windows writes the save correctly, because before that fix DDA rejected valid utf-8 names on Windows, due to the fact that `std::is_print` is undefined for negative input values.

image

**Comment by chaosvolt** [comment]
> Also, if you revert that PR, you should probably check if creating a world named `テスト` on Windows writes the save correctly, because before that fix DDA rejected valid utf-8 names on Windows, due to the fact that `std::is_print` is undefined for negative input values.

Far as we've been able to determine from testing, the issues with world naming in BN didn't start up until after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4713, specifically due to keycode-related stuff that slipped in after we'd already determined that keycode behavior was invalid to port.

Just in case I went ahead and tested it myself too, and specifically did the "ctrl-v the name `テスト` into world entry" test, works fine:
image

So all that leaves is verifying that the linux issue is fixed, which I must leave to Scarf as I am unfortunately a victim of windows.

**Comment by KheirFerrum** [comment]
> > Revert #4918 (for the modifications to is_char_allowed() were better at silencing errors than catching true issues)
> 
> I don't think there was any silencing of errors. `char` is either signed or unsigned, and in both cases `is_char_allowed` rejects unprintable characters in the 0-127 range while allowing utf-8 bytes in the 128-255 range.
> 
> Also, if you revert that PR, you should probably check if creating a world named `テスト` on Windows writes the save correctly, because before that fix DDA rejected valid utf-8 names on Windows, due to the fact that `std::is_print` is undefined for negative input values.

During my testing it allowed through characters that should have been invalid given it's purpose, further work has revealed that that is a limitation from the rest of the function not the `isprint()` portion. That said, my issue with your implementation is that the problem _isn't_ that you were feeding it the wrong data type, and if _you were_, fixing that would have fixed your issues. The problem with your original code isn't that the values were negative, but that it was taking multibyte Unicode characters apart and feeding it to the `isprint()` function in pieces (which is why it was returning invalid characters as tab or other non-sensical options. Hence why `utf8_wrapper` must be used instead of just `std::string`

**Comment by KheirFerrum** [comment]
@Qrox Made heavy edits to comment above, see for explanation as to why I considered your solution flawed. I admit that part of the char, signed char and unsigned char was more a recent discovery by me, but otherwise it should be fairly obvious why I'm not a fan of your solution.

**Comment by Qrox** [comment]
Sorry I do not quite follow some part of your comment, and I really do not want to bother with the `char` signedness shenanigan and integer casting rules of C/C++ unless absolutely necessary, so allow me to keep my reply simple. At the time of the fix, `std::is_print` rejected utf-8 bytes outside the 0-127 range on some platforms, which made some valid world names unusable, so it had to be fixed in some way. I could have used `utf8_wrapper` and tested for the actual codepoint instead of each individual byte, but that would only be unnecessary overhead, because the invalid characters we wanted to reject all fall in the 0-127 range, so testing the bytes within that range should be enough. Whichever `char` is used by `std::string`, when converted to `int`, the original numerical value is preserved, so testing for the value's range should work in any case. If we encounter some file system that hates a particular non-ASCII character, we should update that function, but that seems a very unlikely event to me. It is fine if you do not like my solution, but that was the most reasonable and non-over-engineered fix at that moment, in my opinion.

**Comment by chaosvolt** [comment]
> Sorry I do not quite follow some part of your comment

To make it as clear as I can manage: you're using the characters completely incorrectly, and one of the errors you fixed was basically a message trying to tell you about this mistake, which you "solved" by disabling the error message.
(had the above summary proofread by Kheir to confirm it was adequate)
image

Seeing as you came into this PR to raise your objections unprompted (https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4933#issuecomment-2211115111), I'm going to be blunt with you: now that we're fixing it on our end, it's really not relevant to us whether or you want to address the flaws in your implementation or not. That's a discussion that should be had over in DDA's github.

**Comment by Qrox** [comment]
> disabling the error message.

I still do not understand what error message is being refering to here. A compiler warning/error? A runtime assertion error? Or just a metaphor that means something going wrong during execution? I cannot explain much if I do not know what the exact problem is.

> Seeing as you came into this PR to raise your objections unprompted

You pinged me in #4816 which is related to and marked as fixed by this PR, it is only natural for me to be curious what it has to do with me, and upon finding out that there is some criticism on my previous fix, I do not think it is in any way unprompted for me to try to explain the reasoning of my solution, so that you, who pinged me, could have a better understanding of my solution. I do not plan to convince you that my solution was actually good, I just thought if you pinged me about my PR you would at least be interested in my explanation of that PR, no? If not, please do not ping me next time, I'm only replying to the criticism here out of good will, so I really do not feel it is worth it if is actually unwelcome.

**Comment by KheirFerrum** [comment]
> > disabling the error message.
> 
> I still do not understand what error message is being refering to here. A compiler warning/error? A runtime assertion error? Or just a metaphor that means something going wrong during execution? I cannot explain much if I do not know what the exact problem is.
> 
> > Seeing as you came into this PR to raise your objections unprompted
> 
> You pinged me in #4816 which is related to and marked as fixed by this PR, it is only natural for me to be curious what it has to do with me, and upon finding out that there is some criticism on my previous fix, I do not think it is in any way unprompted for me to try to explain the reasoning of my solution, so that you, who pinged me, could have a better understanding of my solution. I do not plan to convince you that my solution was actually good, I just thought if you pinged me about my PR you would at least be interested in my explanation of that PR, no? If not, please do not ping me next time, I'm only replying to the criticism here out of good will, so I really do not feel it is worth it if it is actually unwelcome.

Not an error message, but an error itself. None of the non-standard characters fed into `isprint()` should be processed as negative values. They are all represented in Unicode as values greater than 127, `char` can be unsigned or signed depending on implementation, but it is always interpreted as a non-negative number by any character interpreting function when containing characters. `is_print()` handles characters beyond 127 just fine, as we see from how it catches `/xa0` but not other non-standard unicode characters (which it catches due to the locale defined for our project, which is another litmus test you removed that was trying to tell you you had fed it the values in the wrong way), so your premise for the issue was suspect to begin with.

By first breaking then forcing signage of characters you have mangled the input for `is_char_allowed()` and thus forced it into undefined behaviour for all non-standard character sets. I had assumed that this was unintended, but it appears that you believe this is a better solution because of "overhead" in the world creation menu (which is what, 2 bytes max, a strange consideration given how `count_by_charges` removal is at least 2000 times more RAM inefficient)? I don't see why we would want this, as if char implementation in the project is changed in any way for any reason, or if a non-standard unprintable character is added to the Unicode library, future maintainers will have to intuit that you have passed it data in a format that it should never have gotten it in in order to fix it.

If you are actually fine with all of these concerns, then there's really nothing to discuss, I prefer my code to not survive on undocumented silencing of undefined behaviour errors.

**Review by scarf005 — APPROVED** [review]
image
image

works on linux.

**Pull request merged**
