### PR TITLE
feat(balance): Steel bowstring, repeating crossbow debuff

### PR DESCRIPTION
**Pull request by yay855**
Made the damage boost 5 instead of 15 and added a reload modifier of 15. Also changed the description to reflect this.

## Purpose of change

The steel crossbow string was too powerful when it was made, allowing for crossbows, especially repeating crossbows, to easily outcompete many guns. The repeating crossbow's buff in the same PR that added the steel bowstring similarly made the default crossbow useless, which was poor for balancing purposes.

## Describe the solution

The steel bowstring now only increases damage by 5 and has a reload penalty. The repeating crossbow now does slightly less damage and has significantly less range than a standard crossbow to make it more balanced, though still more than it had before my crossbow rebalance PR.

### CODE REVIEW

**Review by chaosvolt — APPROVED** [review]

**Comment by scarf005** [comment]
related: #4066

**Comment by scarf005** [comment]
also cc @NappingOcean

**Comment by NappingOcean** [comment]
The crossbow issue seems to be mostly with repeating crossbows. The bowstring nerf is devastating for those, but it seems to be even more so for other crossbows.
The bowstring is obviously very strong, so it needs to be nerfed appropriately, but I think it could be nerfed a bit less to prevent repeating crossbows from using it.

**Comment by yay855** [comment]
> The crossbow issue seems to be mostly with repeating crossbows. The bowstring nerf is devastating for those, but it seems to be even more so for other crossbows. The bowstring is obviously very strong, so it needs to be nerfed appropriately, but I think it could be nerfed a bit less to prevent repeating crossbows from using it.

Honestly, it might be a good idea to just buff other crossbows' damage some instead. The steel bowstring is still useful, an extra 5 damage is nothing to sneeze at, but the main issue is that non-repeating crossbows kind of suck! This game very rarely has you face up against only one enemy at a time, having the ability to just fire multiple crossbow bolts is far and above more useful than extra damage on a single-shot weapon that's nearly impossible to reload mid-battle.

**Comment by scarf005** [comment]
kind of tangential, but it might make sense to change it from steel bowstring to steel prod [(the bow part of crossbow)](https://en.wikipedia.org/wiki/Crossbow#Terminology), as the power of (cross)bow is determined not by bowstring but prod

**Review by chaosvolt — APPROVED** [review]

**Comment by chaosvolt** [comment]
Weird-ass check fail, seems unrelated?
```
Run echo =================================================
=================================================
Get-ChildItem: D:\a\_temp\1bba1bb3-e510-442b-91df-16d7712d8d99.ps1:3
Line |
   3 |  Get-ChildItem "D:\a\Cataclysm-BN/Cataclysm-BN/out/build/$env:CMAKE_PR …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'D:\a\Cataclysm-BN\Cataclysm-BN\out\build\' because it does not exist.
Error: Process completed with exit code 1.
```

**Comment by scarf005** [comment]
image
image
image

@chaosvolt you can rerun failed workflows like this

**Pull request merged**
