### PR TITLE
feat(content): House Nested Chunk Addition, Cleanup:  bungalow 28, 29, house_coop1

### PR DESCRIPTION
**Pull request by LilShiningMan**
### Required

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
make house spawns more dynamic, clean up files : bungalow 28, bungalow 29, house_coop1

## Describe the solution
Adding nested chunk spawns for houses, including front yard, backyard, roof solar, roof item; remove furniture entries and replace with palette symbols where appropriate; clean up house spawn errors, and generally clean up the file

## Testing
linted and spawned in game

## Additional context
bungalow 28
- add roof chunks
-  add res_personal items palette symbol

bungalow 29
- add table_foyer palette symbol

house_coop1
- add backyard and frontyard chunks
-  add roof chunks
-  add table_foyer palette symbol
-  add res_personal items palette symbol

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]
since you're making many related PRs, it also might be a good idea to create one large PR with multiple commits.

**Comment by LilShiningMan** [comment]
I thought it be easier to review if it was split up, but if you want me to I can put the remainder (6 houses) all in one PR

**Review by chaosvolt — APPROVED** [review]

**Comment by scarf005** [comment]
> I thought it would be easier to review if it was split up, 

yeah, but being split up into multiple commits also work well.

> but if you want me to I can put the remainder (6 houses) all in one PR

thanks! would be nice if each (related) changes are split into individual commits (so first commit changes house 1,2, and 3, second commit changes building 1 and 2, etc)

**Comment by LilShiningMan** [comment]
OK, sounds good. I'll do two commits for my PR tomorrow night, 3 houses apiece

**Comment by scarf005** [comment]
sure. if you're unfinished with your work, you can mark it as draft. i'll merge existing PRs as they look complete, tho

**Pull request merged**
