### PR TITLE
feat(UI,balance): Sane default season length

### PR DESCRIPTION
**Pull request by AriaMoradi**
## Purpose of change

The game is going be balanced around 30 day seasons, traditionally seasons have been 14 days. This is a pre-requisite to those new balances.

## Describe the solution

Change default season length to 30, initial day is halfway through the first season, change that to 15 as well. 

## Describe alternatives you've considered

Keep the old-school defaults as is.

### CODE REVIEW

**Review by chaosvolt — DISMISSED** [review]
Seems aight to me. Easy to change either way so. :>

**Comment by RoyalFox2140** [comment]
I worry a bit if we balance everything around any set season length when a lot of people play on 91 day seasons, 14 day, and 7 day by personal choice. Ideally everything should scale as best it can.

**Comment by AriaMoradi** [comment]
I couldn't figure out the weather temperature tests.

**Comment by chaosvolt** [comment]
> I worry a bit if we balance everything around any set season length when a lot of people play on 91 day seasons, 14 day, and 7 day by personal choice. Ideally everything should scale as best it can.

Irrelevant to this PR, this is just changing a default preference, not any code affected by or related to season scaling.

**Comment by AriaMoradi** [comment]
This last PR gives the weather generator more breathing room, it not a valid fix but that is out of the scope of this PR.

**Review by chaosvolt — APPROVED** [review]
:3

**Comment by scarf005** [comment]
image

The PR does not explain why is it 'sane' to have 30-day-season as default.

> The game is going be balanced around 30 day seasons, traditionally seasons have been 14 days. This is a pre-requisite to those new balances.

This feels more like `Describe the solution` than `Describe the solution` as the body lacks who,when,why the game is going to be balanced around 30 day seasons.

please make sure to provide rationale for the changes next time.

**Comment by scarf005** [comment]
```
food freshness and lifetime
  food is stored in a fridge
-------------------------------------------------------------------------------
/home/scarf/repo/cata/Cataclysm/tests/iteminfo_test.cpp:784
...............................................................................

/home/scarf/repo/cata/Cataclysm/tests/iteminfo_test.cpp:50: FAILED:
  CHECK( info == reference )
with expansion:
  "--
  * This food is <color_c_yellow>perishable</color>, and at room temperature
  has an estimated nominal shelf life of <color_c_cyan>1 year</color>.
  * Current storage conditions <color_c_yellow>partially</color> protect this
  item from rot.  It will stay fresh at least <color_c_cyan>8 years</color>.
  * This food looks as <color_c_green>fresh</color> as it can be.
  "
  ==
  "--
  * This food is <color_c_yellow>perishable</color>, and at room temperature
  has an estimated nominal shelf life of <color_c_cyan>3 seasons</color>.
  * Current storage conditions <color_c_yellow>partially</color> protect this
  item from rot.  It will stay fresh at least <color_c_cyan>3 years</color>.
  * This food looks as <color_c_green>fresh</color> as it can be.
  "
with messages:
  escape_newlines( info ) := "--\n
  *`This`food`is`<color_c_yellow>perishable</color>,
  `and`at`room`temperature`has`an`estimated`nominal`shelf`life`of`
  <color_c_cyan>1`year</color>.\n
  *`Current`storage`conditions`<color_c_yellow>partially</color>
  `protect`this`item`from`rot.``It`will`stay`fresh`at`least`<color_c_cyan>
  8`years</color>.\n
  *`This`food`looks`as`<color_c_green>fresh</color>`as`it`can`be.\n
  "
  escape_newlines( reference ) := "--\n
  *`This`food`is`<color_c_yellow>perishable</color>,
  `and`at`room`temperature`has`an`estimated`nominal`shelf`life`of`
  <color_c_cyan>3`seasons</color>.\n
  *`Current`storage`conditions`<color_c_yellow>partially</color>
  `protect`this`item`from`rot.``It`will`stay`fresh`at`least`<color_c_cyan>
  3`years</color>.\n
  *`This`food`looks`as`<color_c_green>fresh</color>`as`it`can`be.\n
  "

Test failure in TALK_TEST_SEASON
response: This is a basic test response.
response: This is a days since Cataclysm 5 test response.
response: This is a season summer test response.
-------------------------------------------------------------------------------
npc_talk_season
-------------------------------------------------------------------------------
/home/scarf/repo/cata/Cataclysm/tests/npc_talk_test.cpp:419
...............................................................................

/home/scarf/repo/cata/Cataclysm/tests/npc_talk_test.cpp:79: FAILED:
  REQUIRE( d.responses.size() == expected_count )
with expansion:
  3 == 4
with message:
  d.responses := { {?}, {?}, {?} }

18:21:58.931 INFO : Language set to 'en_US'
18:21:58.931 INFO : C locale set to 'en_US.UTF-8'
18:21:58.931 INFO : C++ locale set to 'en_US.UTF-8'
18:21:59.176 INFO : Language set to 'fr_FR'
18:21:59.176 INFO : C locale set to 'en_US.UTF-8'
18:21:59.176 INFO : C++ locale set to 'en_US.UTF-8'
18:21:59.425 INFO : Language set to 'ru_RU'
18:21:59.425 INFO : C locale set to 'en_US.UTF-8'
18:21:59.425 INFO : C++ locale set to 'en_US.UTF-8'
18:21:59.604 INFO : Language set to 'en_US'
18:21:59.604 INFO : C locale set to 'en_US.UTF-8'
18:21:59.604 INFO : C++ locale set to 'en_US.UTF-8'
===============================================================================
test cases:       547 |       545 passed | 2 failed
assertions: 7,242,926 | 7,242,922 passed | 4 failed

Test world "Tom" left for inspection.
Ended test at Thu Apr  4 18:23:09 2024
The test took 114.325 seconds
```

after the PR local tests seem to fail due to changes in season length.

**Comment by chaosvolt** [comment]
What. All tests passed on the last commit in this PR...

**Pull request merged**
