### PR TITLE
feat(balance): primitive tool/weapon diassembly, pipe spear buff

### PR DESCRIPTION
**Pull request by yay855**
This makes it possible to disassemble various primitive tools and weapons, as well as buffs the pipe spear to have the same to-hit bonus as the wooden spear; every single item that is now uncraftable has a very simple assembly method, while the pipe spear is basically the same as a wooden spear but made of metal.

## Purpose of change

Numerous tools (especially stone ones) weren't uncraftable despite being rocks (or in one case, a hunk of metal) literally tied to a stick. Furthermore, the pipe spear (and by extension, the sharpened rebar) had a -1 to hit despite being functionally just a wooden spear made of metal.

## Describe the solution

The stone hammer, makeshift hammer, stone shovel, stone knife, stone axe, stone adze, crude lockpick, cestus, quarterstaff, and peasant flail can now all be disassembled. The pipe spear now has a +1 to hit to match the wooden spear.

### CODE REVIEW

**Comment by Zireael07** [comment]
Those primitive tools are not just tied to a stick but connected to it with some glue iirc

**Comment by yay855** [comment]
> Those primitive tools are not just tied to a stick but connected to it with some glue iirc

I mean. They're not ingame, though. Every single primitive tool I gave the reversible line to is made ingame using solely sticks, string/cordage, and a rock or metal. And even if they were, you can't really get back glue once it's cemented to a stone or a stick.

**Comment by Zireael07** [comment]
Obviously this is not modern glue and prehistoric glue isn't represented ingame because we don't really know how it was made

**Comment by RoyalFox2140** [comment]
We don't model any adhesive in these tools, but even if we did you could remove said adhesive and not get it back on disassembly. The important thing is that stone tools are knapped to specific shapes and you can't turn a knife back into a hammer back into a knife back into an adze etc, you could switch it to give pebbles instead of the rock though.

**Review by chaosvolt — APPROVED** [review]
Pointy stick go brrrr

**Pull request merged**
