### PR TITLE
Add "Limit Fungal Growth" mod

### PR DESCRIPTION
**Pull request by FickDiddler**
#### Summary

SUMMARY: Mods: "Add 'Limit Fungal Growth' mod"

#### Purpose of change

The addition of this mod, pretty much a direct port from the DDA version, would I believe be of great use to a lot of people.

#### Describe the solution

No more fungus amongus. The yellow and mucky spore terrain no longer spread. The fungi just sit in their sad little blotches, incapable of expansion.

#### Describe alternatives you've considered

Going the good-old fashioned flamethrower route.

#### Testing

It works. The fungus do not spread.

#### Additional context

Hope everyone is having a great day!

### CODE REVIEW

**Comment by chaosvolt** [comment]
I guess it's handy, but keep in mind this mod if I recall only exists in DDA because they got rid of No Fungal Monsters mod.

**Comment by FickDiddler** [comment]
Fair point! However, I have some mods that interact with the fungus, so removing them completely from my game was a no-go. I believe this mod will primarily be for folks who want the fungi in their world, but don't want them to create lag-inducing swaths of fungusland every second.

**Comment by chaosvolt** [comment]
Also fair, BN also heavily nerfed fungal behavior relative to DDA as well so hmm.

**Comment by FickDiddler** [comment]
It just removes "special_attacks": [ [ "PLANT", 100 ] ].
I am pretty sure the mod is only to remove the spore's ability to spread fungus terrain. Is that no longer a thing in BN?

**Comment by scarf005** [comment]
> I am pretty sure the mod is only to remove the spore's ability to spread fungus terrain. Is that no longer a thing in BN?

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/0f956fa7d3c1f6577903a3d413e00945d061df30/data/json/monsters/fungus.json#L291-L313

it still exists and thus this mod has valid uses.

**Review by scarf005 — CHANGES_REQUESTED** [review]
image
image
image

`FUNGUS` special attack needs to be removed as well. for example fungaloids spread fungus.

**Comment by FickDiddler** [comment]
I'll do some testing and get to work!

**Comment by FickDiddler** [comment]
New Changes:
Spore cloud - disappears after 10 turns
Fungal boomer/fungal blossom/fungal wall/fungaloid/fungal zombie/fungal child/fungal ant/fungal spider - no more spreading of fungal beds

However, pollinator zombies still spread the terrain, due to their ability being tied to an emit_field, rather than special_attacks. Bloated fungal boomers explode into spores as usual. I left that alone. Also, I left the fungal towers alone as well, as I didn't want to completely leave them vulnerable.

**Comment by scarf005** [comment]
alright, but i'd prefer to change modname and description to 'suppress fungal growth' as players may think that this mod will remove all instances of fungal growth.

**Comment by FickDiddler** [comment]
I altered it to 'Limit Fungal Growth' and the description to better match its purpose. How does it look?

**Comment by FickDiddler** [comment]
Whoops, I'll also change the folder name. Just a sec.

**Comment by FickDiddler** [comment]
I think I'm done!

**Review by Firestorm01X2 — APPROVED** [review]
Thank you! Ready.

**Pull request merged**
