### PR TITLE
More feral-related changes

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Content "Add 3 more feral player professions and 1 new feral monster, related JSON updates"

#### Purpose of change

This adds professions filling the same roles as the other feral human monsters not previously covered, pairs a new feral monster+profession to add, and implements a few tweaks to improve some aspects of the scenario .

#### Describe the solution

1. Added `int_dur_faction` to Lucidity and Inner Turmoil effects so the player can tell how much longer the effect will last by number of days.
2. Fixed Inner Turmoil having a max duration of 7 hours instead of 7 days. Given each time the infighting effect triggers you get 7 hours...
3. Fixed No Ferals mod blacklisting acid zombies too for some reason.
4. Swapped the feral socialite's thompson for a repeating crossbow to match the crossbow feral, removed the violin case and gave them an empty quiver.
5. Added three more professions for the scenario: the Feral Butler/Maid is of course a player counterpart to the feral servant, the Feral Reenactor serves as this to the armored feral, and finally the Feral Chainsaw Maniac is based off another feral addition being added below as well as the lumberjack profession, 
6. Ported over a buff to the axe-wielding feral, making it a bit more of a threat in melee in exchange for lacking the ranged attack, and making its name more distinct to stand out more. Was able to implement it with more copy-from and not having to make it a full separate monster entry, my guess is they did so to override the rock-throwing attack but we can do so more easily due to the fact that all ferals have a parrot attack so we have a viable override for special attacks.
7. Also gave feral axemen a chance of dropping firefighter clothing instead of normal clothes.
8. Added feral chainsaw maniacs. Damage is scaled similarly to how the feral axeman's damage is scaled relative to a wood axe, and they get a lower melee skill due to a clumsy weapon. Their parrot attack is also more frequent and made all the time instead of at danger, to make them a noisy threat the player will hear in advance.
9. Added external tileset sprites for chainsaw ferals.
10. Added `HUMAN` flag to the following monsters, all being human-like in some way and many similar to other critters that already have the flag: experimental mutants (other, stranger mutants already get this flag), amigara horrors (because implying it may have once been a human adds a bit of weirdness to it, and adds an additional viable human target in mines alongside twisted bodies which already have the flag). Also changed grackens to give human meat when butchered and gave them the `HUMAN` flag, since they're as human-like as blank bodies which already do this. This gives science and military map extras a proper chance to have a viable target spawning in it.
11. In exchange, removed `HUMAN` flag from dementias and flesh angels, since they reanimate and yield tainted meat when butchered. Additionally set homunculi to return tainted meat on butchery and removed `HUMAN` flag from them, as they can reanimate.
12. Added the new professions to Lost and Damned scenario.
13. Added spawns of feral chainsaw maniacs, mainly to where axe ferals spawn (except `GROUP_VANILLA`) with a lower rate and always spawning a tier later (250 hours if axe ferals spawn instantly in a given area, 500 if axe bois spawn at 250).
14. Per feedback, swapped the mandatory Killer Drive trait for Psychopath so feral survivors can innately tolerate cannibalism. I'll need to remove the code effect that makes Killer Drive affect the NPC withdrawal side effect in a planned followup targeting some other code improvements.

#### Describe alternatives you've considered

I left human snails unchanged since it doesn't really say whether they're a snail that grew a human face or a human that became a snail, so left them alone for now.

Also, figuring out how to make feral socialites spawn with a posse of feral servants without them infighting with zombies is on my to-do list eventually, that will likely make the feral socialite actually solidly worth those 5 points

#### Testing

1. Checked affected files for syntax and lint errors.
2. Load-tested in compiled build.
3. Checked that chainsaw ferals randomly pick a sprite when spawned, and have the corpse sprite assigned to them instead of the generic round dead thing.
4. Started up Lost and Damned, confirmed that the status effects show intensities indicating days left on the clock.

#### Additional context

Axe feral change, by @Aerin-of-the-Toast https://github.com/CleverRaven/Cataclysm-DDA/pull/58028

Couldn't remember how to grab their email to co-auth it in the description and names with hyphens don't ever seem to work when trying to add co-authors in github desktop, weh. I should've set the axe feral changes aside as a different commit anyway.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Forgot to add the new professions to the scenario and the monster to spawns, hecc.

**Comment by chaosvolt** [comment]
Okay, added to scenario and spawns. I also ended up removing the "No Ferals mod blacklists the scenario" idea because evidently it complains if two in-repo mods both mess with scenarios, even though one of them (DSA) is obsoleted:
```
 Terminated: ::error file=data/mods/Dark-Skies-Above/blacklists/scenario_blacklist.json,line=3,col=34::Attempted to load scenario blacklist with an existing scenario blacklist

[
  {
    "type": "SCENARIO_BLACKLIST",
                                 ^
    "subtype": "whitelist",
    "scenarios": [
      "evacuee",

Make sure that you're in the correct working directory and your data isn't corrupted.
```

**Comment by chaosvolt** [comment]
Could mandate the cannibal trait, or tweak it so they start with psychopath mandated instead of killer drive.

**Comment by Firestorm01X2** [comment]
> psychopath

It seems it fits better.

**Comment by chaosvolt** [comment]
Guess that works, though it does mean they'll be barred from picking Killer Drive as an optional trait, and will warrant removing the "having recent Killer Drive morale reduces chance of being afflicted by the anomalous side effects" thing from the code. Can accept that as a writeoff and remove it in my planned update to some other feral-related code stuff I guess.

**Comment by Firestorm01X2** [comment]
> "having recent Killer Drive morale reduces chance of being afflicted by the anomalous side effects"

It seems it is 3 lines that can be removed freely.
```
// Recent non-human kills reduce chance of it triggering but don't prevent entirely.
        if( one_in( 2 ) && has_morale( MORALE_KILLER_HAS_KILLED ) ) {
            return;
        }
```
Take if off to avoid dead code.

**Review by Firestorm01X2 — APPROVED** [review]

**Comment by chaosvolt** [comment]
Fucking doi, I just noticed I changed grackens to have human bitcher yields but I actually forgot to give them the `HUMAN` flag.

**Pull request merged**
