### PR TITLE
Weather sprites for UDP

### PR DESCRIPTION
**Pull request by olanti-p**
It's still unclear whether someone is actively working on UDP, and missing weather sprites are the only glaring issue with #1101, so I pulled out Paint.NET and threw together a temporary solution.

[weather_pdn.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7449325/weather_pdn.zip)

image

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
Is it ok if I add these to the main repo? I won't add them without your consent first.

**Comment by Firestorm01X2** [comment]
> Is it ok if I add these to the main repo? I

Hello. What repo do you mean?

**Comment by Theawesomeboophis** [comment]
https://github.com/Theawesomeboophis/UndeadPeopleTileset

**Comment by olanti-p** [comment]
@Theawesomeboophis Sure, go ahead if you want to.

Here's an autogenerated unpacked version, might come in handy: [pngs_weather_32x32.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7611689/pngs_weather_32x32.zip)

**Comment by Theawesomeboophis** [comment]
Thanks.

**Pull request merged**
