### PR TITLE
feat(content): ammo drops in different amounts

### PR DESCRIPTION
**Pull request by Lamandus**
## Purpose of change
ammo spawned always with their maximum charge, so you always got 80 .22 from a zombie.

now you get a randomized amount between 1-100. So it defaults to 50 (mathematically).

## Describe alternatives you've considered
different counts for different ammo types. Shotguns getting 1-50, pistols 1-200. But maybe it gets a tweak in the future.

## Testing
old
grafik

new
grafik

### CODE REVIEW

**Comment by chaosvolt** [comment]
I should note that some items use a stack size of 20 or 80, so this may not actually be a good fit as-is.

**Comment by RobbieNeko** [comment]
I'd have suggested yoinking the ammo amounts from nested_ammo.json personally. (or at least basing these amounts off of them, rather than just a 1-100 range that has a chance of being *really* disappointing if you get a very low roll)

**Comment by Lamandus** [comment]
> I should note that some items use a stack size of 20 or 80, so this may not actually be a good fit as-is.

yes, but we talked about it. These are those random ammo drops we get from zombies and in houses. They should be randomized. Because the stack sizes were random to begin with.

**Comment by Lamandus** [comment]
> I'd have suggested yoinking the ammo amounts from nested_ammo.json personally. (or at least basing these amounts off of them, rather than just a 1-100 range that has a chance of being _really_ disappointing if you get a very low roll)

true, but sometimes you get some, you loose some. Now ammo spawns a lot more regularly (see house spawns), so the low rolls don't hurt that much.

**Review by chaosvolt — APPROVED** [review]
Suppose it works then but will leave this for others to look at.

**Pull request merged**
