### PR TITLE
Update description for new explosion option

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary

SUMMARY: Interface "Update description for new explosion option"

#### Purpose of change

improve option description from #1348  [for end user](https://www.reddit.com/r/cataclysmbn/comments/10u3dty/new_explosions/)

#### Describe the solution

image

#### Additional context

Cataclysm: Bright Nights - e1e420f-dirty_01

### CODE REVIEW

**Comment by KheirFerrum** [comment]
Suggestion

"If true, utilizes raycasting based explosive system. Obstacles (impassable terrain, furniture or vehicle parts) will block shrapnel, while blast will bash obstacles and throw creatures outward. If obstacles are destroyed, blast continues outward".

**Comment by Coolthulhu** [comment]
The description doesn't help much, the only actually informative part of it is "uses raycasting, monster shield ones behind them from shrapnel". Rest is personal opinions.

**Comment by scarf005** [comment]
> Rest is personal opinions.

do you mean `" Obstacles (impassable terrain, furniture or vehicle parts) will block shrapnel, while blast will bash obstacles and throw creatures outward.  If obstacles are destroyed, blast continues outward."`?

**Comment by Firestorm01X2** [comment]
Current description looks fine and miles better than old.

**Pull request merged**
