### PR TITLE
feat(content): Backalley ripper docs

### PR DESCRIPTION
**Pull request by Zlorthishen**
## Purpose of change
adds three new back alley ripper doc locations

## Testing
created a new world, verified that new maps spawn in correctly

## Additional context
- urban_19_victorian.json
image
- urban_26_dense_club.json
image
- urban_28_dense_cafe_laundry.json
image

### CODE REVIEW

**Comment by Zlorthishen** [comment]
on a related note, some of the dense urban areas rarely spawn

**Comment by ekaratzas** [comment]
What's the proper way to test something like this change? Let's say you spawn a new character in a new world and you wanna test out specific locations.

**Comment by scarf005** [comment]
debug map overmap editor

**Review by chaosvolt — APPROVED** [review]
:3

**Pull request merged**
