### PR TITLE
fix: take account when `gun_all_modes` is empty

### LINKED ISSUE #3315: Trading with friendly npc crashes the game
### Describe the bug

Just a heads up that I used a translator first. I don't speak English very well :(

Friendly NPCs will offer to trade all of the Player faction's items in nearby stashes, but if the amount of these items becomes too large, trading will not work and game will crash.

about... 127 different type items..?

### Steps To Reproduce

1. put a lot of different types of items in your stash. Not quantity, but lots of "kinds".
2. Try "e: let's trade items" to a friendly NPC.
3. CRASH!

### Screenshots

trading

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 61c1386 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    밝은 밤 [bn],
    NPC 욕구 제거 [no_npc_food],
    영양수치 단순화 [novitamins],
    철도역 금지 [No_Rail_Stations],
    고가 다리 [elevated_bridges],
    좀비 부활 방지 [no_reviving_zombies],
    진균 성장 제한 [limit_fungal_growth]
]

### Additional context

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/12767538/debug.log)

no crash.log :(

save files : https://www.dropbox.com/scl/fi/gewv8te0rdbc9524ta4hd/trading_bugs.zip?rlkey=mjm72rdtub8vtj1b8gh454x23&dl=0

### PR DESCRIPTION
**Pull request by scarf005**
## Summary

SUMMARY: Bugfixes "crash caused by NPC gun mode evaluation"

## Purpose of change

- fix #3315

## Describe the solution

exit early when gun modes are empty.

## Describe alternatives you've considered

cri

## Testing

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/b3ead997-a0bc-478a-b024-11b47b686ede

used the same save from #3315. was able to trade without segfault.

## Additional context

@KheirFerrum, could you review the logic?

### CODE REVIEW

**Comment by KheirFerrum** [comment]
Looks fine to me? Not sure what Using does, but based on what I can see if it passes the basic tests it should be completely fine.

**Review by chaosvolt — CHANGES_REQUESTED** [review]
Compiled and load-tested, spawned in a luggage cart next to the shelter's starter NPC, filled it with a fuckload of ammo and guns, tried to trade with them, and it imploded with:
image
image

**Comment by chaosvolt** [comment]
Let me clean solution and re-test just to make sure.

**Comment by scarf005** [comment]
that crash is probably related to #3325

**Comment by chaosvolt** [comment]
Ah, nice. Not sure how to test this other than "it compiles" if that's not what it fixes then. XD

**Comment by scarf005** [comment]
i'll... finish #3325 first then. also could you share the save that fails?

**Comment by chaosvolt** [comment]
Shit, I should've saved before trying to trade. Lemme see if I can recreate the event then will upload.

**Comment by olanti-p** [comment]
This is really weird, if item is gun it should always have at least 1 gun_mode
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/54030bdc0bb2f813f09cb5f557ce927e662fc184/src/item_factory.cpp#L435-L437

**Comment by KheirFerrum** [comment]
@scarf005 You need to fix `best_mode_for_range()` in `ranged.cpp`, _not `confident_shoot_range()`, which should be entirely unrelated to the issue at hand. `ideal_ranged_dps()` is dividing by 0 because `best_mode_for_range()` returns the default constructor instead of a false (as it's not possible with the current return value. Remember when you talked to me about making it return `std::optional`?

**Comment by scarf005** [comment]
@KheirFerrum would #3368 closes this PR as well?

**Comment by KheirFerrum** [comment]
> @KheirFerrum would #3368 close this PR as well?

I think so. You could rework the PR to deal with the root of gun_mode_id and gun_mode not normally being paired, but I think the PR _should_ deal with the same issues this one does.

**Comment by scarf005** [comment]
> This is really weird, if item is gun it should always have at least 1 gun_mode

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/1c153718ab5ebddf00e83394a51c48692a338b4b/src/ranged.cpp#L1958-L1969

after a month i finally found the culprit; `best_mode_for_range` also checks for gunmods and it isn't default initialized. by the way, wonder why gunmods can't be used as stand-alone?

**Pull request closed without merging**
