### PR TITLE
Cleanup and flesh out book morale interactions a bit

### PR DESCRIPTION
**Pull request by chaosvolt**
#### Summary

SUMMARY: Balance "Streamline book morale checks slightly, fix multiplier on spiritual books, add support for psychopaths liking morbid books"

#### Purpose of change

I'd been meaning to clean up some behavior with how Spiritual and Cannibal handle book morale for a while. Actually I wanted to just outright make it so that what traits or trait flags affected this was outright JSONized, but I was having trouble getting that to work so ech.

Now thanks to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2911 we can actually afford to make more use of `has_trait_flag`.

#### Describe the solution

C++ changes:
1. Defined new function in character_functions.cpp, `is_book_morale_boosted` for the sake of unifying and streamlining the if/else logic buried in `is_fun_to_read` and `get_book_fun_for`. It takes the previous if/else stack and checks for trait and item flags for all of the relevant checks, allowing for more mod support and variety. It also makes it so the cannibal check asks for `BOOK_CANNIBAL` instead of exactly just To Serve Man, for support of any other books we want to have use that. Also adds a separate if statement that supports "morbid but not for cannibal reasons" books.
2. Defined function in character_functions.h as well.
3. Changed `is_fun_to_read` to check `is_book_morale_boosted` instead of using its own big if/else chain.
4. Changed `get_book_fun_for` to call `is_book_morale_boosted` for determining whether to invert negative morale into positive morale, and split off the bonus morale for Spiritual into a separate check. This also turns it from a 3x multiplier to a +2 bonus. Idea here is this retains the same result of converting vanilla holy books from +1 to +3 morale, without doing wacky shit like making Oaths to The Chalice in Arcana go from -3 to +9.

JSON changes:
1. Added the relevant item flags to flags.json.
2. Added `BOOK_CANNIBAL` flag to To Serve Man.
3. Changed priest's diary to extend the `MORBID` flag to it, so that psychopath characters enjoy the authors' descent into insanity while spiritual characters actually read more into it.
5. Additionally added -1 morale and the `MORBID` flag to Visions in Solitude (the prisoner diary also seen in the cult quest line the priest's diary is a part of) and patient treatment records. This also fixes them both having innately positive morale due to inheriting from books that have that.
6. Added `SPIRITUAL` flag to Spiritual trait.
7. Added `MORBID` flag to the two mi-go books in Aftershock, and to the necromancy book in Magiclysm.

Documentation changes:
1. Documented the new book flags.
2. Updated the current effects of the `CANNIBAL`, `PSYCHOPATH`, and `SAPIOVORE` trait flags along with the `SPIRITUAL` trait.

#### Describe alternatives you've considered

1. As mentioned, my preferred goal longer-term would be JSONizing this entirely, but this at least gets the behavior a bit less wonky and enables a few extra applications in mods.
2. Some of the lab recipe books could be given the `MORBID` flag if desired since they tend to deal in hilariously-unethical !!SCIENCE!! that a psychopath character might get a kick out of, but that might be a bit potent a bonus.
3. Making it so that Psychopath simply sets base book morale for morbid books to zero instead of inverting it.

#### Testing

1. Checked affected JSON files for syntax and lint errors.
2. Compiled and load-tested.
4. Checked that a random holy book has +1 morale normally and +3 when you have Spiritual.
5. Checked that the priest's diary has -1 morale now, goes up to +1 if you have Psychopath, and goes up to +3 if you add Spiritual.
6. Checked affected C++ file for astyle.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Converting to draft since I'm a bit stuck on the precursor PR.

**Comment by chaosvolt** [comment]
Good news is the precursor PR has been sorted out, but I may or may not end up having to close and remake this PR depending on how merge conflicts go once it's merged.

**Comment by chaosvolt** [comment]
And we should now be in business.

**Comment by chaosvolt** [comment]
1. Compiled and load-tested.
2. Temporarily added in the branch of Arcana from https://github.com/chaosvolt/cdda-arcana-mod/pull/346
3. Started off as a Blood Mage, checked that book morale for Sanguine Codex showed as positive.
4. Debugged away Sanguinist profession trait, book goes back to being unfun to read.
image

**Comment by chaosvolt** [comment]
Also U H
image

**Review by scarf005 — APPROVED** [review]
<details><summary>Test cases</summary>

## normal

normal

## cannibal
cannibal

## spiritual

spiritual

## spiritual cannibal
spiritual-cannibal

## psychopath
psycho

## spiritual psychopath

spiritual-psychopath

</details> 

LGTM

**Comment by chaosvolt** [comment]
I see a small problem there: priest's diary isn't inverting its morale on the psychopath character, something wrong with the logic of the book having both inspiration and morbid?

**Pull request merged**
